%% 1020210119720 - 전자 장치 구성도
%% 생성일: 2026-05-11

classDiagram
    class 판매자단말 {
        +정산요청전송()
    }
    class 전자장치 {
        +정산요청수신()
        +정산작업정보생성()
    }
    class 금융서비스서버 {
        +정산작업정보수신()
    }
    class 회계관련정보처리노드 {
        +승인여부판단()
    }
    판매자단말 --> 전자장치 : "정산 요청 수신"
    전자장치 --> 회계관련정보처리노드 : "승인 여부 수신"
    전자장치 --> 금융서비스서버 : "정산 작업 정보 전송"