%% 1020200004518 - 가상 영상 변환 학습 과정
%% 생성일: 2026-05-11

flowchart TD
    300["학습 장치"]
    400["가상 트레이닝 이미지"]
    500["메타 데이터"]
    600["참조 정보"]
    100["제너레이팅 CNN"]
    200["디스크리미네이팅 CNN"]
    
    400 -->| "입력" | 100
    500 -->| "입력" | 100
    600 -->| "입력" | 100
    300 -->| "제어" | 100
    300 -->| "제어" | 200
    100 -->| "학습" | 200