%% 1020170144234 - 문장 제공 시스템 구성도
%% 생성일: 2026-05-11

classDiagram
    class 터치스크린 {
        +String 입력
        +String 출력
    }
    class 메모리 {
        +String 명령어
    }
    class 프로세서 {
        +String 축약어
        +String 상황정보
        +String 생성된문장
    }
    class 입출력부 {
        +String 사용자상호작용
    }
    터치스크린 --> 프로세서 : "문장을 제공"
    메모리 --> 프로세서 : "명령어를 제공"
    프로세서 <-- 메모리 : "명령어 실행"
    터치스크린 <--> 입출력부 : "입력 및 출력"