%% 1020210162272 - 가상 모델하우스 시뮬레이션 서비스 제공 서버 구성
%% 생성일: 2026-05-11

classDiagram
    class 사용자VR단말 {
        +체험()
        +제품선택()
    }
    class 가상모델하우스서버 {
        +정보전송()
        +광고정보제공()
        +전력소모량산출()
        +전기요금산출()
        +추천제품리스트제공()
    }
    class 가전제품 {
        +제품정보()
    }
    class 전력소모량정보 {
        +소모량()
    }
    class 전기요금정보 {
        +요금()
    }
    사용자VR단말 --> 가상모델하우스서버 : "정보 전송"
    가전제품 <-- 사용자VR단말 : "선택 대상"
    가전제품 <-- 가상모델하우스서버 : "광고 정보 제공"
    전력소모량정보 <-- 가상모델하우스서버 : "산출"
    전기요금정보 <-- 가상모델하우스서버 : "산출"