%% 1020210162272 - 가상 모델하우스 시뮬레이션 서비스 제공 서버 시스템도
%% 생성일: 2026-05-11

graph TD
    100["사용자 VR 단말"]
    200["서버"]
    300["가전 제품"]
    400["전력 소모량 정보"]
    500["전기 요금 정보"]
    
    100 -->| "서비스 제공" | 200
    100 <--| "선택" | 300
    200 <--| "정보 제공" | 300
    200 <--| "산출" | 400
    200 <--| "산출" | 500