%% 1020210162272 - 가상 모델하우스 시뮬레이션 서비스 제공 서버 동작 방법
%% 생성일: 2026-05-11

flowchart TD
    100["사용자 VR 단말"]
    200["서버"]
    300["가전 제품"]
    400["전력 소모량 정보"]
    500["전기 요금 정보"]
    
    100 -->|"서비스 제공"| 200
    200 -->|"가상 공간 정보 전송"| 100
    200 -->|"가전 제품 광고 정보 제공"| 300
    300 -->|"선택"| 100
    200 -->|"N배속 시뮬레이션 제공"| 100
    200 -->|"동작 정보 획득"| 100
    200 -->|"전력 소모량 및 전기 요금 정보 산출"| 400
    200 -->|"전력 소모량 및 전기 요금 정보 산출"| 500
    200 -->|"추천 제품 리스트 제공"| 100