%% 1020230036605 - 유해 컨텐츠 필터링 장치 구성도
%% 생성일: 2026-05-11

classDiagram
    class 제1AI모델 {
        +String 사용자업로드컨텐츠
        +감정정보획득()
    }
    class AI모델추론모듈 {
        +String 감정정보
        +유해스코어산출()
    }
    class 유해컨텐츠필터링모듈 {
        +String 유해지수
        +필터링()
    }
    class 제2AI모델 {
        +String 감정데이터
        +유해값산출()
    }
    제1AI모델 --> AI모델추론모듈 : "입력"
    제1AI모델 --> 제2AI모델 : "입력"
    AI모델추론모듈 --> 유해컨텐츠필터링모듈 : "입력"
    제2AI모델 --> AI모델추론모듈 : "입력"