%% 1020230036605 - 유해 컨텐츠 필터링 방법 흐름도
%% 생성일: 2026-05-11

flowchart TD
    100["제1 AI 모델"]
    200["AI 모델 추론 모듈"]
    300["유해 컨텐츠 필터링 모듈"]
    400["제2 AI 모델"]
    100 -->|"사용자 업로드 컨텐츠 입력"| 200
    200 -->|"유해 스코어 산출"| 300
    100 -->|"감정 정보 입력"| 400
    400 -->|"유해 값 산출"| 300