%% 1020230056094 - 경계구역 지능형 자동 탐지 시스템 흐름도
%% 생성일: 2026-05-11

flowchart TD
    100["카메라"]
    200["단일 복합 센서"]
    300["경계 구역 정보 수집부"]
    400["객체 인식 시스템"]
    500["객체 탐지 시스템"]
    600["객체 메모리"]
    700["객체 제어부"]

    100 -->| "수집된 영상 정보를 제공" | 200
    200 -->| "객체 영상 정보 및 거리 정보를 수신" | 300
    300 -->| "정보를 수신하여 분석" | 400
    400 -->| "분류된 객체 정보를 저장" | 600
    400 -->| "객체 정보를 표시" | 500
    500 -->| "객체 탐지 시스템을 제어" | 700