%% 1020240173044 - 인공지능 미술 자산 가치 평가 시스템 구성도
%% 생성일: 2026-05-11

classDiagram
    class 미술자산가치평가시스템 {
        +String 설명
    }
    class 사용자단말 {
        +String 데이터입력
    }
    class 서버 {
        +String 데이터처리
        +String 알고리즘수행
    }
    class 데이터베이스 {
        +String 데이터저장
    }
    미술자산가치평가시스템 --> 사용자단말 : "통신"
    미술자산가치평가시스템 --> 서버 : "데이터 처리"
    서버 --> 데이터베이스 : "데이터 저장"