%% 1020220102659 - 검색 경로 제공 시스템 구성도
%% 생성일: 2026-05-11

classDiagram
    class 검색어생성부 {
        +String 기본검색어
        +자동생성()
    }
    class 검색어관계DB {
        +String 관계정보
        +정보저장()
    }
    class 검색경로추출부 {
        +String 검색경로정보
        +경로생성()
    }
    class 최적경로추천부 {
        +String 추천리스트
        +리스트생성()
    }
    검색어생성부 --> 검색어관계DB : "검색어 생성부에서 생성된 정보를 저장"
    검색어관계DB --> 검색경로추출부 : "검색어 관계 DB에서 정보를 추출"
    검색경로추출부 --> 최적경로추천부 : "검색 경로 추출부에서 생성된 정보를 사용"