%% 1020220102659 - 검색 경로 제공 프로세스
%% 생성일: 2026-05-11

flowchart TD
    100["검색어 생성부"]
    200["검색어 관계 DB"]
    300["검색 경로 추출부"]
    400["최적 경로 추천부"]
    100 -->|"검색어 생성부에서 생성된 정보를 저장"| 200
    200 -->|"검색어 관계 DB에서 정보를 추출"| 300
    300 -->|"검색 경로 추출부에서 생성된 정보를 사용"| 400