%% 1020240067282 - 멀티모달 학습모델 구조
%% 생성일: 2026-05-11

classDiagram
    class 이미지데이터 {
        +String 관심영역
    }
    class 열화상데이터 {
        +String 관심영역
    }
    class 제1멀티모달학습모델 {
        +String 피처
        +식별()
    }
    class 신경망레이어 {
        +String 가중치
        +학습()
    }
    이미지데이터 <|-- 제1멀티모달학습모델 : "사용"
    열화상데이터 <|-- 제1멀티모달학습모델 : "사용"
    제1멀티모달학습모델 <|-- 신경망레이어 : "구성"