%% 1020220148408 - 장애물 지도 획득 방법 흐름도
%% 생성일: 2026-05-11

flowchart TD
    100["주변 장애물 감지 장치"]
    200["장애물 지도"]
    300["인공신경망"]
    400["제어신호 생성기"]
    
    100 -->|"장애물 감지 정보 반영"| 200
    100 -->|"이미지 분석"| 300
    300 -->|"장애물 정보 업데이트"| 200
    200 -->|"장애물 지도 기반 경로 생성"| 400