%% 1020237037765 - 오퍼 코드 수신 및 구매 트랜잭션 처리 흐름도
%% 생성일: 2026-05-11

flowchart TD
    100["사용자 디바이스"]
    200["오퍼 코드"]
    300["구매 코드"]
    400["구매 트랜잭션"]
    100 -->|"오퍼 코드 수신"| 200
    100 -->|"구매 코드 수신"| 300
    200 -->|"구매 트랜잭션과 연관됨"| 300
    300 -->|"구매 트랜잭션 완성 검출"| 400
    400 <--|"디바이스에서 트랜잭션 검출"| 100