%% 1020230001358 - NFT 마켓 구성 요소 다이어그램
%% 생성일: 2026-05-11

classDiagram
    class 의뢰단말 {
        +String 민팅요청
    }
    class 사용자단말 {
        +String 구매요청
        +String 소유증명서
    }
    class 운영서비스제공서버 {
        +String 요청처리
    }
    class 민팅부 {
        +String 민팅처리
    }
    class 발행부 {
        +String NFT발행
    }
    class 트랜잭션부 {
        +String 지급처리
    }
    class 검색엔진부 {
        +String 검색처리
    }
    class 큐레이션부 {
        +String 추천처리
    }
    
    의뢰단말 --> 운영서비스제공서버 : "민팅 및 발행 요청 수신"
    운영서비스제공서버 --> 민팅부 : "민팅 요청 처리"
    민팅부 --> 발행부 : "민팅 결과 수신"
    발행부 --> 운영서비스제공서버 : "NFT 발행 결과 전달"
    사용자단말 --> 운영서비스제공서버 : "NFT 구매 요청"
    운영서비스제공서버 --> 트랜잭션부 : "구매 요청 수신"
    트랜잭션부 --> 사용자단말 : "트랜잭션 결과 전달"
    운영서비스제공서버 --> 검색엔진부 : "검색 요청 처리"
    사용자단말 --> 큐레이션부 : "추천 요청 수신"