%% 1020250172807 - 클라우드 기반 번호판 인식 시스템 흐름도
%% 생성일: 2026-05-11

flowchart TD
    100["감시 카메라"]
    200["트리아지 코어"]
    300["코그니션 코어"]
    400["클라우드 서버"]
    100 -->|"영상데이터 수신"| 400
    400 -->|"이벤트 프레임 수신"| 200
    200 -->|"이벤트 프레임 제공"| 300
    300 -->|"번호판 인식 결과 제공"| 400