%% 1020250172807 - 번호판 인식 시스템 구성도
%% 생성일: 2026-05-11

classDiagram
    class 감시카메라 {
        +String 영상데이터
        +촬영()
    }
    class 트리아지코어 {
        +String 이벤트프레임
        +프레임감지()
    }
    class 코그니션코어 {
        +String 번호판문자
        +문자인식()
    }
    class 클라우드서버 {
        +String 시스템운영
        +결과제공()
    }
    감시카메라 --> 클라우드서버 : "영상데이터 수신"
    클라우드서버 --> 트리아지코어 : "이벤트 프레임 수신"
    트리아지코어 --> 코그니션코어 : "이벤트 프레임 제공"
    클라우드서버 --> 감시카메라 : "번호판 인식 결과 제공"