%% 1020197012085 - 신경망 처리 방법 흐름도
%% 생성일: 2026-05-11

flowchart TD
    100["컴퓨팅 디바이스"]
    200["제어기"]
    300["메모리 뱅크"]
    400["계산 어레이"]
    
    100 -->|"제어"| 200
    200 -->|"저장"| 300
    200 -->|"액세스"| 400
    200 -->|"입력 활성화 수신"| 100
    200 -->|"입력 활성화의 제로/비-제로 결정"| 100
    200 -->|"비-제로 입력 활성화 인덱스 생성"| 100
    200 -->|"데이터 버스를 통해 입력 활성화 제공"| 400