%% 1020220002231 - 버츄어 휴먼 인터렉션 생성 흐름도
%% 생성일: 2026-05-11

flowchart TD
    100["인터렉션 생성 모듈"]
    200["부적절 인덱싱 모듈"]
    300["부적절 스코어링 인공신경망 모듈"]
    400["적절 텍스트 생성 모듈"]
    500["클라이언트 학습 모듈"]
    600["파라미터 업로드 모듈"]
    700["메인 신경망 다운로드 모듈"]
    
    100 -->| "입력 데이터 제공" | 200
    200 -->| "부적절 여부 정보 입력" | 300
    200 -->| "부적절 텍스트 입력" | 400
    100 -->| "파라미터 업데이트" | 500
    500 -->| "업데이트된 파라미터 입력" | 600
    100 -->| "네트워크 치환" | 700