%% 1020237014608 - 시스템 구성도
%% 생성일: 2026-05-11

classDiagram
    class 클라이언트디바이스 {
        +String 거래요청
    }
    class 메시징애플리케이션 {
        +String 요청처리()
    }
    class 웹기반외부리소스 {
        +String 거래데이터
    }
    class 보안프로세서 {
        +String 데이터보안()
    }
    class 사용자인터페이스 {
        +String 상태표시()
    }
    클라이언트디바이스 --> 메시징애플리케이션 : "거래 요청 수신"
    메시징애플리케이션 --> 웹기반외부리소스 : "요청 처리"
    웹기반외부리소스 <-- 보안프로세서 : "데이터 송신"
    보안프로세서 <-- 메시징애플리케이션 : "데이터 송신"
    보안프로세서 <-- 웹기반외부리소스 : "상태 수신"
    사용자인터페이스 <-- 메시징애플리케이션 : "상태 표시"