%% 1020230048172 - 안면 인식 모듈 구성도
%% 생성일: 2026-05-11

classDiagram
    class 로컬인식모듈 {
        +String 이미지데이터
        +세부정보추출()
    }
    class 공유표현글로벌앙상블모듈 {
        +String 전체정보
        +정보학습()
    }
    class 랭크어텐션유닛모듈 {
        +String 가중치
        +예측결과결정()
    }
    class 복수보팅모듈 {
        +String 최종감정
        +결정()
    }
    로컬인식모듈 --> 공유표현글로벌앙상블모듈 : "입력 데이터 제공"
    공유표현글로벌앙상블모듈 --> 랭크어텐션유닛모듈 : "가중치 할당"
    랭크어텐션유닛모듈 --> 복수보팅모듈 : "예측 결과 결정"