%% 1020220075039 - 조리 공간 대여 프로세스 흐름도
%% 생성일: 2026-05-11

flowchart TD
    100["사용자 단말"]
    200["키오스크"]
    300["플랫폼 관리서버"]
    400["조리 공간 사용 및 비용 정산"]
    
    100 -->|"조리 공간 검색 및 예약"| 200
    200 -->|"대여 코드 유효성 확인"| 300
    300 -->|"정보 관리"| 200
    200 -->|"조리 공간 사용 및 비용 정산"| 400