%% 1020230025066 - 이형제 노즐 도포 분석 방법
%% 생성일: 2026-05-11

flowchart TD
    110["영상데이터 획득단계"]
    100["이형제 분사량 측정기술 개발단계"]
    120["분사량측정 인공지능모델 구현단계"]
    210["이미지데이터 획득단계"]
    200["이형제 도포품질 평가기술 개발단계"]
    220["도포품질평가 인공지능모델 구현단계"]
    
    110 -->|"포함"| 100
    110 -->|"이후"| 120
    210 -->|"포함"| 200
    210 -->|"이후"| 220