%% 1020210146786 - 문서 인식 결과 표시 방법 흐름도
%% 생성일: 2026-05-11

flowchart TD
    100["문서이미지"]
    200["키-밸류쌍 생성 모듈"]
    300["디스플레이 모듈"]
    400["사용자 입력 모듈"]
    100 -->|"입력"| 200
    200 -->|"출력"| 300
    300 -->|"입력"| 400