%% 1020210161676 - 데이터 압축 장치 구성도
%% 생성일: 2026-05-11

classDiagram
    class 사용자 {
        +데이터를 획득()
    }
    class "입력부" {
        +데이터 입력()
    }
    class "제1 인코더부" {
        +손실 압축된 제1 데이터 생성()
    }
    class "확률 분포 예측부" {
        +잔차 데이터의 확률 분포 예측()
    }
    class "제2 인코더부" {
        +무손실 압축된 제2 데이터 생성()
    }
    class "디코더부" {
        +손실없이 데이터 복원()
    }
    사용자 --> "입력부" : 데이터 입력
    "입력부" --> "제1 인코더부" : 데이터 입력
    "제1 인코더부" --> "확률 분포 예측부" : 제1 데이터 출력
    "확률 분포 예측부" --> "제2 인코더부" : 예측된 파라미터 입력
    "제2 인코더부" --> "디코더부" : 제2 데이터 출력
    "제1 인코더부" --> "디코더부" : 제1 데이터 입력