%% 1020210161676 - 데이터 압축 시스템 흐름도
%% 생성일: 2026-05-11

flowchart TD
    100["입력부"]
    200["제1 인코더부"]
    300["확률 분포 예측부"]
    400["제2 인코더부"]
    500["디코더부"]
    100 -->| "데이터 입력" | 200
    200 -->| "제1 데이터" | 300
    300 -->| "예측된 파라미터 입력" | 400
    400 -->| "제2 데이터" | 500
    200 -->| "제1 데이터 입력" | 500