%% 1020240135730 - 온실가스 배출 정보 거래 시스템 구성도
%% 생성일: 2026-05-11

classDiagram
    class 수신모듈 {
        +수신()
    }
    class 마켓플레이스모듈 {
        +등록()
        +승인()
    }
    class 제공모듈 {
        +제공()
    }
    class 정산모듈 {
        +보상제공()
    }
    수신모듈 --> 마켓플레이스모듈 : "수신"
    마켓플레이스모듈 --> 제공모듈 : "제공"
    마켓플레이스모듈 --> 수신모듈 : "승인 요청"
    수신모듈 --> 정산모듈 : "보상 제공"