%% 1020240135730 - 온실가스 배출 정보 거래 시스템 흐름도
%% 생성일: 2026-05-11

flowchart TD
    100["수신 모듈"]
    200["마켓플레이스 모듈"]
    300["제공 모듈"]
    400["정산 모듈"]
    100 -->|"온실가스 배출 정보 수신"| 200
    200 -->|"구매 요청 승인"| 300
    300 -->|"온실가스 배출 정보 제공"| 200
    400 -->|"보상 제공"| 100