%% 1020247011628 - 이송 챔버 로봇의 작동 흐름도
%% 생성일: 2026-05-11

flowchart TD
    100["이송 챔버"]
    200["툴 스테이션"]
    300["프로세스 챔버"]
    400["이송 챔버 로봇"]
    500["센서 툴"]
    
    100 -->|"결합"| 300
    300 -->|"리트리브"| 200
    400 -->|"측정 수행"| 300
    200 -->|"결합"| 500
    400 -->|"센서 데이터 획득"| 500
    400 -->|"부분 제거"| 300