%% 1020247011628 - 전자 디바이스 제조 시스템 구성도
%% 생성일: 2026-05-11

classDiagram
    class 이송챔버 {
        +String 역할: 기판을 프로세스 챔버로 이송하는 역할
    }
    class 툴스테이션 {
        +String 역할: 이송 챔버 내에 위치하여 센서 툴을 리트리브하는 역할
    }
    class 프로세스챔버 {
        +String 역할: 기판 제조 과정에서 사용되는 챔버
    }
    class 이송챔버로봇 {
        +String 역할: 기판을 이송하고 센서 툴을 통해 측정을 수행하는 로봇
    }
    class 센서툴 {
        +String 역할: 측정을 수행하는 센서들이 포함된 툴
    }
    이송챔버 --> 프로세스챔버 : "결합"
    툴스테이션 <-- 이송챔버로봇 : "리트리브"
    프로세스챔버 <-- 이송챔버로봇 : "측정 수행"
    이송챔버로봇 --> 센서툴 : "결합"
    프로세스챔버 <-- 센서툴 : "측정 수행"