%% 1020190075645 - 인기 상품 결정 흐름도
%% 생성일: 2026-05-11

flowchart TD
    100["매장장치"]
    200["운영서버"]
    300["저장영역"]
    400["고객"]
    400 -->| "주문" | 100
    100 -->| "통신" | 200
    200 -->| "저장" | 300
    300 -->| "인기 상품 분석 및 결정" | 200
    200 -->| "상품 정보 제공" | 100