%% 1020220175522 - 구성 요소 클래스 다이어그램
%% 생성일: 2026-05-11

classDiagram
    class 메시지확인부 {
        +String as요청메시지
        +확인()
    }
    class 선정부 {
        +String 대리점정보
        +선정()
    }
    class AS정보생성부 {
        +String 소모품정보
        +생성()
    }
    class 통합관리부 {
        +String 스케줄정보
        +관리()
    }
    메시지확인부 --> 선정부 : "AS 요청 메시지로부터 정보 수신"
    선정부 --> AS정보생성부 : "제품정보와 교체가능성 정보 수신"
    AS정보생성부 --> 통합관리부 : "정보 통합"