%% 1020220175522 - 인쇄 물품 재고관리 시스템 흐름도
%% 생성일: 2026-05-11

flowchart TD
    100["메시지확인부"]
    200["선정부"]
    300["AS정보 생성부"]
    400["통합관리부"]
    100 -->|"AS 요청 메시지로부터 정보 수신"| 200
    200 -->|"제품정보와 교체가능성 정보 수신"| 300
    300 -->|"정보 통합"| 400