%% 1020110097739 - 단말 장치 구조
%% 생성일: 2026-05-11

classDiagram
    class 단말장치 {
        +문서 작성 어플리케이션 실행
    }
    class 디스플레이부 {
        +문서 내용 및 제어창 UI 표시
    }
    class 제어창구성부 {
        +문서 작성 관련 제어 명령 포함
    }
    class 감지부 {
        +터치 입력 감지
    }
    class 디스플레이제어부 {
        +디스플레이부 내용 제어
    }
    class 기울기감지부 {
        +단말 장치 기울기 감지
    }
    class 각도판단부 {
        +기울기 각도 판단
    }
    단말장치 --> 디스플레이부 : "포함"
    단말장치 --> 제어창구성부 : "포함"
    단말장치 --> 감지부 : "포함"
    단말장치 --> 디스플레이제어부 : "포함"
    단말장치 --> 기울기감지부 : "포함"
    단말장치 --> 각도판단부 : "포함"