%% 1020110097739 - 디스플레이 제어 흐름
%% 생성일: 2026-05-11

flowchart TD
    110["단말 장치"]
    111["디스플레이부"]
    112["제어창 구성부"]
    113["감지부"]
    114["디스플레이 제어부"]
    115["기울기 감지부"]
    116["각도 판단부"]
    
    110 -->| "포함" | 111
    110 -->| "포함" | 112
    110 -->| "포함" | 113
    110 -->| "포함" | 114
    110 -->| "포함" | 115
    110 -->| "포함" | 116
    
    113 -->| "터치 입력 감지" | 115
    115 -->| "기울기 감지" | 116
    116 -->| "각도 판단" | 114
    114 -->| "디스플레이 영역 구분 및 내용 출력" | 111