%% 1020137012097 - P2P 거래 방법 흐름도
%% 생성일: 2026-05-11

flowchart TD
    100["P2P 지불 애플리케이션 (PPA)"]
    110["사용자 디바이스"]
    120["P2P 지불 시스템 (PPS)"]
    150["소셜 네트워크 시스템"]
    160["네트워크"]

    110 -->| "사용" | 100
    100 -->| "구성 정보 입력" | 120
    120 -->| "위치 데이터 수집" | 110
    120 -->| "소셜 네트워크 데이터 수집" | 150
    150 -->| "데이터 제공" | 120
    120 -->| "상대 리스트 전송" | 100
    100 -->| "상대 선택 및 거래 진행" | 120