%% 1020230097316 - 예약 및 픽업 프로세스 흐름도
%% 생성일: 2026-05-11

flowchart TD
    100["사용자 단말"]
    200["가맹점 단말"]
    300["플랫폼 서비스 제공 서버"]
    400["기한설정부"]
    500["주문접수부"]
    600["안내부"]
    700["전달부"]
    800["비활성화부"]
    900["준비알람부"]

    100 -->|"상품 주문 및 결제"| 500
    500 -->|"픽업날짜 지정 요청"| 100
    500 -->|"픽업날짜 지정"| 600
    600 -->|"픽업날짜 안내"| 100
    100 -->|"예약정보 및 픽업날짜 제공"| 200
    200 -->|"주문가능기한 설정"| 400
    400 -->|"주문가능기한 설정 요청"| 300
    300 -->|"예약정보 및 픽업날짜 전달"| 200
    200 -->|"예약정보 전달"| 700
    700 -->|"예약정보 및 픽업날짜 전달"| 300
    300 -->|"날짜 비활성화 안내"| 800
    800 -->|"비활성화 처리"| 100
    200 -->|"재료준비리스트 전달"| 900