%% 1020220032074 - 신경망 모델 구조
%% 생성일: 2026-05-11

classDiagram
    class 프로세서 {
        +String 분석방법
    }
    class 유전자온톨로지정보 {
        +String 유전자정보
    }
    class 신경망모델 {
        +학습()
        +분석()
    }
    class 유전자정보 {
        +String 데이터
    }
    프로세서 --> 신경망모델 : "실행됨"
    유전자온톨로지정보 --> 신경망모델 : "기초로 사용됨"
    유전자정보 --> 신경망모델 : "분석됨"