%% 1020220032074 - 유전자 정보 분석 방법 흐름도
%% 생성일: 2026-05-11

flowchart TD
    100["프로세서"]
    200["유전자 온톨로지 정보"]
    300["신경망 모델"]
    400["유전자 정보"]
    200 -->|"기초로 사용됨"| 300
    300 -->|"실행됨"| 100
    300 -->|"기반으로 함"| 200
    400 -->|"분석됨"| 300