%% 1020170003348 - 자바스크립트 분석 장치 구성도
%% 생성일: 2026-05-11

classDiagram
    class 시퀀스추출모듈 {
        +String 호출시퀀스
        +추출()
    }
    class 분류기학습모듈 {
        +String 특징벡터
        +학습()
    }
    class 분류모듈 {
        +String 모델
        +결정()
    }
    시퀀스추출모듈 --> 분류기학습모듈 : "제1 호출 시퀀스를 생성"
    분류기학습모듈 --> 분류모듈 : "모델을 수신"