%% 1020240163127 - 구성 요소 클래스 다이어그램
%% 생성일: 2026-05-11

classDiagram
    class 상품공급자단말 {
        +String 정품정보
    }
    class 해외셀러단말 {
        +String 상품정보
    }
    class 서버 {
        +String 가품탐지모델
        +산출매칭점수()
    }
    class 프로세서 {
        +String 명령어
        +동작수행()
    }
    class 메모리 {
        +String 저장명령어
    }
    상품공급자단말 --> 해외셀러단말 : "상품 공급자 단말과 연결"
    서버 --> 상품공급자단말 : "상품 공급자 단말로부터 정보 수집"
    서버 --> 해외셀러단말 : "해외 셀러 단말에 정보 제공"
    프로세서 --> 서버 : "서버의 주요 동작 수행"
    메모리 --> 서버 : "서버의 명령어 저장"