%% 1020240021816 - 셀러-브랜드 매칭 및 계약 지원 흐름도
%% 생성일: 2026-05-11

flowchart TD
    100["서버"]
    200["셀러 단말"]
    300["브랜드 단말"]
    400["컨택 인터페이스"]
    500["계약 인터페이스"]
    
    200 -->| "제공" | 100
    300 -->| "제공" | 100
    400 -->| "제공" | 100
    500 -->| "제공" | 100