%% 1020240021816 - 셀러-브랜드 시스템 구성도
%% 생성일: 2026-05-11

classDiagram
    class 서버 {
        +String 매칭지원
        +String 계약지원
        +String 정산지원
    }
    class 셀러단말 {
        +String 판매정보
    }
    class 브랜드단말 {
        +String 상품정보
    }
    class 컨택인터페이스 {
        +String 계약조건
    }
    class 계약인터페이스 {
        +String 계약서
    }
    서버 --> 셀러단말 : "제공"
    서버 --> 브랜드단말 : "제공"
    서버 --> 컨택인터페이스 : "제공"
    서버 --> 계약인터페이스 : "제공"
    셀러단말 <-- 서버 : "연결"
    브랜드단말 <-- 서버 : "연결"