%% 1020230003912 - 여행 체험 플랫폼 서비스 흐름도
%% 생성일: 2026-05-11

flowchart TD
    100["사용자 정보 저장부"]
    200["상품 정보 제공부"]
    300["제어부"]
    400["제 1 사용자 단말"]
    500["제 2 사용자 단말"]
    400 -->|"정보 전송"| 300
    500 -->|"정보 요청"| 300
    300 -->|"정보 수신 및 저장"| 100
    300 -->|"상품 정보 전송"| 200