%% 1020230003912 - 여행 체험 플랫폼 구성도
%% 생성일: 2026-05-11

classDiagram
    class 사용자정보저장부 {
        +String 여행정보
        +String 비용
    }
    class 상품정보제공부 {
        +String 상품정보
    }
    class 제어부 {
        +process 정보처리()
        +output 결과출력()
    }
    class 제1사용자단말 {
        +input 여행정보
        +output 결과
    }
    class 제2사용자단말 {
        +request 상품정보
        +output 결과
    }
    제1사용자단말 --> 제어부 : "정보 전송"
    제2사용자단말 --> 제어부 : "정보 요청"
    제어부 --> 사용자정보저장부 : "정보 수신 및 저장"
    제어부 --> 상품정보제공부 : "상품 정보 전송"