%% 1020210108151 - 멀티모달 학습 데이터 수집 및 분석 시스템 흐름도
%% 생성일: 2026-05-11

flowchart TD
    100["센서부"]
    200["제어부"]
    300["데이터베이스부"]
    400["알림부"]
    100 -->|"제어"| 200
    200 -->|"데이터 처리"| 300
    300 <--|"데이터 제공"| 200
    200 <--|"알림신호 수신"| 400