%% 1020200112589 - 시스템 구성도
%% 생성일: 2026-05-11

classDiagram
    class 제1코덱스부 {
        +바우처 발행 또는 소멸
    }
    class 딜러부 {
        +자산 교환 거래 관리
    }
    class 제2코덱스부 {
        +블록 생성
    }
    class 사용자계정 {
        +바우처 및 자산 거래 참여
    }
    사용자계정 --> 제1코덱스부 : "바우처 발행 요청"
    사용자계정 --> 딜러부 : "자산 교환 요청"
    딜러부 --> 제1코덱스부 : "바우처 발행 요청 처리"
    딜러부 --> 제2코덱스부 : "블록 생성 요청 처리"
    제2코덱스부 --> 딜러부 : "교환 거래에 따른 블록 생성"