%% 1020217010363 - 신호 처리 흐름도
%% 생성일: 2026-05-11

flowchart TD
    100["어레이 센서"]
    200["신호 처리부"]
    300["연산부"]
    400["출력부"]
    100 -->|"신호를 취득"| 200
    200 -->|"영역 정보를 생성"| 300
    300 -->|"영역 정보를 신호 처리부에 전달"| 200
    300 -->|"검출 신호를 기반으로 물체 검출"| 100
    200 -->|"신호 처리부로부터 출력 신호 수신"| 400