%% 1020210158508 - 게이트볼 서비스 흐름도
%% 생성일: 2026-05-11

flowchart TD
    100["게이트볼 관리 서버 시스템"]
    200["게이트볼 서비스 App"]
    300["챗봇 서버"]
    400["사용자"]
    
    400 -->|"게이트볼 서비스 요청"| 200
    200 -->|"연결"| 100
    100 -->|"제어"| 300
    300 -->|"질의 응답 수행"| 400