%% 1020180139369 - 전자 장치 구성도
%% 생성일: 2026-05-11

classDiagram
    class 하우징 {
        +String 구조
    }
    class 회전부재 {
        +회전()
    }
    class 디스플레이 {
        +정보표시()
    }
    class 프로세서 {
        +제어()
    }
    class 메모리 {
        +저장()
    }
    하우징 --> 회전부재 : "구성 요소"
    하우징 --> 디스플레이 : "구성 요소"
    하우징 --> 프로세서 : "구성 요소"
    프로세서 --> 디스플레이 : "제어"
    프로세서 --> 메모리 : "저장"