%% 1020230109772 - 건강 기록 분석 플랫폼 클래스 다이어그램
%% 생성일: 2026-05-11

classDiagram
    class 통신회로 {
        +String 데이터
        +전송()
    }
    class 프로세서 {
        +String 처리결과
        +데이터처리()
    }
    class 메모리 {
        +String 저장데이터
        +데이터저장()
    }
    통신회로 --> 프로세서 : "연결"
    프로세서 --> 메모리 : "데이터 처리"
    메모리 <-- 프로세서 : "데이터 저장"