%% 1020200091525 - 시스템 구성도
%% 생성일: 2026-05-11

classDiagram
    class 사용자단말 {
        +String 결제요청
    }
    class 서버 {
        +String 결제중계
        +String 소유권이전처리
    }
    class 온라인몰 {
        +String 상품정보제공
        +String 결제처리
    }
    사용자단말 --> 서버 : "결제 요청"
    서버 --> 온라인몰 : "상품 정보 요청"
    온라인몰 --> 서버 : "상품 정보 제공"
    서버 --> 사용자단말 : "결제 결과 통보"