%% 1020250034744 - 하이브리드 양자계산시스템 구성도
%% 생성일: 2026-05-11

flowchart TD
    100["제 1 큐비트레지스터"]
    200["큐비트변환기"]
    300["제 2 큐비트레지스터"]
    400["보정정보획득장치"]
    500["큐비트오류 보정장치"]
    600["측정센서"]
    
    100 -->|"연결"| 200
    200 -->|"연결"| 300
    200 -->|"연결"| 400
    400 -->|"연결"| 500
    400 -->|"연결"| 600