%% 1020240086488 - 시계열 영상 변화 추정 및 학습 데이터 구축 방법
%% 생성일: 2026-05-11

flowchart TD
    100["정사영상수집열서버"]
    200["유사도측정서버"]
    300["학습모델"]
    400["변화 여부 확인"]
    100 -->|"시계열 영상 확보"| 200
    200 -->|"유사도 측정"| 300
    300 -->|"변화 여부 확인"| 400