%% 1020240086488 - 처리 결과 전후 화면
%% 생성일: 2026-05-11

stateDiagram
    [*] --> "정사영상수집열서버"
    "정사영상수집열서버" -->|"시계열 영상 확보"| "유사도측정서버"
    "유사도측정서버" -->|"유사도 측정"| "학습모델"
    "학습모델" -->|"변화 여부 확인"| "유사도측정서버"
    "유사도측정서버" --> [*]