%% 1020240086488 - 시스템 블럭도
%% 생성일: 2026-05-11

classDiagram
    class 정사영상수집열서버 {
        +String 영상데이터
        +영상확보()
    }
    class 유사도측정서버 {
        +String 유사도결과
        +유사도측정()
    }
    class 학습모델 {
        +String 유사이미지
        +이미지생성()
    }
    정사영상수집열서버 --> 유사도측정서버 : "시계열 영상 확보"
    유사도측정서버 --> 학습모델 : "유사도 측정"