%% 1020200163675 - 뉴럴 네트워크 기반 계층 최적화 과정
%% 생성일: 2026-05-11

flowchart TD
    100["뉴럴 네트워크 장치"]
    200["물리적 매개변수"]
    300["하이퍼 매개변수"]
    400["최적의 파라미터"]
    500["최소채널크기"]
    600["RRAM"]
    
    100 -->|"사용됨"| 200
    100 -->|"사용됨"| 300
    100 -->|"생성됨"| 400
    100 -->|"사용됨"| 500
    100 -->|"최적화됨"| 600