%% 1020230060320 - 혜택 장소 검색 프로세스
%% 생성일: 2026-05-11

flowchart TD
    100["사용자 단말"]
    200["서버"]
    300["검색 정보"]
    400["그래픽 표현"]
    100 -->|"사용자가 입력"| 300
    300 -->|"서버에 전송"| 200
    200 -->|"소속 인증 요청 처리"| 100
    200 -->|"서버에서 전송"| 400
    400 -->|"사용자에게 표시"| 100