%% 1020240092022 - 시스템 구성도
%% 생성일: 2026-05-11

classDiagram
    class 사용자단말기 {
        +String 요청
        +인증()
    }
    class 시스템서버 {
        +String 지갑주소
        +String 광고속성정보
        +요청처리()
        +SBT발행()
    }
    class 정보저장부 {
        +String SBT
        +String 광고속성정보
        +정보저장()
    }
    class 블록체인노드 {
        +String SBT
        +정보기록()
    }
    사용자단말기 --> 시스템서버 : "요청 및 응답"
    시스템서버 --> 정보저장부 : "정보 저장"
    시스템서버 --> 블록체인노드 : "SBT 발행 및 관리"
    블록체인노드 --> 정보저장부 : "정보 기록"