%% 1020160098727 - 전자 장치 구성도
%% 생성일: 2026-05-11

classDiagram
    class 하우징 {
        +String 외부 구조
    }
    class 디스플레이 {
        +String 정보 제공
    }
    class 터치 센서 {
        +String 터치 감지
    }
    class 압력 센서 {
        +String 압력 감지
    }
    class 프로세서 {
        +String 동작 제어
    }
    class 메모리 {
        +String 인스트럭션 저장
    }
    하우징 --> 디스플레이 : "노출됨"
    디스플레이 --> 터치 센서 : "연결됨"
    터치 센서 --> 압력 센서 : "연결됨"
    압력 센서 --> 프로세서 : "연결됨"
    프로세서 --> 메모리 : "연결됨"