%% 1020200146542 - 비대면 트레이닝 서비스 흐름도
%% 생성일: 2026-05-11

flowchart TD
    100["사용자 단말"]
    200["서비스 서버"]
    300["트레이너 단말"]
    400["설문에 대한 답변 입력 및 전송"]
    500["운동수준 선택"]
    600["조건 입력"]
    700["트레이너 추천"]
    800["트레이너 선택 및 강좌 수강"]
    900["운동 결과 기록 및 전송"]
    100 -->| "데이터 전송" | 400
    400 -->| "데이터 전송" | 500
    500 -->| "데이터 전송" | 600
    600 -->| "트레이너 추천 요청" | 200
    200 -->| "트레이너 정보 제공" | 700
    700 -->| "트레이너 선택" | 800
    800 -->| "운동 결과 전송" | 900
    900 -->| "트레이너 평가 입력 및 전송" | 200
    200 -->| "강좌 정보 수신" | 300