%% 1020200025029 - 피트니스 서비스 시스템 구성도
%% 생성일: 2026-05-11

classDiagram
    class 회원DB {
        +String 수강정보
    }
    class 운동량산출모듈 {
        +String 운동정보
        +산출()
    }
    class 커뮤니티모듈 {
        +String 운동메이트
        +형성()
    }
    class 스케줄관리모듈 {
        +String 사용스케줄
        +관리()
    }
    class 동기부여모듈 {
        +String 보상
        +제공()
    }
    class 카페테리아모듈 {
        +String 이용정보
        +관리()
    }
    회원DB --> 운동량산출모듈 : "회원 정보 제공"
    운동량산출모듈 --> 커뮤니티모듈 : "운동량을 기반으로"
    커뮤니티모듈 --> 스케줄관리모듈 : "운동 메이트 정보 제공"
    스케줄관리모듈 --> 동기부여모듈 : "스케줄 정보 제공"
    동기부여모듈 --> 카페테리아모듈 : "보상 정보 제공"