%% 1020250081552 - 물류 운영 최적화 시스템 구성도
%% 생성일: 2026-05-11

classDiagram
    class 데이터저장유닛 {
        +String 상품정보
        +String 차량정보
    }
    class 물류흐름제어모듈 {
        +산출적재호환성지수()
        +제어적재방식()
    }
    class 배송계획모듈 {
        +산출동적배차적합도지수()
        +할당최적차량()
    }
    class 운영최적화모듈 {
        +분석과거배송데이터()
        +개선시스템()
    }
    데이터저장유닛 --> 물류흐름제어모듈 : "데이터 제공"
    데이터저장유닛 --> 배송계획모듈 : "데이터 제공"
    물류흐름제어모듈 --> 배송계획모듈 : "적재 정보 요청"
    배송계획모듈 --> 운영최적화모듈 : "피드백 제공"