%% 1020230150449 - 시스템 구성 요소
%% 생성일: 2026-05-11

classDiagram
    class 디스플레이부 {
        +String 화면
    }
    class 사용자입력부 {
        +String 입력데이터
    }
    class 컴퓨팅장치 {
        +디스플레이부 디스플레이
        +사용자입력부 입력부
    }
    class 서버 {
        +통신부 통신
        +저장부 저장
        +제어부 제어
    }
    class 제어부 {
        +process 사용자 입력 처리
        +crawling 기준 데이터 크롤링
        +checklist 체크리스트 생성
    }
    class 통신부 {
        +String 외부통신
    }
    class 저장부 {
        +String 도면 데이터
        +String 기준 데이터
    }

    사용자입력부 --> 컴퓨팅장치 : "사용자 입력 제공"
    컴퓨팅장치 --> 서버 : "서버와 연결"
    서버 --> 제어부 : "기준 데이터 제공"
    제어부 --> 통신부 : "기준 데이터 크롤링"
    제어부 --> 저장부 : "체크리스트 생성"