%% 1020180167336 - 폴더블 전자 장치 구성도
%% 생성일: 2026-05-11

classDiagram
    class 플렉서블디스플레이 {
        +String 화면구성
    }
    class 힌지어셈블리 {
        +String 접힘기능
    }
    class 열확산부재 {
        +String 열분산기능
    }
    class 제1브래킷 {
        +String 고정기능
    }
    class 제2브래킷 {
        +String 고정기능
    }
    플렉서블디스플레이 --> 힌지어셈블리 : "지지"
    플렉서블디스플레이 --> 열확산부재 : "열 전도"
    힌지어셈블리 --> 제1브래킷 : "고정"
    힌지어셈블리 --> 제2브래킷 : "고정"
    열확산부재 --> 힌지어셈블리 : "위치"