%% 1020230059664 - 이미지 캡션 생성 프로세스
%% 생성일: 2026-05-11

flowchart TD
    100["사용자 정의 객체 사전 데이터베이스"]
    200["획득부"]
    300["처리부"]
    400["캡션 생성 프로그램"]
    500["인공신경망"]
    
    200 -->| "객체 이미지 제공" | 500
    500 -->| "입력으로 객체 이미지 수신" | 300
    100 -->| "사용자 정의 객체 사전 참조" | 300
    300 -->| "캡션 생성 결과 출력" | 400