%% 1020230133557 - 멸구 분류 방법 흐름도
%% 생성일: 2026-05-11

flowchart TD
    100["타겟 이미지"]
    200["제1관심 영역 이미지"]
    300["제2관심 영역 이미지"]
    400["멸구 분류 모델"]
    500["프로세서"]
    100 -->|"획득"| 200
    200 -->|"획득"| 300
    100 -->|"처리"| 500
    200 -->|"처리"| 500
    300 -->|"처리"| 500
    500 -->|"입력"| 400