%% 1020230133557 - 해충 포집망 이미지
%% 생성일: 2026-05-11

classDiagram
    class 타겟이미지 {
        +String 이미지데이터
    }
    class 제1관심영역이미지 {
        +String 이미지데이터
    }
    class 제2관심영역이미지 {
        +String 이미지데이터
    }
    class 멸구분류모델 {
        +classify()
    }
    class 프로세서 {
        +process()
    }
    타겟이미지 --> 제1관심영역이미지 : "획득"
    제1관심영역이미지 --> 제2관심영역이미지 : "획득"
    제1관심영역이미지 --> 멸구분류모델 : "입력"
    제2관심영역이미지 --> 멸구분류모델 : "입력"
    타겟이미지 --> 프로세서 : "처리"
    제1관심영역이미지 --> 프로세서 : "처리"
    제2관심영역이미지 --> 프로세서 : "처리"
    프로세서 --> 멸구분류모델 : "사용"