%% 1020180116750 - 실험 가설 생성 방법 흐름도
%% 생성일: 2026-05-11

flowchart TD
    100["전처리부"]
    200["실험 변수 인코딩부"]
    300["실험 생성 모델부"]
    400["가설 시각화 모듈"]
    500["가설 임베딩 모듈"]
    
    100 -->|"입력"| 200
    200 -->|"입력"| 300
    200 -->|"출력"| 400
    300 -->|"입력"| 500