%% 1020230106520 - 인플루언서-판매자 통합 플랫폼 구조
%% 생성일: 2026-05-11

classDiagram
    class 인플루언서판매자통합플랫폼제공서버 {
        +사용자 정보 관리
        +권한 부여
        +대시보드 관리
        +이벤트 관리
    }
    class 인플루언서단말 {
        +상호작용()
    }
    class 판매자단말 {
        +상호작용()
    }
    class 구매자단말 {
        +이벤트 정보 수신()
    }
    class 이벤트관리부 {
        +이벤트 정보 관리()
        +전달()
    }
    class 사용자정보관리부 {
        +사용자 정보 관리()
        +평가 정보 생성()
    }
    class 사용자권한부여부 {
        +사용자 권한 관리()
        +쌍 형성()
    }
    class 인플루언서판매자통합대시보드관리부 {
        +대시보드 인터페이스 관리()
        +정보 표시()
    }

    인플루언서단말 --> 인플루언서판매자통합플랫폼제공서버 : "연결"
    판매자단말 --> 인플루언서판매자통합플랫폼제공서버 : "연결"
    구매자단말 --> 인플루언서판매자통합플랫폼제공서버 : "연결"
    이벤트관리부 --> 인플루언서판매자통합플랫폼제공서버 : "소속"
    사용자정보관리부 --> 인플루언서판매자통합플랫폼제공서버 : "소속"
    사용자권한부여부 --> 인플루언서판매자통합플랫폼제공서버 : "소속"
    인플루언서판매자통합대시보드관리부 --> 인플루언서판매자통합플랫폼제공서버 : "소속"