%% 1020100129423 - 신용카드 결제 시스템 구성도
%% 생성일: 2026-05-11

classDiagram
    class 휴대단말기 {
        +String 결제요청정보
        +String OTP생성()
    }
    class 물품구매서버 {
        +String 결제요청정보
        +상품결제요청()
    }
    class 유효성검증서버 {
        +String 결제정보
        +결제승인정보처리()
    }
    class 카드사서버 {
        +String 결제승인정보
        +결제정보처리()
    }
    class 애플리케이션 {
        +String OTP_PIN
        +결제요청처리()
    }
    class USIM칩 {
        +String OTP
        +결제요청정보처리()
    }
    휴대단말기 --> 물품구매서버 : "상품구매 요청정보 전송"
    휴대단말기 --> 유효성검증서버 : "결제 승인 요청정보 전송"
    유효성검증서버 --> 카드사서버 : "결제정보 전송"
    카드사서버 --> 유효성검증서버 : "상품결제 승인정보 수신"
    유효성검증서버 --> 휴대단말기 : "결제 SMS 전송"
    물품구매서버 --> 휴대단말기 : "상품구매 완료정보 전송"
    애플리케이션 --> 휴대단말기 : "OTP PIN 인증 요청"
    애플리케이션 --> USIM칩 : "OTP 생성 요청"
    USIM칩 --> 애플리케이션 : "OTP 생성 요청 수신"
    USIM칩 --> 유효성검증서버 : "결제 요청정보 전송"