%% 1020140153875 - 추천 시스템 구성도
%% 생성일: 2026-05-11

classDiagram
    class 컴퓨터시스템 {
        +추천 제공 방법 수행()
    }
    class 사용자모델 {
        +정보 갱신()
    }
    class 공간데이터구조 {
        +아이템 저장()
    }
    class 추천아이템 {
        +아이템 제공()
    }
    컴퓨터시스템 --> 사용자모델 : "갱신됨"
    컴퓨터시스템 --> 공간데이터구조 : "쿼리됨"
    공간데이터구조 --> 사용자모델 : "기반"
    컴퓨터시스템 --> 추천아이템 : "제공됨"