%% 1020240115140 - 수출입 업무 서비스 시스템 구성도
%% 생성일: 2026-05-11

classDiagram
    class 수출입업무서비스서버 {
        +String 프로세스관리
        +사진분석()
    }
    class 컨테이너운전자단말기 {
        +사진촬영()
        +정보입력()
    }
    class 컨테이너작업자단말기 {
        +사진촬영()
        +정보입력()
    }
    class AI사진분석프로그램 {
        +사진분석()
        +평가()
    }
    class OCR프로그램 {
        +텍스트인식()
        +저장()
    }
    수출입업무서비스서버 --> 컨테이너운전자단말기 : "사진을 전송함"
    수출입업무서비스서버 --> 컨테이너작업자단말기 : "사진을 전송함"
    수출입업무서비스서버 --> AI사진분석프로그램 : "서버에서 호출됨"
    수출입업무서비스서버 --> OCR프로그램 : "서버에서 호출됨"