%% 1020190081133 - 시스템 구성 요소 다이어그램
%% 생성일: 2026-05-11

classDiagram
    class 주문자App {
        +String 메뉴선택()
        +String 주문()
        +String 결제()
    }
    class 테이블주문용키오스크 {
        +String 주문처리()
    }
    class 주문확인용POS단말기 {
        +String 주문내역확인()
        +String 결제통계제공()
    }
    class 주방용메뉴정보표시장치 {
        +String 주문정보표시()
    }
    class 유무선랜공유기 {
        +String 데이터송수신()
    }
    주문자App --> 유무선랜공유기 : "연결"
    테이블주문용키오스크 --> 주문자App : "사용"
    테이블주문용키오스크 --> 유무선랜공유기 : "연결"
    주문확인용POS단말기 --> 테이블주문용키오스크 : "연결"
    주문확인용POS단말기 --> 유무선랜공유기 : "연결"
    주방용메뉴정보표시장치 --> 주문확인용POS단말기 : "연결"
    주방용메뉴정보표시장치 --> 유무선랜공유기 : "연결"