%% 1020240180773 - 드론 구성 요소 다이어그램
%% 생성일: 2026-05-11

classDiagram
    class 드론 {
        +String 기능
    }
    class 프로세서 {
        +제어()
        +데이터 처리()
    }
    class 카메라 {
        +영상 수집()
    }
    class GPU {
        +영상 전처리()
    }
    class 관제서버 {
        +신호 제공()
    }
    드론 <--> 관제서버 : "통신"
    프로세서 --> 카메라 : "제어"
    프로세서 --> GPU : "데이터 처리"
    카메라 <-- 프로세서 : "제어됨"
    GPU <-- 프로세서 : "연결됨"