%% 1020250071857 - 결제 서비스 제공 시스템 흐름도
%% 생성일: 2026-05-11

flowchart TD
    100["정보 데이터베이스"]
    200["회원 데이터베이스"]
    300["바코드 발급부"]
    400["결제 이벤트 발생부"]
    500["이체 요청부"]
    600["결제 완료부"]
    
    300 -->|"정보 요청"| 100
    300 -->|"회원 정보 요청"| 200
    400 -->|"회원 정보 확인"| 200
    500 -->|"전자지갑 정보 확인"| 100
    500 -->|"회원 정보 확인"| 200
    600 -->|"결제 이벤트 발생 후"| 400