%% 1020230142119 - 전자 장치의 동작 흐름
%% 생성일: 2026-05-11

flowchart TD
    100["프로세서"]
    200["메모리"]
    300["사용자 디바이스"]
    400["서버"]
    300 -->|"통신"| 400
    400 -->|"연결"| 100
    100 -->|"정량 데이터 획득"| 200
    200 -->|"예측 대상 질환 결정"| 100
    100 -->|"전처리"| 200
    200 -->|"질환 발생 확률 출력"| 400