%% 1020240146684 - 인공지능 모델 구성도
%% 생성일: 2026-05-11

classDiagram
    class 데이터수집모듈 {
        +수집데이터()
    }
    class 제1인공지능모델 {
        +특징추출()
    }
    class 제2인공지능모델 {
        +인사이트생성()
    }
    class 퓨전모듈 {
        +특징결합()
    }
    class 구조화된질의생성모듈 {
        +질의생성()
    }
    데이터수집모듈 --> 제1인공지능모델 : "데이터 수집"
    제1인공지능모델 --> 제2인공지능모델 : "특징 분석 결과 입력"
    제2인공지능모델 --> 구조화된질의생성모듈 : "인사이트 생성"
    제1인공지능모델 --> 퓨전모듈 : "특징 결합"