%% 1020167005538 - 주소 정보 영역 추출 흐름도
%% 생성일: 2026-05-11

flowchart TD
    100["획득 모듈"]
    200["확정 모듈"]
    300["인식 모듈"]
    400["트리밍 서브 모듈"]
    100 -->|"사용"| 200
    200 -->|"사용"| 300
    200 -->|"사용"| 400