%% 1020167005538 - 영역 추출 장치 구성도
%% 생성일: 2026-05-11

classDiagram
    class 획득모듈 {
        +영역 위치 획득()
    }
    class 확정모듈 {
        +정점 좌표 확정()
    }
    class 인식모듈 {
        +영역 분할 수행()
    }
    class 트리밍서브모듈 {
        +주소 정보 영역 트리밍()
    }
    획득모듈 --> 확정모듈 : "사용"
    확정모듈 --> 인식모듈 : "사용"
    확정모듈 --> 트리밍서브모듈 : "사용"