%% 1020250115591 - 구성 요소 클래스 다이어그램
%% 생성일: 2026-05-11

classDiagram
    class 데이터저장부 {
        +String 원본설계데이터
        +String 기준데이터
    }
    class 데이터수신부 {
        +String 촬영데이터
        +String 위치정보
        +String 시간정보
    }
    class 위조검출부 {
        +String 응답특성
        +판단위조여부()
    }
    class 데이터분석부 {
        +String 위조발생빈도
        +String 분포분석결과
    }
    데이터저장부 <|-- 데이터수신부 : "기준데이터와 연계"
    데이터저장부 <|-- 위조검출부 : "기준데이터 사용"
    데이터수신부 <|-- 위조검출부 : "촬영데이터 사용"
    위조검출부 <|-- 데이터분석부 : "위조 검출 결과 사용"