%% 1020250115591 - 스펙트럼 기반 코드이미지 위조 검출 시스템 흐름도
%% 생성일: 2026-05-11

flowchart TD
    100["데이터 저장부"]
    200["데이터 수신부"]
    300["위조 검출부"]
    400["데이터 분석부"]
    100 -->|"기준데이터와 연계"| 200
    200 -->|"촬영데이터 사용"| 300
    100 -->|"기준데이터 사용"| 300
    300 -->|"위조 검출 결과 사용"| 400