%% 1020250096518 - 동작 인식 장치 구성도
%% 생성일: 2026-05-11

classDiagram
    class 인식부 {
        +String description
    }
    class 인식모델 {
        +String description
        +weightOperation()
    }
    class 시각언어모델 {
        +String description
        +generateEmbedding()
    }
    class 시간분석기 {
        +String description
        +deriveVectors()
    }
    class 출력모듈 {
        +String description
        +softmaxOperation()
    }
    인식부 --> 인식모델 : "입력"
    인식모델 --> 시각언어모델 : "사용"
    인식모델 --> 시간분석기 : "사용"
    시각언어모델 --> 시간분석기 : "사용"
    시간분석기 --> 출력모듈 : "사용"