%% 1020250096518 - 동작 인식 방법 흐름도
%% 생성일: 2026-05-11

flowchart TD
    100["인식부"]
    200["인식모델"]
    300["시각언어모델"]
    400["시간분석기"]
    500["출력모듈"]
    100 -->| "입력" | 200
    200 -->| "사용" | 300
    200 -->| "사용" | 400
    300 -->| "사용" | 400
    400 -->| "사용" | 500