%% 1020230193866 - 구성 요소 및 관계
%% 생성일: 2026-05-11

classDiagram
    class 상점단말기 {
        +String 상품관리
        +String 주문관리
        +String 판매관리
    }
    class 소비자단말기 {
        +String 상품검색
        +String 주문요청
    }
    class 라이브커머스서비스제공부 {
        +String 상품판매방송
        +String 온라인매출정보생성
    }
    class 오픈마켓서비스제공부 {
        +String 상품정보전송
        +String 온라인매출정보생성
    }
    class DB {
        +String 온오프라인매출정보저장
        +String 카테고리화
    }
    class 판매예측모듈 {
        +String 판매예측
        +String 소비자행동분석
    }
    class 안내정보제공모듈 {
        +String 길찾기
        +String 교통정보제공
    }
    class 3D정보제공모듈 {
        +String 3D모델링
        +String 전통시장로드맵정보제공
    }
    class 증강현실제공부 {
        +String 증강현실모델구축
    }

    소비자단말기 -->| "주문 및 배송 요청 전송" | 상점단말기
    라이브커머스서비스제공부 -->| "상품 정보 제공" | 소비자단말기
    오픈마켓서비스제공부 -->| "상품 정보 전송" | 소비자단말기
    상점단말기 <--| "상점 정보 저장" | DB
    라이브커머스서비스제공부 <--| "매출 정보 저장" | DB
    오픈마켓서비스제공부 <--| "매출 정보 저장" | DB
    판매예측모듈 <--| "매출 정보 분석" | DB
    3D정보제공모듈 -->| "정보 제공" | 소비자단말기
    증강현실제공부 <--| "정보 활용" | 3D정보제공모듈