%% 1020230193866 - 스마트 전통시장 판매 예측 시스템 개요
%% 생성일: 2026-05-11

flowchart TD
    100["상점 단말기"]
    200["소비자 단말기"]
    300["라이브커머스 서비스 제공부"]
    400["오픈마켓 서비스 제공부"]
    500["DB"]
    600["판매 예측 모듈"]
    700["안내정보 제공 모듈"]
    800["3D 정보 제공 모듈"]
    900["증강현실 제공부"]

    100 -->| "상점 정보 저장" | 500
    200 -->| "주문 및 배송 요청 전송" | 100
    200 -->| "상품 정보 제공" | 300
    200 -->| "상품 정보 전송" | 400
    300 -->| "매출 정보 저장" | 500
    400 -->| "매출 정보 저장" | 500
    500 -->| "매출 정보 분석" | 600
    200 -->| "정보 제공" | 800
    800 -->| "정보 활용" | 900