%% 1020240139111 - 이벤트 기획 및 운영 계획 수립 과정
%% 생성일: 2026-05-11

flowchart TD
    100["사용자 단말"]
    200["이벤트 데이터베이스"]
    300["예산 결정 프로세스"]
    400["결과 제공"]
    100 -->|"기본 정보 제공"| 200
    200 -->|"유사도 결정 및 성과도 산출"| 300
    300 -->|"결과 제공"| 400
    400 -->|"결과 전달"| 100