%% 1020230170745 - 피트니스 센터 시스템 구성도
%% 생성일: 2026-05-11

classDiagram
    class 고객용단말 {
        +String 회원권구매기능
        +String 상담기능
    }
    class 피트니스센터전사적운영관리시스템 {
        +String 회원관리
        +String 운동스케줄관리
        +String 급여정산
    }
    class 관리자단말 {
        +String 운영관리기능
        +String 직원관리기능
    }
    고객용단말 --> 피트니스센터전사적운영관리시스템 : "지원"
    관리자단말 --> 피트니스센터전사적운영관리시스템 : "연결"