%% 1020207029856 - 모바일 디바이스 구성도
%% 생성일: 2026-05-11

classDiagram
    class 모바일디바이스 {
        +String 생체인식특성처리
    }
    class 광학센서 {
        +String 객체이미지획득
    }
    class 뉴럴네트워크 {
        +String 이미지처리
        +String 생체인식특성추출
    }
    class 저장디바이스 {
        +String 생체인식특성저장
    }
    class 식별수단 {
        +String 사용자식별
    }
    모바일디바이스 --> 광학센서 : "장착됨"
    광학센서 --> 뉴럴네트워크 : "입력받음"
    뉴럴네트워크 --> 저장디바이스 : "출력함"
    저장디바이스 --> 뉴럴네트워크 : "저장됨"
    저장디바이스 --> 식별수단 : "비교함"
    뉴럴네트워크 --> 식별수단 : "입력받음"