%% 1020207029856 - 사용자 식별 방법 흐름도
%% 생성일: 2026-05-11

flowchart TD
    100["모바일 디바이스"]
    200["광학 센서"]
    300["뉴럴 네트워크"]
    400["저장 디바이스"]
    500["식별 수단"]
    100 -->| "장착됨" | 200
    200 -->| "입력받음" | 300
    300 -->| "저장됨" | 400
    300 -->| "입력받음" | 500
    400 -->| "비교함" | 500