%% 1020170097848 - 인공 신경망 학습 방법 흐름도
%% 생성일: 2026-05-11

flowchart TD
    100["예측 기준 시점 설정기"]
    200["상태 추정 네트워크"]
    300["상태 전이 네트워크"]
    400["업데이터"]
    100 -->|"기준 시점 설정"| 200
    200 -->|"생성된 벡터를 기반으로 학습"| 300
    400 -->|"업데이트된 벡터를 기반으로 학습"| 200
    400 -->|"업데이트된 벡터를 기반으로 학습"| 300