%% 1020170097848 - 인공 신경망 구성도
%% 생성일: 2026-05-11

classDiagram
    class 예측기준시점설정기 {
        +설정기능()
    }
    class 상태추정네트워크 {
        +히든벡터생성()
        +셀벡터생성()
    }
    class 상태전이네트워크 {
        +상태기반학습()
    }
    class 업데이터 {
        +결과업데이트()
    }
    예측기준시점설정기 --> 상태추정네트워크 : "예측 기준 시점 설정"
    상태추정네트워크 --> 상태전이네트워크 : "생성된 벡터를 기반으로 학습"
    업데이터 --> 상태추정네트워크 : "업데이트된 벡터를 기반으로 학습"
    업데이터 --> 상태전이네트워크 : "업데이트된 벡터를 기반으로 학습"