%% 1020200076842 - 주식을 이용한 결제 방법
%% 생성일: 2026-05-11

flowchart TD
    100["고객 단말"]
    200["전자 화폐 결제 서버"]
    300["계정 관리 서버"]
    400["결제 단말"]
    500["주식 관리 서버"]
    600["지불 보증 서버"]
    
    100 -->|"결제 요청"| 400
    400 -->|"결제 요청"| 200
    200 -->|"매입 요청"| 300
    300 -->|"매입 요청 수신"| 200
    100 -->|"충전 요청"| 600
    600 -->|"충전 정보 제공"| 300
    500 -->|"주식 정보 제공"| 600