%% 1020210162275 - 가상 모델하우스 시뮬레이션 서비스 서버 구성도
%% 생성일: 2026-05-11

classDiagram
    class 사용자VR단말 {
        +String 사용자정보
        +정보전송()
        +선택입력()
    }
    class 가상모델하우스시뮬레이션서버 {
        +String 서비스정보
        +가상공간정보전송()
        +광고정보제공()
        +N배속시뮬레이션제공()
    }
    class 가전제품 {
        +String 제품정보
        +광고정보제공()
        +선택입력()
    }
    class 전력소모량및전기요금정보 {
        +String 소모량정보
        +정보제공()
        +산출기반()
    }
    사용자VR단말 --> 가상모델하우스시뮬레이션서버 : "정보 전송"
    가전제품 --> 사용자VR단말 : "선택 입력"
    가전제품 --> 가상모델하우스시뮬레이션서버 : "광고 정보 제공"
    전력소모량및전기요금정보 --> 사용자VR단말 : "정보 제공"
    전력소모량및전기요금정보 --> 가상모델하우스시뮬레이션서버 : "산출 기반"