%% 1020220180424 - NFT 발행 및 거래 과정 흐름도
%% 생성일: 2026-05-11

flowchart TD
    100["사용자 단말"]
    200["서버"]
    300["메타버스"]
    400["저작물의 NFT 발행"]
    500["저작물의 메타버스 내 전시"]
    600["사용자 캐릭터 생성"]
    700["저작물 체험 제공"]
    800["저작물의 NFT 거래 제공"]

    100 -->| "신호 전송" | 200
    200 -->| "신호 수신" | 100
    200 -->| "NFT 발행 요청 메시지 발송" | 400
    400 -->| "저작물의 NFT 발행" | 500
    500 -->| "메타버스 전시" | 300
    300 -->| "전시 요청" | 200
    200 -->| "메타버스 접속 요청 신호 수신" | 600
    600 -->| "사용자 캐릭터 생성" | 700
    700 -->| "거래 요청 신호 수신" | 200
    200 -->| "저작물의 NFT 거래 제공" | 800