%% 1020220180424 - 메타버스 기반 NFT 유통 플랫폼 서비스 흐름도
%% 생성일: 2026-05-11

flowchart TD
    100["사용자 단말"]
    200["서버"]
    300["메타버스"]
    400["저작물의 NFT 발행"]
    500["저작물의 메타버스 내 전시"]
    600["사용자 캐릭터 생성"]
    700["저작물 체험 제공"]
    800["저작물의 NFT 거래 제공"]

    100 -->| "저작물의 업로드 요청 신호 수신" | 200
    200 -->| "NFT 발행 요청 메시지 발송" | 400
    400 -->| "저작물의 NFT 발행" | 200
    200 -->| "메타버스 전시" | 300
    300 -->| "저작물의 메타버스 내 전시" | 500
    200 -->| "메타버스 접속 요청 신호 수신" | 300
    300 -->| "사용자 캐릭터 생성" | 600
    600 -->| "저작물 체험 제공" | 700
    200 -->| "거래 요청 신호 수신" | 800
    800 -->| "저작물의 NFT 거래 제공" | 200