%% 1020230068885 - 국내 사업 지원 및 언어 매칭 통합 서비스 시스템 흐름도
%% 생성일: 2026-05-11

flowchart TD
    100["서버"]
    200["고객 단말"]
    300["공유오피스 서버"]
    400["전문 인력 단말"]
    200 -->|"서비스 요청"| 100
    100 -->|"정보 송출"| 300
    300 -->|"임대 정보 및 결제 처리"| 100
    100 -->|"임대차계약서 제공 및 우편물 이미지 처리"| 400
    400 <--> 200