%% 1020240009607 - 전자 장치 구성도
%% 생성일: 2026-05-11

classDiagram
    class 전자장치 {
        +String NFT처리
    }
    class 스마트계약 {
        +String 발행요청처리
    }
    class 블록체인네트워크 {
        +String NFT기록
    }
    class 영수증 {
        +String 구매정보
    }
    전자장치 --> 스마트계약 : "실행하는 장치"
    전자장치 --> 블록체인네트워크 : "연결된 네트워크"
    스마트계약 --> 블록체인네트워크 : "정보 기록"
    영수증 --> 스마트계약 : "연관된 데이터"