%% 1020240009607 - NFT 처리 방법 흐름도
%% 생성일: 2026-05-11

flowchart TD
    100["전자 장치"]
    200["스마트 계약"]
    300["블록체인 네트워크"]
    400["영수증"]
    100 -->|"실행하는 장치"| 200
    200 -->|"연관된 데이터"| 400
    200 -->|"정보 기록"| 300
    100 -->|"연결된 네트워크"| 300