%% 1020210172385 - 정점 특성 예측 흐름도
%% 생성일: 2026-05-11

flowchart TD
    100["입출력부"]
    200["저장부"]
    300["제어부"]
    400["인코더"]
    500["특성 디코더"]
    600["레이블 디코더"]
    
    100 -->|"입출력"| 300
    300 -->|"프로그램 실행"| 200
    300 -->|"데이터 처리"| 400
    400 -->|"모델링"| 500
    400 -->|"모델링"| 600