%% 1020230101233 - 레이블링 방법 흐름도
%% 생성일: 2026-05-11

flowchart TD
    100["객체탐지부"]
    200["객체추적부"]
    300["행위식별부"]
    400["행동검출부"]
    500["클립처리부"]
    100 -->|"검출된 객체를 추적"| 200
    200 -->|"추적된 객체의 행위를 식별"| 300
    300 -->|"식별된 행위에 따라 이상행동 검출"| 400
    400 -->|"검출된 이상행동에 따라 클립 생성"| 500