%% 1020220109395 - 수산 식품 분류 처리 흐름도
%% 생성일: 2026-05-11

flowchart TD
    100["로봇암"]
    200["카메라"]
    300["분류처리부"]
    400["파지처리부"]
    500["학습부"]
    200 -->| "원본 영상 생성" | 300
    300 -->| "분류 정보 도출" | 400
    400 -->| "파지 정보 제공" | 100