%% 1020207035843 - 신경 네트워크 활동 특성화 방법
%% 생성일: 2026-05-11

flowchart TD
    100["데이터 프로세싱 장치"]
    200["인공 신경 네트워크"]
    300["시간 윈도우"]
    400["소집단 패턴"]
    
    300 -->|"신호 전송 활동을 한정"| 200
    200 -->|"활동을 특성화하는 방법을 수행"| 100
    200 -->|"신호 전송 활동의 특성을 나타냄"| 400