%% 1020170084177 - 사용자 인증 방법 흐름도
%% 생성일: 2026-05-11

flowchart TD
    100["입력 영상"]
    200["제1 환경 정보"]
    300["등록 특징 벡터"]
    400["퓨전 유사도"]
    500["인증 프로세서"]
    
    100 -->|"처리하는"| 500
    500 -->|"매칭되는"| 200
    200 -->|"매칭되는"| 300
    500 -->|"산출하는"| 400