%% 1020220110729 - 플랫폼 구성 요소 클래스 다이어그램
%% 생성일: 2026-05-11

classDiagram
    class 사업자단말기 {
        +String 결제정보
        +회원가입()
        +접속()
    }
    class VAN사서버 {
        +String 결제정보
        +고객서비스툴()
    }
    class PG사서버 {
        +String 결제정보
        +고객서비스툴()
    }
    class ERP시스템서버 {
        +String 세무신고정보
        +원천정보관리()
    }
    class Hometax {
        +String 세무정보
        +인증()
    }
    class 정보통합관리센터부 {
        +String 통합DB
        +정보가공()
    }
    사업자단말기 --> VAN사서버 : "결제정보 전송"
    사업자단말기 --> PG사서버 : "결제정보 전송"
    VAN사서버 --> 정보통합관리센터부 : "가공정보 전송"
    PG사서버 --> 정보통합관리센터부 : "가공정보 전송"
    ERP시스템서버 --> 정보통합관리센터부 : "정보 통합 관리"
    Hometax --> 정보통합관리센터부 : "정보 통합 관리"