%% 1020217017878 - 정보 예측 방법 흐름도
%% 생성일: 2026-05-11

flowchart TD
    100["예측될 이미지"]
    200["예측될 특징 세트"]
    300["타겟 결합 모델"]
    400["훈련 이미지 세트"]
    500["훈련 특징 세트"]
    600["훈련 레이블"]
    
    100 -->|"추출됨"| 200
    200 -->|"사용됨"| 300
    400 -->|"추출됨"| 500
    500 -->|"연관됨"| 600