%% 1020240155158 - 스마트 티켓 발권 시스템 구성도
%% 생성일: 2026-05-11

classDiagram
    class 키오스크부 {
        +String 요청
    }
    class 스마트디바이스 {
        +String 발권된티켓
        +요청()
    }
    class 관리서버 {
        +String 사용자정보
        +티켓발권()
    }
    class 게이트부 {
        +String 입장허가
    }
    키오스크부 --> 스마트디바이스 : "요청"
    스마트디바이스 --> 관리서버 : "발권"
    관리서버 --> 게이트부 : "정보 제공"
    게이트부 --> 스마트디바이스 : "입장"