%% 1020177006871 - 지능적 채점 방법 흐름도
%% 생성일: 2026-05-11

flowchart TD
    100["이미지 획득 모듈"]
    200["할당 모듈"]
    300["제1판단 모듈"]
    400["연산 모듈"]
    500["제2판단 모듈"]
    600["출력 모듈"]
    100 -->|"답안 이미지 획득"| 200
    200 -->|"할당 결과 판단"| 300
    300 -->|"판단 결과 기반 연산"| 400
    400 -->|"신뢰수준 기반 판단"| 500
    500 -->|"판단 결과 출력"| 600