%% 1020200131294 - 호스트 장치의 동작 방법
%% 생성일: 2026-05-11

flowchart TD
    100["호스트 장치"]
    200["스토리지 장치"]
    300["호스트 컨트롤러"]
    400["서브미션 큐"]
    500["컴플리션 큐"]
    
    100 -->|"연결"| 300
    300 -->|"커맨드를 서브미션 큐에 기입"| 400
    300 -->|"호스트 커맨드 크레딧을 스토리지 장치에 전송"| 200
    200 -->|"리스폰스를 컴플리션 큐에 기입"| 500