%% 1020117016711 - 시스템 구성도
%% 생성일: 2026-05-11

classDiagram
    class 웹프론트엔드서버 {
        +String 요청
        +요청전달()
    }
    class 갱신엔진 {
        +String 데이터소스
        +데이터전달()
        +결과반환()
    }
    class 커스텀데이터모듈 {
        +String 데이터
        +데이터검색()
        +데이터처리()
    }
    웹프론트엔드서버 --> 갱신엔진 : "요청 전달"
    갱신엔진 --> 커스텀데이터모듈 : "데이터 전달"
    커스텀데이터모듈 --> 갱신엔진 : "데이터 반환"
    갱신엔진 <-- 웹프론트엔드서버 : "결과 반환"