%% 1020220030349 - 플랫폼 서버 구성도
%% 생성일: 2026-05-11

classDiagram
    class 플랫폼서버 {
        +String 거래상황관리()
        +String SCM코드생성()
    }
    class 소비자 {
        +String 리뷰NFT생성()
        +String 경로요청()
    }
    class 판매자 {
        +String 제품제공()
    }
    class 리뷰NFT {
        +String 리뷰정보
    }
    class 블록체인노드 {
        +String 거래검증()
    }
    소비자 -->|거래 요청| 플랫폼서버 : 
    판매자 <--|거래 정보 제공| 플랫폼서버 : 
    리뷰NFT -->|경로 생성에 사용| 플랫폼서버 : 
    블록체인노드 <--|거래 검증| 리뷰NFT :