%% 1020220030349 - 경로 생성 서비스 제공 방법 흐름도
%% 생성일: 2026-05-11

flowchart TD
    100["플랫폼 서버"]
    200["소비자"]
    300["판매자"]
    400["리뷰 NFT"]
    500["블록체인 노드"]
    
    200 -->| "거래 요청" | 100
    300 <--| "거래 정보 제공" | 100
    100 -->| "SCM 코드 생성" | 200
    200 -->| "리뷰 NFT 생성" | 400
    400 -->| "경로 생성에 사용" | 100
    400 <--| "거래 검증" | 500