%% 1020190093807 - 수어 또는 제스처 인식 방법 흐름도
%% 생성일: 2026-05-11

flowchart TD
    100["2D EDM 생성부"]
    200["3D EDM 생성부"]
    300["관절 정보 생성부"]
    400["오류보정부"]
    500["인식부"]
    100 -->|"입력"| 200
    200 -->|"입력"| 300
    300 -->|"입력"| 400
    200 -->|"입력"| 500
    400 -->|"입력"| 500