%% 1020220043374 - 과금 처리 방법 흐름도
%% 생성일: 2026-05-11

flowchart TD
    100["채널 형성부"]
    200["카운팅부"]
    300["금액 산출부"]
    400["금액 정보 제공부"]
    500["변환부"]
    600["충전금 처리부"]
    
    100 -->|"채널 형성"| 200
    200 -->|"음소 개수 카운팅"| 300
    300 -->|"산정 금액 표시"| 400
    500 -->|"음소 개수 카운팅에 사용"| 200
    600 -->|"충전금 관리"| 100