%% 1020220157930 - 대체 불가능 토큰 발행 프로세스
%% 생성일: 2026-05-11

flowchart TD
    100["플랫폼 운영자 장치"]
    200["통신 유닛"]
    300["블록체인망"]
    400["피투자자 단말"]
    500["투자자 단말"]
    
    400 <--| "요청" | 100
    500 <--| "요청" | 100
    100 -->| "통신" | 200
    100 -->| "관리" | 300
    200 -->| "대체 불가능 토큰 발행 요청 수신" | 300
    300 -->| "블록체인망에서 발행 계약 코드 실행" | 200
    200 -->| "투자자 단말에 토큰 전송 및 거래 완료" | 500