%% 1020220157930 - 시스템 구성 요소
%% 생성일: 2026-05-11

classDiagram
    class 플랫폼운영자장치 {
        +String 기능
        +발행()
        +관리()
    }
    class 통신유닛 {
        +String 기능
        +연결()
    }
    class 블록체인망 {
        +String 기록
        +저장()
    }
    class 피투자자단말 {
        +String 사용자정보
        +요청()
    }
    class 투자자단말 {
        +String 사용자정보
        +요청()
    }
    플랫폼운영자장치 --> 통신유닛 : "통신"
    플랫폼운영자장치 --> 블록체인망 : "관리"
    피투자자단말 <-- 플랫폼운영자장치 : "요청"
    투자자단말 <-- 플랫폼운영자장치 : "요청"