%% 1020197013747 - 요금 시스템 구성도
%% 생성일: 2026-05-11

classDiagram
    class 인바운드과금장치 {
        +String 바코드스캔()
        +정보전송()
    }
    class 아웃바운드과금장치 {
        +String 아웃바운드정보처리()
        +정보전송()
    }
    class 서비스시스템 {
        +String 사용자ID
        +요금처리()
    }
    class 클라이언트디바이스 {
        +String 사용자정보
        +요금지불()
    }
    클라이언트디바이스 --> 인바운드과금장치 : "바코드 스캔"
    인바운드과금장치 --> 아웃바운드과금장치 : "정보 전송"
    아웃바운드과금장치 --> 서비스시스템 : "정보 전송"