%% 1020197013747 - 교통 구간 요금 지불 방법 흐름도
%% 생성일: 2026-05-11

flowchart TD
    100["인바운드 과금 장치"]
    200["아웃바운드 과금 장치"]
    300["서비스 시스템"]
    400["클라이언트 디바이스"]
    400 -->|"인바운드 바코드 스캔"| 100
    100 -->|"정보 전송"| 200
    200 -->|"아웃바운드 바코드 스캔"| 300
    300 -->|"요금 결제"| 400