%% 1020230131860 - 정보시스템 전체 구성도
%% 생성일: 2026-05-11

flowchart TD
    100["KoCharELECTRA 모델"]
    200["FFNN"]
    300["양방향 LSTM"]
    400["CRFs"]
    100 -->|"입력받음"| 200
    200 -->|"연결됨"| 300
    200 -->|"연결됨"| 400