%% 1020210168032 - 배터리 진단 방법 흐름도
%% 생성일: 2026-05-11

flowchart TD
    100["배터리진단장치"]
    110["프로파일예측모델"]
    120["상태예측모델"]
    130["전압파형"]
    140["열화상태"]
    210["전압프로파일"]
    
    100 -->| "포함" | 110
    100 -->| "포함" | 120
    100 -->| "입력" | 130
    110 -->| "입력" | 130
    110 -->| "출력" | 210
    120 -->| "입력" | 210
    120 -->| "출력" | 140