%% 1020230075924 - 광고 시스템 동작 방법
%% 생성일: 2026-05-11

flowchart TD
    100["마켓 플레이스 서버"]
    200["사용자 기기"]
    300["광고주 서비스 서버"]
    400["데이터베이스"]
    200 -->|"광고 판매 정보 전송"| 100
    100 -->|"광고 판매 정보 저장"| 400
    100 -->|"광고 구매 요청 수신"| 300
    300 -->|"광고 구매 정보 수신"| 100