%% 1020230064122 - 온실가스 배출권 거래 시스템 흐름도
%% 생성일: 2026-05-11

flowchart TD
    100["크레딧 공급 기업 서버"]
    200["인증 서버"]
    300["추천 시스템"]
    400["수요 기업 서버"]
    100 <--|"감축 정보 수신"| 200
    200 -->|"진위 여부 판단"| 300
    300 <--|"감축 사실 정보 비교"| 200
    300 -->|"추천 증명서 표시"| 400
    400 <--|"추천 증명서 수신"| 300