%% 1020230064122 - 크레딧 거래 시스템 구성도
%% 생성일: 2026-05-11

classDiagram
    class 크레딧공급기업서버 {
        +String 감축정보
    }
    class 인증서버 {
        +String 진위여부
        +판단()
    }
    class 추천시스템 {
        +String 추천증명서
        +추천()
    }
    class 수요기업서버 {
        +String 표시된증명서
    }
    크레딧공급기업서버 --> 인증서버 : "감축 정보 수신"
    인증서버 --> 추천시스템 : "진위 여부 판단"
    추천시스템 --> 수요기업서버 : "추천 증명서 표시"
    추천시스템 <-- 인증서버 : "감축 사실 정보 비교"
    수요기업서버 <-- 추천시스템 : "추천 증명서 수신"