%% 1020207035847 - 신경 네트워크 신호 전송 프로세스
%% 생성일: 2026-05-11

flowchart TD
    100["소스 순환 신경 네트워크"]
    200["입력"]
    300["액추에이터"]
    400["센서"]
    500["교사 모듈"]
    200 -->|"입력 데이터 제공"| 100
    100 -->|"출력 수신"| 300
    400 -->|"측정 데이터 제공"| 300
    400 -->|"측정 데이터 해석"| 500
    500 -->|"보상 및 후회 제공"| 100