%% 1020240001497 - 경로 생성 서비스 제공 방법 흐름도
%% 생성일: 2026-05-11

flowchart TD
    100["플랫폼 서버"]
    200["소비자"]
    300["SCM 코드"]
    400["리뷰 NFT"]
    100 -->|"거래 상황 관리"| 200
    200 -->|"리뷰 NFT 생성"| 400
    100 -->|"SCM 코드 제공"| 300
    300 -->|"사용됨"| 200
    100 -->|"경로 생성"| 400