%% 1020220088711 - 미세먼지 농도 예측 및 발생원 추론 프로세스
%% 생성일: 2026-05-11

flowchart TD
    100["데이터 수집 인터페이스"]
    200["CNN 모델"]
    300["RNN 모델"]
    400["CAM 적용 프로세서"]
    100 -->|"데이터 수집"| 200
    200 -->|"미세먼지 발생 등급 보정"| 300
    300 -->|"미세먼지 발생 등급 사용"| 400