%% 1020227015892 - 로봇 디바이스 자세 식별 프로세스
%% 생성일: 2026-05-11

flowchart TD
    100["로봇 디바이스"]
    200["신경망"]
    300["촉각 센서"]
    400["메모리"]
    500["프로세서"]
    300 -->| "데이터 제공" | 200
    200 -->| "신경망 저장" | 400
    500 -->| "신경망 훈련" | 200
    500 -->| "자세 식별 수행" | 100
    100 -->| "자세 식별을 위한 데이터 제공" | 200