%% 1020200079497 - 가상코인 기반 쓰레기 수거 비용 관리 흐름도
%% 생성일: 2026-05-11

flowchart TD
    100["사용자 관리부"]
    200["가상지갑 관리부"]
    300["코인충전/차감부"]
    400["리더기"]
    500["사용자 단말"]
    
    100 <--|"사용자 정보 제공"| 200
    200 -->|"가상코인 전달"| 300
    500 -->|"결제정보 제공"| 300
    400 -->|"가상코인 차감 요청"| 300
    300 -->|"가상코인 차감 및 이체"| 200