%% 1020220168043 - 인메모리 연산 장치 구성도
%% 생성일: 2026-05-11

classDiagram
    class 입출력단 {
        +String 데이터
        +String 커맨드
        +String 어드레스
    }
    class PIM_IU {
        +String 입력신호
        +processRequest()
    }
    class 메모리_뱅크 {
        +performInMemoryOperation()
    }
    class 레지스터 {
        +String 저장된데이터
        +String 결과전달()
    }
    입출력단 --> PIM_IU : "입출력신호 수신"
    PIM_IU --> 메모리_뱅크 : "메모리 뱅크와 연산 요청 처리"
    메모리_뱅크 --> 레지스터 : "메모리 뱅크와 데이터 저장 및 전달"