%% 1020220168043 - 인메모리 연산 동작 흐름도
%% 생성일: 2026-05-11

flowchart TD
    100["입출력단"]
    200["PIM IU"]
    300["메모리 뱅크"]
    400["레지스터"]
    100 -->|"입출력신호 수신"| 200
    200 -->|"메모리 뱅크와 연산 요청 처리"| 300
    300 -->|"메모리 뱅크와 데이터 저장 및 전달"| 400