%% 1020197028921 - 내비게이션 시스템 구성도
%% 생성일: 2026-05-11

classDiagram
    class 전자프로세서 {
        +String 데이터처리
        +String 이미지라벨링
    }
    class 카메라 {
        +String 이미지캡처
        +String 데이터전송
    }
    class 지도 {
        +String 피처정보
        +String 로딩
    }
    전자프로세서 --> 카메라 : "이미지 캡처"
    전자프로세서 --> 지도 : "지도 로딩"
    카메라 --> 전자프로세서 : "데이터 전송"
    지도 --> 전자프로세서 : "로딩"