%% 1020160051877 - 사용자 인터랙션 흐름도
%% 생성일: 2026-05-11

flowchart TD
    10["커뮤니티부"]
    20["마켓부"]
    30["결제부"]
    40["검색부"]
    10 -->|"사용자가 회원가입"| 40
    40 -->|"엔터테이너 정보 검색"| 20
    20 -->|"상품 구매 또는 경매 참여"| 30