%% 1020230130050 - 시스템 구성도
%% 생성일: 2026-05-11

classDiagram
    class 서버 {
        +String 이벤트처리
        +배출권획득()
    }
    class 메모리 {
        +String 명령어저장
    }
    class 프로세서 {
        +String 명령어실행
        +이벤트처리()
    }
    서버 --> 메모리 : "명령어를 실행"
    프로세서 --> 서버 : "서버의 일부"
    프로세서 --> 메모리 : "명령어를 실행"