%% 1020230130050 - 탄소 저감 이벤트 처리 흐름도
%% 생성일: 2026-05-11

flowchart TD
    100["서버"]
    200["메모리"]
    300["프로세서"]
    400["탄소 저감 이벤트 획득"]
    500["탄소 저감량 판별"]
    600["탄소 배출권 획득"]
    
    400 -->|"이벤트 수집"| 100
    100 -->|"명령어를 실행"| 300
    300 -->|"판별 결과"| 500
    500 -->|"배출권 획득"| 600