%% 1020240181445 - 의약품 원료 공급 플랫폼 서비스 흐름도
%% 생성일: 2026-05-11

flowchart TD
    100["구매자 단말"]
    200["서버"]
    300["공급사 단말"]
    400["최종 견적 정보"]
    500["구매 요청 정보"]
    600["배송 추적 정보"]
    700["재고 정보"]
    800["배송 완료 메시지"]

    100 -->| "검색 정보 제공" | 200
    200 -->| "주문 정보 수신" | 100
    100 -->| "주문 정보 제공" | 300
    300 -->| "견적 정보 제공" | 200
    200 -->| "최종 견적 정보 제공" | 400
    100 -->| "최종 견적 정보 수신" | 400
    200 -->| "구매 요청 정보 수신" | 500
    100 -->| "구매 요청 정보 제공" | 500
    200 -->| "배송 추적 정보 제공" | 600
    100 -->| "배송 추적 정보 수신" | 600
    200 -->| "재고 정보 수신" | 700
    100 -->| "재고 정보 수신" | 700
    200 -->| "배송 완료 메시지 전송" | 800
    100 -->| "배송 완료 메시지 수신" | 800