%% 1020230107281 - 자산 거래 지원 시스템 내부 구성도
%% 생성일: 2026-05-11

flowchart TD
    100["제1 수신부"]
    200["생성부"]
    300["제2 수신부"]
    400["자산 거래 관리부"]
    100 -->|"자산 거래 요청 정보 수신"| 200
    200 -->|"제1 링크를 통해 접속"| 300
    300 -->|"자산 거래 수락 정보 참조"| 400