%% 1020240097010 - 가축 개체군 비정상 사육 상태 정보 산출 방법
%% 생성일: 2026-05-11

flowchart TD
    100["프로세서"]
    200["메모리"]
    300["축사 이미지"]
    400["인덱스 계열 정보"]
    300 -->|"분석 대상"| 100
    200 <--|"명령을 제공"| 100
    400 -->|"비정상 상태 판단에 사용"| 100