%% 1020257019800 - 권선 프로세스 모니터링 흐름도
%% 생성일: 2026-05-11

flowchart TD
    30["권선 장치"]
    20["변압기 권선"]
    40["컴퓨터 비전 시스템"]
    37["인간 기계 인터페이스(HMI)"]
    49["설계 데이터"]
    100["머신 러닝 모델"]

    30 <--|형성됨| 20
    30 -->|모니터링| 40
    20 -->|이미지 프로세싱| 40
    40 -->|실행됨| 100
    40 <--|비교됨| 49
    40 -->|불일치 검출| 37