%% 1020240108647 - 정전식 버튼용 햅틱 장치의 작동 흐름도
%% 생성일: 2026-05-11

flowchart TD
    100["터치제어모듈"]
    200["햅틱제어모듈"]
    300["진동소자 및 클릭커소자"]
    100 -->|"트리거 신호를 출력"| 200
    200 -->|"진동소자와 클릭커소자를 구동"| 300
    200 <--|"트리거 신호를 입력받음"| 100
    300 <--|"햅틱제어모듈에 의해 구동됨"| 200