%% 1020220016773 - 지적재산권 거래 시스템 구성도
%% 생성일: 2026-05-11

classDiagram
    class 지적재산권등록부 {
        +String 지적재산권정보
        +인증절차진행()
    }
    class NFT발행부 {
        +String NFT정보
        +발행()
    }
    class NFT및지적재산권정보제공부 {
        +String 메타정보
        +정보제공()
    }
    class NFT거래서비스제공부 {
        +String 거래정보
        +거래서비스제공()
    }
    class 로열티관리부 {
        +String 로열티정보
        +관리및분배()
    }
    class 연차료납부관리부 {
        +String 청구정보
        +청구및납부관리()
    }
    지적재산권등록부 --> NFT발행부 : "등록된 지적재산권 정보 사용"
    NFT발행부 --> NFT및지적재산권정보제공부 : "발행된 NFT 정보 제공"
    NFT발행부 --> NFT거래서비스제공부 : "발행된 NFT 사용"
    NFT및지적재산권정보제공부 --> NFT거래서비스제공부 : "정보 제공"
    지적재산권등록부 --> 로열티관리부 : "지적재산권 정보 사용"
    지적재산권등록부 --> 연차료납부관리부 : "지적재산권 정보 사용"