%% 1020197006033 - 디스플레이 시스템 구성도
%% 생성일: 2026-05-11

classDiagram
    class 디스플레이스크린 {
        +String 프로젝션정보
        +프로젝션()
    }
    class 프로세서 {
        +String 이미지데이터
        +인증수행()
    }
    class 컴퓨터단말기 {
        +String 프로젝션정보
        +이미지획득()
    }
    디스플레이스크린 --> 프로세서 : "제어"
    컴퓨터단말기 --> 프로세서 : "연결"