%% 1020177035954 - 프로그램가능한 IC 구조도
%% 생성일: 2026-05-11

classDiagram
    class 프로그램가능한IC {
        +메모리 관리 기능
    }
    class 프로세서서브시스템 {
        +메모리 어드레스 공간의 제1 부분
    }
    class 프로그램가능한로직서브시스템 {
        +메모리 어드레스 공간의 제2 부분
    }
    class 캐시회로 {
        +프로세서 서브시스템과 프로그램가능한 로직 서브시스템에 커플링
    }
    class 가상메모리블록회로 {
        +가상 메모리 블록 구현
    }
    프로그램가능한IC <-- 프로세서서브시스템 : 구성 요소
    프로세서서브시스템 --> 캐시회로 : 연관
    프로그램가능한로직서브시스템 --> 캐시회로 : 연관
    프로그램가능한로직서브시스템 --> 가상메모리블록회로 : 구현