%% 1020177035954 - 메모리 관리 방법 흐름도
%% 생성일: 2026-05-11

flowchart TD
    100["프로그램가능한 IC"]
    200["프로세서 서브시스템"]
    300["프로그램가능한 로직 서브시스템"]
    400["캐시 회로"]
    500["가상 메모리 블록 회로"]
    
    100 -->| "구성 요소" | 300
    200 -->| "커플링" | 300
    200 -->| "연관" | 400
    300 -->| "연관" | 400
    300 -->| "구현" | 500