%% 1020230104523 - 차량 가치평가 및 보상 시스템 흐름도
%% 생성일: 2026-05-11

flowchart TD
    100["관리서버"]
    200["스마트폰"]
    300["차량 데이터 서버"]
    400["블록체인 서버"]
    500["AI 서버"]
    
    200 -->| "데이터 요청 및 수신" | 100
    100 -->| "데이터 제공 요청" | 300
    300 -->| "데이터 수신" | 400
    400 -->| "분석 요청" | 500
    500 -->| "결과 통지" | 200
    400 -->| "분석 결과 제공" | 300