%% 1020230118745 - Residual CNN-LSTM 모델 구조
%% 생성일: 2026-05-11

flowchart TD
    300["온도 센서"]
    100["Residual CNN-LSTM 모델"]
    200["ConvLSTM-VAE 모델"]
    300 -->|"입력값 제공"| 100
    100 -->|"입력값을 받아 예측값을 생성"| 200