%% 1020227009700 - 정규화 회로 구조도
%% 생성일: 2026-05-11

classDiagram
    class 정규화회로 {
        +수신값()
        +정규화값생성()
    }
    class 정규화레지스터컬럼 {
        +정규화값저장()
        +처리()
    }
    class 정규화레지스터 {
        +정규화값계산()
        +전달()
    }
    class 활성화회로 {
        +함수적용()
        +활성화값생성()
    }
    class 풀링회로 {
        +정규화값풀링()
        +풀링값생성()
    }
    정규화회로 --> 정규화레지스터컬럼 : "구성 요소"
    정규화레지스터컬럼 --> 정규화레지스터 : "소속"
    정규화회로 --> 활성화회로 : "커플링"
    정규화회로 --> 풀링회로 : "구성 요소"