%% 1020220103522 - 데이터 수집 프로세스 흐름도
%% 생성일: 2026-05-11

flowchart TD
    100["실행 관리부"]
    200["실행 처리부"]
    300["전처리 수행부"]
    400["데이터 수집부"]
    500["밸류 레포지토리"]
    100 -->| "요청 수신" | 200
    200 -->| "전처리 데이터 수집 요청 생성" | 300
    200 -->| "수집모듈 실행 개시" | 300
    300 -->| "전처리 데이터 수집 결과 수신" | 400
    300 -->| "밸류 레포지토리에 데이터 저장" | 500