%% 1020220103522 - 데이터 수집 시스템 구성도
%% 생성일: 2026-05-11

classDiagram
    class 실행관리부 {
        +요청 수신()
    }
    class 실행처리부 {
        +수집모듈 실행()
        +전처리 데이터 수집 요청 생성()
    }
    class 전처리수행부 {
        +전처리 데이터 저장()
    }
    class 데이터수집부 {
        +데이터 통합 저장()
    }
    class 밸류레포지토리 {
        +데이터 저장()
    }
    실행관리부 --> 실행처리부 : "요청 수신"
    실행처리부 --> 전처리수행부 : "전처리 데이터 수집 요청 생성"
    전처리수행부 --> 밸류레포지토리 : "밸류 레포지토리에 데이터 저장"
    전처리수행부 --> 데이터수집부 : "전처리 데이터 수집 결과 수신"