%% 1020097000804 - 시스템 구성도
%% 생성일: 2026-05-11

classDiagram
    class 휴대용소비자기기 {
        +String 거래데이터
    }
    class 백엔드컴퓨터 {
        +String 동적데이터요소
        +String 검증값생성()
    }
    class POS단말 {
        +String 지불데이터
        +processPayment()
    }
    휴대용소비자기기 --> 백엔드컴퓨터 : "데이터 수신"
    백엔드컴퓨터 --> POS단말 : "검증 값 생성"
    POS단말 --> 백엔드컴퓨터 : "데이터 전달"