%% 1020240056060 - 물류 배송 자동화 프로세스
%% 생성일: 2026-05-11

flowchart TD
    100["화주 단말"]
    200["배송 기사 단말"]
    300["출고 창고"]
    400["물류 처리 시스템"]
    500["비용 정산"]
    
    100 -->|"물류 배송 요청 수신"| 400
    400 -->|"업무 지시 전송"| 200
    200 -->|"업무 지시 승인 수신"| 400
    400 -->|"재고 차감 지시"| 300
    300 -->|"재고 정보 차감"| 400
    200 -->|"배송 및 설치 완료 정보 송신"| 400
    400 -->|"비용 정산 정보 수신"| 500