%% 1020160021837 - 출장 예약 시스템 구성도
%% 생성일: 2026-05-11

classDiagram
    class 출장결재서버 {
        +String 출장정보
        +결재진행()
    }
    class 출장예약서버 {
        +String 예약정보
        +일정예약()
        +결제처리()
    }
    class 외부예약서버 {
        +String 예약데이터
        +예약처리()
    }
    class 사원정보유닛 {
        +String 개인정보
        +정보제공()
    }
    class 규정정보유닛 {
        +String 출장규정
        +정보매칭()
    }
    출장결재서버 --> 출장예약서버 : "연동"
    출장예약서버 --> 외부예약서버 : "정보 수신"
    외부예약서버 <-- 출장예약서버 : "정보 수신"
    사원정보유닛 <-- 출장결재서버 : "정보 제공"
    규정정보유닛 <-- 출장결재서버 : "정보 매칭"