%% 1020220171834 - 승객 탑재중량 등록 과정
%% 생성일: 2026-05-11

flowchart TD
    100["사용자 단말부"]
    200["블록체인 네트워크"]
    300["탑재중량 등록부"]
    400["탑재중량 거래부"]
    100 -->|"정보 전송"| 200
    200 -->|"정보 제공"| 300
    300 -->|"정보 요청"| 200
    200 -->|"거래 정보 전송"| 400