%% 1020220171834 - 시스템 구성도
%% 생성일: 2026-05-11

classDiagram
    class 사용자단말부 {
        +String 탑재중량정보
        +정보전송()
    }
    class 블록체인네트워크 {
        +String 저장된정보
        +정보제공()
    }
    class 탑재중량등록부 {
        +String 등록정보
        +보상결정()
    }
    class 탑재중량거래부 {
        +String 거래정보
        +거래처리()
    }
    사용자단말부 --> 블록체인네트워크 : "정보 전송"
    블록체인네트워크 --> 사용자단말부 : "정보 수신"
    블록체인네트워크 --> 탑재중량등록부 : "정보 제공"
    탑재중량등록부 --> 블록체인네트워크 : "정보 요청"
    블록체인네트워크 --> 탑재중량거래부 : "거래 정보 전송"