%% 1020220043774 - 편의 기능 제공 플랫폼 시스템 구성도
%% 생성일: 2026-05-11

classDiagram
    class 학생단말 {
        +String 주문정보
    }
    class 시설단말 {
        +String 메뉴정보
    }
    class 배달자단말 {
        +String 배달정보
    }
    class 플랫폼제공서버 {
        +String 서비스
        +배달자배정()
    }
    학생단말 --> 플랫폼제공서버 : "서비스 제공"
    시설단말 --> 플랫폼제공서버 : "서비스 제공"
    배달자단말 --> 플랫폼제공서버 : "서비스 제공"