%% 1020220043774 - 편의 기능 제공 프로세스 흐름도
%% 생성일: 2026-05-11

flowchart TD
    100["학생 단말"]
    200["시설 단말"]
    300["배달자 단말"]
    400["플랫폼 제공 서버"]
    100 -->|"주문 정보 입력"| 400
    400 -->|"배달자 배정"| 300
    300 -->|"배달 수행"| 200