%% 1020197013953 - 이미지 시그니처 생성 및 카테고리 결정 흐름도
%% 생성일: 2026-05-11

flowchart TD
    100["서버 프로세서"]
    200["게시물 데이터베이스"]
    300["이미지"]
    400["이미지 시그니처"]
    500["카테고리 세트"]
    
    300 -->| "이미지를 수신함" | 100
    100 -->| "카테고리 세트 결정" | 500
    100 -->| "이미지 시그니처 생성" | 400
    200 <--| "게시물 세트를 식별하기 위해 사용됨" | 100
    400 <--| "게시물 목록 생성에 사용됨" | 100
    500 <--| "게시물 세트를 식별하는 데 사용됨" | 100