%% 1020210078871 - 보안등급 인증 프로세스
%% 생성일: 2026-05-11

flowchart TD
    100["보안등급 관리서버"]
    200["컨텐츠 제공자 단말기"]
    300["컨텐츠 서버/수신자 단말기"]
    400["단말 고유번호 수신"]
    500["단말 인증키 생성 및 전송"]
    600["보안등급 수신 및 저장"]
    700["단말 인증키 수신 및 보안등급 인증"]

    400 -->| "인증 요청" | 200
    200 -->| "단말 인증키 생성 및 전송" | 500
    500 -->| "보안등급 수신 및 저장" | 600
    600 -->| "단말 인증키 수신 및 보안등급 인증" | 700
    700 -->| "데이터 송수신" | 100
    100 <--> 300