%% 1020220002232 - 버츄어 휴먼 인터렉션 생성 과정
%% 생성일: 2026-05-11

flowchart TD
    100["인터렉션 생성 모듈"]
    200["부적절 인덱싱 모듈"]
    300["부적절 스코어링 인공신경망 모듈"]
    400["적절 텍스트 생성 모듈"]
    500["클라이언트 학습 모듈"]
    600["파라미터 업로드 모듈"]
    700["메인 신경망 다운로드 모듈"]
    800["스타일 판별기"]

    100 -->| "사용자 최후 대화 정보 수신" | 200
    200 -->| "부적절 여부 정보 출력" | 300
    300 -->| "부적절 스코어 출력" | 400
    400 -->| "적절 텍스트 생성" | 100
    100 -->| "파라미터 업데이트" | 500
    500 -->| "업데이트된 파라미터 입력" | 600
    600 -->| "업로드된 파라미터 통합" | 700
    700 -->| "메인 신경망 다운로드" | 800
    800 -->| "유사도 판단 및 레이어 업데이트" | 100