%% 1020227015590 - 신경망 처리 흐름도
%% 생성일: 2026-05-11

flowchart TD
    100["컨트롤러"]
    200["어드레스 레지스터"]
    300["활성화 메모리"]
    400["파라미터 메모리"]
    500["계산 유닛"]
    100 -->|"입력 묶음을 처리하여"| 200
    200 -->|"메모리 위치를 저장하여"| 300
    300 -->|"가중치 값을 저장하는"| 400
    300 -->|"입력 처리"| 500