%% 1020230037438 - 기부 시스템 흐름도
%% 생성일: 2026-05-11

flowchart TD
    100["기부자"]
    200["기부대상자"]
    300["키오스크"]
    400["모바일 애플리케이션"]
    100 -->|"기부금 충전"| 300
    300 -->|"기부금 사용 안내"| 200
    200 -->|"기부금 요청"| 300
    300 <-->|"모바일 애플리케이션 연동"| 400
    400 <-->|"정보 공유"| 300