%% 1020230037438 - 키오스크 및 모바일 애플리케이션 구성도
%% 생성일: 2026-05-11

classDiagram
    class 기부자 {
        +기부금 충전()
        +기부대상자 선택()
    }
    class 기부대상자 {
        +기부금 사용()
        +기부금 요청()
    }
    class 키오스크 {
        +기부금 충전 안내()
        +기부금 사용 안내()
        +모바일 애플리케이션 연동()
    }
    class 모바일 애플리케이션 {
        +정보 공유()
    }
    기부자 --> 키오스크 : "기부금 충전"
    기부대상자 <-- 키오스크 : "기부금 사용"
    기부대상자 --> 키오스크 : "기부금 요청"
    키오스크 <-- 기부자 : "기부금 충전 안내"
    키오스크 <-- 기부대상자 : "기부금 사용 안내"
    키오스크 <--> 모바일 애플리케이션 : "모바일 애플리케이션 연동"
    모바일 애플리케이션 <--> 키오스크 : "정보 공유"