%% 1020227026698 - 오브젝트 검출 모델 생성 흐름도
%% 생성일: 2026-05-11

flowchart TD
    100["중간 검출 모델"]
    200["스케일링 계수 선별 모듈"]
    300["프루닝할 채널 선별 유닛"]
    400["오브젝트 검출 모델"]
    100 -->|"사용"| 200
    100 -->|"사용"| 300
    200 -->|"연계"| 300
    300 -->|"생성"| 400