%% 1020190024451 - 작동 흐름도
%% 생성일: 2026-05-11

flowchart TD
    200["폴더블키보드"]
    100["개방기능부"]
    300["보안기능부"]
    400["외부디스플레이"]
    200 -->|"사용자 입력"| 100
    100 -->|"개방형 콘텐츠 실행"| 400
    200 -->|"사용자 입력"| 300
    300 -->|"보안형 콘텐츠 실행"| 400