%% 1020097023628 - 스레드 처리 방법 흐름도
%% 생성일: 2026-05-11

flowchart TD
    100["병렬 프로세서"]
    200["컴퓨터 메모리"]
    300["마스터 프로세서"]
    400["스레드 처리 단계"]
    
    100 -->|"메모리에 접근"| 200
    300 -->|"병렬 프로세서를 관리함"| 100
    400 -->|"로컬 캐시를 특정 3개의 레지스터에 할당"| 100
    400 -->|"단일 스레드를 처리하기 위해 프로세서 중 하나를 할당"| 300
    400 -->|"각각의 할당된 스레드를 처리"| 100
    400 -->|"처리된 스레드의 결과를 처리"| 300
    400 -->|"스레드 처리 후 프로세서 중 하나를 역-할당"| 300