%% 1020160170360 - 통합 핀테크 서비스 제공 흐름도
%% 생성일: 2026-05-11

flowchart TD
    100["통합 핀테크 단말기"]
    200["핀테크 중계 서버"]
    300["가맹점 인증 IC카드"]
    400["핀테크 서비스 서버"]
    100 -->|"핀테크 요청 정보를 전송"| 200
    100 -->|"인증 IC 정보를 등록"| 300
    200 <--|"핀테크 요청 정보 수신"| 100
    200 -->|"핀테크 서비스 서버에 요청 전송"| 400
    300 <--|"인증 IC 정보 수신"| 100
    400 <--|"서비스 요청 처리"| 200