%% 1020240112833 - 시스템 구성 요소
%% 생성일: 2026-05-11

classDiagram
    class 상품제공서버부 {
        +String 상품관리
        +String 정산관리
    }
    class 위탁판매단말부 {
        +String 샘플요청
        +String 결제수행
    }
    class 상품등록모듈 {
        +등록상품명()
    }
    class 수량등록모듈 {
        +등록수량()
    }
    class 가격등록모듈 {
        +등록가격()
    }
    class 수수료등록모듈 {
        +등록수수료()
    }
    class 샘플제공여부등록모듈 {
        +등록샘플제공여부()
    }
    class 조정모듈 {
        +조정정산조건()
    }
    class 판매수량산출모듈 {
        +산출판매수량()
    }
    class 정산금액산출모듈 {
        +산출정산금액()
    }
    class 반납날짜산출모듈 {
        +산출반납날짜()
    }
    
    상품제공서버부 --> 위탁판매단말부 : "연결"
    상품제공서버부 --> 상품등록모듈 : "구성"
    상품제공서버부 --> 수량등록모듈 : "구성"
    상품제공서버부 --> 가격등록모듈 : "구성"
    상품제공서버부 --> 수수료등록모듈 : "구성"
    상품제공서버부 --> 샘플제공여부등록모듈 : "구성"
    상품제공서버부 --> 조정모듈 : "구성"
    상품제공서버부 --> 판매수량산출모듈 : "구성"
    상품제공서버부 --> 정산금액산출모듈 : "구성"
    상품제공서버부 --> 반납날짜산출모듈 : "구성"