%% 1020240112833 - 샘플 주문 및 정산 프로세스
%% 생성일: 2026-05-11

flowchart TD
    10["상품제공서버부"]
    20["위탁판매단말부"]
    101["상품등록모듈"]
    102["수량등록모듈"]
    103["가격등록모듈"]
    104["수수료등록모듈"]
    105["샘플제공여부등록모듈"]
    106["조정모듈"]
    107["판매 수량산출모듈"]
    108["정산 금액산출모듈"]
    109["반납날짜산출모듈"]

    10 -->|연결| 20
    10 -->|구성| 101
    10 -->|구성| 102
    10 -->|구성| 103
    10 -->|구성| 104
    10 -->|구성| 105
    10 -->|구성| 106
    10 -->|구성| 107
    10 -->|구성| 108
    10 -->|구성| 109