'use client'

import Nav from '@/components/Nav'
import Footer from '@/components/Footer'
import Link from 'next/link'
import { useLang } from '@/contexts/LangContext'
import { t, tr } from '@/lib/i18n'

const content = {
  ko: {
    tag: 'LEGAL', h1: '이용약관', desc: 'PatentAI 서비스 이용에 관한 약관입니다.',
    sections: [
      { title: '제1조 (목적)', body: '본 약관은 PatentAI(이하 "회사")가 제공하는 AI 기반 지식재산 상담 서비스(이하 "서비스")의 이용과 관련하여 회사와 이용자 간의 권리·의무 및 책임사항을 규정함을 목적으로 합니다.' },
      { title: '제2조 (정의)', body: '"서비스"란 회사가 제공하는 AI 특허 상담, 선행기술 조사, 명세서 초안 생성, 도면 자동 생성 등 모든 기능을 의미합니다.\n"이용자"란 본 약관에 동의하고 서비스를 이용하는 개인 또는 법인을 의미합니다.\n"AI 생성 결과물"이란 서비스를 통해 생성된 명세서 초안, 도면, 조사 보고서 등을 의미합니다.' },
      { title: '제3조 (약관의 효력 및 변경)', body: '본 약관은 서비스 화면에 게시하거나 이용자에게 통지함으로써 효력이 발생합니다. 회사는 합리적인 사유가 있을 경우 관련 법령에 위배되지 않는 범위에서 본 약관을 변경할 수 있으며, 변경된 약관은 서비스 내 공지를 통해 이용자에게 공지됩니다.' },
      { title: '제4조 (서비스 이용)', body: '서비스는 특허 출원을 위한 초안 작성을 보조하는 목적으로 제공됩니다. AI가 생성하는 명세서·청구항·도면은 초안 수준으로, 특허청 제출 전 반드시 자격을 갖춘 변리사의 검토가 필요합니다. 회사는 AI 생성 결과물의 특허 등록 여부에 대하여 어떠한 보증도 하지 않습니다.' },
      { title: '제5조 (이용자 의무)', body: '이용자는 본 약관 및 관계 법령을 준수하여야 합니다. 이용자는 타인의 지식재산권을 침해하는 발명 내용을 입력해서는 안 됩니다. 이용자는 서비스를 통해 생성된 결과물을 불법적인 목적으로 사용할 수 없습니다.' },
      { title: '제6조 (회사의 의무)', body: '회사는 서비스를 안정적으로 운영하기 위해 최선을 다합니다. 회사는 이용자의 개인정보를 개인정보처리방침에 따라 안전하게 보호합니다. 회사는 서비스 장애 발생 시 신속하게 복구하기 위하여 노력합니다.' },
      { title: '제7조 (지식재산권)', body: 'AI 생성 결과물의 권리 귀속은 이용자에게 있습니다. 다만, 회사는 서비스 개선 목적으로 익명화된 상담 데이터를 활용할 수 있습니다. 서비스의 소프트웨어, 디자인, 상표 등 회사 고유의 지식재산권은 회사에 귀속됩니다.' },
      { title: '제8조 (면책조항)', body: '회사는 천재지변, 전쟁, 해킹 등 불가항력적 사유로 서비스를 제공하지 못한 경우 책임이 면제됩니다. AI 생성 결과물로 인한 특허 분쟁, 손해에 대하여 회사는 책임을 지지 않습니다. 이용자는 서비스 이용 전 반드시 변리사 상담을 통해 법적 검토를 받을 것을 권고합니다.' },
      { title: '제9조 (준거법 및 관할법원)', body: '본 약관의 해석과 분쟁 해결에 관하여는 대한민국 법률이 적용됩니다. 서비스 이용으로 발생한 분쟁에 대해서는 서울중앙지방법원을 전속 관할 법원으로 합니다.' },
    ],
    meta: ['시행일: 2026년 1월 1일', '최종 개정: 2026년 5월 14일', '버전: v1.2'],
  },
  en: {
    tag: 'LEGAL', h1: 'Terms of Service', desc: 'Terms governing your use of the PatentAI service.',
    sections: [
      { title: 'Article 1 (Purpose)', body: 'These Terms govern the rights, obligations, and responsibilities between PatentAI ("Company") and users in connection with the use of the AI-based IP consultation service ("Service").' },
      { title: 'Article 2 (Definitions)', body: '"Service" means all features provided by the Company including AI patent consultation, prior art search, specification drafting, and automatic drawing generation.\n"User" means an individual or legal entity who agrees to these Terms and uses the Service.\n"AI-generated content" means specification drafts, drawings, and research reports generated through the Service.' },
      { title: 'Article 3 (Effectiveness and Amendment)', body: 'These Terms take effect upon posting on the Service screen or notifying users. The Company may amend these Terms within the scope not violating applicable laws, and amended Terms shall be notified to users through announcements within the Service.' },
      { title: 'Article 4 (Use of Service)', body: 'The Service is provided to assist in drafting patent applications. Specifications, claims, and drawings generated by AI are at a draft level and must be reviewed by a licensed patent attorney before submission to the patent office. The Company makes no warranty regarding whether AI-generated content will result in patent registration.' },
      { title: 'Article 5 (User Obligations)', body: 'Users must comply with these Terms and applicable laws. Users must not input invention content that infringes the intellectual property rights of others. Users may not use results generated through the Service for illegal purposes.' },
      { title: 'Article 6 (Company Obligations)', body: 'The Company will do its best to operate the Service stably. The Company protects users personal information in accordance with its Privacy Policy. The Company will endeavor to restore service promptly in the event of a failure.' },
      { title: 'Article 7 (Intellectual Property)', body: 'Rights to AI-generated content belong to the user. However, the Company may use anonymized consultation data for service improvement. Intellectual property rights inherent to the Company, including software, design, and trademarks, belong to the Company.' },
      { title: 'Article 8 (Disclaimer)', body: 'The Company is exempt from liability if the Service cannot be provided due to force majeure such as natural disasters, war, or hacking. The Company is not responsible for patent disputes or damages resulting from AI-generated content. Users are advised to seek legal review from a patent attorney before using the Service.' },
      { title: 'Article 9 (Governing Law)', body: 'The laws of the Republic of Korea apply to the interpretation and dispute resolution of these Terms. The Seoul Central District Court shall have exclusive jurisdiction over disputes arising from the use of the Service.' },
    ],
    meta: ['Effective Date: January 1, 2026', 'Last Updated: May 14, 2026', 'Version: v1.2'],
  },
  ja: {
    tag: 'LEGAL', h1: '利用規約', desc: 'PatentAIサービスのご利用に関する規約です。',
    sections: [
      { title: '第1条（目的）', body: '本規約は、PatentAI（以下「会社」）が提供するAI基盤の知的財産相談サービス（以下「サービス」）の利用に関して、会社と利用者との間の権利・義務および責任事項を定めることを目的とします。' },
      { title: '第2条（定義）', body: '「サービス」とは、会社が提供するAI特許相談、先行技術調査、明細書草稿生成、図面自動生成など全ての機能を意味します。\n「利用者」とは、本規約に同意しサービスを利用する個人または法人を意味します。\n「AI生成結果物」とは、サービスを通じて生成された明細書草稿、図面、調査報告書などを意味します。' },
      { title: '第3条（規約の効力および変更）', body: '本規約はサービス画面への掲示または利用者への通知により効力を生じます。会社は合理的な理由がある場合、関連法令の範囲内で本規約を変更でき、変更された規約はサービス内の告知を通じて利用者に通知されます。' },
      { title: '第4条（サービス利用）', body: 'サービスは特許出願のための草稿作成を補助する目的で提供されます。AIが生成する明細書・請求項・図面は草稿レベルであり、特許庁への提出前に必ず資格を持つ弁理士の審査が必要です。会社はAI生成結果物の特許登録可否について一切の保証を行いません。' },
      { title: '第5条（利用者の義務）', body: '利用者は本規約および関係法令を遵守しなければなりません。利用者は他人の知的財産権を侵害する発明内容を入力してはなりません。利用者はサービスを通じて生成された結果物を不法な目的で使用することはできません。' },
      { title: '第6条（会社の義務）', body: '会社はサービスを安定的に運営するために最善を尽くします。会社は利用者の個人情報をプライバシーポリシーに従い安全に保護します。会社はサービス障害発生時に迅速に復旧するよう努力します。' },
      { title: '第7条（知的財産権）', body: 'AI生成結果物の権利は利用者に帰属します。ただし、会社はサービス改善目的で匿名化された相談データを活用できます。サービスのソフトウェア・デザイン・商標など会社固有の知的財産権は会社に帰属します。' },
      { title: '第8条（免責事項）', body: '会社は天災、戦争、ハッキングなど不可抗力的事由によりサービスを提供できない場合、責任が免除されます。AI生成結果物による特許紛争・損害について会社は責任を負いません。利用者はサービス利用前に必ず弁理士の法的審査を受けることを推奨します。' },
      { title: '第9条（準拠法および管轄裁判所）', body: '本規約の解釈と紛争解決については大韓民国の法律が適用されます。サービス利用により生じた紛争についてはソウル中央地方裁判所を専属管轄裁判所とします。' },
    ],
    meta: ['施行日：2026年1月1日', '最終改定：2026年5月14日', 'バージョン：v1.2'],
  },
  zh: {
    tag: 'LEGAL', h1: '服务条款', desc: '有关使用PatentAI服务的条款。',
    sections: [
      { title: '第一条（目的）', body: '本条款旨在规定PatentAI（以下简称"公司"）提供的AI驱动知识产权咨询服务（以下简称"服务"）使用过程中，公司与用户之间的权利、义务及责任事项。' },
      { title: '第二条（定义）', body: '"服务"是指公司提供的AI专利咨询、现有技术检索、说明书草稿生成、附图自动生成等所有功能。\n"用户"是指同意本条款并使用服务的个人或法人。\n"AI生成内容"是指通过服务生成的说明书草稿、附图及检索报告等。' },
      { title: '第三条（条款效力及变更）', body: '本条款自在服务页面公示或通知用户之日起生效。公司在有合理理由时，可在不违反相关法规的范围内变更本条款，变更后的条款将通过服务内公告通知用户。' },
      { title: '第四条（服务使用）', body: '服务旨在辅助专利申请草稿撰写。AI生成的说明书、权利要求书和附图均为草稿水平，提交专利局前必须经过具有资格的专利代理人审查。公司对AI生成内容能否获得专利注册不作任何保证。' },
      { title: '第五条（用户义务）', body: '用户必须遵守本条款及相关法律法规。用户不得输入侵犯他人知识产权的发明内容。用户不得将服务生成的结果用于违法目的。' },
      { title: '第六条（公司义务）', body: '公司将尽最大努力稳定运营服务。公司将依据隐私政策安全保护用户个人信息。公司将努力在服务故障发生时迅速恢复。' },
      { title: '第七条（知识产权）', body: 'AI生成内容的权利归属于用户。但公司可将匿名化的咨询数据用于改善服务目的。服务的软件、设计、商标等公司固有知识产权归公司所有。' },
      { title: '第八条（免责条款）', body: '因自然灾害、战争、黑客攻击等不可抗力原因导致无法提供服务时，公司免于承担责任。对于因AI生成内容引发的专利纠纷或损害，公司不承担责任。建议用户在使用服务前务必通过专利代理人获取法律审查。' },
      { title: '第九条（准据法及管辖法院）', body: '本条款的解释及纠纷解决适用大韩民国法律。因使用服务产生的纠纷以首尔中央地方法院为专属管辖法院。' },
    ],
    meta: ['施行日期：2026年1月1日', '最后修订：2026年5月14日', '版本：v1.2'],
  },
}

export default function TermsPage() {
  const { lang } = useLang()
  const c = content[lang] ?? content.ko

  return (
    <div className="site">
      <style>{`
        .legal-wrap { max-width: 900px; margin: 0 auto; padding: 4rem 3rem; }
        .legal-meta { font-size: .78rem; color: #999; margin-bottom: 3rem; border-bottom: 1px solid #E8E4DC; padding-bottom: 1.5rem; display: flex; gap: 2rem; flex-wrap: wrap; }
        .legal-section { margin-bottom: 2.5rem; padding-bottom: 2.5rem; border-bottom: 1px solid #F0EDE8; }
        .legal-section:last-child { border-bottom: none; }
        .legal-h3 { font-family: 'Noto Serif KR', serif; font-size: 1.05rem; font-weight: 400; color: #0A0A16; margin-bottom: 1rem; }
        .legal-body { font-size: .88rem; color: #444; line-height: 2; white-space: pre-line; word-break: keep-all; }
        @media(max-width:768px){ .legal-wrap { padding: 2.5rem 1.5rem; } }
      `}</style>
      <Nav />
      <div className="hero">
        <div className="tag">{c.tag}</div>
        <h1>{c.h1}</h1>
        <p>{c.desc}</p>
      </div>
      <div className="legal-wrap">
        <div className="legal-meta">
          {c.meta.map((m, i) => <span key={i}>{m}</span>)}
        </div>
        {c.sections.map((s, i) => (
          <div key={i} className="legal-section">
            <div className="legal-h3">{s.title}</div>
            <div className="legal-body">{s.body}</div>
          </div>
        ))}
        <div style={{ display: 'flex', gap: '1rem', marginTop: '2rem', flexWrap: 'wrap' }}>
          <Link href="/privacy" style={{ fontSize: '.82rem', color: '#C9A84C', textDecoration: 'underline' }}>{tr(t.privacy.toPrivacy, lang)}</Link>
          <Link href="/contact" style={{ fontSize: '.82rem', color: '#888' }}>{tr(t.privacy.toContact, lang)}</Link>
        </div>
      </div>
      <Footer />
    </div>
  )
}
