%% 1020250086141 - 시스템 구성 요소 클래스 다이어그램
%% 생성일: 2026-05-11

classDiagram
    class 데이터 저장 유닛 {
        +String 상품정보
        +String 차량정보
    }
    class 정보 획득 모듈 {
        +getData()
    }
    class 물류 흐름 제어 모듈 {
        +controlCompatibility()
    }
    class 배송 계획 모듈 {
        +dispatchVehicle()
    }
    class 운영 최적화 모듈 {
        +optimizeSystem()
    }
    정보 획득 모듈 --> 데이터 저장 유닛 : "데이터를 저장 유닛에서 획득"
    물류 흐름 제어 모듈 --> 정보 획득 모듈 : "정보 획득 모듈로부터 정보 획득"
    배송 계획 모듈 --> 정보 획득 모듈 : "정보 획득 모듈로부터 정보 획득"
    배송 계획 모듈 --> 물류 흐름 제어 모듈 : "물류 흐름 제어 모듈로부터 적재 정보 획득"
    운영 최적화 모듈 --> 배송 계획 모듈 : "배송 계획 모듈에 피드백 제공"