%% 1020117018607 - 요약 테이블 디스플레이 방법
%% 생성일: 2026-05-11

flowchart TD
    100["요약 테이블"]
    200["데이터 소스"]
    300["디스플레이 장치"]
    400["데이터 분석 프로그램 모듈"]
    400 -->|"데이터 판독"| 200
    200 -->|"데이터 제공"| 100
    400 -->|"테이블 렌더링"| 100
    400 -->|"디스플레이"| 300
    100 -->|"테이블 표시"| 300