%% 1020230153895 - 데이터 기록 장치 구성도
%% 생성일: 2026-05-11

classDiagram
    class 데이터입력부 {
        +String 데이터파일
        +입력()
    }
    class 무결성검증생성부 {
        +String 무결성검증데이터
        +생성()
    }
    class 삭제검증정보생성부 {
        +String 삭제검증정보
        +생성()
    }
    class 무결성검증파일생성부 {
        +String 무결성검증파일
        +생성()
    }
    class 데이터저장제어부 {
        +저장()
    }
    class 무결성검증부 {
        +검증()
    }
    데이터입력부 --> 무결성검증생성부 : "입력받은 데이터 파일을 사용하여"
    무결성검증생성부 --> 삭제검증정보생성부 : "무결성 검증 데이터를 사용하여"
    무결성검증생성부 --> 무결성검증파일생성부 : "무결성 검증 데이터를 사용하여"
    삭제검증정보생성부 --> 무결성검증파일생성부 : "삭제 검증 정보를 사용하여"
    무결성검증파일생성부 --> 데이터저장제어부 : "무결성 검증 파일을 저장하여"
    데이터저장제어부 --> 무결성검증부 : "저장된 데이터 파일을 사용하여"