%% 1020230153895 - 데이터 무결성 검증 방법 흐름도
%% 생성일: 2026-05-11

flowchart TD
    100["데이터 입력부"]
    200["무결성 검증 생성부"]
    300["삭제 검증 정보 생성부"]
    400["무결성 검증 파일 생성부"]
    500["데이터 저장 제어부"]
    600["무결성 검증부"]
    
    100 -->|"입력받은 데이터 파일을 사용하여"| 200
    200 -->|"무결성 검증 데이터를 사용하여"| 300
    200 -->|"무결성 검증 데이터를 사용하여"| 400
    300 -->|"삭제 검증 정보를 사용하여"| 400
    400 -->|"무결성 검증 파일을 저장하여"| 500
    500 -->|"저장된 데이터 파일을 사용하여"| 600