FROM node:20-alpine AS dev

WORKDIR /app
COPY frontend/package*.json ./
RUN npm ci
COPY frontend/ .

EXPOSE 3000
CMD ["npm", "run", "dev"]

FROM node:20-alpine AS builder

WORKDIR /app
COPY frontend/package*.json ./
RUN npm ci
COPY frontend/ .
RUN npm run build

FROM nginx:alpine AS prod
COPY --from=builder /app/dist /usr/share/nginx/html
COPY docker/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
