%% 1020207014462 - 판별 네트워크 트레이닝 흐름도
%% 생성일: 2026-05-11

flowchart TD
    100["생성 네트워크"]
    200["판별 네트워크"]
    300["입력 이미지"]
    400["출력 이미지"]
    300 -->|"생성 네트워크에 입력됨"| 100
    100 -->|"트레이닝 절차에 포함됨"| 200
    100 -->|"출력 이미지"| 400
    400 -->|"판별 네트워크에 입력됨"| 200