%% 1020240016394 - 코인지갑 운영 시스템 구성도
%% 생성일: 2026-05-11

classDiagram
    class 관리서버 {
        +String 블록체인기술
        +코인교환()
    }
    class 쇼핑몰서버 {
        +String 포인트분배
        +물품구매()
    }
    class 사용자단말 {
        +String 사용자정보
        +코인교환요청()
        +물품구매요청()
    }
    사용자단말 --> 관리서버 : "코인 교환 요청"
    사용자단말 --> 쇼핑몰서버 : "물품 구매 요청"
    쇼핑몰서버 --> 관리서버 : "포인트 교환 요청"