%% 1020230107940 - 건물 임대 관리 서비스 시스템 흐름도
%% 생성일: 2026-05-11

flowchart TD
    100["관리 서비스 모듈"]
    200["입주 서비스 모듈"]
    300["데이터베이스"]
    400["임대인"]
    500["입주자"]
    600["금융기관 서버"]
    700["세금 관리 서버"]
    
    400 -->| "관리비 정보 요청" | 100
    100 -->| "관리비 고지내역 제공" | 200
    200 -->| "결제 요청 수신" | 600
    600 -->| "결제 수행" | 300
    300 -->| "수납 정보 생성" | 200
    200 -->| "결제 정보 저장" | 300
    300 -->| "결제 정보 제공" | 200