%% 1020190164745 - 에너지 절감 가열 장치 동작 흐름도
%% 생성일: 2026-05-11

flowchart TD
    100["하우징"]
    200["가열 부재"]
    300["전력 공급부"]
    400["제어부"]
    500["진동 센서"]
    600["통신부"]
    700["탑플레이트"]
    
    500 -->| "정보를 제공함" | 400
    600 -->| "정보를 제공함" | 400
    400 -->| "전력을 공급받음" | 200
    300 -->| "제어부에 의해 제어됨" | 400
    100 -->| "하우징의 상부에 배치됨" | 700
    700 -->| "피가열체를 지지함" | 200