%% 1020147031950 - 제약 트랜잭션 검사 흐름도
%% 생성일: 2026-05-11

flowchart TD
    100["프로세서"]
    200["메인 메모리"]
    300["트랜잭션"]
    400["중단 조건"]
    100 -->|"트랜잭션 실행 요청"| 300
    300 -->|"트랜잭션 데이터 저장"| 200
    300 -->|"트랜잭션 처리에 영향을 미침"| 400
    200 <--|"트랜잭션 실행을 위한 데이터 저장"| 100