%% 1020200113681 - 전자 장치 구성도
%% 생성일: 2026-05-11

classDiagram
    class 문서파일저장부 {
        +String 전자문서파일
    }
    class 대체글자저장부 {
        +String 한글낱글자
        +String 대체한글낱글자
    }
    class 위치정보저장부 {
        +String 오타위치정보
    }
    class 이벤트발생부 {
        +이벤트발생()
    }
    class 구분부 {
        +구분키워드()
    }
    class 검색수행부 {
        +검색전자문서()
    }
    문서파일저장부 --> 검색수행부 : "문서 검색"
    대체글자저장부 --> 구분부 : "대체 글자 참조"
    위치정보저장부 --> 구분부 : "위치 정보 참조"
    이벤트발생부 --> 구분부 : "이벤트 발생"