%% 1020230055750 - 영상 정성적 특성 추출 장치 구성도
%% 생성일: 2026-05-11

classDiagram
    class 영상분할모듈 {
        +분할()
    }
    class 그래프임베딩모듈 {
        +생성()
    }
    class 영상분류모듈 {
        +분류()
    }
    영상분할모듈 --> 그래프임베딩모듈 : "사용"
    그래프임베딩모듈 --> 영상분류모듈 : "사용"