%% 1020190098351 - 침수 예측 장치 구성도
%% 생성일: 2026-05-11

classDiagram
    class 비선형_자기회귀_인공신경망 {
        +String 누적강우량
        +String 누적월류량
        +학습()
    }
    class 자기조직화_지도_인공신경망 {
        +String 강우_시나리오
        +String 실제_강우
        +도출()
    }
    class 침수_범위_예측부 {
        +String 누적월류량
        +String 침수지도_데이터
        +예측()
    }
    비선형_자기회귀_인공신경망 --> 자기조직화_지도_인공신경망 : "데이터 입력"
    비선형_자기회귀_인공신경망 --> 침수_범위_예측부 : "예측 데이터 제공"
    자기조직화_지도_인공신경망 --> 침수_범위_예측부 : "예측 데이터 제공"