%% 1020240121692 - 제어 서버 개념도
%% 생성일: 2026-05-11

classDiagram
    class 이동단말 {
        +String 사용자
    }
    class 제어서버 {
        +String 웹기반플랫폼
        +접근()
    }
    class 판매관리부 {
        +String 제품정보
        +관리()
    }
    class 체험관리부 {
        +String 프로그램정보
        +관리()
    }
    class 리뷰관리부 {
        +String 리뷰데이터
        +관리()
    }
    class 알림관리부 {
        +String 알림메시지
        +관리()
    }
    이동단말 --> 제어서버 : "접근"
    제어서버 --> 판매관리부 : "관리"
    제어서버 --> 체험관리부 : "관리"
    제어서버 --> 리뷰관리부 : "관리"
    제어서버 --> 알림관리부 : "관리"