%% 1020250055479 - 시스템 구성 요소 클래스 다이어그램
%% 생성일: 2026-05-11

classDiagram
    class 관리서버 {
        +String 경로생성기능
        +manageInventory()
    }
    class 데이터수집부 {
        +collectData()
    }
    class 리스트생성부 {
        +generateOrderList()
    }
    class 경로생성부 {
        +createPickingAndDeliveryPath()
    }
    class 정보제공부 {
        +provideInformation()
    }
    class 물품관리부 {
        +monitorStorageCondition()
    }
    class 관리자단말 {
        +interactWithSystem()
    }
    class IoT기반RFID센서 {
        +collectInventoryData()
    }
    class 온도및습도센서 {
        +detectStorageCondition()
    }

    관리서버 --> 데이터수집부 : "소속"
    관리서버 --> 리스트생성부 : "소속"
    관리서버 --> 경로생성부 : "소속"
    관리서버 --> 정보제공부 : "소속"
    관리서버 --> 물품관리부 : "소속"
    관리서버 <--> 관리자단말 : "통신"
    데이터수집부 --> IoT기반RFID센서 : "데이터 수집"
    물품관리부 --> 온도및습도센서 : "데이터 수집"