%% 1020240138555 - 신경망 모델 구성도
%% 생성일: 2026-05-11

classDiagram
    class 생체신호획득모듈 {
        +생체신호획득()
    }
    class 제1신경망모델 {
        +결과값생성()
    }
    class 제2신경망모델 {
        +결과값생성()
    }
    class 가중치적용모듈 {
        +가중치적용()
    }
    class 건강상태예측모듈 {
        +건강상태예측()
    }
    생체신호획득모듈 --> 제1신경망모델 : "입력"
    생체신호획득모듈 --> 제2신경망모델 : "입력"
    제1신경망모델 --> 가중치적용모듈 : "입력"
    제2신경망모델 --> 가중치적용모듈 : "입력"
    가중치적용모듈 --> 건강상태예측모듈 : "입력"