%% 1020170003374 - 터치 입력 장치 구성도
%% 생성일: 2026-05-11

classDiagram
    class 터치스크린 {
        +String 객체전송인터페이스
    }
    class 압력센서 {
        +String 압력감지
    }
    class 프로세서 {
        +String 압력크기연산
        +executeCommand()
    }
    class 메모리 {
        +String 압력크기정보
        +String 임계값정보
    }
    터치스크린 --> 압력센서 : "감지하는 대상"
    터치스크린 --> 프로세서 : "명령 실행"
    압력센서 --> 프로세서 : "압력 크기 연산"
    프로세서 --> 메모리 : "정보 저장"