%% 1020250123649 - GPS 기반 주문 취소 예측 흐름도
%% 생성일: 2026-05-11

flowchart TD
    100["서버"]
    200["사용자 단말"]
    300["매장 단말"]
    400["이용권 정보 생성 및 갱신"]
    
    200 -->| "주문 정보 전송" | 100
    100 -->| "결제 완료 정보 전송" | 300
    300 -->| "QR코드 스캔 및 정보 전송" | 200
    100 -->| "이용권 정보 생성 및 갱신" | 400