%% 1020250123649 - 원격 주문 및 결제 처리 흐름도
%% 생성일: 2026-05-11

flowchart TD
    100["서버"]
    200["사용자 단말"]
    300["매장 단말"]
    400["이용권 정보 생성 및 갱신"]
    
    200 -->| "주문 정보 전송" | 100
    100 -->| "주문 가능 메뉴 정보 수신" | 200
    300 -->| "결제 완료 정보 전송" | 100
    100 -->| "이용권 정보 갱신" | 400
    200 -->| "QR코드 스캔 및 정보 전송" | 300