%% 1020200161286 - 뉴로모픽 컴퓨팅 모듈 구성도
%% 생성일: 2026-05-11

classDiagram
    class 뉴로모픽컴퓨팅모듈 {
        +String 입력데이터
        +추론()
    }
    class 메모리 {
        +String 저장정보
    }
    class 입력데이터 {
        +String 데이터
    }
    class 흥분성뉴런레이어 {
        +스파이크발화()
    }
    class 억제성뉴런레이어 {
        +스파이크수신()
    }
    뉴로모픽컴퓨팅모듈 --> 메모리 : "정보 저장"
    입력데이터 --> 뉴로모픽컴퓨팅모듈 : "입력"
    흥분성뉴런레이어 --> 억제성뉴런레이어 : "스파이크 전달"