%% 1020240131371 - 의료 영상 분석 방법 흐름도
%% 생성일: 2026-05-11

flowchart TD
    100["제어부"]
    200["의료 영상"]
    300["측정 값"]
    400["분석 모델"]
    100 -->|"의료 영상을 처리"| 200
    100 -->|"측정 값을 생성"| 300
    100 -->|"분석 모델 선택"| 400