%% 1020170122363 - 비정상 세션 감지 방법 흐름도
%% 생성일: 2026-05-11

flowchart TD
    100["서버"]
    200["클라이언트"]
    300["컨볼루셔널 신경망"]
    400["LSTM 신경망"]
    200 -->| "요청 메시지 송신" | 100
    100 -->| "데이터 변환 요청" | 300
    300 -->| "표현 벡터 입력" | 400
    400 -->| "비정상 여부 결과 전달" | 100