%% 1020220189350 - 텍스트-수어 병렬 코퍼스 취득 방법 흐름도
%% 생성일: 2026-05-11

flowchart TD
    100["수어영상 수신부"]
    200["수어영상 단편화부"]
    300["정규화부"]
    400["ROI 취득부"]
    500["모션데이터 분석부"]
    100 -->|"수신된 수어영상을 처리"| 200
    200 -->|"단편화된 영상의 데이터를 사용"| 300
    300 -->|"정규화된 데이터를 사용"| 400
    400 -->|"ROI 데이터를 사용"| 500