%% 1020220090887 - 전자 장치 구성도
%% 생성일: 2026-05-11

classDiagram
    class 전자장치 {
        +String 청진음데이터
        +String 청진위치데이터
        +질병정보확인()
    }
    class 인공지능모델 {
        +String 모델가중치
        +질병분류()
    }
    class 청진음데이터 {
        +String 심음
        +String 폐음
    }
    class 청진위치데이터 {
        +String 신체부위위치
    }
    class 생체데이터 {
        +String 심박수
        +String 호흡수
        +String 체온
    }
    전자장치 --> 청진음데이터 : "입력"
    전자장치 --> 청진위치데이터 : "입력"
    생체데이터 --> 인공지능모델 : "입력"
    전자장치 --> 인공지능모델 : "입력"