%% 1020230044382 - 태블릿 카드 결제 누락 방지 시스템 구성도
%% 생성일: 2026-05-11

classDiagram
    class 태블릿 {
        +String description
        +receiveApprovalSignal()
    }
    class POS단말 {
        +String description
        +executePaymentInquiry()
    }
    class 외부결제서버 {
        +String description
        +sendApprovalSignal()
    }
    태블릿 --> POS단말 : "무선통신 연동"
    POS단말 --> 외부결제서버 : "유선통신 연동"
    외부결제서버 --> 태블릿 : "결제 승인 신호 송신"