%% 1020197030212 - 카메라 자세 정보 결정 장치 구성도
%% 생성일: 2026-05-11

classDiagram
    class 제1획득모듈 {
        +String 이미지데이터
        +획득()
    }
    class 검출모듈 {
        +String 특징점
        +검출()
    }
    class 추적모듈 {
        +String 호모그래피
        +결정()
    }
    class 상보적필터링모듈 {
        +String 자세정보
        +필터링()
    }
    제1획득모듈 --> 검출모듈 : "이미지 획득"
    검출모듈 --> 추적모듈 : "특징점 검출 결과 사용"
    추적모듈 --> 상보적필터링모듈 : "호모그래피 결과 사용"