%% 1020170022582 - 결제 거래 처리 흐름도
%% 생성일: 2026-05-11

flowchart TD
    100["전자 디바이스"]
    200["제1 애플리케이션"]
    300["제2 애플리케이션"]
    400["결제 어포던스 선택 검출"]
    500["제1 거래 정보 전달"]
    600["제1 구매 상세사항 어포던스 선택 수신"]
    700["대안적 값 선택 수신 및 업데이트"]

    100 -->|"사용자 인터페이스 디스플레이"| 200
    200 -->|"정보 전달"| 400
    400 -->|"제1 거래 정보 전달"| 500
    500 -->|"정보 수신"| 300
    300 -->|"제2 애플리케이션 디스플레이"| 600
    600 -->|"대안적 값 선택 수신 및 업데이트"| 700