%% 1020220153912 - 레이블링 방법 흐름도
%% 생성일: 2026-05-11

flowchart TD
    100["객체탐지부"]
    200["객체추적부"]
    300["행위식별부"]
    400["행동검출부"]
    100 -->|"객체 탐지 결과를 기반으로"| 200
    200 -->|"객체 추적 결과를 기반으로"| 300
    300 -->|"행위 식별 결과를 기반으로"| 400