%% 1020200059705 - 퓨 샷 학습 프로세스
%% 생성일: 2026-05-11

flowchart TD
    100["메인 바디"]
    200["제1 헤드"]
    300["제2 헤드"]
    400["제3 헤드"]
    100 -->|"특징 벡터 생성"| 200
    100 -->|"특징 벡터 생성"| 300
    100 -->|"특징 벡터 생성"| 400
    200 -->|"제1 태스크: 제1 모델을 퓨 샷 학습시키기"| 300
    300 -->|"제2 태스크: 제2 모델을 지도 학습시키기"| 400
    400 -->|"제3 태스크: 제3 모델을 약 지도 학습시키기"| 200