%% 1020130042378 - 키오스크 장치 동작 흐름도
%% 생성일: 2026-05-11

flowchart TD
    100["태양 위치추적 센싱 유닛"]
    200["키오스크 하우징"]
    300["디스플레이 유닛"]
    400["디스플레이 회전 유닛"]
    500["키오스크 하우징 회전 유닛"]
    600["데이터 베이스"]
    900["제어 유닛"]
    
    100 -->|"태양 위치 정보 측정"| 900
    900 -->|"디스플레이 유닛 각도 정보 추출"| 300
    300 -->|"디스플레이 회전 제어"| 400
    200 -->|"회전 유닛에 의해 회전됨"| 500
    400 -->|"회전 유닛에 의해 회전됨"| 300
    500 -->|"키오스크 하우징을 회전시킴"| 200
    900 -->|"데이터베이스에서 정보 추출"| 600