%% 1020227013279 - 폐쇄 루프 거래 수행 방법
%% 생성일: 2026-05-11

flowchart TD
    202A["제1 사용자 디바이스"]
    202B["제2 사용자 디바이스"]
    204["지불 서버"]
    206["하드웨어 보안 모듈"]
    208["폐쇄 루프 서비스 공급자"]
    
    202A -->|"데이터 송신"| 202B
    202B -->|"데이터 송신"| 204
    204 <--|"데이터 복호화 요청"| 206
    206 -->|"복호화된 데이터 송신"| 208