%% 1020197029282 - 시스템 구성도
%% 생성일: 2026-05-11

classDiagram
    class 비_일시적_메모리 {
        +String roomImage
        +String neuralNetwork
    }
    class 하드웨어_프로세서 {
        +analyzeImage()
        +determineLayout()
    }
    class 인코더_디코더_서브_네트워크 {
        +generate2DKeypointMap()
    }
    class 분류자_서브_네트워크 {
        +classifyRoomType()
    }
    비_일시적_메모리 <|-- 하드웨어_프로세서 : "통신"
    비_일시적_메모리 <|-- 인코더_디코더_서브_네트워크 : "입력"
    인코더_디코더_서브_네트워크 <|-- 분류자_서브_네트워크 : "통신"
    하드웨어_프로세서 <|-- 인코더_디코더_서브_네트워크 : "통신"
    하드웨어_프로세서 <|-- 분류자_서브_네트워크 : "통신"