%% 1020220118978 - 생활밀착형 원스톱 플랫폼 서비스 제공 방법
%% 생성일: 2026-05-11

flowchart TD
    100["가맹점 단말"]
    200["사용자 단말"]
    300["플랫폼 서비스 제공 서버"]
    400["경로안내부"]
    500["매칭부"]
    600["테마별추천부"]
    700["아이템중개부"]
    800["예약관리부"]
    900["충전결제부"]

    100 -->|"등록부와 매핑"| 300
    200 -->|"검색 및 오버레이"| 100
    300 -->|"위치 기반 서비스 제공"| 200
    200 -->|"서비스 제공"| 400
    200 -->|"정보 입력 및 매칭"| 500
    200 -->|"추천 서비스 제공"| 600
    200 -->|"거래 중개"| 700
    200 -->|"예약 이벤트 전송"| 800
    200 -->|"결제 처리"| 900