%% 1020157015119 - 바이오메트릭 등록 및 인증 과정
%% 생성일: 2026-05-11

flowchart TD
    100["카메라"]
    200["디스플레이"]
    300["사용자"]
    400["등록 이미지 캡쳐링"]
    500["후보 이미지 캡쳐링"]
    600["이미지 정렬 및 인증"]
    
    300 -->| "신체 일부 제시" | 100
    100 -->| "이미지 제시" | 200
    200 -->| "이미지 확인" | 300
    300 -->| "등록 이미지 캡쳐링" | 400
    400 -->| "후보 이미지 캡쳐링" | 500
    500 -->| "이미지 정렬 및 인증" | 600