%% 1020240151668 - 시스템 구성도
%% 생성일: 2026-05-11

classDiagram
    class ERP사용자단말 {
        +String 요청
        +결제요청()
    }
    class 결제플랫폼서버 {
        +String 승인상태
        +결제승인요청()
        +정산처리()
    }
    class 결제대행회사서버 {
        +String 인증상태
        +인증처리()
    }
    class 신용카드사서버 {
        +String 결제상태
        +결제승인()
    }
    class 외상매출금데이터베이스 {
        +String 데이터
        +저장()
    }
    ERP사용자단말 -->| "통신" | 결제플랫폼서버
    결제플랫폼서버 -->| "연결" | 결제대행회사서버
    결제플랫폼서버 -->| "연결" | 신용카드사서버
    결제대행회사서버 -->| "연결" | 외상매출금데이터베이스