%% 1020157035775 - 실리콘 플랫폼 상에서 공유 메모리를 에뮬레이션하기 위한 실현 가능한 확장형 구조의 블록도이다
%% 도 1
%% deterministic renderer
%% 생성일: 2026-05-11

flowchart TD
    N500["500 메모리 장치"]
    N504["504 단계 캐시"]
    N506["506 스크래치패드"]
    N512["512 응답 수신 버퍼"]
    N10["10 2254585"]
    N21["21 22일"]
    N74["74 77)"]
    N14["14 16일"]
    N77["77 82)"]
    N39["39 64) 및 간행물 5(M. Forsell 및 J. Roivainen"]
    N18["18 21일"]
    N11["11 --- [페이지 구분] ---"]
    N12["12 --- [페이지 구분] ---"]
    N13["13 --- [페이지 구분] ---"]
    N15["15 --- [페이지 구분] ---"]
    N16["16 --- [페이지 구분] ---"]
    N17["17 --- [페이지 구분] ---"]
    N508["508 스레드화된 프로 세서의 데이터 메모리"]
    N502["502 상기 단계 캐시에 액세스하도록 구성되는 해시 및 구성 장치"]
    N510["510 에 액세스하도록 구성되는 메모리 요청 전송 논리 개체"]
    N108["108 물리적으로 확장 가능한 높은 대역폭의 상호 연결 네트워크"]
    N112["112 Mp"]
    N102["102 Pp"]
    N110["110 와 관련된 활성 메모리 장치"]
    N104["104 Ip"]
    N106["106 Sp"]
    N200["200 를 포함하는 ESM CMP 구조"]
    N300["300 도 3은 단계 캐시를 사용하는 전형적인 MCRCW ESM 프로세서"]
    N302["302 메모리 장치 대기 세그먼트 이전 및 이후에 논리적으로 배치되는 ALU"]
    N410["410 전송 논리"]
    N404["404 이중 어레이 단계 캐시"]
    N406["406 스크 래치패드"]
    N412["412 응답 수신 논리"]
    N414["414 및 수신 ALU"]
    N402["402 HCU"]
    N408["408 모리 시스템"]
    N602["602 방법의 시작"]
    N604["604 메모리 어레이를 형성하는 단계 캐시는 단계"]
    N606["606 단계"]
    N614["614 참조 에 대한 연산 및 결과 바이패스가 단계"]
    N618["618 SEQ"]
    N616["616 단계"]

    N500 -->|"형성하는"| N504
    N500 -->|"포함하는"| N506