%% 1020170022365 - 통신 방법 어포던스 활성화 흐름도
%% 생성일: 2026-05-11

flowchart TD
    100["전자 디바이스"]
    200["결제 계좌"]
    300["금융 기관"]
    400["통신 방법 어포던스"]
    100 -->|"링크 요청"| 200
    100 -->|"검증 필요 여부 결정"| 300
    300 -->|"검증 통신 요청"| 100
    100 -->|"활성화 검출"| 400
    400 -->|"어포던스 활성화 검출"| 100