%% 1020240155799 - 전자 장치 구성도
%% 생성일: 2026-05-11

classDiagram
    class 검색질의 {
        +String 검색어
    }
    class 검색결과정보 {
        +String 관련컨텐츠정보
    }
    class 프롬프트 {
        +String 질의
    }
    class 언어모델 {
        +결정검색의도()
    }
    검색질의 --> 검색결과정보 : "기초하여 결정됨"
    검색결과정보 --> 프롬프트 : "기초하여 생성됨"
    프롬프트 --> 언어모델 : "입력받음"