%% 1020240155799 - 검색 의도 결정 방법 흐름도
%% 생성일: 2026-05-11

flowchart TD
    100["검색 질의"]
    200["검색 결과 정보"]
    300["프롬프트"]
    400["언어 모델"]
    100 -->|"기초하여 결정됨"| 200
    200 -->|"기초하여 생성됨"| 300
    300 -->|"입력받음"| 400