%% 1020210001419 - 스마트 상담 매칭 프로세스
%% 생성일: 2026-05-11

flowchart TD
    100["재무관리 서버"]
    200["사용자 단말기"]
    300["전문가 단말기"]
    400["외부 금융기관 서버"]
    200 -->|"상담 요청 송신"| 100
    100 -->|"사용자 정보를 송신"| 200
    100 -->|"상담 요청 수신 및 매칭"| 300
    300 -->|"상담 요청 수락"| 100
    300 -->|"상담 결과 송신"| 200
    100 -->|"전문가 평가 및 지역화폐 제공"| 400
    400 -->|"지역화폐 거래 처리"| 100