%% 1020200073425 - 공동주택 통합 관리 플랫폼 제공 시스템
%% 생성일: 2026-05-11

classDiagram
    class 사용자단말 {
        +CCTV 영상 출력
        +관리비 정보 출력 및 결제
        +커뮤니티 데이터 업로드/조회
    }
    class CCTV관리부 {
        +엑세스 요청 처리
    }
    class 세대관리부 {
        +관리비 정보 제공
    }
    class 결제연동부 {
        +결제 수단 제공
    }
    사용자단말 --> CCTV관리부 : "CCTV 영상 요청"
    CCTV관리부 --> 사용자단말 : "영상 스트리밍"
    사용자단말 --> 세대관리부 : "관리비 정보 요청"
    세대관리부 --> 사용자단말 : "관리비 내역 전송 및 결제 진행"