%% 1020200073425 - 통합 관리 서비스 제공 서버 블록 구성도
%% 생성일: 2026-05-11

classDiagram
    class 사용자단말 {
        +CCTV 영상 출력
        +관리비 정보 출력 및 결제
        +커뮤니티 데이터 업로드/조회
    }
    class CCTV관리부 {
        +엑세스 요청 처리()
    }
    class 세대관리부 {
        +관리비 정보 제공()
    }
    class 관리자관리부 {
        +구인구직풀 생성 및 관리()
    }
    class 결제연동부 {
        +결제 수단 제공()
    }
    class 리뷰관리부 {
        +평점 및 리뷰 데이터 관리()
    }
    class 투표진행부 {
        +투표 진행()
    }
    class 에스크로부 {
        +보수 지급 관리()
    }
    사용자단말 --> CCTV관리부 : "엑세스 요청 처리"
    사용자단말 --> 세대관리부 : "관리비 정보 제공"
    사용자단말 --> 결제연동부 : "결제 수단 제공"