%% 1020230183351 - 서버 구성도
%% 생성일: 2026-05-11

classDiagram
    class 제안자단말 {
        +String 요청
        +전송()
    }
    class 서버 {
        +String 매칭기능
        +알림전송()
    }
    class 응답자단말 {
        +String 참여요청
        +전송()
    }
    class 매칭수행부 {
        +매칭()
    }
    class 참여지원부 {
        +전자계약()
        +결제진행()
    }
    제안자단말 --> 서버 : "생성 요청 수신"
    서버 --> 응답자단말 : "응답자 단말에 프로젝트 알림"
    응답자단말 --> 서버 : "참여 요청 전송"
    서버 --> 매칭수행부 : "서버의 일부"
    서버 --> 참여지원부 : "서버의 일부"