%% 1020230183351 - 서버 동작 순서
%% 생성일: 2026-05-11

flowchart TD
    100["제안자 단말"]
    200["서버"]
    300["응답자 단말"]
    400["매칭 수행부"]
    500["참여 지원부"]
    
    100 -->|"생성 요청 수신"| 200
    200 -->|"응답자 선택 및 알림 전송"| 300
    300 -->|"참여 요청 전송"| 200
    200 -->|"전자 계약 및 결제 진행"| 500