%% 1020230003745 - 중고 서적 거래 인세 지급 프로세스
%% 생성일: 2026-05-11

flowchart TD
    100["서버"]
    200["제1 사용자 단말"]
    300["제2 사용자 단말"]
    400["저자 단말"]
    500["인센티브 DB"]
    600["인세 DB"]
    
    200 -->| "판매 희망 정보 전송" | 100
    300 -->| "구매 희망 정보 전송" | 100
    400 -->| "저자 정보 입력" | 100
    100 -->| "인세 정보 저장" | 600
    100 -->| "인센티브 정보 저장" | 500