%% 1020230001162 - 객체 검출 방법 흐름도
%% 생성일: 2026-05-11

flowchart TD
    100["시각 정보 및 관심 영역 정보 입력"]
    200["제1 인공 신경망 학습"]
    300["청각 정보 및 관심 영역 정보 입력"]
    400["제2 인공 신경망 학습"]
    500["청각 정보 입력 및 관심 영역 예측"]
    600["제3 인공 신경망 학습"]
    700["시각 및 청각 특징점 통합"]
    800["제4 인공 신경망 학습"]
    900["시각 특징점 분류"]
    1000["제5 인공 신경망 학습"]
    1100["청각 특징점 분류"]
    1200["제6 인공 신경망 학습"]

    100 --> 200
    200 --> 300
    300 --> 400
    400 --> 500
    500 --> 600
    600 --> 700
    700 --> 800
    800 --> 900
    900 --> 1000
    1000 --> 1100
    1100 --> 1200