%% 1020177001104 - 시스템 구성도
%% 생성일: 2026-05-11

classDiagram
    class 서버 {
        +String 지오로케이션데이터
        +manageEventGallery()
    }
    class 클라이언트디바이스 {
        +String 사용자메시지
        +accessEventGallery()
    }
    class 지오로케이션데이터 {
        +String 위치정보
    }
    class 이벤트갤러리 {
        +String 콘텐츠
    }
    클라이언트디바이스 --> 서버 : "데이터 요청 및 수신"
    서버 --> 지오로케이션데이터 : "서버에 의해 수신됨"
    지오로케이션데이터 <-- 클라이언트디바이스 : "클라이언트 디바이스에서 생성됨"
    서버 --> 이벤트갤러리 : "서버에서 관리됨"
    이벤트갤러리 <-- 클라이언트디바이스 : "사용자가 접근함"