%% 1020177001104 - 클라이언트 측 처리 흐름도
%% 생성일: 2026-05-11

flowchart TD
    100["서버"]
    200["클라이언트 디바이스"]
    300["지오-로케이션 데이터"]
    400["이벤트 갤러리"]
    
    200 -->| "데이터 요청 및 수신" | 100
    100 -->| "서버에 의해 수신됨" | 300
    300 -->| "지오-로케이션 펜스와 비교" | 100
    100 -->| "이벤트 갤러리 정보 추가" | 400
    200 -->| "사용자 선택 검출" | 400
    400 -->| "팔로워 추가" | 100