%% 1020220186878 - 렌터카 대여 프로세스 흐름도
%% 생성일: 2026-05-11

flowchart TD
    100["렌터카"]
    200["사용자단말기"]
    300["관리자단말기"]
    400["관리서버"]
    500["예약관리부"]
    600["계약관리부"]
    700["대차관리부"]
    800["매출관리부"]
    900["차량관리부"]

    200 -->| "예약 및 정보 제공" | 100
    200 -->| "예약 정보 제공" | 400
    400 -->| "예약 정보 수신" | 500
    500 -->| "예약 정보 감지" | 600
    600 -->| "차량 인도 및 반납 정보 수신" | 700
    700 -->| "매출 정보 관리" | 800
    700 -->| "차량 사용 정도 관리" | 900