%% 1020220186878 - 렌터카 관리 시스템 구성도
%% 생성일: 2026-05-11

classDiagram
    class 렌터카 {
        +String 차량정보
    }
    class 사용자단말기 {
        +예약()
        +정보제공()
    }
    class 관리자단말기 {
        +관리정보수신()
    }
    class 관리서버 {
        +예약정보관리()
        +관리정보제공()
    }
    class 예약관리부 {
        +예약정보수신()
    }
    class 계약관리부 {
        +예약정보감지()
    }
    class 대차관리부 {
        +차량인도반납정보수신()
    }
    class 매출관리부 {
        +매출관리()
    }
    class 차량관리부 {
        +사용정도관리()
    }

    사용자단말기 -->|예약 및 정보 제공| 렌터카
    관리서버 <--|예약 정보 제공| 사용자단말기
    관리서버 <--|관리 정보 제공| 관리자단말기
    예약관리부 -->|예약 정보 수신| 관리서버
    계약관리부 -->|예약 정보 감지| 예약관리부
    대차관리부 -->|차량 인도 및 반납 정보 수신| 렌터카