%% 1020210133890 - 드라이브 스루 픽업 서비스 시스템 구성도
%% 생성일: 2026-05-11

classDiagram
    class 고객단말 {
        +String 요청
        +String 결제
    }
    class 관리자단말 {
        +String 관리
        +String 결제정보처리
    }
    class 관리자서버 {
        +String 요청처리
        +String 상품이송관리
    }
    고객단말 --> 관리자서버 : "통신"
    관리자단말 --> 관리자서버 : "관리"
    관리자서버 --> 고객단말 : "통신"
    관리자서버 --> 관리자단말 : "통신"