%% 1020227009490 - 물리적 환경과의 상호작용 방법
%% 생성일: 2026-05-11

flowchart TD
    100["컴퓨터 제어 시스템"]
    120["데이터 인터페이스"]
    140["프로세서 서브시스템"]
    160["센서 인터페이스"]
    180["액추에이터 인터페이스"]
    030["기본 가중치 행렬 데이터"]
    040["파라미터 세트"]

    100 -->| "정책의 파라미터 세트에 액세스" | 120
    120 -->| "기본 가중치 행렬 데이터 획득" | 030
    160 -->| "센서 데이터 획득" | 100
    100 -->| "신경망의 최종 계층 적용" | 030
    100 -->| "액추에이터 데이터 제공" | 180