%% 1020220071866 - 하드웨어 기반 스파이킹 뉴럴 네트워크 구성도
%% 생성일: 2026-05-11

classDiagram
    class 시냅스어레이 {
        +구성()
    }
    class 뉴런회로 {
        +추론()
    }
    class 제어부 {
        +제어()
    }
    class 메모리 {
        +저장()
    }
    class 프로세서 {
        +실행()
    }
    제어부 --> 시냅스어레이 : "제어"
    제어부 --> 뉴런회로 : "제어"
    뉴런회로 <-- 시냅스어레이 : "구성"
    프로세서 --> 메모리 : "실행"