%% 1020107008865 - 디바이스의 기본 구조 블록도
%% 생성일: 2026-05-11

classDiagram
    class 디스플레이수단 {
        +String 정보
    }
    class 메모리수단 {
        +String 데이터
    }
    class 프로세서수단 {
        +String 명령
        +처리()
    }
    class 제1입력수단 {
        +String 기본문자입력
    }
    class 제2입력수단 {
        +String 보충문자입력
    }
    제1입력수단 --> 디스플레이수단 : "입력"
    제2입력수단 --> 디스플레이수단 : "입력"
    프로세서수단 --> 메모리수단 : "데이터 처리"