%% 1020107008865 - 문자 생성 방법의 흐름도
%% 생성일: 2026-05-11

flowchart TD
    100["디스플레이 수단"]
    200["메모리 수단"]
    300["프로세서 수단"]
    400["제 1 입력 수단"]
    500["제 2 입력 수단"]
    
    400 -->|"입력"| 100
    500 -->|"입력"| 100
    100 -->|"기본 문자 구성요소에 상응하는 입력 수신"| 300
    300 -->|"보충 문자 구성요소에 상응하는 입력 수신"| 200
    200 -->|"문자 입력 형성"| 100