%% 1020230005898 - 주택관리 서비스 제공 흐름도
%% 생성일: 2026-05-11

flowchart TD
    100["지자체 서버"]
    200["사용자 단말"]
    300["공공지원안내부"]
    400["사용자등록부"]
    500["일괄납부관리부"]
    600["성능진단부"]
    700["주택관리중개부"]
    
    200 -->|"소유지 또는 거주지 정보 입력"| 400
    400 -->|"정보 입력 수신"| 300
    300 -->|"공공지원사업 정보 제공"| 200
    200 -->|"유지비 일괄납부 요청"| 500
    500 -->|"청구 정보 전송"| 200
    200 -->|"성능진단 요청"| 600
    600 -->|"주택성능진단 결과 전송"| 200
    200 -->|"서비스 요청"| 700