%% 1020230024571 - IoT 센서를 이용한 GCN 기반 안전관리시스템 구성도
%% 생성일: 2026-05-11

classDiagram
    class IoT엣지게이트웨이 {
        +String 센싱값
        +분석()
    }
    class 복합센서 {
        +String 환경변수
        +데이터제공()
    }
    class GCN상황분류모델 {
        +String 분석결과
        +상황분류()
    }
    class LSTM오토인코더 {
        +String 시계열데이터
        +정상비정상분류()
    }
    IoT엣지게이트웨이 --> 복합센서 : "수집 및 분석"
    복합센서 --> IoT엣지게이트웨이 : "데이터 제공"
    복합센서 --> GCN상황분류모델 : "상황 반영"
    GCN상황분류모델 --> IoT엣지게이트웨이 : "분석 결과 제공"
    복합센서 --> LSTM오토인코더 : "데이터 분석"
    LSTM오토인코더 --> GCN상황분류모델 : "결과 제공"