%% 1020230024571 - GCN 상황분류 모델 구축 과정
%% 생성일: 2026-05-11

flowchart TD
    100["IoT 엣지 게이트웨이"]
    200["복합 센서"]
    300["GCN 상황분류 모델"]
    400["LSTM 오토인코더"]
    200 -->|"데이터 제공"| 100
    100 -->|"수집 및 분석"| 200
    200 -->|"상황 반영"| 300
    300 -->|"분석 결과 제공"| 100
    200 -->|"데이터 분석"| 400
    400 -->|"결과 제공"| 300