%% 1020197037891 - 인공지능 프로세서 아키텍처
%% 생성일: 2026-05-11

classDiagram
    class OfflineExecutableFile {
        +String requirements
    }
    class AIProcessor {
        +processData()
    }
    class AcquisitionModule {
        +getExecutableFile()
    }
    class TransmissionModule {
        +sendInformation()
    }
    AIProcessor --> OfflineExecutableFile : "생성"
    AIProcessor --> AcquisitionModule : "포함"
    AIProcessor --> TransmissionModule : "포함"