%% 1020197037891 - 데이터 처리 방법 흐름도
%% 생성일: 2026-05-11

flowchart TD
    100["오프라인 실행 파일"]
    200["인공지능 프로세서"]
    300["획득 모듈"]
    400["송신 모듈"]
    300 -->|"생성"| 100
    200 -->|"포함"| 300
    200 -->|"포함"| 400