%% 1020237010470 - AR 시스템을 통한 링키지 결정 과정
%% 생성일: 2026-05-11

flowchart TD
    100["AR 시스템"]
    200["외향 카메라"]
    300["광학 센서"]
    400["문서"]
    500["사람"]
    200 -->|"구성 요소"| 100
    300 -->|"구성 요소"| 100
    400 <--|"링키지 대상"| 100
    500 <--|"링키지 대상"| 100
    100 -->|"환경의 이미지 획득"| 200
    100 -->|"사람 및 문서 검출"| 300
    100 -->|"개인 정보 추출"| 400
    100 -->|"링키지 결정"| 500