%% 1020210101757 - 시스템 구성 요소 다이어그램
%% 생성일: 2026-05-11

classDiagram
    class 서버 {
        +String 콘텐츠관리
        +결제지원()
    }
    class 구매자기기 {
        +String 사용자인터페이스
        +결제진행()
    }
    class 호스트기기 {
        +String 콘텐츠생성
        +판매물품소개()
    }
    서버 --> 구매자기기 : "제어 및 데이터 제공"
    서버 --> 호스트기기 : "정보 수신 및 처리"
    호스트기기 --> 서버 : "콘텐츠 제공"
    호스트기기 --> 구매자기기 : "판매 물품 정보 제공"
    구매자기기 --> 서버 : "데이터 요청 및 결제 진행"
    구매자기기 --> 호스트기기 : "결제 정보 수신"