%% 1020210101757 - 실시간 결제 시스템 흐름도
%% 생성일: 2026-05-11

flowchart TD
    100["서버"]
    200["구매자 기기"]
    300["호스트 기기"]
    100 -->|"제어 및 데이터 제공"| 200
    100 -->|"콘텐츠 제공"| 300
    200 <--|"데이터 요청 및 결제 진행"| 100
    200 <--|"결제 정보 수신"| 300
    300 -->|"판매 물품 정보 제공"| 200