%% 1020240052421 - U형 자동화 컨테이너 부두 관리 시스템 개요
%% 생성일: 2026-05-11

flowchart TD
    100["컨테이너 추적 관리 모듈"]
    200["데이터 분석 모듈"]
    300["작업 배치 모듈"]
    400["사물인터넷 집적 모니터링 모듈"]
    500["통신관리 모듈"]
    600["친환경 에너지 관리 및 최적화 모듈"]
    700["가상 현실 모의 모듈"]

    100 -->|"데이터 제공"| 200
    200 -->|"작업 데이터 제공"| 300
    100 -->|"데이터 수집"| 400