%% 1020210187390 - 검색 결과 페이지 변경 흐름도
%% 생성일: 2026-05-11

flowchart TD
    100["전자 장치"]
    200["검색 엔진"]
    300["데이터 세트"]
    400["랜딩 페이지"]
    
    200 -->|"키워드 정보를 제공받음"| 100
    100 -->|"키워드 입력"| 200
    100 -->|"키워드 정보를 포함함"| 300
    100 -->|"키워드에 따라 변경됨"| 400
    400 -->|"랜딩 페이지 타입 설정"| 100
    100 -->|"검색 건수 확인"| 400
    400 -->|"정보 변경 및 제공"| 100