%% 1020250162568 - 부재 마킹 및 인식 과정
%% 생성일: 2026-05-11

flowchart TD
    100["메인서버"]
    200["제1 영상수집장치"]
    300["코드인식부"]
    400["제2 영상수집장치"]
    100 <--|"코드 인식 결과 등록"| 300
    200 -->|"영상 데이터 전송"| 100
    300 -->|"인식 결과 전송"| 100
    400 -->|"영상 데이터 전송"| 100