%% 1020170106440 - 전자 장치 구성도
%% 생성일: 2026-05-11

classDiagram
    class 하우징 {
        +String 외부구조
    }
    class 터치스크린디스플레이 {
        +String 사용자상호작용
    }
    class 프로세서 {
        +String 어플리케이션실행
        +controlPermissions()
    }
    class 메모리 {
        +String 권한정보
        +storeData()
    }
    하우징 --> 터치스크린디스플레이 : "전기적으로 연결됨"
    프로세서 --> 메모리 : "전기적으로 연결됨"
    프로세서 <-- 터치스크린디스플레이 : "알림 제공"