%% 1020190103620 - 무인 점포 결제 시스템 구성도
%% 생성일: 2026-05-11

classDiagram
    class 소비자단말 {
        +결제요청()
    }
    class 무인점포단말 {
        +QR코드스캐닝()
    }
    class 서버 {
        +결제수단식별()
        +결제처리()
    }
    class 제1결제서버 {
        +결제처리()
    }
    class 제2결제서버 {
        +결제처리()
    }
    class 제3결제서버 {
        +결제처리()
    }
    소비자단말 --> 무인점포단말 : "결제 요청"
    무인점포단말 --> 서버 : "스캐닝"
    서버 --> 제1결제서버 : "결제 승인 요청"
    제1결제서버 --> 서버 : "결제 승인 요청"
    서버 --> 제2결제서버 : "결제 요청 정보 수신"
    서버 --> 제1결제서버 : "결제 승인 요청 거절 정보 수신"