%% 1020190103620 - 무인 점포 결제 흐름도
%% 생성일: 2026-05-11

flowchart TD
    100["소비자 단말"]
    200["무인 점포 단말"]
    300["서버"]
    400["제1 결제 서버"]
    500["제2 결제 서버"]
    600["제3 결제 서버"]
    
    100 -->| "제1 결제 수단 식별"| 200
    200 -->| "스캐닝"| 300
    300 -->| "결제 승인 요청"| 400
    400 -->| "결제 승인 요청 거절 정보 전송"| 300
    300 -->| "결제 승인 요청 거절 정보 수신"| 500
    500 -->| "제2 결제 수단 결제 승인 요청"| 300
    300 -->| "제3 결제 수단으로 결제 요청"| 600