%% 1020230128975 - 선박건조 스마트계약 프로세스 흐름도
%% 생성일: 2026-05-11

flowchart TD
    100["스마트계약 관리서버"]
    200["블록체인 네트워크"]
    300["블록체인-노드 구성원 클라이언트 단말기"]
    400["선박건조자 클라이언트 단말기"]
    500["선박소유자 클라이언트 단말기"]
    600["계약확인자 클라이언트 단말기"]
    900["금융기관 서버"]

    100 -->| "키-이벤트 코드 전송" | 200
    100 -->| "블록체인 노드와 상호작용" | 300
    100 -->| "선박건조자 클라이언트와 상호작용" | 400
    100 -->| "선박소유자 클라이언트와 상호작용" | 500
    100 -->| "계약확인자 클라이언트와 상호작용" | 600
    100 -->| "금융기관 서버와 상호작용" | 900