%% 1020210117592 - 전자 장치 구성도
%% 생성일: 2026-05-11

classDiagram
    class 전자장치 {
        +String 사용자입력
        +애니메이션제공()
    }
    class 통신모듈 {
        +String 입력데이터
        +입력수신()
    }
    class 데이터베이스 {
        +String 콘텐츠정보
        +정보저장()
    }
    class 프로세서 {
        +String 애니메이션상태
        +입력처리()
    }
    전자장치 --> 통신모듈 : "연결"
    전자장치 --> 데이터베이스 : "연결"
    전자장치 --> 프로세서 : "구성 요소"
    통신모듈 --> 프로세서 : "사용자 입력 수신"
    데이터베이스 --> 프로세서 : "데이터 처리"