%% 1020210134063 - 디지털 트윈 장치 구성도
%% 생성일: 2026-05-11

classDiagram
    class 디지털트윈장치 {
        +String 데이터수집()
        +String 잔여수명예측()
    }
    class 클라우드저장소 {
        +String 데이터저장()
    }
    class 딥러닝모델 {
        +String 모델생성()
        +String 열화경향예측()
    }
    디지털트윈장치 --> 클라우드저장소 : "데이터 저장"
    디지털트윈장치 --> 딥러닝모델 : "모델 생성"