%% 1020220181263 - 도로 상태이상 식별 시스템 구성도
%% 생성일: 2026-05-11

classDiagram
    class 이미지획득장치 {
        +String 저화질이미지
        +이미지획득()
    }
    class 식별모델생성장치 {
        +String 학습데이터
        +모델생성()
    }
    class 화질변환부 {
        +String 고화질이미지
        +변환()
    }
    class 라벨링이미지생성부 {
        +String 라벨링이미지
        +라벨링()
    }
    class 모델생성부 {
        +String 상태이상식별모델
        +모델생성()
    }
    이미지획득장치 --> 식별모델생성장치 : "이미지 획득"
    식별모델생성장치 --> 화질변환부 : "입력"
    화질변환부 --> 라벨링이미지생성부 : "입력"
    라벨링이미지생성부 --> 식별모델생성장치 : "출력"
    라벨링이미지생성부 --> 모델생성부 : "입력"