%% 1020220140197 - 학습 시스템 구성
%% 생성일: 2026-05-11

classDiagram
    class 샘플링부 {
        +데이터 획득()
    }
    class 재생성부 {
        +신경망 재생성()
    }
    class 적대적 생성 모델 {
        +생성()
        +판별()
    }
    class 베이지안 신경망 {
        +샘플링()
    }
    샘플링부 --> 베이지안 신경망 : "샘플링부에서 사용됨"
    재생성부 --> 샘플링부 : "샘플링부에서 데이터를 획득하여"
    재생성부 --> 적대적 생성 모델 : "재생성부에서 사용됨"
    베이지안 신경망 --> 재생성부 : "재생성부에서 사용됨"