%% 1020220140197 - 태스크 점진 학습 개괄
%% 생성일: 2026-05-11

flowchart TD
    100["샘플링부"]
    200["재생성부"]
    300["적대적 생성 모델"]
    400["베이지안 신경망"]
    400 -->|"샘플링부에서 사용됨"| 100
    100 -->|"샘플링부에서 데이터를 획득하여"| 200
    300 -->|"재생성부에서 사용됨"| 200
    400 -->|"재생성부에서 사용됨"| 200