%% 1020200148939 - 암 환자 치료 반응성 예측 방법 흐름도
%% 생성일: 2026-05-11

flowchart TD
    100["프로세서"]
    200["병리 슬라이드 이미지"]
    300["면역 세포 정보"]
    400["종양 세포 정보"]
    500["상호작용 스코어"]
    600["기계학습 모델"]
    
    200 -->| "처리됨" | 100
    300 -->| "사용됨" | 100
    400 -->| "사용됨" | 100
    100 -->| "예측에 사용됨" | 500
    500 -->| "입력됨" | 600