%% 1020240103624 - 구성 요소 및 관계도
%% 생성일: 2026-05-11

classDiagram
    class 구인단말 {
        +String 구인정보
        +registerJob()
    }
    class 구직단말 {
        +String 이력서
        +registerResume()
    }
    class 서버 {
        +manageJobInfo()
        +matchResume()
    }
    구인단말 --> 서버 : "구인 정보 등록"
    구직단말 --> 서버 : "이력서 등록 및 매칭"