%% 1020170022546 - 결제 거래 처리 흐름도
%% 생성일: 2026-05-11

flowchart TD
    100["전자 디바이스"]
    200["결제 계좌"]
    300["거래 정보"]
    400["금융 기관"]
    100 -->|"디스플레이 및 거래 진행"| 200
    100 -->|"디스플레이"| 300
    200 -->|"연관"| 300
    400 -->|"정보 제공"| 300