%% 1020170022546 - 전자 디바이스 구성도
%% 생성일: 2026-05-11

classDiagram
    class 전자디바이스 {
        +String 디스플레이()
        +String 거래진행()
    }
    class 결제계좌 {
        +String 결제정보
    }
    class 거래정보 {
        +String 거래필요정보
    }
    class 금융기관 {
        +String 정보제공()
    }
    전자디바이스 --> 결제계좌 : "디스플레이 및 거래 진행"
    전자디바이스 --> 거래정보 : "디스플레이"
    거래정보 --> 결제계좌 : "연관"
    금융기관 --> 거래정보 : "정보 제공"