%% 1020160144305 - 모바일 기프트 제공 장치 구성도
%% 생성일: 2026-05-11

classDiagram
    class 통신모듈 {
        +String 전송데이터
    }
    class 메모리 {
        +String 프로그램
    }
    class 프로세서 {
        +executeProgram()
    }
    class 사용자단말기 {
        +String 수신데이터
        +selectGift()
    }
    프로세서 --> 통신모듈 : "데이터 전송"
    프로세서 --> 메모리 : "프로그램 실행"
    사용자단말기 <-- 프로세서 : "데이터 수신"