%% 1020230195963 - 차량번호 인식 시스템 구성도
%% 생성일: 2026-05-11

classDiagram
    class 촬영부 {
        +String 이미지
        +전송()
    }
    class 차량검지부 {
        +String 검지영역
        +차량검지()
    }
    class 차량번호인식부 {
        +String 번호판정보
        +인식()
    }
    class 서버 {
        +String 차량번호
        +검색()
    }
    class 데이터베이스 {
        +String 차량정보
        +정보저장()
    }
    촬영부 --> 차량검지부 : "이미지 전송"
    차량검지부 --> 차량번호인식부 : "차량 검지 결과 사용"
    차량번호인식부 --> 서버 : "인식 정보 수신"
    서버 --> 데이터베이스 : "정보 검색"
    서버 <-- 데이터베이스 : "데이터베이스와 상호작용"