%% 1020200018698 - 클라우드 서비스 제공 방법 흐름도
%% 생성일: 2026-05-11

flowchart TD
    100["인메모리 클러스터"]
    200["서버 모듈"]
    300["데이터 접근 제어 모듈"]
    400["데이터 분산 모듈"]
    500["보안 모듈"]
    600["관리 모듈"]
    
    200 -->|"이벤트 데이터 제공"| 100
    200 -->|"Web API 접근"| 300
    200 -->|"데이터 복제"| 400
    200 -->|"인증 수행"| 500
    400 -->|"데이터 복제"| 100
    600 -->|"보안 모듈 조절"| 500