%% 1020097002237 - 맞춤형 소프트웨어 애플리케이션 개발 사이클
%% 생성일: 2026-05-11

flowchart TD
    100["VIDEA"]
    200["컴포넌트"]
    300["XML 파일"]
    400["런-타임 로더"]
    100 -->|"사용하여 생성됨"| 200
    200 -->|"소프트웨어 애플리케이션 생성 시작"| 300
    300 -->|"사용하여 저장됨"| 400
    400 -->|"파일을 판독함"| 100