%% 1020097002237 - 맞춤형 소프트웨어 애플리케이션 개발 사이클
%% 생성일: 2026-05-11

flowchart TD
    100["VIDEA"]
    200["컴포넌트 박스"]
    300["편집기"]
    400["특성 박스"]
    100 -->|"요구 식별"| 200
    200 -->|"드래그하여 편집기로 이동"| 300
    300 -->|"컴포넌트의 특성을 조작"| 400