%% 1020190140001 - 메모리 시스템 구성도
%% 생성일: 2026-05-11

classDiagram
    class MemoryDevice {
        +String data
    }
    class MemoryController {
        +String errorStatus
        +control()
        +judgeError()
    }
    class PowerController {
        +String powerSettings
        +adjustPower()
    }
    MemoryDevice <-- MemoryController : "제어"
    MemoryController --> PowerController : "전원 제어기와 상호작용"
    PowerController <-- MemoryController : "제어받음"