%% 1020220176917 - 통합 영업 플랫폼 시스템 구성도
%% 생성일: 2026-05-11

classDiagram
    class 영업조직랜딩페이지데이터베이스 {
        +String 랜딩페이지정보
    }
    class 랜딩페이지노출부 {
        +exposeToSNS()
    }
    class 사용자정보제공부 {
        +provideInformation()
    }
    class 사용자정보수신부 {
        +receiveUserInfo()
    }
    class 지원정보제공부 {
        +provideSupportInfo()
    }
    사용자정보제공부 -->| "데이터 요청" | 영업조직랜딩페이지데이터베이스
    사용자정보수신부 -->| "정보 제공" | 사용자정보제공부
    랜딩페이지노출부 -->| "데이터 제공" | 영업조직랜딩페이지데이터베이스
    지원정보제공부 -->| "정보 분석" | 사용자정보수신부