%% 1020240101366 - 구성 요소 클래스 다이어그램
%% 생성일: 2026-05-11

classDiagram
    class 사용자단말 {
        +String 사용자정보
        +접근()
    }
    class 콘텐츠감시서버 {
        +String 서버정보
        +데이터수신()
        +데이터수집()
        +데이터분석()
        +유해콘텐츠분류()
        +채증삭제관리()
        +데이터저장()
    }
    class 데이터수집부 {
        +String 수집정보
        +키워드추출()
    }
    class 데이터검출부 {
        +String 분석정보
        +유해콘텐츠분류()
    }
    class 데이터분석부 {
        +String 분석결과
        +특성분석()
    }
    class 채증삭제관리부 {
        +String 요청정보
        +관리()
    }
    class 데이터베이스 {
        +String 저장정보
        +저장()
    }

    사용자단말 --> 콘텐츠감시서버 : "데이터 수신"
    콘텐츠감시서버 --> 데이터수집부 : "데이터 수집"
    콘텐츠감시서버 --> 데이터검출부 : "데이터 분석"
    콘텐츠감시서버 --> 데이터분석부 : "유해 콘텐츠 분류"
    콘텐츠감시서버 --> 채증삭제관리부 : "채증 및 삭제 관리"
    콘텐츠감시서버 --> 데이터베이스 : "데이터 저장"