%% 1020220143407 - 행동 인식 모델의 동작 방법
%% 생성일: 2026-05-11

flowchart TD
    100["수신단계"]
    200["혼합단계"]
    300["학습단계"]
    400["행동 인식 모델"]
    500["객체 검출부"]
    600["객체 추적부"]
    
    500 -->| "동영상 수신 및 검출"| 100
    100 -->|"이 단계의 이전 단계"| 200
    200 -->|"이 단계의 이전 단계"| 300
    300 -->|"프레임 인식"| 400