%% 1020200128459 - 모바일 플랫폼을 이용한 온라인 광고 시스템 구성도
%% 생성일: 2026-05-11

classDiagram
    class 사용자단말기 {
        +String 사용자정보
        +상호작용()
    }
    class 출력부 {
        +String 콘텐츠정보
        +출력()
    }
    class 콘텐츠정보 {
        +String 데이터
    }
    class 신문기사 {
        +String 기사내용
    }
    class 광고이미지 {
        +String 이미지데이터
    }
    사용자단말기 --> 출력부 : "콘텐츠 정보 출력"
    출력부 --> 콘텐츠정보 : "출력하는 콘텐츠"
    출력부 <-- 신문기사 : "출력되는 신문기사"
    출력부 <-- 광고이미지 : "출력되는 광고 이미지"