%% 1020200128459 - 모바일 플랫폼을 이용한 온라인 광고 방법 흐름도
%% 생성일: 2026-05-11

flowchart TD
    100["사용자 단말기"]
    200["출력부"]
    300["콘텐츠 정보"]
    400["신문기사"]
    500["광고 이미지"]
    
    100 -->|"콘텐츠 정보 요청"| 200
    200 -->|"출력하는 콘텐츠"| 300
    300 -->|"신문기사 접근 유도 문구 출력"| 400
    400 -->|"출력되는 신문기사"| 200
    200 -->|"출력되는 광고 이미지"| 500