%% 1020210138676 - 진열 어셈블리 구성도
%% 생성일: 2026-05-11

classDiagram
    class 진열어셈블리 {
        +String 진열공간
        +String 키오스크단말기
        +manageProducts()
    }
    class 관리서버 {
        +String 배송정보
        +monitorStock()
    }
    class 배송담당자단말기 {
        +String 진열가이드
        +receiveInfo()
    }
    class 임직원단말기 {
        +String 리워드정보
        +provideInfo()
    }
    진열어셈블리 <-- 관리서버 : "관리"
    관리서버 --> 배송담당자단말기 : "정보 전송"
    배송담당자단말기 <-- 관리서버 : "정보 수신"
    배송담당자단말기 --> 진열어셈블리 : "진열 가이드"
    관리서버 --> 임직원단말기 : "정보 제공"