%% 1020220144287 - 폐디바이스 재활용 및 AI모델 운영 흐름도
%% 생성일: 2026-05-11

flowchart TD
    100["소상공인 단말기"]
    200["마켓플레이스 플랫폼"]
    300["AI모델 제공자 단말기"]
    400["엣지 디바이스"]
    100 -->|"기부 의사 정보 전송"| 200
    200 <--|"니즈정보 수집"| 100
    200 -->|"AI모델 제공"| 300
    300 <--|"기획설계정보 전송"| 200
    300 -->|"AI모델 전송"| 400
    400 -->|"예측결과 데이터 전송"| 200
    200 -->|"예측결과 데이터 분석"| 400