%% 1020220144287 - 시스템 구성도
%% 생성일: 2026-05-11

classDiagram
    class 소상공인단말기 {
        +기부의사정보전송()
    }
    class 마켓플레이스플랫폼 {
        +니즈정보수집()
        +AI모델제공()
        +예측결과데이터분석()
    }
    class AI모델제공자단말기 {
        +기획설계정보전송()
        +AI모델전송()
    }
    class 엣지디바이스 {
        +예측결과데이터전송()
    }
    소상공인단말기 --> 마켓플레이스플랫폼 : "기부 의사 정보 전송"
    마켓플레이스플랫폼 <-- 소상공인단말기 : "니즈정보 수집"
    마켓플레이스플랫폼 --> AI모델제공자단말기 : "AI모델 제공"
    AI모델제공자단말기 <-- 마켓플레이스플랫폼 : "기획설계정보 전송"
    AI모델제공자단말기 --> 마켓플레이스플랫폼 : "AI모델 전송"
    마켓플레이스플랫폼 --> 엣지디바이스 : "예측결과 데이터 분석"
    엣지디바이스 --> 마켓플레이스플랫폼 : "예측결과 데이터 전송"