%% 1020230106712 - 경조사비 결제 시스템 구성도
%% 생성일: 2026-05-11

classDiagram
    class 사용자단말 {
        +String url
        +결제정보입력()
    }
    class 키오스크단말 {
        +String 식권
        +String 답례품
        +출력()
    }
    class 관리서버 {
        +String 결제정보
        +정보처리()
    }
    사용자단말 --> 관리서버 : "정보 전송"
    관리서버 --> 키오스크단말 : "정보 수집"
    키오스크단말 --> 사용자단말 : "결제 정보 제공"