%% 1020220131207 - 신경망 모델 구성도
%% 생성일: 2026-05-11

classDiagram
    class 신경망모델 {
        +예측회복정보()
    }
    class 환부이미지 {
        +String 이미지데이터
    }
    class 회복정보 {
        +String 상태정보
    }
    class 과업 {
        +String 학습데이터
    }
    class 시술경과일정보 {
        +int 경과일
    }
    환부이미지 --> 신경망모델 : "입력"
    시술경과일정보 --> 환부이미지 : "추가 입력"
    신경망모델 --> 회복정보 : "출력"
    과업 --> 신경망모델 : "학습 기반"