%% 1020180122065 - 멀티 커널 시스템 구성도
%% 생성일: 2026-05-11

classDiagram
    class 메인프로세서의제1커널 {
        +입출력태스크처리()
    }
    class 병렬프로세서의경량커널 {
        +입출력태스크생성()
        +공유메모리설정()
    }
    class 공유메모리 {
        +데이터송수신()
    }
    메인프로세서의제1커널 --> 병렬프로세서의경량커널 : "입출력 태스크를 전달받음"
    병렬프로세서의경량커널 --> 메인프로세서의제1커널 : "입출력 태스크를 전달함"
    병렬프로세서의경량커널 --> 공유메모리 : "공유 메모리를 설정함"