%% 1020117002469 - 데이터 저장 및 암호화 과정
%% 생성일: 2026-05-11

flowchart TD
    100["소프트웨어 애플리케이션"]
    200["제1 버퍼"]
    300["암호화 파일 시스템"]
    400["비휘발성 스토리지"]
    100 -->| "데이터 기록 요청" | 200
    200 -->| "암호화 요청" | 300
    300 -->| "데이터 암호화" | 200
    300 -->| "암호화된 데이터 저장" | 400