%% 1020147034720 - 트랜잭션 실행 제어 흐름도
%% 생성일: 2026-05-11

flowchart TD
    100["프로세서"]
    200["트랜잭션 시작 기계어 명령"]
    300["제어 요소"]
    400["부동 소수점 명령"]
    500["액세스 레지스터"]
    
    200 -->| "실행" | 100
    100 -->| "사용" | 300
    300 -->| "제어" | 400
    300 -->| "제어" | 500