%% 1020220126066 - 영상 특성 추출 단계 세부 흐름도
%% 생성일: 2026-05-11

flowchart TD
    100["영상 특성 추출 단계"]
    200["산림 비율 추출 단계"]
    300["시간 특성 추출 단계"]
    400["특성 기록 단계"]
    500["영상데이터 분류 단계"]
    100 -->|"이전 단계"| 200
    200 -->|"이전 단계"| 300
    300 -->|"이전 단계"| 400
    400 -->|"이전 단계"| 500