%% 1020240129470 - 통합 학사 행정 플랫폼 구성도
%% 생성일: 2026-05-11

classDiagram
    class 통합_학사_행정_플랫폼_서버 {
        +String 공교육_정보
        +String 사교육_정보
        +통합_관리()
    }
    class 교육_수혜자_단말 {
        +String 사용자_정보
        +연동()
    }
    class 국가_교육_정보_플랫폼_서버 {
        +String 공교육_일정
        +정보_제공()
    }
    class 클라우드_서버 {
        +String 사교육_일정
        +정보_제공()
    }
    class 통합_학사_행정_앱 {
        +String 일정_관리
        +연동()
    }
    교육_수혜자_단말 --> 통합_학사_행정_플랫폼_서버 : "연동"
    국가_교육_정보_플랫폼_서버 --> 통합_학사_행정_플랫폼_서버 : "정보 제공"
    클라우드_서버 --> 통합_학사_행정_플랫폼_서버 : "정보 제공"
    통합_학사_행정_앱 --> 통합_학사_행정_플랫폼_서버 : "연동"
    통합_학사_행정_앱 --> 교육_수혜자_단말 : "제공"