%% 1020240129470 - 통합 학사 행정 플랫폼 흐름도
%% 생성일: 2026-05-11

flowchart TD
    100["통합 학사 행정 플랫폼 서버"]
    200["교육 수혜자 단말"]
    300["국가 교육 정보 플랫폼 서버"]
    400["클라우드 서버"]
    500["통합 학사 행정 앱"]
    
    200 -->|"연동"| 100
    300 -->|"정보 제공"| 100
    400 -->|"정보 제공"| 100
    100 -->|"학사 일정 정보 통합"| 500
    500 -->|"제공"| 200