%% 1020240163492 - 하수관망 모델링 시스템 구성도
%% 생성일: 2026-05-11

classDiagram
    class 사용자인터페이스 {
        +String 사용자상호작용
    }
    class 기본정보설정부 {
        +String 초기정보
        +설정()
    }
    class 레이어목록부 {
        +String 지도레이어
        +관리()
    }
    class SWMM요소제공부 {
        +String 하수관망요소
        +제공()
    }
    class 지도뷰 {
        +String 시각화
        +편집()
    }
    class 하단메뉴부 {
        +String 시뮬레이션결과
        +제공()
    }
    class 상단메뉴부 {
        +String 주요기능
        +접근()
    }
    class 제어부 {
        +String 시스템제어
        +연결()
    }

    사용자인터페이스 --> 기본정보설정부 : "정보 제공"
    기본정보설정부 --> 레이어목록부 : "정보 제공"
    레이어목록부 --> SWMM요소제공부 : "관리 기능 제공"
    SWMM요소제공부 --> 지도뷰 : "데이터 제공"