%% 1020220088007 - 시스템 구성도
%% 생성일: 2026-05-11

classDiagram
    class 제1업체단말 {
        +판매요청정보전송()
    }
    class SNS서버 {
        +인플루언서정보제공()
    }
    class 인공지능시스템 {
        +판매요구사항분석()
        +SNS활동현황분석()
    }
    class 제1인플루언서단말 {
        +추천정보수신()
        +판매페이지생성()
    }
    class 제1페이지 {
        +판매페이지제공()
    }
    제1업체단말 --> SNS서버 : "판매 요청 정보 수신"
    SNS서버 --> 인공지능시스템 : "인플루언서 정보 분석"
    인공지능시스템 --> 제1인플루언서단말 : "추천 정보 전송"
    제1인플루언서단말 --> 제1페이지 : "판매 페이지 생성"
    제1페이지 --> 제1인플루언서단말 : "판매 페이지 제공"