%% 1020240081489 - 선박 상태 모니터링 및 예지보전 관리 시스템 구성도
%% 생성일: 2026-05-11

classDiagram
    class 데이터전처리부 {
        +로우 데이터 수집()
        +전처리()
    }
    class 데이터통신부 {
        +전처리된 데이터 전송()
    }
    class 예지보전판단부 {
        +이상 데이터 식별()
        +분석()
    }
    class 선박대시보드 {
        +결과 디스플레이()
    }
    class 머신러닝운영시스템부 {
        +알고리즘 생성()
        +업데이트()
    }
    데이터전처리부 --> 데이터통신부 : "전처리된 데이터 전송"
    데이터전처리부 --> 예지보전판단부 : "전처리 데이터 수신"
    데이터통신부 --> 예지보전판단부 : "데이터 수신"
    예지보전판단부 --> 선박대시보드 : "결과 전송"
    머신러닝운영시스템부 --> 데이터통신부 : "데이터 수신"
    머신러닝운영시스템부 --> 예지보전판단부 : "알고리즘 업데이트"