%% 1020230039672 - 서버 시스템 구성도
%% 생성일: 2026-05-11

classDiagram
    class 메모리 {
        +String 명령어들
        +저장()
    }
    class 프로세서 {
        +String 증권형토큰
        +발행()
        +증명데이터획득()
    }
    class 사용자 {
        +String 이벤트
        +토큰지급받기()
    }
    사용자 --> 프로세서 : "증명 데이터를 기반으로 토큰을 지급받음"
    프로세서 --> 메모리 : "저장된 명령어를 실행"