%% 1020230039672 - 탄소 저감 이벤트 처리 흐름도
%% 생성일: 2026-05-11

flowchart TD
    100["메모리"]
    200["프로세서"]
    300["사용자"]
    400["증권형 토큰 지급"]
    300 -->|"탄소 저감 이벤트 수행"| 200
    200 -->|"증명 데이터 획득"| 100
    100 -->|"탄소 저감량 판별"| 200
    200 -->|"토큰 지급"| 400