%% 1020130123902 - 이동식 저장매체 처리 시스템 구성도
%% 생성일: 2026-05-11

classDiagram
    class 단말기 {
        +String 처리주체
    }
    class 저장경로제어모듈 {
        +String 저장경로
        +제어()
    }
    class 격리공간관리모듈 {
        +String 격리공간
        +관리()
    }
    class 저장디스크 {
        +String 저장장치
    }
    class 운영체제 {
        +String 시스템소프트웨어
    }
    class 이동식저장매체 {
        +String 저장파일
    }
    단말기 --> 이동식저장매체 : "접속"
    이동식저장매체 --> 저장경로제어모듈 : "전송"
    저장경로제어모듈 --> 운영체제 : "제어"
    격리공간관리모듈 --> 저장디스크 : "관리"