%% 1020130123902 - 이동식 저장매체 저장파일 처리 방법 흐름도
%% 생성일: 2026-05-11

flowchart TD
    100["단말기"]
    200["이동식 저장매체"]
    110["저장경로 제어모듈"]
    120["격리공간 관리모듈"]
    140["저장디스크"]
    150["운영체제"]

    100 -->|"접속 확인"| 200
    200 -->|"저장경로 설정"| 110
    110 -->|"저장파일 실행 및 변경데이터 저장"| 150
    120 -->|"격리공간 관리 및 데이터 삭제"| 140