%% 1020220164779 - 학습 데이터 생성 장치 구성도
%% 생성일: 2026-05-11

classDiagram
    class 학습데이터생성장치 {
        +String 데이터전송()
    }
    class 학습데이터수집장치 {
        +String 데이터수신()
    }
    class 이미지정보 {
        +String 메타정보
    }
    학습데이터생성장치 -->| "데이터 전송" | 학습데이터수집장치
    학습데이터수집장치 -->| "데이터 수신" | 학습데이터생성장치
    이미지정보 -->| "비교 대상" | 학습데이터생성장치