%% 1020170111374 - 디스플레이 장치 구성도
%% 생성일: 2026-05-11

classDiagram
    class 디스플레이 {
        +String 정보
    }
    class 터치입력부 {
        +detectTouch()
    }
    class 메모리 {
        +String 데이터
    }
    class 프로세서 {
        +controlDisplay()
    }
    디스플레이 --> 터치입력부 : "제어"
    디스플레이 --> 메모리 : "연결"
    터치입력부 --> 메모리 : "연결"
    디스플레이 --> 프로세서 : "제어"
    터치입력부 --> 프로세서 : "제어"
    메모리 --> 프로세서 : "사용"