%% 1020230033546 - 정보 처리 시스템 구성도
%% 생성일: 2026-05-11

classDiagram
    class 병리슬라이드이미지 {
        +String 이미지데이터
    }
    class 기계학습모델 {
        +String 모델정보
        +정보결정()
    }
    class 상호작용스코어 {
        +int 점수
    }
    class 정보처리시스템 {
        +예측치료반응성()
    }
    병리슬라이드이미지 --> 기계학습모델 : "입력"
    기계학습모델 --> 상호작용스코어 : "산출"
    기계학습모델 --> 정보처리시스템 : "실행"
    상호작용스코어 --> 정보처리시스템 : "결과"