%% 1020240119349 - 전체 시스템 구성도
%% 생성일: 2026-05-11

classDiagram
    class 원두주문관리서버 {
        +String 생두주문정보
        +String 로스팅요청정보
        +String 소분포장정보
    }
    class 로스팅기계 {
        +String 로스팅상태
    }
    class 개인카페창업자단말기 {
        +String 주문정보
    }
    class 관리자단말기 {
        +String 관리정보
    }
    class 외부서버 {
        +String 원두가격정보
    }
    원두주문관리서버 --> 로스팅기계 : "로스팅 기계와 연결"
    원두주문관리서버 --> 외부서버 : "외부 서버와 데이터 전송"
    원두주문관리서버 --> 개인카페창업자단말기 : "개인 카페 창업자 단말기와 소통"
    원두주문관리서버 --> 관리자단말기 : "관리자 단말기와 소통"
    로스팅기계 --> 관리자단말기 : "관리자 단말기와 소통"
    외부서버 --> 원두주문관리서버 : "원두주문관리서버와 데이터 전송"