%% 1020230075894 - 1인 공간 개발 및 대여 프로세스
%% 생성일: 2026-05-11

flowchart TD
    100["후보 지역 선정"]
    200["선정 지역 확인"]
    300["정보 획득"]
    400["메시지 전송"]
    500["리모델링 이미지 획득"]
    600["정보 업로드"]
    700["공간 대여 요청 수신"]
    800["공간 선정"]
    900["공간 대여"]
    
    100 -->| "이후 단계" | 200
    200 -->| "이후 단계" | 300
    300 -->| "이후 단계" | 400
    400 -->| "이후 단계" | 500
    500 -->| "이후 단계" | 600
    600 -->| "이후 단계" | 700
    700 -->| "이후 단계" | 800
    800 -->| "이후 단계" | 900