%% 1020250054620 - 협력사 빠른 정산 방법 흐름도
%% 생성일: 2026-05-11

flowchart TD
    100["프로세서"]
    200["메모리"]
    300["협력사 서버"]
    400["판매사 서버"]
    500["협력사의 월간 및 주간 매출액, 판매량, 반품률 수집"]
    600["협력사의 등급 계산"]
    700["빠른 정산 가능 금액 예비 계산"]
    800["판매사의 예상 잔고 비율 계산"]
    900["정산 가능 추가 금액 결정"]
    1000["최종 빠른 정산 가능 금액 결정"]
    1100["빠른 정산 신청 승인 또는 거절"]

    300 -->| "정산 요청을 전송" | 100
    100 -->| "저장된 명령을 실행" | 200
    200 -->| "협력사의 월간 및 주간 매출액, 판매량, 반품률 수집" | 500
    500 -->| "협력사의 등급 계산" | 600
    600 -->| "빠른 정산 가능 금액 예비 계산" | 700
    700 -->| "판매사의 예상 잔고 비율 계산" | 800
    800 -->| "정산 가능 추가 금액 결정" | 900
    900 -->| "최종 빠른 정산 가능 금액 결정" | 1000
    1000 -->| "정산 가능 금액 계산 요청" | 400
    400 -->| "빠른 정산 신청 승인 또는 거절" | 1100