%% 1020200075626 - 파일 관리 기능 흐름도
%% 생성일: 2026-05-11

flowchart TD
    100["탐색창 표시부"]
    200["관리 폴더 복사부"]
    300["파일 표시부"]
    400["파일 복사부"]
    500["파일 삭제부"]
    
    100 -->|"파일 관리 기능 실행 명령 수신"| 200
    100 -->|"파일 탐색창 표시"| 300
    300 -->|"파일 복사 명령 수신"| 400
    300 -->|"파일 삭제 명령 수신"| 500