%% 1020227008703 - 기계 학습 모델 기반 기록 생성 및 평가 흐름도
%% 생성일: 2026-05-11

flowchart TD
    100["컴퓨팅 장치"]
    200["훈련 데이터세트"]
    300["제1 기계 학습 모델"]
    400["제2 기계 학습 모델"]
    500["제3 기계 학습 모델"]
    200 -->|"저장 및 분석"| 100
    100 -->|"실행"| 300
    300 -->|"분석"| 200
    100 -->|"실행"| 400
    300 -->|"평가"| 400
    200 -->|"훈련"| 500