%% 1020227017608 - SR 프레임워크의 테스트 스테이지 작업 흐름
%% 생성일: 2026-05-11

flowchart TD
    100["비디오 데이터"]
    200["신경망"]
    300["이진 마스크"]
    400["컨볼루션 연산"]
    100 -->|"비디오 데이터 품질 수신"| 200
    200 -->|"가중치 계수 생성에 사용"| 300
    100 -->|"비디오 데이터 입력"| 400
    200 -->|"가중치 계수 사용"| 400
    300 -->|"마스킹된 가중치 계수 사용"| 400