%% 1020207011290 - 시스템 구성도
%% 생성일: 2026-05-11

classDiagram
    class 모바일디바이스 {
        +String 이미지데이터
        +데이터송신()
    }
    class 서버 {
        +String 수신데이터
        +데이터수신()
    }
    class 소프트웨어모듈 {
        +String 알고리즘
        +스푸핑검출()
    }
    모바일디바이스 --> 서버 : "데이터 송신"
    서버 --> 모바일디바이스 : "데이터 수신"
    서버 --> 소프트웨어모듈 : "데이터 분석"