%% 1020207011290 - 모바일 오브젝트 인증 프로세스 흐름도
%% 생성일: 2026-05-11

flowchart TD
    100["모바일 디바이스"]
    200["서버"]
    300["소프트웨어 모듈"]
    100 -->|"데이터 송신"| 200
    200 -->|"이미지 데이터 분석"| 300
    300 -->|"스푸핑 여부 결정"| 200