%% 1020230025818 - 상품 거래 프로세스 흐름도
%% 생성일: 2026-05-11

flowchart TD
    100["상품 거래 서버"]
    200["제1 사용자"]
    300["제2 사용자"]
    400["제1 중개 서버"]
    500["제2 중개 서버"]
    
    200 -->|"상품 거래 서버와 연결"| 100
    300 -->|"상품 거래 서버와 연결"| 100
    400 -->|"제2 사용자에게 자산을 매도"| 300
    400 -->|"상품 거래 서버와 연결"| 100
    500 -->|"제1 사용자에게 대금을 전달"| 200
    500 -->|"상품 거래 서버와 연결"| 100