%% 1020230025818 - 상품 거래 시스템 구성도
%% 생성일: 2026-05-11

classDiagram
    class 상품거래서버 {
        +String 거래정보
        +거래링크생성()
        +거래조건결정()
        +결제프로세스수행()
    }
    class 제1사용자 {
        +String 판매상품
        +상품판매()
    }
    class 제2사용자 {
        +String 구매상품
        +상품구매()
    }
    class 제1중개서버 {
        +String 중개자산
        +자산매도()
    }
    class 제2중개서버 {
        +String 대금정보
        +대금전달()
    }
    제1사용자 --> 상품거래서버 : "상품 거래 서버와 연결"
    제2사용자 --> 상품거래서버 : "상품 거래 서버와 연결"
    제1중개서버 --> 제2사용자 : "제2 사용자에게 자산을 매도"
    제1중개서버 --> 상품거래서버 : "상품 거래 서버와 연결"
    제2중개서버 --> 제1사용자 : "제1 사용자에게 대금을 전달"
    제2중개서버 --> 상품거래서버 : "상품 거래 서버와 연결"