%% 1020230029204 - 기업 투자 시스템 구성도
%% 생성일: 2026-05-11

classDiagram
    class 투자판단장치 {
        +String 산업선정()
        +String 기업판단()
    }
    class 기술판단장치 {
        +String 정량적데이터산출()
        +String 정성적기술분석()
    }
    class 기술분석기관 {
        +String 분석요청()
        +String 결과제공()
    }
    투자판단장치 --> 기술판단장치 : "요청"
    기술분석기관 --> 기술판단장치 : "분석 요청"
    기술판단장치 --> 기술분석기관 : "분석 결과 제공"
    기술판단장치 <-- 투자판단장치 : "결과 전달"