%% 1020217011467 - 정밀 프로그래밍 프로세스
%% 생성일: 2026-05-11

flowchart TD
    100["비휘발성 메모리 셀"]
    200["조대 프로그래밍 프로세스"]
    300["정밀 프로그래밍 프로세스"]
    400["검증 동작"]
    200 -->|"프로그램 대상"| 100
    300 -->|"프로그램 대상"| 100
    400 -->|"검증 대상"| 100