%% 1020167011605 - 금융 기관 시스템의 작동 흐름도
%% 생성일: 2026-05-11

flowchart TD
    100["프로세서 컴포넌트"]
    200["메모리 컴포넌트"]
    300["통신 컴포넌트"]
    400["전자 디바이스"]
    500["판매자 서브시스템"]
    
    100 -->|"연관된 사용자 정보 처리"| 200
    100 -->|"가상 크리덴셜 식별"| 300
    300 -->|"거래 요청 수신"| 500
    400 -->|"거래 요청 전송"| 300
    300 -->|"가상 크리덴셜 프로비저닝"| 400