%% 1020207025178 - 증강 현실 제공 장치 구성도
%% 생성일: 2026-05-11

classDiagram
    class 영상처리장치 {
        +String 영상데이터
        +영상분석()
    }
    class 렌더링모듈 {
        +렌더링()
    }
    class 상황인지모듈 {
        +상황정보분석()
    }
    class 편집모듈 {
        +추가컨텐츠생성()
    }
    영상처리장치 --> 렌더링모듈 : "구성 요소"
    영상처리장치 --> 상황인지모듈 : "구성 요소"
    영상처리장치 --> 편집모듈 : "구성 요소"