%% 1020210068892 - 암 진단 및 암 종 예측 방법 흐름도
%% 생성일: 2026-05-11

flowchart TD
    100["해독부"]
    200["정렬부"]
    300["이미지 생성부"]
    400["암 진단부"]
    500["암 종 예측부"]
    100 -->|"서열정보를 입력받음"| 200
    200 -->|"정렬된 서열정보를 입력받음"| 300
    300 -->|"생성된 이미지를 입력받음"| 400
    400 -->|"출력 결과값을 입력받음"| 500