%% 1020170155897 - 전자 장치 구성도
%% 생성일: 2026-05-11

classDiagram
    class 입력부 {
        +String 자연어입력
    }
    class 통신부 {
        +전송()
    }
    class 프로세서 {
        +String 입력문장
        +모델선택()
    }
    class 메모리 {
        +String 대화히스토리
    }
    입력부 --> 프로세서 : "입력 수신"
    프로세서 --> 통신부 : "정보 전송"
    통신부 --> 프로세서 : "제어"