%% 1020197009324 - 바이오메트릭 매치 스코어 계산 방법
%% 생성일: 2026-05-11

flowchart TD
    100["사용자의 얼굴 이미지"]
    200["안구 이미지 영역"]
    300["안구 주위 이미지 영역"]
    400["바이오메트릭 매치 스코어"]
    500["프로세싱 유닛"]
    100 -->|"이미지 수신"| 500
    500 -->|"안구 이미지 영역 정의"| 200
    500 -->|"안구 주위 이미지 영역 정의"| 300
    200 -->|"포함"| 300
    500 -->|"매치 스코어 계산"| 400