%% 1020240001496 - 경로 생성 서비스 제공 방법 흐름도
%% 생성일: 2026-05-11

flowchart TD
    100["플랫폼 서버"]
    200["소셜 네트워크"]
    300["리뷰 NFT"]
    400["판매자"]
    500["제3 소비자"]
    200 -->| "거래 요청 수신" | 100
    100 -->| "리뷰 NFT 로딩" | 300
    300 -->| "경로 생성" | 400
    100 -->| "정보 제공" | 500