%% 1020220074727 - 시스템 구성도
%% 생성일: 2026-05-11

classDiagram
    class 중앙서버 {
        +String 차량정보
        +String 주문정보
        +데이터제공()
        +주문정보제공()
    }
    class 매장POS시스템 {
        +String 상품정보
        +String 주문처리
        +데이터수신()
        +주문정보수신()
    }
    class 데이터베이스 {
        +String 운전자정보
        +String 주문이력
        +데이터저장()
    }
    중앙서버 --> 매장POS시스템 : "데이터 제공"
    매장POS시스템 --> 중앙서버 : "데이터 수신"
    중앙서버 --> 데이터베이스 : "주문 정보 제공"
    데이터베이스 --> 중앙서버 : "데이터 저장"