%% 1020220055365 - 시스템 구성 요소 다이어그램
%% 생성일: 2026-05-11

classDiagram
    class 이커머스플랫폼관리서버 {
        +String 관리기능
        +데이터수집및관리()
        +클라이언트와상호작용()
    }
    class 제2데이터베이스부 {
        +String 가맹점정보
        +String 서비스상품정보
    }
    class 클라이언트 {
        +String 사용자정보
        +서비스상품구매()
    }
    class 가맹점서버 {
        +String 가맹점정보
        +가맹점등록요청()
    }
    이커머스플랫폼관리서버 --> 제2데이터베이스부 : "이커머스 플랫폼 관리서버에 의해 접근됨"
    이커머스플랫폼관리서버 --> 클라이언트 : "클라이언트와 상호작용"
    가맹점서버 --> 이커머스플랫폼관리서버 : "가맹점 등록 요청을 전송"