%% 1020220055365 - 이커머스 플랫폼 운영 흐름도
%% 생성일: 2026-05-11

flowchart TD
    100["이커머스 플랫폼 관리서버"]
    200["제2 데이터베이스부"]
    300["클라이언트"]
    400["가맹점 서버"]
    300 -->|"회원 가입 요청"| 100
    400 -->|"가맹점 등록 요청"| 100
    100 -->|"데이터를 수집 및 관리"| 200
    100 -->|"클라이언트와 상호작용"| 300