%% 1020220171274 - 세굴 위험도 평가 방법의 순서도
%% 생성일: 2026-05-11

flowchart TD
    100["해상풍력터빈 구조물"]
    200["지반"]
    300["환경하중 정의"]
    400["세굴 취약도 산출"]
    500["KC 계산"]
    600["세굴 위험도 평가"]

    200 -->| "설치됨" | 100
    100 -->| "영향을 미침" | 300
    300 -->| "구조해석 수행" | 400
    400 -->| "관계 있음" | 500
    500 -->| "결합하여 평가됨" | 600