%% 1020147031233 - 트랜잭션 처리 방법 흐름도
%% 생성일: 2026-05-11

flowchart TD
    100["프로세서"]
    200["비-일시적인 컴퓨터 판독 가능 저장 매체"]
    300["기계어 명령"]
    400["트랜잭션 실행 모드 종료 여부 판별"]
    
    200 -->| "명령을 실행하기 위해 사용" | 100
    300 -->| "프로세서에 의해 실행됨" | 100
    300 -->| "저장된 명령" | 200
    100 -->| "명령을 실행하여 제1 오퍼랜드를 제2 오퍼랜드에 비트랜잭션적으로 배치" | 400