%% 1020240082552 - 요양시설 중개시스템 구성도
%% 생성일: 2026-05-11

classDiagram
    class 요양시설중개서버 {
        +중개()
        +데이터처리()
    }
    class 보호자단말 {
        +정보요청()
        +예약진행()
    }
    class 요양시설단말 {
        +정보입력()
        +파트너등록()
    }
    요양시설중개서버 <--> 보호자단말 : "중개"
    요양시설중개서버 <--> 요양시설단말 : "데이터 처리"
    보호자단말 --> 요양시설중개서버 : "요청"
    요양시설단말 --> 요양시설중개서버 : "등록"
    요양시설단말 --> 보호자단말 : "정보 제공"
    보호자단말 <-- 요양시설단말 : "정보 제공"