%% 1020207034340 - 3D 객체 구별 방법 흐름도
%% 생성일: 2026-05-11

flowchart TD
    100["광학 센서"]
    200["뉴럴 네트워크"]
    300["모바일 디바이스"]
    400["스푸프 또는 실제 객체 결정"]
    300 -->| "광학 센서 포함" | 100
    100 -->| "이미지 입력" | 200
    200 -->| "방법 실행" | 300
    200 -->| "결과" | 400