%% 1020250086116 - 패키지 분류 및 이송 시스템 구성도
%% 생성일: 2026-05-11

classDiagram
    class 데이터저장유닛 {
        +String 상품정보
        +String 차량정보
    }
    class 정보획득모듈 {
        +getData()
    }
    class 물류흐름제어모듈 {
        +controlLoading()
    }
    class 배송계획모듈 {
        +planDelivery()
    }
    class 운영최적화모듈 {
        +optimize()
    }
    데이터저장유닛 <|-- 정보획득모듈 : "정보를 저장 유닛으로부터 획득"
    정보획득모듈 <|-- 물류흐름제어모듈 : "상품 정보를 기반으로 제어"
    정보획득모듈 <|-- 배송계획모듈 : "배송 그룹 정보를 기반으로 계획"
    물류흐름제어모듈 <|-- 배송계획모듈 : "물류 흐름 제어 모듈과 상호작용"
    배송계획모듈 <|-- 운영최적화모듈 : "배송 계획 모듈을 제어"