%% 1020240094169 - 전자 장치 구성도
%% 생성일: 2026-05-11

classDiagram
    class 인공지능모델 {
        +학습()
    }
    class 특징데이터 {
        +String 제조사
        +String 양식품종
        +String 용량
    }
    class 이미지데이터 {
        +String 이미지파일
    }
    class 양식장이미지 {
        +String 양식장사진
    }
    class 인증부표식별정보 {
        +String 식별정보
    }
    특징데이터 --> 인공지능모델 : "학습 데이터로 사용"
    이미지데이터 --> 인공지능모델 : "학습 데이터로 사용"
    양식장이미지 --> 인공지능모델 : "입력 데이터"