%% my_drawing - 스펙트럼 기반 코드이미지 위조 검출 시스템 개요
%% 생성일: 2026-05-11

flowchart TD
    100["데이터 저장부"]
    200["데이터 수신부"]
    300["위조 검출부"]
    400["데이터 분석부"]
    200 -->|"기준데이터와 비교"| 100
    300 -->|"기준데이터 활용"| 100
    300 -->|"촬영데이터 활용"| 200
    400 -->|"위조 검출 결과 활용"| 300