%% 1020180123300 - 의료영상 공간 정규화 장치 구성도
%% 생성일: 2026-05-11

classDiagram
    class 적응형템플릿생성부 {
        +String 기능적의료영상
        +generateTemplate()
    }
    class 학습부 {
        +String 생성된템플릿
        +generateImage()
        +determineAuthenticity()
    }
    class 공간정규화부 {
        +String 학습결과
        +provideNormalizedImage()
    }
    적응형템플릿생성부 --> 학습부 : "적응형 템플릿 생성부에서 생성된 템플릿을 사용하여"
    학습부 --> 공간정규화부 : "학습부의 결과를 기반으로"