%% 1020210085431 - 전자 장치 구성도
%% 생성일: 2026-05-11

classDiagram
    class 전자장치 {
        +제어()
        +상호작용()
    }
    class 제1뉴럴네트워크 {
        +파라미터식별()
    }
    class 제2뉴럴네트워크 {
        +파라미터식별()
    }
    class 메모리 {
        +저장()
    }
    class 프로세서 {
        +작동()
    }
    전자장치 --> 제1뉴럴네트워크 : "제어"
    전자장치 --> 제2뉴럴네트워크 : "상호작용"
    전자장치 --> 메모리 : "저장"
    프로세서 --> 메모리 : "작동"