%% 1020170083779 - 악성코드 검출 방법 흐름도
%% 생성일: 2026-05-11

flowchart TD
    100["악성코드 바이너리 데이터 입력부"]
    200["메타데이터 추출부"]
    300["데이터 변환부"]
    400["신경망부"]
    100 -->|"악성코드 바이너리 데이터 입력"| 200
    200 -->|"메타데이터를 변환"| 300
    300 -->|"영상 데이터를 신경망에 입력"| 400