%% 1020230175224 - 상품 교환권 선물하기 서비스 흐름도
%% 생성일: 2026-05-11

flowchart TD
    100["판매자 단말"]
    200["서버"]
    300["구매자 단말"]
    400["블록체인"]
    100 -->| "식별코드 생성 요청 수신" | 200
    200 -->| "식별코드 생성 및 제공" | 100
    200 -->| "상품 교환권 등록 요청 수신 및 처리" | 400
    300 -->| "구매자 단말로부터 식별코드 입력 수신" | 200
    200 -->| "구매자 신원 검증 및 상품 교환권 제공" | 300
    300 -->| "사용자 단말로부터 선물하기 입력 수신" | 200
    200 -->| "가상자산 예치 및 상품 교환권 제공" | 300
    200 <--> | "상호작용" | 400