%% 1020160053785 - 기부금 접수 및 처리 흐름도
%% 생성일: 2026-05-11

flowchart TD
    100["기부금 접수부"]
    200["터치스크린"]
    300["컨트롤러"]
    400["데이터베이스"]
    500["카메라"]
    600["기프트 박스"]
    
    200 -->|"기부금 접수부와 연결"| 100
    200 -->|"컨트롤러와 연결"| 300
    300 -->|"데이터베이스와 연결"| 400
    300 -->|"기부자 촬상"| 500
    300 -->|"기부예우 상품 제공"| 600