%% 1020120121549 - TTA 적용 태스크 추출 과정
%% 생성일: 2026-05-11

flowchart TD
    100["대상 시스템"]
    200["TTA 적용 태스크"]
    300["이벤트 및 태스크 특성"]
    400["태스크 수행 주기"]
    500["시스템 테스팅"]
    
    100 -->|"적용 대상"| 200
    200 -->|"필요 데이터"| 300
    200 -->|"필요 데이터"| 400
    200 -->|"결과 검증"| 500