%% 1020237024663 - 시스템 구성도
%% 생성일: 2026-05-11

classDiagram
    class 디스플레이생성컴포넌트 {
        +String 사용자인터페이스
        +String 기계판독가능코드
    }
    class 입력디바이스 {
        +String 인증데이터
        +receiveData()
    }
    class 프로세서 {
        +evaluateCriteria()
        +controlDisplay()
    }
    입력디바이스 --> 디스플레이생성컴포넌트 : "통신"
    프로세서 --> 디스플레이생성컴포넌트 : "제어"
    프로세서 --> 입력디바이스 : "데이터 처리"