%% 1020187037824 - 신경망 구성 요소 다이어그램
%% 생성일: 2026-05-11

classDiagram
    class 신경망 {
        +String 반전피처
        +훈련()
    }
    class 순방향물리적모델 {
        +String 출력이미지
        +생성()
    }
    class 잔여계층 {
        +String 차이
        +결정()
    }
    class 컴퓨터서브시스템 {
        +String 시스템정보
        +운영()
    }
    컴퓨터서브시스템 --> 신경망 : "훈련"
    신경망 --> 순방향물리적모델 : "입력"
    순방향물리적모델 --> 잔여계층 : "입력"
    컴퓨터서브시스템 --> 순방향물리적모델 : "운영"
    컴퓨터서브시스템 --> 잔여계층 : "운영"