%% 1020187037824 - 신경망 훈련 시스템 흐름도
%% 생성일: 2026-05-11

flowchart TD
    100["신경망"]
    200["순방향 물리적 모델"]
    300["잔여 계층"]
    400["컴퓨터 서브 시스템"]
    400 -->|"훈련"| 100
    100 -->|"입력 이미지의 훈련 세트 입력"| 200
    200 -->|"출력 이미지 세트 생성"| 300
    300 -->|"입력 이미지와 출력 이미지 간의 차이 결정"| 100