%% 1020250074382 - 유통플랫폼 시스템 흐름도
%% 생성일: 2026-05-11

flowchart TD
    100["사용자 계정모듈"]
    200["검색정보 처리모듈"]
    300["제품그룹정보 처리모듈"]
    400["구매확률 연산모듈"]
    500["수요정보 연산모듈"]
    
    100 -->|"검색정보 입력"| 200
    200 -->|"제공"| 300
    300 -->|"사용"| 400
    400 -->|"연산"| 500