%% 1020167013936 - 페이지 테이블 구조
%% 생성일: 2026-05-11

classDiagram
    class 페이지테이블 {
        +String 가상주소
        +String 물리주소
    }
    class 프로세서 {
        +accessTable()
        +updateTable()
    }
    class 액세스플래그 {
        +boolean 안전상태
    }
    class 더티비트 {
        +boolean 클린상태
    }
    프로세서 --> 페이지테이블 : "액세스 및 수정"
    액세스플래그 --> 페이지테이블 : "페이지 테이블과 연관"
    더티비트 --> 페이지테이블 : "페이지 테이블과 연관"
    프로세서 <-- 액세스플래그 : "수정됨"
    프로세서 <-- 더티비트 : "수정됨"