%% 1020167013936 - 페이지 테이블 관리 방법 흐름도
%% 생성일: 2026-05-11

flowchart TD
    100["페이지 테이블"]
    200["프로세서"]
    300["액세스 플래그"]
    400["더티 비트"]
    200 -->|"액세스 및 수정"| 100
    100 -->|"페이지 테이블과 연관"| 300
    100 -->|"페이지 테이블과 연관"| 400
    300 -->|"수정됨"| 200
    400 -->|"수정됨"| 200