%% 1020197036280 - 물품 식별 시스템 구성도
%% 생성일: 2026-05-11

classDiagram
    class 이미지획득장치 {
        +String 다중프레임이미지
        +획득()
    }
    class 정보획득장치 {
        +String 보조정보
        +획득()
    }
    class 서버 {
        +String 식별결과
        +처리()
    }
    이미지획득장치 --> 서버 : "데이터 처리"
    정보획득장치 --> 서버 : "데이터 처리"