%% 1020160177931 - 휴먼 추종 로봇의 작동 흐름도
%% 생성일: 2026-05-11

flowchart TD
    100["위치 추정 모듈"]
    200["탐색 범위 설정 모듈"]
    300["추적 모듈"]
    400["영상 수신 모듈"]
    400 -->| "추적 모듈에 영상 제공" | 300
    100 <--| "위치 정보를 제공받음" | 200
    200 <--| "탐색 범위를 사용함" | 300