%% 1020210046441 - 이미지 기반 객체 정보 획득 방법 흐름도
%% 생성일: 2026-05-11

flowchart TD
    100["카메라"]
    200["인공신경망"]
    300["제어부"]
    100 -->|"타겟 이미지 획득"| 200
    200 -->|"객체 정보 산출"| 300
    300 <--|"객체 정보 입력"| 200