%% 1020210046441 - 객체 정보 획득 장치 구성도
%% 생성일: 2026-05-11

classDiagram
    class 카메라 {
        +String 타겟이미지
        +획득()
    }
    class 인공신경망 {
        +String 객체정보
        +산출()
    }
    class 제어부 {
        +String 출력정보
        +출력()
    }
    카메라 --> 인공신경망 : "타겟 이미지 획득"
    인공신경망 --> 제어부 : "객체 정보 산출"
    제어부 <-- 인공신경망 : "객체 정보 입력"