%% 1020230141643 - 구성 요소 클래스 다이어그램
%% 생성일: 2026-05-11

classDiagram
    class 상점단말기 {
        +String 상품관리
        +String 주문관리
        +String 판매관리
    }
    class 소비자단말기 {
        +String 상품검색
        +String 주문
        +String 배송요청
    }
    class 통합관리서버 {
        +String 데이터관리
    }
    class DB {
        +String 상점영업정보
        +String 상품정보
    }
    class 상품거래모듈 {
        +String 주문처리
        +String 배송요청처리
    }
    class 3D정보제공모듈 {
        +String 정보제공
    }

    소비자단말기 -->|주문 및 배송 요청| 상점단말기
    통합관리서버 <--|정보 수신 및 저장| 상점단말기
    통합관리서버 <--|정보 전송 및 관리| 소비자단말기
    DB <--|데이터 저장| 통합관리서버
    상품거래모듈 <--|요청 수신| 소비자단말기
    상품거래모듈 -->|정보 전송| 상점단말기
    3D정보제공모듈 -->|정보 제공| 소비자단말기