%% 1020230141643 - 스마트 전통시장 플랫폼 구조도
%% 생성일: 2026-05-11

flowchart TD
    100["상점 단말기"]
    200["소비자 단말기"]
    300["통합관리서버"]
    400["DB"]
    500["상품 거래 모듈"]
    600["3D 정보 제공 모듈"]

    200 -->|"주문 및 배송 요청"| 100
    100 <--|"정보 수신 및 저장"| 300
    200 <--|"정보 전송 및 관리"| 300
    300 <--|"데이터 저장"| 400
    200 <--|"요청 수신"| 500
    500 -->|"정보 전송"| 100
    200 -->|"정보 제공"| 600