%% 1020220033925 - MADDPG 알고리즘 기반 드론 에이전트 학습 과정
%% 생성일: 2026-05-11

flowchart TD
    100["입력부"]
    200["학습부"]
    300["계획 생성부"]
    400["출력부"]
    100 -->|"입력받음"| 200
    200 -->|"학습된 정보를 이용함"| 300
    300 -->|"운용 계획 생성"| 400