%% 1020220048990 - 가상화폐 및 결제 시스템 흐름도
%% 생성일: 2026-05-11

flowchart TD
    100["사용자 단말"]
    200["쇼핑몰 서비스 제공 서버"]
    300["가상화폐 거래소"]
    400["중소기업지원부"]
    100 -->|"상품 구매 및 결제 요청"| 200
    100 -->|"가상화폐 구매 요청"| 300
    200 <--|"결제 정보 수신"| 100
    200 -->|"상품 업로드 및 관리"| 400
    400 <--|"상품 업로드"| 200
    300 <--|"가상화폐 구매 요청 처리"| 100