%% 1020227010826 - 메모리 프로세싱 시스템 구성도
%% 생성일: 2026-05-11

classDiagram
    class 메모리어레이 {
        +String 메모리셀
    }
    class 드라이버 {
        +구동()
    }
    class 감지증폭기 {
        +수신신호()
    }
    class 회로부 {
        +신호생성()
        +신호처리()
    }
    드라이버 --> 메모리어레이 : "구동"
    감지증폭기 --> 메모리어레이 : "커플링"
    회로부 --> 드라이버 : "구성"
    회로부 --> 감지증폭기 : "구성"