%% 1020190107252 - 기부 물품거래 시스템 흐름도
%% 생성일: 2026-05-11

flowchart TD
    100["기부자 단말기"]
    200["운영서버"]
    300["후원자/후원단체 단말기"]
    400["토큰 관리부"]
    100 -->|"기부 요청정보 전송"| 200
    200 -->|"후원단체 리스트 제공"| 100
    200 -->|"토큰 기부정보 수신"| 300
    300 -->|"환전 요청정보 전송"| 400
    400 -->|"토큰 갱신 내역 전송"| 200