%% 1020190107252 - 기부 물품거래 시스템 구성도
%% 생성일: 2026-05-11

classDiagram
    class 기부자단말기 {
        +String 요청정보
        +String 토큰정보
        +기부요청전송()
        +토큰기부전송()
    }
    class 운영서버 {
        +String 후원단체리스트
        +기부요청수신()
        +토큰기부수신()
        +후원단체리스트제공()
    }
    class 후원자후원단체단말기 {
        +String 기부토큰
        +기부완료정보수신()
        +환전요청전송()
    }
    class 토큰관리부 {
        +String 토큰갱신내역
        +토큰발행()
        +토큰충전()
        +토큰갱신()
    }
    기부자단말기 --> 운영서버 : "기부 요청정보 전송"
    운영서버 --> 기부자단말기 : "기부 요청정보 수신"
    운영서버 --> 후원자후원단체단말기 : "후원단체 리스트 제공"
    후원자후원단체단말기 --> 운영서버 : "기부 완료 정보 수신"
    후원자후원단체단말기 --> 토큰관리부 : "환전 요청정보 전송"
    운영서버 --> 토큰관리부 : "토큰 갱신 내역 전송"