%% 1020240044918 - 시스템 구성도
%% 생성일: 2026-05-11

classDiagram
    class 사용자단말 {
        +String 위치정보
        +인식()
    }
    class 서버 {
        +String 방문확인
        +코인제공()
        +장소추천()
    }
    class 점포단말 {
        +String 보유코인
        +코인사용승인()
    }
    class 방문확인부 {
        +String 위치정보
        +방문여부판단()
    }
    class 장소추천부 {
        +String 추천점포
        +추천기능()
    }
    사용자단말 --> 서버 : "위치정보 및 간판 인식"
    서버 --> 점포단말 : "코인 사용 승인"
    서버 --> 방문확인부 : "방문 확인 및 가치 계산"
    서버 --> 장소추천부 : "장소 추천"
    점포단말 <-- 서버 : "코인 차감 및 할인"