%% 1020250109740 - 라벨링모듈 과정
%% 생성일: 2026-05-11

flowchart TD
    100["인공지능서버"]
    200["웹서버"]
    110["이미지전처리모듈"]
    120["라벨링모듈"]
    130["모델생성모듈"]
    300["데이터베이스"]
    
    200 -->| "데이터 요청" | 100
    100 -->| "데이터 전달" | 110
    110 -->| "전처리된 이미지 전달" | 120
    120 -->| "라벨링된 데이터 전달" | 130
    100 <--| "데이터 저장" | 300