%% 1020240128601 - 전자 장치 구성도
%% 생성일: 2026-05-11

classDiagram
    class 사용자 {
        +String 타겟키워드
        +inputKeyword()
    }
    class 검색엔진 {
        +String 시간범위
        +receiveTimeRange()
    }
    class 키워드변동정보 {
        +String 순위변동정보
    }
    class 그래프 {
        +visualize()
    }
    사용자 --> 검색엔진 : "입력 받음"
    사용자 --> 키워드변동정보 : "연관됨"
    검색엔진 --> 키워드변동정보 : "연관됨"
    키워드변동정보 --> 그래프 : "데이터 제공"