flowchart TD
    A[사용자의 단말로부터 적어도 하나의 상품에 대한 구매 요청을 수신하는 단계] --> B[상기 구매 요청에 응답하여, 상기 사용자의 결제수단 관련 정보를 획득하는 단계]
    B --> C[결제 이력 데이터를 이용하여 딥러닝 모델을 학습시키는 단계]
    C --> D[상기 인코더를 통해 상기 학습용 사용자 정보와 상기 학습용 상품 정보를 인코딩하는 단계]
    D --> E[상기 인코딩의 결과를 상기 제1 예측기에 입력하여 결제수단의 유형을 예측하는 제1 태스크를 수행하는 단계]
    E --> F[상기 인코딩의 결과를 상기 제2 예측기에 입력하여 결제수단을 예측하는 제2 태스크를 수행하는 단계]
    F --> G[상기 학습용 결제수단 정보를 레이블 정보로 이용하여, 상기 제1 태스크의 수행 결과로부터 상기 딥러닝 모델을 학습시키는 단계]
    G --> H[상기 학습용 결제수단 정보를 레이블 정보로 이용하여, 상기 제2 태스크의 수행 결과로부터 상기 딥러닝 모델을 더 학습시키는 단계]