flowchart TD
    A[결제 정보를 안전하게 저장] --> B[결제 동작 검출]
    B --> C[결제 거래 승인 기계적 입력 미수신 결정]
    C --> D[미수신 자극 제시]
    D --> E[기계적 승인 입력 검출]
    E --> F[결제 정보 인에이블]
    F --> G[결제 정보 배포]
    G --> H[다른 결제 동작 검출]
    H --> I[다른 인스턴스 미수신 결정]
    I --> J[다른 기계적 입력 검출]
    J --> K[결제 정보 인에이블]
    K --> L[결제 정보 배포]