flowchart TD
    A[구매 정보를 수신하는 단계] --> B[결제 완료 정보를 수신하는 단계]
    B --> C[이용권 정보를 생성하는 단계]
    C --> D[현장 주문 정보를 수신하는 단계]
    C --> E[원격 주문 정보를 수신하는 단계]
    E --> F[원격 주문 정보를 송신하는 단계]
    D --> G[이용권 정보를 갱신하는 단계]
    H[제1 QR코드를 스캔하는 단계] --> I[구매 정보를 읽어오는 단계]
    I --> J[금액을 결제 처리하는 단계]
    J --> K[결제 완료 정보를 송신하는 단계]
    E --> L[주문 가능 메뉴 정보를 수신하는 단계]
    L --> M[주문 가능 메뉴 정보를 송신하는 단계]
    M --> N[주문 수량 정보를 입력받는 단계]
    N --> O[원격 주문 정보를 생성하는 단계]
    D --> P[입장 요청 정보를 수신하는 단계]
    P --> Q[제2 QR코드를 생성하는 단계]
    H --> R[제2 QR코드를 스캔하는 단계]
    R --> S[입장 요청 정보 및 이용권 정보를 읽어오는 단계]
    S --> T[입장 승인 정보 및 이용권 차감 정보를 생성하는 단계]
    T --> U[현장 주문 정보를 생성하는 단계]
    O --> V[GPS 정보를 실시간으로 수신하는 단계]
    V --> W[제1 거리를 산출하는 단계]
    W --> X{제1 거리가 임계값 이상인 경우}
    X --> Y[주문 대기 정보를 생성하는 단계]
    Y --> Z[조리 요청 정보 또는 주문 취소 정보를 생성하는 단계]
    X --> AA{제1 거리가 임계값 미만인 경우}
    AA --> AB[조리 요청 정보를 생성하는 단계]
    AB --> AC[이용권 차감 정보를 생성하는 단계]
    AC --> AD[조리 요청 정보 및 이용권 차감 정보를 원격 주문 정보로 지정하는 단계]
    Z --> AE[예상 조리 시간을 산출하는 단계]
    AE --> AF[이동 속도를 산출하는 단계]
    AF --> AG[제1 예상 도착 시간을 산출하는 단계]
    AG --> AH{제1