flowchart TD
    A[작가의 단말로부터 작가의 정보 획득] --> B[작가의 단말로부터 작품의 정보 획득]
    B --> C[작가의 단말로부터 전시 일정 정보 획득]
    C --> D[갤러리 데이터베이스로부터 후보 갤러리 추출 및 정보 획득]
    D --> E[작품을 전시할 갤러리 선정]
    E --> F[작품의 콘텐츠 생성]
    F --> G[작품의 콘텐츠 온라인 플랫폼에 업로드]
    G --> H[소비자의 단말로부터 작품 이미지 선택]
    H --> I[작품의 콘텐츠 및 갤러리 정보 제공]
    I --> J[소비자의 작품 구매 요청 수신]
    J --> K[작품 결제 수행]
    E --> L[후보 갤러리의 공간 정보 획득]
    L --> M[후보 갤러리의 히스토리 정보 획득]
    M --> N[제1 입력 신호 생성]
    N --> O[제1 인공신경망에 제1 입력 신호 적용]
    O --> P[후보 갤러리 중 작품을 전시할 갤러리 선정]
    P --> Q[갤러리에 작품 배치]
    Q --> R[작가의 데뷔 일자 확인]
    R --> S[작가의 작품 배치 위치 결정]
    S --> T[업로드된 작품 추천]
    T --> U[소비자의 SNS 게시글 수신]
    U --> V[색상 관련 키워드 추출 및 제1 비율 확인]
    V --> W[작품의 색상 비율 확인]
    W --> X[제1 비율과 제2 비율에 기반하여 작품 추천]