flowchart TD
    A[입력 이미지로부터 유의미한 피쳐들을 추출하는 인코더] --> B[상기 추출된 피쳐들을 소스 도메인에서 타겟 도메인으로 변경하는 번역기]
    B --> C[상기 번역된 피쳐들을 활용하여 동일한 해상도의 번역 이미지를 구성하는 디코더]
    C --> D[일련의 전치된 콘볼루션을 활용하여 피쳐들을 원하는 차원으로 업스케일]
    D --> E[출력물을 복수 채널의 RGB 이미지에 매핑]
    E --> F[생성기의 결과물을 판별하는 판별기]