flowchart TD
    A[화주의 단말로부터 물류 배송 요청 수신] --> B[배송 기사 및 출고 창고 배정]
    B --> C[업무 지시를 배송 기사의 단말로 전송]
    C --> D[업무 지시에 대한 승인 수신]
    D --> E[배송 기사의 실시간 위치 정보 수신]
    E --> F[출고 창고의 제품 재고 정보 차감]
    F --> G[배송 및 설치 완료 정보 수신]
    G --> H[배송 및 설치 완료 정보 송신]
    H --> I[비용 정산 정보 수신]
    I --> J[배송 비용 정보 송신]
    D --> K[제품 적재 정보 생성]
    K --> L[제품의 적재 구역 결정]
    K --> M[적재 구역 내 제품의 적재 배열 결정]
    E --> N[제1 진동 알림 제공]
    E --> O[제2 진동 알림 제공]
    N --> P[배송 기사의 현재 위치 확인]
    P --> Q[현재 위치와 배송할 지역 간 거리 산출]
    Q --> R[거리가 기준 미만인 경우 제1 진동 패턴 생성]
    R --> S[제1 진동 패턴 포함한 진동 알림 제공]
    S --> T[제1 진동 패턴 생성]
    O --> U[제품의 포장 박스에 대한 NFC 태깅 신호 수신]
    U --> V[NFC 태깅 신호 및 실시간 위치 정보 기반 업무 지시 추출]
    V --> W[추출된 업무 지시로부터 제품의 강도 확인]
    W --> X[제품의 강도에 반비례하여 제2 진동 알림의 지속 시간 결정]