flowchart TD
    A[구매자 단말에서 제1 결제 요청 정보 전송] --> B[결제 서버의 결제 승인]
    B --> C[결제 중개 서버가 이용권 정보 블록체인에 기록]
    C --> D[결제 중개 서버가 제1 금액 송금 및 보관]
    D --> E[구매자의 상품 이용에 따라 제2 금액 송금]
    D --> F[이자 수익 블록체인에 기록]
    F --> G[제1 결제 한도 결정]
    E --> H[제2 결제 한도 결정]
    F --> I[제1 이자 수익 분배 비율 결정]
    F --> J[제2 이자 수익 분배 비율 결정]
    I --> K[이자 수익 구매자 단말과 공유]
    J --> L[이자 수익 판매자 단말과 공유]
    A --> M[제2 결제 요청 정보 수신]
    M --> N[제2 금액 송금]