flowchart TD
    A[상품 코드 스캔] --> B[상품 정보 전송]
    B --> C[결제 완료 및 매장내 수령 메뉴 선택]
    C --> D[결제 정보 전송]
    D --> E[반출준비 완료]
    E --> F[픽업준비 완료코드 전송]
    F --> G[픽업준비 완료코드 스캔]
    G --> H[상품 반출 완료]
    H --> I[상품수령 완료정보 전송]
    I --> J[취소 요청]
    J --> K[취소 요청코드 전송]
    K --> L[취소 요청코드 스캔]
    L --> M[상품취소 완료정보 전송]
    A1[매장내 상품 픽업장소 정보 전송] --> A2[픽업장소 정보 수신]
    A2 --> A3[매장 단말기로 픽업장소 정보 전송]
    A3 --> A4[반출준비 완료정보 수신]
    A4 --> A5[픽업준비 완료코드 전송]
    A5 --> A6[픽업준비 완료코드 스캔]
    A6 --> A7[상품 반출 완료]
    A7 --> A8[상품수령 완료정보 전송]
    B1[택배 수령 메뉴 선택] --> B2[택배 수령지 정보 수신]
    B2 --> B3[택배사 서버로 수령지 정보 전송]
    B3 --> B4[상품 택배사로 전송 메시지 전송]
    C1[재고품 없음] --> C2[택배 수령 메뉴 전송]
    C2 --> C3[택배 수령지 정보 수신]
    C3 --> C4[택배사 서버로 수령지 정보 전송]
    C4 --> C5[상품 택배사로 전송 메시지 전송]