flowchart TD
    A[중고, 렌탈, 신제품 지게차 시세 확인] --> B[온라인 매입 및 중개 시스템]
    B --> C[물류 장비 종합 쇼핑몰 서버]
    C --> D[검색 기능 제공]
    C --> E[가격 비교 및 구매 기능 제공]
    B --> F[명판 스캔하는 OCR 모듈]
    F --> G[스캔 정보 저장하는 데이터 제공 모듈]
    G --> H[재고등록 및 매물등록 DB]
    H --> I[명판 정보 표준화하는 표준화 모듈]
    C --> J[정보 검색 모듈]
    C --> K[견적 및 상품 추천 모듈]
    B --> L[서류 교환 결제 자동화 모듈]
    B --> M[경매 모듈]
    B --> N[스펙/가격 정보 모듈]
    F --> O[텍스트 추출부]
    O --> P[형태소 분석 및 데이터 생성]
    F --> Q[명판 파일 업로드 및 텍스트 추출]
    Q --> R[정보 검색 모듈을 통한 검색 기능 제공]
    S[온라인 플랫폼을 통한 경매 형태로 매물 확인] --> T[판매 장비의 적정 시세 제공]
    S --> U[서류 교환/결제 자동화]
    S --> V[경매 형식 매물 확인]