flowchart TD
    A[이미지 전처리모듈] --> B[이미지클리닝부]
    B --> C[정규화처리부]
    C --> D[해상도표준화부]
    A --> E[라벨링모듈]
    E --> F[이미지증강부]
    E --> G[수동라벨링부]
    E --> H[자동라벨링부]
    I[모델생성모듈] --> J[딥러닝 신경망]
    K[웹서버] --> L[사용자단말기]
    M[데이터베이스] --> N[인공지능서버]