flowchart TD
    A[관찰 이미지 수신] --> B[입력을 프로세싱하여 동작 선택 출력 생성]
    B --> C[중간 출력을 프로세싱하여 기하학적 피처 예측]
    C --> D[기하학적 피처의 실제 값 결정]
    D --> E[예측과 실제 값 사이의 에러에 기초하여 보조 업데이트 결정]
    E --> F[보조 손실의 그래디언트 결정]
    F --> G[그래디언트를 역전파하여 보조 업데이트 결정]