flowchart TD
    A[회원가입 요청 처리] --> B[데이터 수집 및 분석]
    B --> C[상품 전송 및 광고]
    C --> D[공동구매 수행]
    D --> E[회비납부 요청 및 배송 순서 결정]
    E --> F[상품 배송 순위 결정]
    F --> G[회원별 비용 결정 및 입력]
    G --> H[상품 배송 및 수령 확인]
    H --> I[대금 지불 요청]