flowchart TD
    A[프레임 수준 영상특징 추출 모듈을 통해 입력 비디오에서 프레임 레벨 시각적 특징을 추출하는 단계] --> B[주의 기반 비디오 요약 네트워크 모듈을 통해 주의 가중치를 계산하고, 상기 주의 가중치를 이용하여 중요도 점수를 키프레임을 선택하기 위한 프레임 추적 확률로 나타내는 단계]
    B --> C[평가 모듈을 통해 상기 키프레임을 선택하기 위한 키프레임 간의 시각적 유사성 거리와 시간적 거리에 따른 시간적 일관성 보상 함수와 대표성 보상 함수를 구하는 단계]
    C --> D[정책 경사 알고리즘 기반 학습 모듈을 통해 상기 예측된 중요도 점수에 따라 해당 키프레임을 선택하기 위한 파라미터화된 정책 경사(Policy Gradient) 학습을 수행하는 단계]
    D --> E[상기 비디오 요약 네트워크 모듈을 통해 상기 정책 경사 학습 결과에 따라 키프레임을 선택할 확률을 제어하기 위한 정규화 및 재구성 손실을 계산하는 단계]
    E --> F[비디오 요약 생성 모듈을 통해 상기 계산된 정규화 및 재구성 손실에 따라 키프레임을 선택하여 비디오 요약을 생성하는 단계]