flowchart TD
    A[저작물 업로드 요청 신호 수신] --> B[저작물 NFT 발행 요청 메시지 발송]
    B --> C[NFT 발행 요청 신호 수신]
    C --> D[NFT 발행]
    D --> E[저작물 메타버스 전시]
    E --> F[메타버스 접속 요청 신호 수신]
    F --> G[사용자 캐릭터 생성]
    G --> H[전시 및 체험 제공]
    H --> I[거래 요청 신호 수신]
    I --> J[저작물 NFT 거래 제공]
    J --> K[NFT 사용 기간 획득]
    K --> L{NFT 사용 기간 확인}
    L -->|제1 사용기간 이내| M[제1 가격 제공]
    L -->|제2 사용기간 이내| N[제2 가격 제공]
    L -->|제3 사용기간 이내| O[제3 가격 제공]
    K --> P[거래 요청 순위 획득]
    P --> Q{거래 요청 순위 확인}
    Q -->|제1 할인구간 이내| R[제1 추가 할인 적용]
    Q -->|제2 할인구간 이내| S[제2 추가 할인 적용]
    Q -->|제3 할인구간 이내| T[제3 추가 할인 적용]
    J --> U[구매 완료 신호 수신]
    U --> V[NFT 구매 시점 획득]
    V --> W{제1 기간 확인}
    W -->|제1 기간 = 제2 기간| X[남은 사용 기간 알림 메시지 발송]
    W -->|제1 기간 = 사용 기간| Y[NFT 회수]
    E --> Z[저작물 전시 시 평점 추가]
    G --> AA[캐릭터 생성 시 평점 추가]