flowchart TD
    A[소셜 네트워크를 통해 거래 대상 제품에 대한 검색 요청 수신] --> B[거래 대상 제품에 대한 리뷰 NFT 로딩]
    B --> C[리뷰 NFT의 거래 대상 제품 SCM 코드와 동일한 SCM 코드를 가지는 거래 대상 제품을 제공하는 복수의 판매자와 리뷰 NFT 간에 경로 생성]
    C --> D[제3 소비자가 리뷰 NFT에 접속하면 경로가 생성된 복수의 밸류 체인의 정보 제공]
    D --> E[복수의 판매자가 제공하는 동일한 SCM 코드를 가지는 거래 대상 제품 외의 제품에 대한 정보 추가 제공]
    D --> F[복수의 밸류 체인이 동일 SCM 코드를 가지는 거래 대상 제품에 대한 프로모션 정보 제공]