flowchart TD
    A[사용자의 기본 정보 획득] --> B[사용자의 바이오리듬 및 체온 정보 획득]
    B --> C[사용자의 건강 검진 정보 수신]
    C --> D[사용자의 개인 정보 결정 및 저장]
    D --> E[사용자의 구매 목적 정보 획득]
    E --> F[사용자의 상태 정보 획득]
    F --> G[사용자의 취향 정보 획득]
    G --> H[사용자의 경험 정보 획득]
    H --> I[환경 정보 획득]
    I --> J[건강기능식품 및 복약 방법 결정]
    J --> K[추천 건강기능식품 및 복약 방법 제시]
    K --> L[사용자 주문 입력 받기]
    L --> M[사용자의 반응도 측정]
    M --> N[사용자의 경험 정보 생성 또는 업데이트]
    L --> O[건강기능식품 섭취 영상 촬영]
    O --> P[섭취 여부 판단 및 저장]
    M --> Q[상태 정보 재측정 전]
    M --> R[상태 정보 재측정 후]
    M --> S[반응도 결정]