flowchart TD
    A[앰비언트 컴퓨팅 디바이스에 의해 프리페치 프로세스를 수행] --> B[프리페치된 명령과 데이터로 캐시를 채우는 단계]
    B --> C[저전력 상태로 진입하는 단계]
    C --> D[저전력 상태에서 입력 처리]
    A1[로컬 캐시 포함] --> A2[프리페치된 명령의 일부로 로컬 캐시를 채우는 단계]
    A3[SRAM 메모리 양 증가] --> A4[저전력 상태 동안 이용 가능한 메모리]
    A5[프리페치 저장 메모리 요청 발행] --> A6[캐시에 캐시 라인들을 할당]
    A7[더미 데이터 기록 시 메모리 요청 저장]
    A8[캐시의 계층 구조 포함] --> A9[저전력 절차의 메모리 크기 결정]
    A10[프리페치된 명령과 데이터 저장을 위한 캐시 결정]
    A11[시스템-레벨 캐시 선택]
    A12[선택된 캐시보다 아래 캐시 전원 차단]
    A13[선택된 캐시보다 아래 캐시 데이터 경로 전원 차단]