flowchart TD
    A[진열대상상품 결정 단계] --> B[진열대상상품 배송 및 진열 가이드 단계]
    A --> C[진열 상품 소진 모니터링 단계]
    B --> D[진열대상상품 그루핑 단계]
    D --> E[배송 담당자 배정 단계]
    E --> F[진열대상상품 진열 가이드 단계]
    F --> G[진열 정보 전송 단계]
    F --> H[최적 진열 이미지 생성]
    H --> I[서브 진열 이미지 포함]
    G --> J[진열 프로세스 평가 단계]
    J --> K[사업장 평가 정보 입력]