flowchart TD
    A[브랜드 로고의 로고 이미지 및 로고 텍스트를 획득하는 단계] --> B[도용 의심 이미지를 입력받는 단계]
    B --> C[로고 식별 모델을 이용하여 이미지 도용 정보를 생성하는 단계]
    C --> D[텍스트 분석을 수행하여 텍스트 도용 정보를 생성하는 단계]
    D --> E[도용 탐지 정보를 생성하는 단계]
    E --> F[이미지 도용 정보 및 텍스트 도용 정보에 기초]
    F --> G[이미지 도용 정보는 제1 확률 및 브랜드 이름 포함]
    F --> H[텍스트 도용 정보는 제2 확률 및 브랜드 이름 포함]
    F --> I[이미지 도용 정보는 로고 이미지 부분의 주변에 표시]
    F --> J[텍스트 도용 정보는 로고 텍스트 부분의 주변에 표시]
    F --> K[로고 텍스트는 OCR의 결과로 오판독 유의 부분 포함]
    K --> L[오판독 유의 부분의 제1 캐릭터와 제2 캐릭터의 처리 설정]
    L --> M[텍스트 도용 판별 임계치 설정]