flowchart TD
    A[비디오에서 사람을 식별하는 시스템] --> B[비디오로부터 시공간 감정 데이터 개요(STEM-DC) 생성]
    B --> C[제1 사람 표현 벡터 결정]
    C --> D[심층 완전 적응형 그래프 컨볼루션 네트워크(FAGC) 사용]
    D --> E[IFV 생성]
    E --> F[랜드마크 피처 벡터 합산]
    F --> G[전이 확률로 가중치 부여]
    G --> H[기본 감정 상태 결정]
    H --> I[사전 트레이닝된 얼굴 랜드마크 추출 네트워크(FLEN) 사용]
    I --> J[비디오로부터 얼굴 이미지 추출]
    J --> K[후속 제2 사람 표현 벡터와 비교]
    K --> L[사람 식별]