flowchart TD
    A[다양한 표정의 얼굴 이미지 데이터셋 입력] --> B[전처리한 이미지 감정 관련 세부 정보 추출 및 학습하는 로컬 인식 단계]
    B --> C[얼굴 전체 정보 추출 및 학습하는 공유 표현 글로벌 앙상블 단계]
    C --> D[각 분류기의 가중치 할당하는 랭크 어텐션 단계]
    D --> E[예측되는 감정 최종 결정하는 복수 보팅 단계]
    C --> F[분기 레벨 2 내지 4 중 하나 포함]
    B --> G[두 정점의 좌표 기반으로 ROI 세 개 영역으로 분리]
    B --> H[약분류 단계와 강분류 단계 포함]
    A --> I[비디오 스트리밍 데이터에서 처음 프레임 및 마지막 3개 프레임 선택]
    I --> J[회색조 사진으로 변환]
    J --> K[마지막 3개 프레임에 감정 레이블 태그 붙임]
    K --> L[Viola & Jones 알고리즘으로 얼굴 감지 및 정렬]
    L --> M[배경 또는 얼굴 아닌 영역 제거] 
    D --> N[가중치 벡터 S 기반으로 계산]
    E --> O[초기 분류 결과 값 기반으로 계산]
    O --> P[가중치 부과 및 복수 보팅 결과 값 계산]
    P --> Q[argmax(arguments of maximum) 역할 수행]