flowchart TD
    A[트레이닝 세트를 수신하는 단계] --> B[소스 순환 신경 네트워크에서의 노드들 사이에서 신호 전송 활동의 위상적 패턴들의 복수의 표현들을 포함]
    B --> C[각 표현에서의 신호 전송 활동은 소스 순환 신경 네트워크로의 입력에 응답]
    C --> D[위상적 패턴들의 표현들은 신호 전송 활동의 패턴들이 소스 순환 신경 네트워크 내 어디에서 일어나는가를 규정하지 않음]