flowchart TD
    A[소비자가 카드단말기, POS, 결제시스템 중 선택적 결제 수행] --> B[사업자단말기에서 소비자 결제정보를 VAN사 서버와 PG사 서버로 전송]
    B --> C[사업자단말기에서 Meta Bank 회원 가입 후 비대면으로 PC 및 Mobile 통합 플랫폼 접속]
    C --> D[VAN사 서버와 PG사 서버를 통해 사업자 카드매출 내역 저장된 플랫폼 통합 DB 원천정보 조회]
    D --> E[ERP 시스템 서버와 Hometax를 통해 기업 및 개인사업자의 개요, 재무제표, 부가가치세 신고서 및 세무신고정보 추가 저장]
    E --> F[금융서비스부를 통해 여신상담(ChatBot), 신청 및 결과 조회]
    F --> G[본인 및 사업자 인증]
    G --> H[VAN사, PG사, ERP 자료의 자동 제출]
    H --> I[진단서비스부를 통해 경영진단 및 상권현황, 등록자료 조회]
    I --> J[정보서비스부를 통해 은행별 상품 소개 및 맞춤 상품 추천]
    J --> K[사업자단말기로부터 소비자 결제정보 전송받고 플랫폼 통합 DB 원천정보에 저장]
    K --> L[PC 및 Mobile 통합 플랫폼의 정보통합 관리 센터부에서 가공된 플랫폼 통합 DB의 가공정보를 VAN사 고객서비스 툴을 통해 전송받음]
    L --> M[PC 및 Mobile 통합 플랫폼의 정보통합 관리 센터부에서 가공된 플랫폼 통합 DB의 가공정보를 PG사 고객서비스 툴을 통해 전송받음]
    M --> N[ERP시스템 서버와 연동되어 세무신고정보 전송]
    N --> O[본인 및 사업자 인증 후 ERP시스템 서버 내 정보 금융기관서버로 자동 전송]
    O --> P[홈택스와 연동되어 세무신고정보 전송]
    P --> Q[본인 및 사업자 인증 후 홈택스 세무정보와 증명정보 금융기관서버로 자동 전송]
    Q --> R[사업자 단말기에서 Meta Bank 회원 가입 후 비대면으로 PC 및 Mobile