flowchart TD
    A[크레딧 공급 기업 서버로부터 감축 정보 수신] --> B[감축 사실 정보와 비교하여 진위 여부 판단]
    B --> C[추가 온실가스 감축 증명서 발행 및 복수의 온실가스 감축 증명서에 포함]
    C --> D[추천 온실가스 감축 증명서 선택]
    D --> E[추천 온실가스 감축 증명서를 표시하는 웹 페이지 송신]
    D --> F[웹 페이지 접속 이력 및 수요 기업 정보 획득]
    F --> G[감축 방법에 따라 분류된 제1 리스트 추출]
    G --> H[시청 시간 및 클릭 횟수 확인하여 제2 리스트 추출]
    F --> I[위치, 고객층 성향 및 키워드 추출]
    I --> J[홍보 스토리 추출]
    H --> K[제2 리스트에서 홍보 스토리 적용 가능한 온실가스 감축 증명서 선택]