flowchart TD
    A[예측될 이미지 획득] --> B[예측될 특징 세트 추출]
    B --> C[타겟 결합 모델 사용하여 제1 레이블 및/또는 제2 레이블 획득]
    C --> D[제1 레이블은 동작 내용과 관련]
    C --> E[제2 레이블은 동작 의도와 관련]
    C --> F[제3 레이블은 승리 또는 패배의 결과와 관련]
    
    G[사용될 훈련 이미지 세트 획득] --> H[사용될 훈련 특징 세트 추출]
    H --> I[제1 사용될 훈련 레이블 및 제2 사용될 훈련 레이블 획득]
    I --> J[타겟 결합 모델 획득]