flowchart TD
    A[인바운드 바코드 스캔] --> B[제1의 전자 크리덴셜 정보 획득]
    B --> C[인바운드 정보 전송]
    C --> D[제2의 전자 크리덴셜 정보 획득]
    D --> E[아웃바운드 정보 전송]
    E --> F[서비스 계정 결정 및 교통 요금 지불]
    C1[인바운드 과금 장치에 의한 제1의 전자 크리덴셜 정보 유효성 검증] --> C
    D1[아웃바운드 과금 장치에 의한 제2의 전자 크리덴셜 정보 유효성 검증] --> E
    C --> C1
    E --> D1