flowchart TD
    A[요구사항 전송받아 저장] --> B[요구사항 인식 및 분석]
    B --> C[검증 정보 생성]
    C --> D[검증 정보 검증 및 품질 점수 생성]
    D --> E[제공 정보 생성 및 전송]
    A1[사용자 단말기 요청 정보 전송] --> A2[입력부 인증 정보 전송받기]
    A2 --> A3[인증 정보 입력부로 전송]
    A3 --> A4[인증 정보 일치 여부 확인]
    A4 -->|일치| A5[요구사항 입력부에 전송]
    A5 --> A6[디스플레이부 인증용 데이터 디스플레이]
    A6 --> A7[디텍터부 인증 정보 검출]
    A7 -->|검출| A8[디스플레이부 인증용 데이터 디스플레이]
    A8 --> A9[보조 조절부 개방]
    A9 --> A10[보조 개구 순차적으로 개방]