flowchart TD
    A[키오스크부 설치] --> B[사용자 QR코드 스캔 또는 NFC 태깅]
    B --> C[스마트 티켓 발권 요청]
    C --> D[스마트 티켓 발권]
    D --> E[스마트 티켓 QR코드 스캔 또는 NFC 태깅]
    E --> F[공공시설물 또는 공연장 입장]
    C --> G[개인 정보 입력]
    G --> H[스마트 티켓 결제 요청]
    H --> I[스마트 티켓 결제]
    I --> J[스마트 티켓 저장]
    J --> K[관광지 정보 열람]
    K --> L[스마트 티켓 예약]
    D --> M[유저 인터페이스 제공]
    M --> N[사용자 신원 인증 요청]
    N --> O[할인 감면 확인]
    O --> P[스마트 ID 발급]
    P --> Q[스마트 ID 저장]
    P --> R[스마트 티켓 결제 서비스 제공]
    R --> S[스마트 티켓 발권]
    S --> T[스캔·태깅 관리]
    T --> U[관광지 정보 제공]
    U --> V[통계 산출]
    C --> W[가족 스마트 티켓 관리]
    W --> X[신원 요청 조회]
    X --> Y[할인 및 감면 확인]
    Y --> Z[스마트 티켓 발권]
    E --> AA[비용 차감]
    AA --> AB[입장 시간 및 퇴장 시간 계산]
    AB --> AC[비용 할인 및 포인트 지급]