flowchart TD
    A[생체시료에서 핵산을 추출하여 서열정보를 획득하는 단계] --> B[획득한 서열정보(reads)를 표준 염색체 서열 데이터베이스에 정렬하는 단계]
    B --> C[정렬된 서열정보(reads)를 이용하여 핵산단편의 크기 및 커버리지 정보가 포함된 이미지를 생성하는 단계]
    C --> D[생성된 이미지를 학습된 인공지능 모델에 입력하여 분석한 출력 결과값과 기준값을 비교하여 암 유무를 판정하는 단계]
    D --> E[출력 결과값 비교를 통해 암 종을 예측하는 단계]
    
    subgraph 청구항 2
        A1[혈액, 정액, 질 세포, 모발, 타액, 소변, 구강세포, 태반세포 또는 태아세포를 포함하는 양수, 조직세포 및 이의 혼합물에서 핵산을 수득하는 단계]
        A2[채취된 핵산에서 솔팅-아웃 방법, 컬럼 크로마토그래피 방법 또는 비드 방법을 사용하여 단백질, 지방, 및 기타 잔여물을 제거하고 정제된 핵산을 수득하는 단계]
        A3[정제된 핵산 또는 효소적 절단, 분쇄, 수압 절단 방법으로 무작위 단편화된 핵산에 대하여, 싱글 엔드 시퀀싱 또는 페어 엔드 시퀀싱 라이브러리를 제작하는 단계]
        A4[제작된 라이브러리를 차세대 유전자서열검사기에 반응시키는 단계]
        A5[차세대 유전자서열검사기에서 핵산의 서열정보(reads)를 획득하는 단계]
    end
    A --> A1
    A1 --> A2
    A2 --> A3
    A3 --> A4
    A4 --> A5

    subgraph 청구항 4
        B1[염색체를 일정구간으로 구분하는 단계]
        B2[각 구간에 정렬된 핵산단편의 수를 결정하는 단계]
        B3[각 구간의 순서를 X