flowchart TD
    A[하나 이상의 메타 학습 데이터에 기초하여 제1 모델을 퓨 샷 학습(FSL; Few Shot Learning)시키는 제1 태스크 수행] --> B[상기 제1 모델로 입력된 메타 학습 데이터에 대한 상기 제1 헤드의 분류 결과와 상기 제1 모델로 입력된 메타 학습 데이터에 사전 할당된 레이블 사이의 제1 손실을 산출]
    B --> C[상기 제1 손실에 기초하여 상기 메인 바디의 학습 파라미터를 갱신]
    A --> D[상기 하나 이상의 메타 학습 데이터로부터 변형된 하나 이상의 파생 데이터에 기초하여 제2 모델을 지도 학습(supervised learning)시키는 제2 태스크 수행]
    D --> E[상기 제2 모델로 입력된 파생 데이터에 대한 상기 제2 헤드의 분류 결과와 상기 제2 모델로 입력된 파생 데이터에 기초하여 생성된 자가 레이블 사이의 제2 손실을 산출]
    E --> F[상기 제2 손실에 기초하여 상기 메인 바디의 학습 파라미터를 갱신]
    A --> G[상기 하나 이상의 메타 학습 데이터에 기초하여 제3 모델을 약 지도 학습(weakly-supervised learning)시키는 제3 태스크 수행]
    G --> H[상기 제3 모델로 입력된 메타 학습 데이터에 대해 상기 모조 레이블을 생성]
    H --> I[상기 제3 모델로 입력된 메타 학습 데이터에 대한 상기 디코더의 영역 검출 결과와 상기 모조 레이블 사이의 제3 손실을 산출]
    I --> J[상기 제3 손실에 기초하여 상기 메인 바디의 학습 파라미터를 갱신]
    A --> K[상기 하나 이상의 메타 학습 데이터 및 라벨링되지 않은 하나 이상의 추가 데이터에 기초하여 상기 제1 모델을 비지도 학습(unsupervised learning)시키는 제4 태스크 수행]
    K --> L[상기 메인 바디에서 입력된 메타 학습 데이터에 대한