flowchart TD
    A[카메라로 객체 영상 정보 수집] --> B[단일 복합 센서로 객체 거리 정보 생성]
    B --> C[경계 구역 정보 수집부로 정보 전송]
    C --> D[객체 영상 정보 및 객체 거리 정보 수신]
    D --> E[객체 분석하여 안전객체 및 위협객체로 분류]
    E --> F[위협객체 분석하여 침입객체 및 미침입객체로 분류]
    F --> G[분류한 객체정보 저장 및 전송]
    G --> H[주요 경계 위치 설정]
    H --> I[경계 구역 및 경계 알람 구역 설정]
    I --> J[객체 정보 표시 및 침입객체 이동 경로 추적]
    J --> K[객체 영상 정보 분할하여 객체 이미지 정보 생성]
    K --> L[객체 이미지 정보를 픽셀 단위로 분할]
    L --> M[픽셀 단위 객체 이미지 정보 분석]
    M --> N[위치 이동 객체와 고정 객체 분리]
    N --> O[각 객체에 대한 윤곽선 생성]
    O --> P[객체와 윤곽선 분리하여 객체 윤곽 정보 생성]
    P --> Q[객체 윤곽 정보 분석하여 안전객체 정보 및 위협객체 정보 분류]
    Q --> R[위협객체 정보 분석하여 침입객체 및 미침입객체 정보 저장]
    R --> S[객체 메모리에 정보 저장]
    S --> T[객체 인식 시스템 구동 제어 및 정보 송수신]