flowchart TD
    A[발광체 포함 광원] --> B[2차원 이미지 획득]
    B --> C[3차원 헤드포즈 정보 획득]
    C --> D[2차원 이미지와 3차원 헤드포즈 정보 매칭]
    D --> E[헤드 회전 방향 결정]
    E --> F[매칭되는 2차원 이미지 추출]
    F --> G[3차원 상대 좌표 획득]
    G --> H[3차원 헤드포즈 정보 보정]
    H --> I[보정된 3차원 헤드포즈 정보 획득]
    I --> J[2차원 이미지와 3차원 헤드포즈 정보 매칭 시점 설정]
    J --> K[헤드 랜드마크 지점 검출]
    K --> L[발광체로부터 이미지 획득]
    L --> M[프레임 매칭 조건 설정]
    M --> N[타임 스탬프 동기화]
    N --> O[타임 스탬프 메타 데이터 저장]
    O --> P[타임 스탬프 매칭]
    P --> Q[헤드 로테이션 정보 포함]
    Q --> R[헤드 방향 기준 값 비교]
    R --> S[복수의 2차원 이미지 선택]
    S --> T[2차원 이미지에 대한 보정된 3차원 헤드포즈 정보 레이블링]
    T --> U[3차원 헤드포즈 추론 모델 훈련]
    U --> V[3차원 헤드포즈 정보 획득]