flowchart TD
    A[실행을 위한 기계어 명령을 획득하는 단계] --> B[상기 기계어 명령을 실행하는 단계]
    B --> C[제2 오퍼랜드의 복수의 엘리먼트들을 모두 더하는 단계]
    C --> D[하나 또는 그 이상의 엔드 어라운드 캐리 애드 연산들을 수행하는 단계]
    D --> E[합을 생산하는 단계]
    E --> F[상기 합의 선정된 위치로부터의 캐리가 있다면, 이를 상기 제1 오퍼랜드의 선택된 엘리먼트 내의 선택된 위치에 더하는 단계]
    F --> G[상기 제1 오퍼랜드의 선택된 엘리먼트 내에 상기 제1 결과를 배치하는 단계]