flowchart TD
    A[원본 데이터를 수신하는 데이터 수신부] --> B[상기 데이터 수신부로부터 수신된 원본 데이터를 기초로 학습예제(X') 생성]
    B --> C[교사모델과 학생모델에 제공하여 지식 전이]
    C --> D[교사모델의 예측확률을 포함한 교사보상 피드백]
    C --> E[학생모델의 예측확률을 포함한 학생보상 피드백]
    D --> F[훈련하여 교사모델의 정답 예측확률이 학생모델의 정답 예측확률보다 크도록 학습예제(X') 생성]
    E --> F
    F --> G[튜터 네트워크부]