flowchart TD
    A[제1 환경 정보를 획득하는 단계] --> B[제1 특징 벡터를 추출하는 단계]
    B --> C[제2 특징 벡터를 선택하는 단계]
    C --> D[제1 유사도를 산출하는 단계]
    D --> E[제2 유사도를 산출하는 단계]
    E --> F[퓨전 유사도를 산출하는 단계]
    F --> G[사용자를 인증하는 단계]