flowchart TD
    A[사용자 식별 단계] --> B[도어 개방 단계]
    B --> C[구매 상품 식별 단계]
    C --> D[결제 처리 단계]
    C --> E[촬영 이미지 획득 단계]
    E --> F[상품 식별 단계]
    C --> G[가격 정보 업데이트 단계]
    G --> H[할인율 결정 단계]
    A --> I[무선 신호 전송 단계]
    I --> J[신호 강도 판단 단계]
    J --> K[사용자 인증 단계]
    J --> L[언락 버튼 활성화 단계]
    A --> M[관리 권한 판단 단계]
    M --> N[재고 정보 업데이트 단계]
    A --> O[신호 강도 센 모바일 장치 활성화 단계]
    C --> P[무게 센서 측정 값 기반 상품 식별 단계]