flowchart TD
    A[사용자의 얼굴 영역의 이미지를 수신하는 단계] --> B[안구 이미지 영역을 정의하는 단계]
    B --> C[안구 주위 이미지 영역을 정의하는 단계]
    C --> D[안구 주위 이미지 영역들을 순위 매기는 단계]
    D --> E[복수의 관심 포인트들을 식별하는 단계]
    E --> F[관심 포인트를 둘러싸는 텍스쳐에 대한 영역 값을 계산하는 단계]
    F --> G[얼굴 영역의 이미지에 대한 품질 메트릭을 결정하는 단계]