flowchart TD
    A[단백질 서열 데이터를 전처리하여 스펙트럼 라이브러리를 구축하는 단계] --> B[상기 스펙트럼 라이브러리로부터의 예측된 MS 데이터 및 실험 MS 데이터에 기초하여 PMSM 데이터를 생성하는 단계]
    B --> C[PMSM 스코어링 모델을 통해 생성된 PMSM을 평가하는 단계]
    C --> D[설정된 스코어 이상의 PMSM에 대한 펩타이드 분류를 학습하는 단계]
    D --> E[학습된 분류에 기초하여 펩타이드 동정 결과를 생성하는 단계]