flowchart TD
    A[객체의 전자 이미지를 획득하는 단계] --> B[에지 검출 알고리즘 수행]
    B --> C[제1 세트의 에지들 획득]
    C --> D[에지 풀링 알고리즘 수행]
    D --> E[제2 세트의 에지들 획득]
    E --> F[에지 패치들의 세트 획득]
    F --> G[컬러 패치들의 세트 획득]
    G --> H[텍스처 패치들의 세트 획득]
    H --> I[패치 선택]
    I --> J[부분 선택 알고리즘 수행]
    J --> K[부분 풀링 알고리즘 수행]
    K --> L[제2 세트의 부분들 등록]