flowchart TD
    A[주행 중인 차량의 영상을 촬영해 영상데이터를 생성하는 감시 카메라] --> B[영상데이터의 프레임에서 스트립 영역을 설정]
    B --> C[스트립 영역의 신호 변화량을 분석해 차량이 통과하는 이벤트 프레임을 감지해 추출]
    C --> D[번호판 문자열의 수평적 특징과 수직적 특징을 강조하도록 설계된 딥러닝 모델을 이용해 번호판 문자를 검지하고 인식]
    D --> E[트리아지 코어가 주기적으로 이벤트 프레임을 강제 추출하여 코그니션 코어로 제공]
    E --> F[트리아지 코어의 해상도 축소부로 프레임의 해상도를 축소]
    F --> G[감지선 도입부로 스트립 영역에 감지선 설정]
    G --> H[신호 축약부로 2차원 스트립 영역을 1차원 신호로 축약]
    H --> I[변화량 산출부로 변화량 지표 산출]
    I --> J[적응 임계 판정부로 변화량 지표 분석]
    J --> K[트리거 제어부로 이벤트 프레임 추출]
    K --> L[딥러닝 모델의 이중 특징 추출부로 특징맵 추출]
    L --> M[특징 정제부로 특징맵 정제]
    M --> N[다중 해상도 통합부로 특징 융합]
    N --> O[다중 속성 검출부로 번호판의 다중 속성 검출]
    O --> P[문자 시퀀스 해석부로 문자열 판독]