flowchart TD
    A[타겟 키워드를 입력 받는 제1 오브젝트를 디스플레이하는 단계] --> B[제1 키워드의 순위 변동 정보를 디스플레이하는 단계]
    B --> C[타겟 키워드에 문자를 추가한 문자열과 연관된 제2 키워드의 순위 변동 정보를 디스플레이하는 단계]
    C --> D[제1 키워드 및 제2 키워드의 키워드 변동 정보를 디스플레이하는 단계]
    D --> E[제3 그래프를 디스플레이하는 단계]
    E --> F[제3 키워드의 목록, 제4 키워드의 목록 및 제5 키워드의 목록을 디스플레이하는 단계]
    F --> G[제4 키워드에 식별자를 부여하여 디스플레이하는 단계]
    G --> H[제1 키워드의 순위 변동 정보, 키워드 변동 정보 및 제2 키워드의 순위 변동 정보의 업데이트 날짜를 디스플레이하는 단계]
    H --> I[제2 오브젝트를 디스플레이하는 단계]
    I --> J[제1 키워드의 순위 변동 정보를 디스플레이하는 단계]
    J --> K[사용자 입력에 기초하여 결정된 적어도 일부의 키워드의 순위 변동 정보를 디스플레이하는 단계]
    K --> L[하나의 키워드에 대응하는 시간 단위별 식별자들을 연결하여 선을 디스플레이하는 단계]
    L --> M[제2 그래프에서 순위 변동 정보를 디스플레이하는 단계]