flowchart TD
    A[정식 URL 및 인증 번호가 암호화된 개인화 URL을 사용자 단말기로 전송하는 단계] --> B[상기 개인화 URL을 통해 상기 사용자 단말기가 접속되면, 상기 사용자 단말기로 복수의 상품 정보를 제공하는 단계]
    B --> C[상기 사용자 단말기로부터 상기 복수의 상품 정보 중 어느 하나에 따른 상품에 대한 사용자 선택을 입력받는 단계]
    C --> D[상기 사용자 선택에 따른 상품에 대한 모바일 기프트를 발행하는 단계]