flowchart TD
    A[세무 회계 랜딩 페이지 저장] --> B[경영 컨설팅 랜딩 페이지 저장]
    B --> C[법인 설립 운영 랜딩 페이지 저장]
    C --> D[지식재산권 랜딩 페이지 저장]
    D --> E[광고 마케팅 랜딩 페이지 저장]
    E --> F[랜딩 페이지 노출부 구성]
    F --> G[사용자 정보 제공부 구성]
    G --> H[사용자 정보 수신부 추가]
    H --> I[지원 정보 제공부 추가]
    I --> J[지원 사업 정보 수신부 추가]
    J --> K[지원 사업 정보 제공부 추가]
    K --> L[사용자 선정 및 정보 제공]