flowchart TD
    A[광고 캠페인을 진행할 제품 데이터 등록] --> B[광고 콘텐츠 제작 의뢰]
    B --> C[인플루언서 데이터 수집]
    C --> D[인플루언서 분류]
    D --> E[제품 데이터 등록 접수]
    E --> F[유사도 기준으로 인플루언서 추천]
    F --> G[인플루언서 선정 시 매칭 이벤트 전달]
    G --> H[상담 채널 연결 및 설정]
    H --> I[상담 히스토리 생성 및 저장]
    I --> J[광고해지 여부 예측]
    J --> K[예측 결과 제공]
    K --> L[광고 아이디어 추출]
    L --> M[광고 이미지 또는 영상 생성]
    M --> N[광고 매체 추천]
    N --> O[인플루언서 광고출연 이력 고려]