flowchart TD
    A[제 1 큐비트레지스터: 제 1 방식으로 구현된 제 1 큐비트 포함] --> B[큐비트변환기: 제 1 큐비트를 제 2 방식의 큐비트로 변환]
    B --> C[제 2 큐비트레지스터: 제 2 방식으로 구현된 제 2 큐비트 포함]
    C --> D[제 1 측정센서: 제 1 환경정보 획득]
    C --> E[제 2 측정센서: 제 2 환경정보 획득]
    D --> F[보정정보획득장치: 오류 보정 정보 획득]
    E --> F
    F --> G[큐비트오류 보정장치: 제 1 큐비트레지스터 및 제 2 큐비트레지스터의 값 보정]