flowchart TD
    A[복수의 렌탈 시설의 공간 맵 생성] --> B[렌탈 시설 예약 수행]
    B --> C[물품 주문 및 판매 수행]
    C --> D[시설 정비 관리]
    D --> E[예약 상태 표시]
    E --> F[이용 상태 표시]
    F --> G[시설 정비 상태 표시]
    G --> H[예약자 단말에서 예약 진행]
    H --> I[렌탈 비용 정산]
    I --> J[모바일 이용 티켓 저장]
    J --> K[관리 감독자 단말에서 상태 표시]
    K --> L[모바일 리더기로 모바일 이용 티켓 판독]
    L --> M[시설 정비 관리자 단말에서 모바일 출입증 저장]