flowchart TD
    A[사용자 단말로부터 대상 식자재에 대한 소정의 과거 시구간 동안의 시계열 데이터 획득] --> B[시계열 데이터에 대해 정규화 처리 수행 및 가공 시계열 데이터 생성]
    B --> C[가공 시계열 데이터를 메모리에 저장된 식자재 데이터베이스에 누적 저장]
    C --> D[가공 시계열 데이터를 딥러닝 기반 인공지능 모델에 입력하여 예측 수요량 추이 획득]
    D --> E[예측 수요량 추이, 실시간 재고량 및 평균 리드 타임을 기반으로 부족 위험도 산출]
    E --> F[부족 위험도가 임계 위험도 이상인 위험 식자재에 대한 발주 필요 알림 제공]
    F --> G[평균 리드 타임 확인 후 제1 단기 예측 수요량 확인]
    G --> H[실시간 재고량에서 제1 단기 예측 수요량 차감하여 제1 차이 확인]
    H --> I[제1 차이의 크기에 반비례하여 부족 위험도 확인]
    I --> J[제1 기준 미래 시점으로부터 제2 기준 미래 시점까지의 제2 단기 예측 수요량 확인]
    J --> K[제2 단기 예측 수요량이 임계 수요량 초과 시 평균 발주량 확인]
    K --> L[실시간 재고량에서 제1 단기 예측 수요량 차감한 제1 값 확인]
    L --> M[제1 값과 평균 발주량 합산한 값이 제2 단기 예측 수요량 미만인 경우 추가 발주 필요 알림 제공]