flowchart TD
    A[관심 영역에 대응하는 이미지 데이터를 획득하는 단계] --> B[상기 관심 영역에 대응하는 열화상 데이터를 획득하는 단계]
    B --> C[상기 열화상 데이터에서 객체가 식별되고 상기 이미지 데이터에서 상기 객체가 식별되지 않는 경우를 제1 데이터 세트로 결정하는 단계]
    C --> D[상기 제1 데이터 세트에 기반하여 상기 이미지 데이터 및 상기 열화상 데이터를 피처로 상기 객체를 레이블로 하는 제1 멀티모달 학습모델을 생성하는 단계]
    D --> E[상기 제1 멀티모달 학습모델은 상기 이미지 데이터 및 상기 열화상 데이터를 피처로 하여 상기 객체를 식별하도록 하는 제1 가중치에서, 상기 열화상 데이터를 피처로 상기 객체를 식별하도록 하는 제2 가중치를 차감하도록 하는 신경망 레이어를 포함하는 방법]
    E --> F[상기 이미지 데이터로부터 컨볼루션 연산에 기반하여 제1 피처를 생성하는 단계]
    F --> G[상기 열화상 데이터로부터 컨볼루션 연산에 기반하여 제2 피처를 생성하는 단계]
    G --> H[상기 제1 피처 및 상기 제2 피처를 다중 모달 융합을 하여, 표현 정보를 생성하는 단계]
    H --> I[상기 표현 정보를 입력으로 하여, 상기 객체를 식별할 수 있는 신경망 레이어의 가중치를 학습하는 단계]
    I --> J[상기 열화상 데이터에서 상기 객체가 식별되고 상기 이미지 데이터에서 상기 객체가 식별되는 경우를 제2 데이터 세트로 결정하는 단계]
    J --> K[상기 제2 데이터 세트에 기반하여 상기 이미지 데이터 및 상기 열화상 데이터를 피처로 상기 객체를 레이블로 하는 제2 멀티모달 학습모델을 생성하는 단계]
    K --> L[상기 열화상 데이터 및 상기 이미지 데이터를 제1 멀티모달 학습모델에 입력하여 상기 객체를 재식별하는 단계]
    L --> M[상기 열화