flowchart TD
    A[제1 사용자 단말로부터 상품 이미지 정보 수신] --> B[상품 이미지 정보에 대한 제1 객체 및 제2 객체 이미지 보정]
    B --> C[보정된 상품 이미지 정보 생성 및 저장]
    C --> D[보정된 상품 이미지 정보 광고판 디스플레이에서 출력 제어]
    D --> E[카메라 모듈이 불특정 다수 촬영]
    E --> F[영상 정보에 기반하여 제3 객체 추출]
    F --> G[제3 객체로부터 불특정 다수의 움직임 및 시선 식별]
    G --> H[불특정 다수의 움직임으로부터 제1 시간 및 제2 시간 산출]
    H --> I[불특정 다수의 시선에 기반하여 제3 시간 산출]
    I --> J[제1 시간이 제1 기준 시간보다 길고, 제2 시간이 제2 기준 시간보다 길고, 제3 시간이 제3 기준 시간보다 긴 경우 보정된 상품 이미지 정보를 소정의 리스트에 포함]
    J --> K[제1 사용자 단말로부터 제1 카테고리 정보 수신]
    K --> L[제1 카테고리 정보를 제2 카테고리 정보에 자동으로 매칭]
    L --> M[제2 사용자 단말로부터 사용자 정보 수신]
    M --> N[사용자 정보에 따른 선호 가중치 기반으로 선호 상품 추천 정보 및 상품 추천 푸쉬 생성]
    N --> O[선호 상품 추천 정보 및 상품 추천 푸쉬를 제2 사용자 단말에 전송]
    O --> P[상품에 대한 구매 요청 정보 수신]
    P --> Q[구매 요청 정보 및 제2 카테고리 정보에 기반하여 통관 EDI 폼 전송]
    Q --> R[복수의 속성 중 제1 속성에 구매 요청 정보 및 제2 카테고리 정보 자동 매칭]
    R --> S[복수의 속성 중 제1 속성을 제외한 제2 속성에 대한 입력 정보 수신]