flowchart TD
    A[샘플 데이터들을 셔플(shuffle)하는 단계] --> B[제 1 샘플 데이터 세트의 서브세트들을 생성하는 단계]
    B --> C[학습 데이터 세트를 구성하는 단계]
    C --> D[복수의 피해 감지 모델들을 기준으로 인덱싱(indexing)하는 단계]
    D --> E[인덱싱된 제 1 샘플 데이터 세트의 서브세트들을 제 2 샘플 데이터 세트와 그룹핑(grouping)하여 서브세트들을 생성하는 단계]
    E --> F[복수의 피해 감지 모델들 각각을 학습시키는 단계]
    G[이미지를 수신하는 단계] --> H[학습 데이터 세트를 이용하여 이상(anomaly) 객체를 추정하는 단계]
    H --> I[기본 스코어를 획득하는 단계]
    I --> J[기본 스코어의 전체 평균값을 연산하여 최종 스코어를 획득하는 단계]