flowchart TD
    A[사용자의 위치정보를 획득] --> B[사용자가 방문한 점포의 간판 인식]
    B --> C[위치정보 및 인식된 점포의 간판 확인]
    C --> D[방문한 점포 특정]
    D --> E[사용자에게 코인 제공]
    E --> F[사용자단말 인식]
    F --> G[사용자가 보유한 코인 사용 승인]
    G --> H[코인 차감 및 제품 가격 할인]
    H --> I[방문확인부: 위치정보 확인]
    I --> J[장소관리부: 코인 수 평가]
    J --> K[장소추천부: 다른 점포 추천]
    K --> L[가치계산부: 코인 개수 결정]
    L --> M[사용자관리부: 보유코인정보 생성]