flowchart TD
    A[개방통신모듈 탑재] --> B[개방기능부 제공]
    B --> C[일측키보드 및 타측키보드로 이루어진 폴더블키보드]
    C --> D[보안통신모듈 탑재]
    D --> E[보안기능부 제공]
    E --> F[제1 커넥터 연결]
    F --> G[제2 커넥터 연결]
    G --> H[외부디스플레이 제공]
    H --> I[메인 터치디스플레이 제공]
    I --> J[메인하우징 제공]
    J --> K[안착패널 제공]
    K --> L[연결바 제공]
    L --> M[외부디스플레이 접속부 제공]