flowchart TD
    A[플랫폼 어플리케이션 설치] --> B[이커머스 서비스 제공]
    B --> C[수익 발생 시 거주-수수료 지급]
    B --> D[증권거래소 운영서버 포함]
    D --> E[증권거래 운영방식 결정]
    E --> F[데이터 수집부 실행]
    F --> G[도시DB 수집]
    G --> H[비상장-도시 도시DB 추출]
    H --> I[상장여부 판단]
    I --> J[상장대상도시 IPO 실행]
    J --> K[상장일자 및 공모가 계획 수립]
    K --> L[증권거래 서비스 운영]
    E --> M[명의개서대리인 선정]
    M --> N[예탁기관 선정]
    N --> O[토지분할소유권 거래중개인 지정]
    O --> P[발행인 관리계좌 개설]
    P --> Q[대금 결제 및 거래 운영]
    J --> R[주당순이익(EPS) 산출]
    R --> S[주가수익비율(PER) 산출]
    S --> T[공모 예정가 결정]
    T --> U[공모주 청약 서비스 실행]
    B --> V[비대면 가맹점 단말기 설치]
    V --> W[가맹점 등록 요청 수신]
    W --> X[가맹점 인터페이스 생성]
    W --> Y[회원 가입 요청 수신]
    Y --> Z[가입자 및 전시-룸 인터페이스 생성]
    Z --> AA[서비스-상품 구매 요청 수신]
    AA --> AB[구매 서비스 정보 입력]