flowchart TD
    A[폴더블 전자 장치] --> B[플렉서블 디스플레이]
    A --> C[힌지 어셈블리]
    C --> D[제1 힌지 프레임]
    C --> E[제2 힌지 프레임]
    C --> F[제1 힌지]
    C --> G[제2 힌지]
    A --> H[열 확산 부재]
    A --> I[제1 브래킷]
    A --> J[제2 브래킷]
    H --> K[제1 열 확산 부재]
    H --> L[제2 열 확산 부재]
    I --> M[제1 안착부]
    J --> N[제2 안착부]