flowchart TD
    A[휴대단말기(100)에서 결제 SMS 수신] --> B[OTP PIN 입력]
    B --> C[USIM칩(120)으로 OTP 생성]
    C --> D[신용카드 결제 요청 정보 인가]
    D --> E[결제 승인 요청 정보 전송]
    E --> F[상품결제 승인 정보 수신]
    
    G[물품구매서버(200)에서 상품구매 요청 정보 수신] --> H[상품결제 요청 정보 전송]
    H --> I[상품결제 승인 정보 수신]
    I --> J[상품구매 완료 정보 생성]
    J --> K[상품결제 DB(210) 갱신]