flowchart TD
    A[신경망 모델에서 중간 특징을 병목 특징으로 정의하는 단계] --> B[병목 특징을 기초로 신경망 모델을 제1 파라미터를 가진 포워드 네트워크와 제2 파라미터를 가진 백워드 네트워크로 분리하여 정의하는 단계]
    B --> C[백워드 네트워크의 출력값과 실제 레이블값(GT) 사이의 손실로 정의되는 손실 함수에 대한 경사하강법을 적용하여 제2 파라미터와 병목 특징을 업데이트하여 백워드 네트워크를 업데이트하는 단계]
    C --> D[손실 함수에서 제1 파라미터의 기울기와 병목 특징에 대한 기울기를 모두 고려하여 포워드 네트워크를 업데이트하는 단계]