flowchart TD
    A[탄소 배출권을 특정하는 증권형 토큰을 발행하는 동작] --> B[사용자가 수행한 탄소 저감 이벤트에 대한 증명 데이터를 획득하는 동작]
    B --> C[상기 증명 데이터를 기초로 상기 사용자에게 상기 증권형 토큰을 지급하는 동작]
    C --> D[상기 증명 데이터는 중고 거래 대상이 된 물품의 정보 및 상기 물품의 중고 거래가 발생한 시점에 대한 정보를 포함]
    B --> E[상기 물품에 의해 발생하는 탄소의 기본 배출량에서 상기 물품의 수명에 대한 물품의 잔여 수명의 비율에 대응하는 제1 수치에 상기 물품의 중복 거래가 발생할 확률인 제2 수치를 고려하여 탄소 저감량을 판별하는 동작]
    E --> F[상기 잔여 수명은 상기 물품의 수명 중에 상기 물품의 중고 거래가 발생한 시점의 이후 시간을 기초로 계산됨]
    C --> G[상기 탄소 저감량을 기초로 상기 중고 거래와 관련된 주체에게 상기 증권형 토큰을 지급하는 동작]