flowchart TD
    A[이미지에 액세스] --> B[제1 CNN 및 이미지에 기초하여 콘볼루셔널 특징 맵 생성]
    B --> C[RPN에 기초하여 적어도 하나의 RoI 결정]
    C --> D[풀링 층 및 큐보이드 이미지 위치에 기초하여 RoI에 대응하는 서브맵 결정]
    D --> E[서브맵 및 회귀자 층에 기초하여 정제된 RoI 및 큐보이드 표현 결정]
    E --> F[정제된 큐보이드 이미지 위치에 기초하여 정제된 RoI에 대응하는 서브맵 결정]
    F --> G[풀링 층, 회귀자 층, 정제된 RoI에 기초하여 추가로 정제된 RoI 및 큐보이드 표현 결정]