flowchart TD
    A[소정 영역의 객체를 파지하기 위한 로봇암] --> B[소정 영역을 촬영하여 원본 영상을 생성하는 카메라]
    B --> C[원본 영상이 입력되면 분류모델을 통해 분석]
    C --> D[분류 정보를 도출하는 분류처리부]
    D --> E[파지 정보를 도출한 후 분류 정보와 파지 정보를 매핑]
    E --> F[로봇암에 제공하는 파지처리부]
    F --> G[원본 영상의 왜곡 보정]
    G --> H[왜곡이 보정된 원본 영상을 그레이 레벨 이미지로 변환]
    H --> I[변환된 그레이 레벨 이미지를 이진화하여 이진화 이미지 생성]
    I --> J[이진화 이미지의 마스크 영역 값들을 정렬 후 중간 값 선택]
    J --> K[중앙의 값을 변화시켜 노이즈 제거]
    K --> L[노이즈가 제거된 이진화 이미지에서 객체 외곽선 검출]
    L --> M[검출된 외곽선을 원본 영상에 적용]
    M --> N[객체의 외접사각형 검출]
    N --> O[객체의 파지 정보 도출]
    O --> P[원본 영상의 픽셀 좌표계 정규화]
    P --> Q[정규화 영상을 보정하여 보정 영상 생성]
    Q --> R[보정 영상을 원본 영상의 픽셀 좌표계로 복원]