flowchart TD
    A[서버가, 특정 중고 서적을 판매하고자 하는 제1 사용자 단말로부터 상기 특정 중고 서적에 대한 판매 희망 정보를 획득] --> B[서버가, 특정 중고 서적을 구매하고자 하는 제2 사용자 단말로부터 상기 특정 중고 서적에 대한 구매 희망 정보를 획득]
    B --> C[서버가, 상기 특정 중고 서적에 대응되는 특정 저자 정보를 획득]
    C --> D[서버가, 상기 제1 사용자 단말로부터의 상기 판매 희망 정보 및 상기 제2 사용자 단말로부터의 상기 구매 희망 정보를 참조로 하여 상기 특정 중고 서적에 대한 특정 거래를 성사시키는 단계]
    D --> E[서버가, 상기 특정 중고 서적의 특정 거래 정보 및 상기 특정 저자 정보를 참조로 하여 상기 특정 중고 서적에 대한 인세 금액을 결정]
    E --> F[상기 인세 금액을 상기 특정 저자 정보에 대응되도록 적립]
    F --> G[서버가, 상기 특정 저자 정보에 대응되는 특정 커뮤니티를 운영하거나 운영하도록 지원]
    G --> H[서버는, 상기 특정 중고 서적에 대한 상기 특정 거래가 성사되면, 상기 제1 사용자 단말 및 상기 제2 사용자 단말 중 적어도 일부에 상기 특정 커뮤니티에 대한 가입을 요청할 수 있는 자격 부여]
    H --> I[서버가, 상기 제1 사용자 단말 및 상기 제2 사용자 단말 중 적어도 일부의 상기 특정 커뮤니티에서의 레벨에 대한 조정을 수행]
    I --> J[서버가, 상기 특정 거래에 대한 현재 데이터 및 상기 제1 사용자 단말 및 상기 제2 사용자 단말 중 적어도 일부의 과거 데이터를 참조로 하여, 상기 특정 커뮤니티에서의 상기 레벨을 조정]
    J --> K[서버가, 상기 제1 사용자 단말 및 상기 제2 사용자 단말 각각의 레벨 및 기설정된 인센티브 지급기준을 참