flowchart TD
    A[타깃 메모리 영역에 저장된 타깃 데이터에 에러 발생 여부 판단] --> B[타깃 데이터에 에러 발생 시 전원 제어기의 동작 파라미터를 제1 동작 파라미터로 설정]
    B --> C[전원 소스로부터 공급되는 전원의 크기를 제1 파워 레벨에서 제2 파워 레벨로 변경]
    D[전원 제어기] --> E[메모리 컨트롤러]
    F[체크섬에 에러 발생 시 타깃 데이터에 에러 발생 판단] --> E
    G[제1 동작 파라미터에 대한 토탈 데이터 라이트 사이즈에 따라 전원 제어기의 동작 파라미터 변경 여부 결정] --> E
    H[제1 동작 파라미터에 대한 토탈 데이터 라이트 사이즈가 제1 사이즈 미만 시 제2 동작 파라미터로 변경] --> E
    I[제1 동작 파라미터에 대한 토탈 데이터 라이트 사이즈를 히스토리 영역에 저장 여부 결정] --> E
    J[제1 동작 파라미터에 대한 토탈 데이터 라이트 사이즈가 제2 사이즈 이상 시 히스토리 영역에 정보 저장] --> E
    K[후보 동작 파라미터 전부에 대한 토탈 데이터 라이트 사이즈가 제1 사이즈 미만 시 최대인 후보 동작 파라미터로 설정] --> E