flowchart TD
    A[제1 객체를 제어하기 위한 제1 뉴럴 네트워크의 제1 파라미터들 식별] --> B[제1 객체와 제2 객체 사이의 상호 작용 관련 제2 뉴럴 네트워크의 제2 파라미터들 식별]
    B --> C[제1 뉴럴 네트워크를 이용하여 제1 객체를 최초 상태로부터 변경하는 동안 제1 정보 획득]
    C --> D[제2 파라미터들에 의해 나타나는 제2 뉴럴 네트워크에 제1 정보 입력하여 제2 정보 획득]
    D --> E[제1 파라미터들 또는 제2 파라미터들 중 적어도 하나를 조정]