flowchart TD
    A[문서이미지로부터 텍스트 추출] --> B[키-밸류쌍 생성]
    B --> C[출력항목에 대응하는 키-밸류쌍 추출]
    C --> D[강조객체 추가하여 제1 이미지 생성]
    D --> E[제1 이미지 디스플레이]
    E --> F[키-밸류쌍 테이블 생성 및 디스플레이]
    F --> G[키-밸류쌍 누적]
    C --> H[출력항목에 대응하는 키-밸류쌍 검색]
    H --> I[유사매핑DB 이용하여 키값 검색]
    A --> J[출력항목 추가 또는 삭제 입력 수신]
    J --> K[출력항목 설정]
    F --> L[테이블을 파일형태로 생성]
    E --> M[썸네일 이미지 표시]
    M --> N[선택된 썸네일 이미지에 대응하는 문서 이미지 표시]