flowchart TD
    A[모바일 경조사 초대장에 기록된 경조사 웹 페이지의 URL에 접속] --> B[경조사비 수급자 선택]
    B --> C[해당 경조사비 수급자가 지정한 계좌로 경조사비 모바일 결제처리]
    A2[모바일 경조사 초대장에 기록된 QR 코드 인식] --> B2[경조사비 수급자 식별]
    B2 --> C2[입금계좌 및 전자 방명록 표시]
    C2 --> D2[경조사비 입금 완료 시 식권 및 답례품 출력]
    A3[사용자 단말로 경조사 웹 페이지의 URL 및 QR 코드 전송] --> B3[URL의 웹 페이지 및 키오스크 단말에서 경조사비 결제수단 제공]
    B3 --> C3[입금정보, 방명록 정보 및 답례품 출력정보 제공]
    A4[경조사 웹 페이지에서 결제 인터페이스 제공] --> B4[신용카드, 계좌이체로 경조사비 결제]
    B4 --> C4[결제 완료 시 식권 및 답례품 교환 QR 코드 발급]
    C4 --> D4[결제 완료 시 방명록 정보 제공]
    A5[결제선택 인터페이스 지원] --> B5[분할결제 참여 구성원 명 기입 기능 지원]
    A6[관리서버 구성] --> B6[키오스크 관리부, 모바일 결제처리부, 웹 페이지 관리부 및 QR 코드 발급부 포함]
    A7[키오스크 관리부 기능] --> B7[키오스크 동작상태 관리]
    B7 --> C7[결제한 경조사비 지급자 및 결제내역 관리]
    C7 --> D7[현금인출 내역 및 잔여 현금보유량 관리]
    A8[모바일 결제처리부 기능] --> B8[신용카드 결제 요청 시 절차정보 안내]
    B8 --> C8[신용카드 결제정보 PG사 서버 제공]
    C8 --> D8[결제내역 및 소득공제 승인