flowchart TD
    A[유전자 온톨로지 정보에 기초하여 생성된 신경망 모델을 학습하는 단계] --> B[상기 신경망 모델에 기초하여 유전자 정보를 분석하는 단계]
    B --> C[상기 복수의 노드들이 상기 유전자 온톨로지 용어들간의 관계에 관련된 가중치로 연결되는 단계]
    C --> D[상기 신경망 모델의 출력층으로부터 역전파된 복수개의 가중치들을 분석하여 상대적으로 중요한 노드들을 결정하는 단계]
    A --> E[분석 대상 데이터와 연관된 유전자 데이터베이스를 기초로 상기 신경망 모델을 사전 학습하는 단계]
    E --> F[상기 분석 대상 데이터를 활용하여 상기 사전 학습이 완료된 신경망 모델을 추가 학습하는 단계]
    F --> G[상기 유전자 데이터베이스로부터 추출된 표적암의 RNA 염기서열을 기초로 상기 신경망 모델을 학습하는 단계]