flowchart TD
    A[제1 도메인 스타일의 이미지 데이터 및 제2 도메인 스타일의 이미지 데이터 획득] --> B[제1 도메인 스타일 및 제2 도메인 스타일 이미지 데이터 기반 GAN 모델 학습]
    B --> C[이미지 데이터 생성 모델 생성자]
    B --> D[이미지 데이터 생성 모델 판별자]
    C --> E[인코더 및 디코더로 구성된 생성자]
    E --> F[저주파 성분 추출부]
    F --> G[특징맵 전달]
    C --> H[고주파 성분 추출부]
    H --> I[고주파 성분 전송]
    J[제1 도메인 스타일 이미지 데이터는 버추얼 스타일, 제2 도메인 스타일 이미지 데이터는 실사 스타일]
    K[전처리 수행]
    L[Basic GAN, Cycle GAN, WGAN, WGAN-GP, SRGAN, InfoGAN 중 하나에 기반하여 학습]