flowchart TD
    A[프로그램가능한 IC의 메모리 어드레스 공간의 어드레스들의 제1 서브세트가 상기 프로그램가능한 IC의 물리적 메모리에 연관되게, 상기 프로그램가능한 IC의 메모리 맵을 구성하는 단계] --> B[상기 메모리 어드레스 공간의 어드레스들의 제2 서브세트가 가상 메모리 블록에 연관되게 상기 메모리 맵을 구성하는 단계]
    B --> C[상기 가상 메모리 블록을 상기 프로그램가능한 로직 서브시스템의 프로그램가능한 로직 회로 내의 회로로서 구현하는 단계]
    C --> D[상기 프로그램가능한 IC의 상기 프로세서 서브시스템 내의 제2-레벨 캐시의 적어도 일 부분을 상기 어드레스들의 제2 서브세트에 대해 락킹하는 단계]
    D --> E[상기 어드레스들의 제2 서브세트 내의 어드레스를 참조하는 상기 프로세서 서브시스템의 프로세서 코어로부터의 메모리 액세스 요청에 대한 응답으로 상기 제2-레벨 캐시의 락킹된 부분에 액세스하는 단계]
    E --> F[상기 제2-레벨 캐시의 락킹된 부분에 대한 업데이트들을 위해 상기 물리적 메모리의 업데이트를 바이패싱하는 단계를 포함하는 방법]