flowchart TD
    A[태그 정보를 수신하여 데이터베이스 업데이트] --> B[특정 키워드를 갖는 태그 정보 획득]
    B --> C[검색 결과를 터치 디스플레이에 표시]
    C --> D[적어도 두가지 타입의 콘텐츠에 대한 선택 정보 수신]
    D --> E[선택된 콘텐츠에 대한 액션 정보 수신]
    E --> F[선택된 콘텐츠들을 그룹화]
    F --> G[그룹화된 콘텐츠를 다른 전자 장치에 전송]
    G --> H[URI를 가공하고, 공유, 삭제 및 압축 중 적어도 하나의 액션 수행]