flowchart TD
    A[제1 이미지에 액세스하는 단계] --> B[제1 이미지 처리하여 렌즈 결함 분석하는 단계]
    B --> C[클래스 활성화 맵(CAM) 생성하는 단계]
    C --> D[라벨링된 CAM 출력하는 단계]
    D --> E[제1 이미지에 대한 분류 생성하고 출력하는 단계]
    E --> F[제2 이미지에 액세스하는 단계]
    F --> G[제2 이미지 처리하여 렌즈 결함 분석하는 단계]
    G --> H[클래스 활성화 맵(CAM) 생성하는 단계]
    H --> I[라벨링된 CAM 출력하는 단계]
    I --> J[제2 이미지에 대한 분류 생성하고 출력하는 단계]