flowchart TD
    A[렌터카 대여] --> B[렌터카 검색 및 선택]
    B --> C[렌터카 예약]
    C --> D[렌터카 정보 제공]
    D --> E[관리서버 정보 관리]
    E --> F[예약관리부 관리]
    E --> G[계약관리부 관리]
    E --> H[대차관리부 관리]
    E --> I[매출관리부 관리]
    E --> J[차량관리부 관리]
    F --> K[예약정보 수신]
    F --> L[예약정보 저장]
    F --> M[차량정보 갱신]
    F --> N[차량정보 수정]
    G --> O[예약정보 감지]
    G --> P[계약정보 생성]
    G --> Q[계약정보 전송]
    G --> R[계약정보 승인]
    G --> S[차량정보 매핑]
    H --> T[개시정보 수신]
    H --> U[개시영상 저장]
    H --> V[반납정보 수신]
    H --> W[반납영상 저장]
    H --> X[영상 비교]
    H --> Y[손상 검출]