flowchart TD
    S1[소정의 제1 신경망에 따라 NAS 네트워크 모델을 검색하는 단계] --> S2[트레이닝 세트를 이용하여 제1 표적 검출 모델을 트레이닝하며, 트레이닝 횟수가 제1 소정 횟수에 도달하면, 검증 세트를 이용하여 현재의 제1 표적 검출 모델을 평가하고, 평가 결과를 출력하는 단계]
    S2 --> S3[상기 현재 제1 표적 검출 모델에 대응하는 표적 검출 태스크 리워드(reward)를 계산하는 단계]
    S3 --> S4[상기 표적 검출 태스크 리워드에 따라 상기 NAS 네트워크 모델 검색에 사용되는 파라미터를 조정하는 단계]
    S1 --> S11[미리 구성된 하이퍼파라미터에 따라 순환 신경망 컨트롤러를 통해 서브네트워크 구조 코드를 샘플링하여 획득하는 단계]
    S11 --> S12[디코더를 통해 상기 서브네트워크 구조 코드를 디코딩하고, NAS 네트워크 모델을 출력하는 단계]
    S4 --> S4_1[상기 리워드를 상기 순환 신경망 컨트롤러에 피드백하는 단계]
    S4_1 --> S4_2[상기 순환 신경망 컨트롤러의 트레이닝 가능 파라미터를 업데이트하는 단계]
    S1 --> S5[상기 S1 내지 S4 단계를 제2 소정의 횟수만큼 반복하고, 상기 평가 결과에 따라 최적의 제1 표적 검출 모델을 결정하고]