flowchart TD
    A[물품의 다중 프레임 이미지 획득] --> B[프레임 이미지에서 위치 정보 및 카테고리 정보 획득]
    B --> C[물품의 보조 정보 획득]
    C --> D[위치 정보와 보조 정보 멀티 모달 융합]
    D --> E[카테고리 정보와 융합 결과에 따라 식별 결과 확정]
    A1[목표 부위의 다중 프레임 이미지 획득] --> B1[프레임 이미지 전처리]
    B1 --> C1[부위 관심 영역 선택]
    C1 --> D1[부위 특징 추출]
    D1 --> E1[복수의 부위 특징 식별]
    B --> F[각 프레임 이미지에 대해 이미지 전처리 진행]
    F --> G[물품 검측 박스 및 카테고리 정보 확정]
    G --> H[물품의 위치 정보 확정]
    E1 --> I[비 최대치 억제 진행]
    E --> J[위치 정보 및 판별 결과에 따라 식별 결과 확정]
    C1 --> K[서브 윈도에 의해 부위 관심 영역 확정]
    E --> L[세립도 분류 진행]