flowchart TD
    A[키워드에 일련의 문자를 상이하게 추가] --> B[기본 검색어 자동 생성]
    B --> C[미리 설정된 검색 엔진을 통해 연관 검색어 획득]
    C --> D[연관 검색어를 입력 검색어로 적용]
    D --> E[검색 결과 리스트 정보를 기초로 검색 의도 파악]
    E --> F[응답 기능별 기능 종류와 응답 결과에서 후속 검색어 추출]
    F --> G[후속 검색어의 노출 순위 및 가중치 산출]
    G --> H[입력 검색어와 후속 검색어 사이의 관계 정보 생성]
    H --> I[검색어 관계 DB에 저장]
    I --> J[복수의 검색어를 노드로 설정하여 방향 가중 그래프 생성]
    J --> K[시작 노드와 종료 노드 사이의 검색 경로 정보 생성]
    K --> L[검색 경로 정보와 통계 정보를 매칭하여 저장]
    L --> M[사용자 단말로 요청 검색어 및 랭킹 조건 수신]
    M --> N[추천 리스트 정보 생성 및 제공]