flowchart TD
    A[학습 단계] --> B[자바스크립트를 동적으로 실행하여 제1 호출 시퀀스 추출]
    B --> C[제1 호출 시퀀스로부터 제1 특징 벡터 추출]
    C --> D[제1 특징 벡터를 이용하여 분류기 모델 학습]
    A --> E[분석 단계]
    E --> F[자바스크립트를 동적으로 실행하여 제2 호출 시퀀스 추출]
    F --> G[제2 호출 시퀀스로부터 제2 특징 벡터 추출]
    G --> H[학습된 분류기 모델로 악성 스크립트 포함 여부 결정]