flowchart TD
    A[사용자 단말로부터, 제1 문서에 관한 문서 작성 요청을 수신하는 단계] --> B[상기 문서 작성 요청으로부터 상기 제1 문서와 관련된 검색 대상을 획득하는 단계]
    B --> C[복수의 리소스가 기 저장된 지식 베이스에 대하여, 상기 검색 대상을 검색하는 단계]
    C --> D[상기 검색의 결과를 이용하여, 상기 지식 베이스에 저장된 리소스에 관한 문서 전처리 데이터를 획득하는 단계]
    D --> E[상기 문서 전처리 데이터 및 상기 문서 작성 요청을 기 학습된 대규모 언어 모델에 입력하고, 상기 제1 문서에 대한 초안 컨텐츠를 생성하는 단계]
    B --> F[상기 문서 작성 요청을 벡터화하고, 요청 임베딩 벡터를 생성하는 단계]
    F --> G[기 정의된 분류 모델을 이용하여, 상기 요청 임베딩 벡터를 기 정의된 카테고리 별로 분류하는 단계]
    G --> H[상기 요청 임베딩 벡터의 구성 요소를 상기 문서 작성 요청에 대응되는 문서 행위, 문서 목적 및 참조 대상 리소스 중 적어도 하나 이상으로 분류하는 모델]
    G --> I[상기 문서 행위, 상기 문서 목적 및 상기 참조 대상 리소스를 구조화하는 단계]
    C --> J[상기 제2 데이터베이스로부터, 상기 검색 대상에 포함된 카테고리에 대응되는 값과 일치하는 키워드가 존재하는 제1 리소스를 획득하는 단계]
    C --> K[상기 제3 데이터베이스로부터, 상기 검색 대상에 포함된 카테고리에 대응되는 임베딩 벡터와 유사도가 기준치 이상인 벡터가 존재하는 제2 리소스를 획득하는 단계]
    J --> L[상기 제1 리소스 및 상기 제2 리소스에 대하여 상기 문서 작성 요청을 매핑하여 복수의 후보 쌍을 생성하는 단계]
    L --> M[상기 복수