flowchart TD
    A[메인서버에 저장된 철골 구조물의 CAD데이터 및 BOM데이터로부터 부재에 마킹할 코드 추출] --> B[추출된 코드가 마킹기에 송신]
    B --> C[마킹기가 수신된 코드를 부재 표면을 타각 방식으로 마킹]
    C --> D[제1 영상수집장치에 의해 부재의 영상데이터 촬영]
    D --> E[촬영된 영상데이터가 메인서버에 업로드]
    E --> F[영상데이터가 인공지능 기반의 코드인식부에 입력]
    F --> G[코드인식부가 영상데이터로부터 부재에 마킹된 코드 인식]
    G --> H[인식된 코드를 메인서버에 등록]
    H --> I[제2 영상수집장치에 의해 부재의 영상데이터 촬영]
    I --> J[촬영된 영상데이터가 메인서버에 업로드]
    J --> K[영상데이터가 인공지능 기반의 코드인식부에 입력]
    K --> L[코드인식부가 영상데이터로부터 부재에 마킹된 코드 인식]
    L --> M[인식된 코드를 제2 영상수집장치의 식별명과 함께 메인서버에 갱신]