flowchart TD
    A[셀 상자 제거] --> B[셀 상자 확장]
    B --> C[행 및 열 수 결정]
    C --> D[정렬 결정]
    D --> E[K-평균 클러스터링 사용]
    E --> F[셀 박스 할당]
    
    subgraph 추가 단계
        G[이웃하는 빈 셀과 중첩 결정] --> H[셀 확장]
        I[이웃하는 빈 셀로 멀티-텍스트 라인 셀 분할]
        J[분할된 셀로부터 텍스트 재-할당]
        K[셀 상자 확장 순서 결정]
    end

    B --> G
    B --> I
    I --> J
    B --> K