flowchart TD
    A[키워드에 매칭되는 랜딩 페이지 타입을 제1 랜딩 페이지로 설정] --> B[키워드가 키워드 세트에 대응하는지 확인]
    B --> C{키워드 세트에 대응할 경우}
    C -->|예| D[랜딩 페이지 타입을 제1 랜딩 페이지에서 제2 랜딩 페이지로 변경]
    D --> E[변경된 제2 랜딩 페이지에 대응하는 검색 건수 확인]
    E --> F[검색 건수에 기초하여 키워드와 관련된 정보 변경]
    F --> G[변경된 정보를 검색 엔진에 제공]
    C -->|아니오| H[기 설정된 조건에 기초하여 검색 건수 조회 여부 결정]
    H --> I{검색 건수 조회할 경우}
    I -->|예| J[검색 건수에 기초하여 데이터 세트와 관련된 정보 업데이트]
    J --> K{검색 건수가 0건인 경우}
    K -->|예| L[블랙 리스트 및 품절 여부 확인하여 랜딩 페이지 타입 및 키워드 상태 업데이트]
    K -->|아니오| M[업데이트 종료]