flowchart TD
    A[제1 페이지를 표시하는 단계] --> B[기설정된 터치 입력 감지]
    B --> C[복수의 프리뷰 페이지를 포함하는 프리뷰 UI 및 제1 페이지 표시]
    C --> D[제2 터치 입력 감지]
    D --> E[필기 컨텐츠를 제1 페이지에 삽입하여 수정하는 단계]
    E --> F[제1 프리뷰 페이지에 핀치-아웃 터치 감지 시 줌-인]
    E --> G[제1 프리뷰 페이지에 핀치-인 터치 감지 시 줌-아웃]
    F --> H[제2 페이지에 대응되는 제2 프리뷰 페이지에 터치 입력 감지]
    H --> I[제2 프리뷰 페이지의 컨텐츠 수정]
    I --> J[수정된 컨텐츠를 포함하는 제2 페이지 저장]
    J --> K[제2 페이지로 전환하기 위한 터치 입력 감지]
    K --> L[수정된 컨텐츠를 포함하는 제2 페이지 표시]
    E --> M[편집 툴 UI에 포함된 아이콘 선택 후 터치 입력 감지]
    M --> N[선택된 아이콘에 따라 프리뷰 페이지의 컨텐츠 수정]
    E --> O[제1 페이지 상의 컨텐츠 수정 시 제1 프리뷰 페이지의 컨텐츠 수정]
    E --> P[프리뷰 UI의 일 지점을 기설정된 시간동안 터치 후 드래그]
    P --> Q[드래그 방향에 따라 프리뷰 UI 드래그]
    M --> R[프리뷰 UI 생성 아이콘 선택 시 프리뷰 UI 표시]
    E --> S[복수의 프리뷰 페이지 중 하나에 터치 입력 감지 및 제1 페이지에 다른 터치 입력 감지]
    S --> T[프리뷰 페이지의 컨텐츠 수정 및 제1 페이지 및 제1 프리뷰 페이지의 컨텐츠 수정]