flowchart TD
    A[사용자에 의해 업로드된 컨텐츠를 제1 인공지능(AI) 모델에 입력하여 감정 정보 획득] --> B[제1 유해 스코어 및 제2 유해 스코어에 기초하여 유해 지수 산출]
    B --> C[유해 지수가 임계값을 초과함에 기초하여 컨텐츠 필터링]
    A1[제1 AI 모델은 얼굴 특징점 또는 음성에 대한 특징 데이터에 기초하여 감정 정보 출력] --> A
    A2[제1 AI 모델은 컨볼루션 레이어, LSTM 레이어, 소프트 맥스 레이어 포함] --> A1
    A3[컨텐츠가 컨볼루션 레이어에 입력되어 얼굴 특징점 추출] --> A2
    A4[특징점이 LSTM 레이어에 입력되어 중간 데이터 추출] --> A3
    A5[중간 데이터가 소프트 맥스 레이어에 입력되어 제1 예측 데이터 추출] --> A4
    A6[컨텐츠가 컨볼루션 레이어에 입력되어 음성에 대한 특징 데이터 추출] --> A5
    A7[특징 데이터가 LSTM 레이어에 입력되어 제2 예측 데이터 추출] --> A6
    B1[제1 예측 데이터 및 제2 예측 데이터를 제2 AI 모델에 입력하여 제1 유해 스코어 획득] --> B
    B2[제1 유해 스코어에 제1 가중치 적용한 값과 제2 유해 스코어에 제2 가중치 적용한 값 합산하여 유해 지수 산출] --> B1
    B3[제1 가중치 및 제2 가중치는 감정 우선순위에 기초하여 결정] --> B2
    B4[제2 AI 모델은 제1 예측 데이터에 포함된 감정에 매칭되는 제1 유해 값 산출] --> B3
    B5[제2 예측 데이터에 포함된 감정에 매칭되는 제2 유해 값 산출] --> B4
    B6[제1 유해 값 및 제2 유해 값에 대해 서로 다른 가중치 적용하여