flowchart TD
    A[사용자의 피부 이미지를 수신하는 단계] --> B[사용자의 피부 측정 데이터를 수신하는 단계]
    B --> C[피부 이미지를 제1 모델에 입력하여 제1 소속도 계산하는 단계]
    C --> D[피부 측정 데이터를 제2 모델에 입력하여 제2 소속도 계산하는 단계]
    D --> E[제1 소속도 및 제2 소속도에 대한 앙상블 가중치를 적용하여 최종 소속도 결정하는 단계]
    E --> F[최종 소속도에 기초하여 맞춤형 처방 데이터 결정하는 단계]
    F --> G[최종 소속도를 복수의 퍼지 로직 모듈에 적용하여 점수 계산하는 단계]
    G --> H[복수의 피부 데이터 점수에 기초하여 맞춤형 처방 데이터 결정하는 단계]
    E --> I[제1 소속도 및 제2 소속도에 대한 앙상블 가중치 결정하는 단계]
    I --> J[제1 소속 함수에 제1 소속도 입력하여 제1 무게중심 계산하는 단계]
    J --> K[제1 소속 함수에 제2 소속도 입력하여 제2 무게중심 계산하는 단계]
    K --> L[제1 소속 함수의 중심점으로부터 제1 무게중심까지의 제1 거리 계산하는 단계]
    L --> M[제1 소속 함수의 중심점으로부터 제2 무게중심까지의 제2 거리 계산하는 단계]
    M --> N[제1 거리 및 제2 거리의 비율에 따라 앙상블 가중치 결정하는 단계]
    F --> O[사용자의 나이, 성별 및 과거 시술 이력 중 적어도 하나를 포함하는 개인 정보 데이터 수신하는 단계]
    O --> P[개인 정보 데이터에 기초하여 맞춤형 처방 데이터 조정하는 단계]
    F --> Q[사용자에 사용될 기기 데이터, 레이저 파장 데이터, 시술 시간 데이터, 강도 데이터 및 주기 데이터 중 적어도 하나를 포함하는 맞춤형 처방 데이터]