flowchart TD
    A[디스플레이부 표시] --> B[사용자입력부로부터 제1사용자입력 수신]
    B --> C[제1로드파일 또는 제2로드파일 표시]
    C --> D[사용자입력부로부터 제2사용자입력 수신]
    D --> E[기준 데이터 크롤링 및 다운로드]
    E --> F[복수의 기준항목 식별]
    F --> G[복수의 카테고리로 분류]
    G --> H[도면데이터 식별]
    H --> I[체크리스트 생성]
    I --> J[제1개체 또는 제1객체 표시]