flowchart TD
    A[회원 DB(11) 저장] --> B[운동량 산출 모듈(12) 운동정보 수집]
    B --> C[운동량 산출]
    A --> D[커뮤니티 모듈(13) 운동 메이트 형성]
    D --> E[커뮤니티 생성부(13a) 게시판, 채팅창, 그룹방 생성]
    D --> F[가입 관리부(13b) 운동 종목 및 레벨 입력]
    D --> G[커뮤니티 검색부(13c) 조건 검색]
    D --> H[공동목표 관리부(13d) 공동목표 설정]
    D --> I[대화 관리부(13e) 채팅방 관리]
    A --> J[스케쥴 관리 모듈(14) 운동실 사용 스케쥴 관리]
    A --> K[동기부여 모듈(15) 보상 제공]
    K --> L[보상 관리부(15a) 운동 진행 상황 비교]
    K --> M[랭킹 관리부(15b) 그룹 내 랭킹 설정]
    K --> N[비용회수 관리부(15c) 회수 금액 통지]
    A --> O[카페테리아 모듈(16) 음식 제공 관리]
    O --> P[음식 추천부(16a) 맞춤형 음식 추천]
    O --> Q[스마트 주문부(16b) 주문 예약 처리]
    O --> R[카페테리아 예약 관리부(14c) 룸 예약 관리]