flowchart TD
    A[사용자 입력에 기반하여 식물에 대한 입력 수신] --> B[식물 데이터베이스 참조하여 정보 검색]
    B --> C[사용자의 공간 정보 및 식물 선호도 입력 받기]
    C --> D[인공지능 기반으로 식물 추천]
    D --> E[추천된 식물에 대한 구매 여부 가이드 표시]
    E --> F[추천된 식물 구매 결정 시 판매자에게 입찰 제안 전송]
    F --> G[판매자 단말의 응답에 기반하여 낙찰 여부 결정]
    G --> H[낙찰된 경우 사용자 주소 정보 배송 업체에 전송]
    H --> I[사용자로부터 식물 이미지 또는 정보 입력 받기]
    I --> J[입력 받은 정보 기반으로 식물 종 및 상태 식별]
    J --> K[식물의 희망 판매 가격 설정]
    K --> L[사용자 단말의 GPS로 식물 위치 정보 획득]
    L --> M[위치 정보를 기반으로 판매 정보 전송]
    M --> N[판매 정보 수신한 사용자 단말로부터 입찰 정보 수신]
    N --> O[입찰 정보를 기반으로 최고 입찰가 결정]
    O --> P[최고 입찰가 제시한 사용자에게 구매 권리 부여]
    P --> Q[구매 권리 부여받은 사용자 단말의 위치 정보 획득]
    Q --> R[위치 정보를 기반으로 식물 배송]
    R --> S[구매된 식물의 배송 일정 및 상태 정보 제공]
    S --> T[배송 완료 응답 수신 후 생육 관리 정보 제공]
    T --> U[배송 완료된 식물 상태 실시간 전송받아 분석]
    U --> V[전문가 단말에서 상태 및 종류 분석하여 상담 기능 제공]
    V --> W[식물 이미지 분석 및 질병 발생 가능성 예측]
    W --> X[식물 관리 정보 공유 및 커뮤니티 기능 제공]
    X --> Y[제 1 소비자 단말의 구매 정보 및 후기 업로드]
    Y --> Z[구매 정보 및 후기에 대응하는 식물 결정]
    Z --> AA[구매 이력 또는 관심 식물 지정된 소비자 단말에 정보 전송]
    AA