flowchart TD
    A[데이터 생성단계] --> B[온도변화 학습단계]
    B --> C[온도변화 예측단계]
    
    A --> A1[입력 시계열특성 추출과정]
    A --> A2[오토인코더 학습과정]
    A --> A3[분류모델 학습과정]
    A --> A4[생성기-복구함수 결합과정]
    
    B --> B1[제1과정]
    B --> B2[제2과정]
    
    C --> C1[제1과정]
    C --> C2[제2과정]
    C --> C3[마지막 출력값 예측]