flowchart TD
    A[예비 트레이닝을 완료한 중간 검출 모델에서 배치 정규화 레이어의 다수의 스케일링 계수를 획득하는 단계] --> B[상기 중간 검출 모델의 다수의 컨볼루션 레이어로부터 프루닝 가능한 컨볼루션 레이어를 선별하는 단계]
    B --> C[다수의 상기 스케일링 계수로부터 상기 프루닝 가능한 컨볼루션 레이어와 대응되는 스케일링 계수를 선별하는 단계]
    C --> D[다수의 상기 스케일링 계수의 수치 크기에 따라, 다수의 상기 스케일링 계수로부터 프루닝할 계수를 선별하는 단계]
    D --> E[상기 중간 검출 모델의 다수의 컨볼루션 레이어의 다수의 채널로부터, 다수의 상기 프루닝할 계수 중의 현재 프루닝 계수와 대응되는 현재 컨볼루션 레이어의 출력 채널 및 상기 현재 컨볼루션 레이어의 다음 컨볼루션 레이어의 입력 채널을 선별하고, 상기 출력 채널과 상기 입력 채널을 프루닝할 채널로 하며, 상기 프루닝할 채널에 대해 채널 프루닝을 수행하여 오브젝트 검출 모델을 생성하는 단계]