flowchart TD
    A[비지니스 시스템으로부터 표준 작업 정의서 수신] --> B[실행 관리부의 데이터 수집 요청 수신]
    B --> C[전처리 데이터 수집 요청에 따라 전처리 데이터 수집 및 밸류 레포지토리에 저장]
    C --> D[프로파일별 데이터 수집을 위한 수집모듈 실행 개시]
    D --> E[밸류 레포지토리를 기초로 수집된 데이터 통합 및 저장]
    D --> F[전처리 데이터 수집 요청과 함께 입력 파라미터 정보 전달]
    E --> G[선행 관계에 있는 수집모듈 존재 시 신규 표준 작업 정의서 생성 및 재요청]