flowchart TD
    A[데이터 파일 입력받기] --> B[무결성 검증 데이터 생성]
    B --> C[삭제 검증 정보 생성]
    C --> D[무결성 검증 파일 생성]
    D --> E[무결성 검증 파일 저장]
    E --> F[타겟 데이터 파일 선택]
    F --> G[삭제 검증 정보 추출]
    G --> H[삭제 검증 정보 비교]
    H --> I[불일치 시 삭제 검출]