flowchart TD
    A[응용 프로그램 설치] --> B[결제 정보 전송 및 대기]
    B --> C[조회 신호 반복 전송]
    C --> D[결제 승인 신호 수신]
    D --> E[결제 대기 상태 종료 및 완료 신호 출력]
    D --> F[결제 승인 신호 미도달]
    F --> G[조회 신호 응답 확인]
    G -->|응답 확인| H[가상 결제 승인 신호 전달]
    H --> I[결제 대기 상태 종료 및 완료 신호 출력]
    G -->|응답 미확인| J[관리자 확인 요청 메신저 출력]