flowchart TD
    A[플랫폼 서버에서 판매자와 소비자 간의 거래 상황을 경영정보관리시스템으로 관리하는 단계] --> B[플랫폼 서버에서 소비자의 구매 확정이 되는 경우, 소비자의 거래 사실 및 거래 품목을 특정하는 단계]
    B --> C[플랫폼 서버는 특정된 품목에 대한 SCM 코드를 생성하여 소비자에게 제공하는 단계]
    C --> D[플랫폼 서버는 소비자가 SCM 코드를 이용하여 생성한 리뷰 NFT와 제3 소비자의 경로를 생성하는 단계]
    
    A1[플랫폼 서버에서 판매자와 소비자 간의 거래 상황을 경영정보관리시스템으로 관리하는 단계] --> E[외부 플랫폼에 고객의 주문 결제 정보를 요청하여 수신하는 단계]
    E --> F[수신한 주문 결제 정보를 바탕으로 판매자와 소비자 간의 거래를 확인하는 단계]

    A2[플랫폼 서버에서 판매자와 소비자 간의 거래 상황을 경영정보관리시스템으로 관리하는 단계] --> G[소비자의 영수증 정보를 플랫폼 서버에서 수집하는 단계]
    G --> H[수집한 영수증 정보를 바탕으로 판매자에게 판매 정보를 요청하는 단계]
    H --> I[수신한 판매 정보를 바탕으로 거래 상황을 관리하는 단계]

    D --> J[제3 소비자와 판매자 간의 거래를 리뷰 NFT의 블록체인 노드에서 수행하는 단계]

    J --> K[리뷰 NFT의 블록체인 노드에서 스마트 컨트랙트에 의해 거래를 검증하는 단계]

    L[플랫폼 서버는 생성된 리뷰 NFT에 대응되는 거래가 취소되는 경우 생성된 경로를 차단하는 단계] 

    M[플랫폼 서버에서 소셜 네트워크를 통해 거래 대상 제품에 대한 검색 요청을 수신하는 단계] --> N[플랫폼 서버에서 거래 대상 제품에 대한 리뷰 NFT를 로딩하는 단계]
    N --> O[플랫폼 서버에서 상기 리뷰 NFT의 거래 대상 제품 SCM 코드와 동일한 SCM 코드를 가지는 거래 대상 제품을 제공하는 복수의 판매자와 상기 리뷰 NFT간에 경로를 생성하는 단계]
    O --> P[플랫폼 서버에서 제3 소비자가 리뷰 NFT에 접속하면 경로