flowchart TD
    A[선박의 현재 위치에 기초하여 장애물 지도 획득] --> B[장애물 지도에 복수의 단위 노드 포함]
    B --> C[각 단위 노드에 지형 가중치 할당]
    A --> D[주변 장애물 감지 장치 통해 장애물 위치 및 이동정보 획득]
    D --> E[장애물 지도 업데이트]
    E --> F[장애물 위치에 대응되는 단위 노드 선택]
    F --> G[장애물 주변 위치에 대응되는 단위 노드 선택]
    G --> H[장애물 단위 노드에 장애물 가중치 할당]
    H --> I[장애물 가중치 결정]
    D --> J[카메라를 통해 이미지 획득]
    J --> K[이미지를 인공신경망에 입력하여 장애물 종류 및 거리 획득]
    E --> L[업데이트된 장애물 지도에 기초하여 선박 경로 생성]
    L --> M[생성된 경로에 기초하여 제어신호 생성]