flowchart TD
    A[기부 시작버튼 선택 받는 단계] --> B[기부방식 선택화면 디스플레이하는 단계]
    B --> C[금액 입력 화면 디스플레이하는 단계]
    C --> D[기부 금액 입력됨에 따라 체크하는 화면 디스플레이하는 단계]
    D --> E[사용자의 이름 입력받는 단계]
    E --> F[사용자의 사진 촬상하는 단계]
    F --> G[기부자 정보 등록하는 단계]
    G --> H[기부할 학과 또는 프로젝트명 선택받는 단계]
    H --> I[복수의 기부자 명단 디스플레이하는 단계]