flowchart TD
    A[기계어 명령을 프로세서에 의해 획득하는 단계] --> B[기계어 명령 실행하는 단계]
    B --> C[제1 오퍼랜드를 제2 오퍼랜드에 의해 명시된 위치에 비트랜잭션적으로 배치하는 단계]
    C --> D[비트랜잭션적으로 배치하는 단계는 프로세서의 트랜잭션 실행 모드가 종료될 때까지 지연되는 단계]
    A1[트랜잭션 실행 모드의 종료는 최외부 트랜잭션의 종료 또는 중단 조건으로부터 기인하는 단계]
    A2[프로세서가 트랜잭션 실행 모드에 있는지를 판정하는 단계] --> A3[트랜잭션이 제약 트랜잭션인지 또는 비제약 트랜잭션인지를 판정하는 단계]
    A3 --> A4[비제약 트랜잭션인 것에 기초하여 기계어 명령의 실행을 계속하는 단계]
    A5[제약 트랜잭션인 것에 기초하여 프로그램 예외를 제공하고 기계어 명령의 실행을 종결시키는 단계]
    A6[프로세서가 트랜잭션 실행 모드에 있지 않는 것에 기초하여 기계어 명령을 저장 명령으로서 실행하는 단계]
    A7[제2 오퍼랜드는 기계어 명령의 인덱스 필드에 의해 명시된 레지스터의 콘텐츠와 베이스 필드에 의해 명시된 레지스터의 콘텐츠, 및 적어도 하나의 변위 필드의 콘텐츠의 조합으로부터 형성되는 단계]
    A8[트랜잭션 시작 명령의 실행에 기초하여 트랜잭션을 개시하는 단계] --> A9[트랜잭션 종료 명령을 실행하는 것에 기초하여 트랜잭션 저장들을 메인 메모리에 커밋하는 단계]
    A9 --> A10[트랜잭션 종료하는 중단에 기초하여 트랜잭션 저장들을 폐기하는 단계]
    A10 --> A11[비트랜잭션적으로 배치하는