flowchart TD
    A[각각의 비디오 프레임의 글로벌 특성에 따라서, 복수의 비디오 프레임의 각각의 비디오 프레임 내의 복수의 스케일의 타깃 사전 예상 위치를 획득하는 단계] --> B[상기 각각의 비디오 프레임 내의 타깃 사전 예상 위치를 수집해서 하나 이상의 타깃 후보 영역을 획득하는 단계]
    B --> C[상기 하나 이상의 타깃 후보 영역의 신뢰도 레벨 및 대응하는 스케일 처리와 조합해서, 각각의 비디오 프레임 내의 상기 하나 이상의 타깃 후보 영역 모두에 따라서, 각각의 비디오 프레임 내의 타깃 실제 영역을 판정하는 단계]
    C --> D[각각의 비디오 프레임의 모든 스케일의 상기 하나 이상의 타깃 후보 영역에 대해서 영역 트리 구조를 큰 스케일부터 작은 스케일의 순서로 설정하는 단계]
    D --> E[각각의 비디오 프레임의 상기 영역 트리 구조 및 상기 하나 이상의 타깃 후보 영역의 신뢰도 레벨에 따라서 각각의 비디오 프레임의 상기 타깃 실제 영역을 획득하는 단계]
    C --> F[상기 복수의 비디오 프레임의 2개의 인접 시점에 있는 2개의 비디오 프레임들 내의 동일한 타깃 실제 영역을 비교해서 상기 타깃 실제 영역이 무효한지 판정하는 단계]
    A --> G[각각의 비디오 프레임에 대해서 크기 정규화를 수행하는 단계]
    A --> H[상기 글로벌 특성은 글로벌 그레이스케일 특성과, 글로벌 질감 특성과, 글로벌 색상 특성과, 글로벌 움직임 특성 중 하나 이상을 포함하는 단계]
    H --> I[각각의 비디오 프레임의 상기 글로벌 질감 특성을 가보르 행렬 혹은 캐니 연산자의 에지 검출 알고리즘을 이용해서 추출하는 단계]
    H --> J[각각의 비디오 프레임의 상기 글로벌 색상 특성을 추출하는 단계]
    J --> K[각각의