flowchart TD
    A[피지망 이용 이알피 비대면 결제 요청 채권회수시스템] --> B[결제플랫폼 서버와 연결]
    B --> C[카드결제 승인 수행]
    B --> D[정산출금 과정 제어]
    B --> E[약정결제 조건 준수 판단]
    E -->|약정결제 조건 준수| F[채권회수 진행]
    F --> G[URL 전송]
    G --> H[채무자 인증 결제 제안]
    E -->|약정결제 조건 미준수| I[비대면 채권추심 요청]
    A --> J[ERP 사용자 단말과 연결]
    J --> K[외상매출금 계정 데이터베이스]
    J --> L[ERP USER Master 정보 데이터베이스]
    B --> M[가맹점 Master 정보 데이터베이스]
    B --> N[카드결제 승인 데이터베이스]
    B --> O[정산출금 데이터베이스]
    B --> P[계좌인증/계좌상태 유효 인증 수행]
    A --> Q[대면 또는 비대면 결제앱 또는 웹 구비]
    Q --> R[프로그램 다운로드 방식 또는 SaaS 방식]