flowchart TD
    A[인증 부표의 특징 데이터를 획득하는 단계] --> B[스티로폼 부표 및 상기 인증 부표의 이미지 데이터를 획득하는 단계]
    B --> C[상기 특징 데이터 및 이미지 데이터에 기반하여 상기 인증 부표를 식별하는 인공지능 모델을 학습시키는 단계]
    C --> D[양식장을 촬영하여 제 1 양식장 이미지를 획득하는 단계]
    D --> E[상기 학습된 인공지능 모델에 상기 제 1 양식장 이미지를 입력하여 상기 양식장 내 인증 부표 및 스티로폼 부표를 식별하여 제 1 인증 부표 식별 정보를 생성하는 단계]
    E --> F[상기 제 1 인증 부표 식별 정보를 표시하는 단계]
    F --> G[상기 제 1 양식장 이미지를 획득한 이후, 상기 양식장을 재 촬영하여 제 2 양식장 이미지를 획득하는 단계]
    G --> H[상기 학습된 인공지능 모델에 상기 제 2 양식장 이미지를 입력하여 상기 양식장 내 인증 부표 및 스티로폼 부표를 식별하여 제 2 인증 부표 식별 정보를 생성하는 단계]
    H --> I[상기 제 1 인증 부표 식별 정보 및 상기 제 2 인증 부표 식별 정보를 비교하여 인증 부표의 변화량을 판단하는 단계]
    F --> J[상기 제 1 인증 부표 식별 정보에 기반하여 상기 인증 부표와 상기 스티로폼 부표의 비율을 나타내는 그래프를 표시하는 단계]