flowchart TD
    A[합성 저화질 영상을 입력받아 원본 고화질 영상과 유사한 위조 고화질 영상으로 변환] --> B[위조 고화질 영상과 원본 고화질 영상을 비교하여 진위 여부를 판별]
    B --> C[진위 여부에 따라 최소화해야 하는 손실(Loss)을 산출]
    C --> D[손실(Loss)을 최소화시키도록 인공 신경망 모델의 가중치를 조정하면서 학습]
    C --> E[미리 저장된 안면의 특징 영역에 대한 안면 특화(Facial Locality)를 사용한 손실을 추가하여 손실을 산출]