flowchart TD
    A[주류주문 입력받기] --> B[주류주문 접수]
    B --> C[결제정보 이용하여 결제요청]
    C --> D[중개자금 지급]
    D --> E[결제수수료 및 선정산이용수수료 결제]
    E --> F[주류배달 완료 후 보증금 후정산]
    F --> G[보증금 산출 및 이자 포함]
    G --> H[선정산이용수수료 조정]
    H --> I[피싱 계좌 확인 및 피드백]
    I --> J[복수 결제정보 등록 및 결제 시도]
    J --> K[결제수단 혜택정보 수신]
    K --> L[일괄 결제 시도]
    L --> M[실시간 자금중개 요청]
    M --> N[공병 및 박스 정보 전달받아 보증금 산정]
    N --> O[재고관리 수행]