flowchart TD
    A[AS 요청 메시지 확인] --> B[대리점단말 선정]
    B --> C[AS 정보 생성]
    C --> D[통합 관리 AS 스케줄 업데이트]
    D --> E[AS 현장 템플릿 제공]
    E --> F[유지 및 보수 정보 입력]
    F --> G[AS 비용 계산서 발행]
    G --> H[AS 비용 계산서 중계]
    H --> I[AS 이미지로 유지 및 보수 정보 자동 작성]
    I --> J[응답 메시지 자동 작성 및 전송]
    A --> K[대리점 필터링]
    K --> L[우선순위 결정]
    L --> M[AS 요청 메시지 전송]
    M --> N[AS 접수 신호 수신]
    N --> O[대리점단말 변경]
    L --> P[우선순위 결정(동일 순위)] 
    C --> Q[자동-응답 챗봇 서비스 제공]
    Q --> R[AS 가이드 콘텐츠 탐색]