flowchart TD
    A[본체프레임(100) 고정] --> B[디스플레이 패널(200) 장착]
    B --> C[제어유닛(300) 설치]
    C --> D[통신유닛(400) 설치]
    D --> E[사용자 조작신호정보 수신]
    E --> F[각 테이블(5) 별 출력 및 운용 제어]
    F --> G[관리자 단말기(2) 또는 관리서버(3)로부터 콘텐츠 제공]
    G --> H[브로드캐스팅, 멀티캐스팅, 유니캐스팅 통신방식 선택]
    H --> I[테이블 공석정보 생성]
    I --> J[공석테이블 광고관리 서브모듈(331) 동작]
    J --> K[착석테이블 광고관리 서브모듈(332) 동작]
    K --> L[광고컨텐츠 관리모듈(330) 동작]
    L --> M[메뉴 관리모듈(320) 동작]
    M --> N[사용자 행동패턴정보 수신]