flowchart TD
    A[도메인 A로부터 도메인 B로의 이미지 변환을 수행하는 모델을 비지도 학습하는 제1 GAN 제공] --> B[도메인 B로부터 도메인 A로의 이미지 변환을 수행하는 모델을 비지도 학습하는 제2 GAN 제공]
    B --> C[도메인 A의 샘플 이미지에 대한 제1 GAN의 이미지 변환에 의해 생성된 변환 이미지를 제2 GAN의 이미지 변환에 의해 원래 도메인 A로 재구성]
    C --> D[도메인 B의 샘플 이미지에 대한 제2 GAN의 이미지 변환에 의해 생성된 변환 이미지를 제1 GAN의 이미지 변환에 의해 원래 도메인 B로 재구성]