flowchart TD
    A[사용자의 질의어 수신] --> B[유사 질의어 생성]
    B --> C[검색 엔진에 적용]
    C --> D[검색 결과 리스트 정보 수신]
    D --> E[유사 질의어 그룹핑]
    E --> F[검색어 설정]
    F --> G[특정 검색어 적용]
    G --> H[토큰 추출]
    H --> I[TF-IDF 벡터 산출]
    I --> J[코사인 유사도 점수 산출]
    J --> K[최종 유사도 점수 산출]
    K --> L[대표 질의어 선정]
    L --> M[서비스 제공]