flowchart TD
    A[인플루언서-판매자 통합 플랫폼 제공 서버] --> B[사용자 정보관리부]
    B --> C[인플루언서 단말, 판매자 단말, 구매자 단말로부터 정보 획득]
    B --> D[인플루언서 평가 정보 생성]
    B --> E[인플루언서 추천 정보 생성]
    A --> F[사용자 권한부여부]
    F --> G[인플루언서 ID 부여]
    F --> H[판매자 ID 부여]
    F --> I[인플루언서-판매자 쌍 형성]
    A --> J[인플루언서-판매자 통합 대시보드 관리부]
    J --> K[대시보드 인터페이스 표시]
    J --> L[정보 표시]
    A --> M[이벤트 관리부]
    M --> N[추천 이벤트 정보 제공]
    M --> O[이벤트 진행 정보 획득]