flowchart TD
    A[사용자 단말에서 CCTV에 접속하여 영상 출력] --> B[관리비 정보 출력]
    B --> C[관리비 결제]
    C --> D[커뮤니티에 데이터 업로드 또는 조회 및 출력]
    E[CCTV 관리부에서 엑세스 요청 수신] --> F[엑세스 허가 및 영상 스트리밍]
    G[세대관리부에서 사용자 단말과 세대 매핑 및 관리] --> H[관리비 내역 전송 및 결제 진행]
    I[관리자관리부에서 구인구직풀 생성 및 업무범위 설정]
    J[건물관리자 단말에서 구인정보 등록]
    K[유지보수업체 단말에서 위탁관리업체 정보 등록]
    L[투표진행부에서 건물관리자 및 유지보수업체 정보 공개 및 투표 진행]
    M[에스크로부에서 하자 발생 시 보수 지급 관리]
    N[커뮤니티관리부에서 건의사항 및 공지 공유]
    O[리뷰관리부에서 평점 및 리뷰 데이터 입력 및 교체 진행]
    P[결제연동부에서 결제 수단 선택 및 결제 진행]