flowchart TD
    A[위성 영상을 수신하는 데이터 수집 모듈] --> B[오브젝트 분할 모듈]
    B --> C[분할 결과 생성]
    C --> D[특징 추출 모듈]
    D --> E[특징 추출]
    E --> F[군집화 모듈]
    F --> G[군집화 결과 생성]
    F --> H[전처리부]
    H --> I[전처리 결과 생성]
    I --> J[군집화 모델에 입력]
    J --> K[군집화 결과 생성]