flowchart TD
    A[단말 장치] --> B[디스플레이부]
    A --> C[제어창 구성부]
    A --> D[감지부]
    A --> E[디스플레이 제어부]
    A --> F[기울기 감지부]
    A --> G[각도 판단부]
    A --> H[속성 값 테이블 관리부]
    A --> I[속성 값 추출부]
    A --> J[해상도 데이터베이스]
    A --> K[크기 정보 추출부]
    A --> L[식별 값 데이터베이스]
    A --> M[식별 값 테이블 관리부]
    A --> N[식별 값 추출부]
    A --> O[제어 명령 집단 선택부]