flowchart TD
    A[데이터 수집부] --> B[데이터 가공 및 정제부]
    B --> C[직무적합도 분석부]
    C --> D[홍보전략 최적화 분석부]
    A1[교육기관정보] --> A
    A2[학생의 인적정보] --> A
    A3[학생의 학업정보] --> A
    A4[학생의 진로희망정보] --> A
    A5[특정직무에 대한 홍보활동정보] --> A
    A6[홍보활동정보에 대한 반응정보] --> A
    A7[지역 공공데이터정보] --> A
    B1[데이터 비식별화 모듈] --> B
    B2[정형/비정형 데이터 처리모듈] --> B
    B3[특성생성모듈] --> B
    B4[데이터통합모듈] --> B
    C1[지역사회 안정성 지수] --> C
    C2[리더십 경험 지수] --> C
    C3[공동체 기여 지수] --> C