flowchart TD
    A[학습 데이터에 포함된 표적들 중 배치에 포함될 표적을 결정하는 단계] --> B[학습 데이터에 포함된 약물들 중, 결정된 표적과 연관된 둘 이상의 약물들을 선택하는 단계]
    B --> C[결정된 표적 및 선택된 둘 이상의 약물들과 관련된, 둘 이상의 표적-약물 쌍들을 동일한 배치에 포함시키는 단계]
    A --> D[M개의 표적들을 결정하는 단계]
    B --> E[M개의 표적들 각각에 대하여, 각각의 표적과 연관된 K개의 약물들을 선택하는 단계]
    C --> F[M*K개의 표적-약물 쌍들을 동일한 배치에 포함시키는 단계]
    D --> G[각각의 표적과 연관된 약물들의 개수에 기초하여, 각각의 표적이 배치에 포함될 확률을 서로 상이하게 적용하는 단계]
    G --> H[각각의 표적이 배치에 포함될 확률은, 학습 데이터 내에서 각각의 표적과 연관된 약물의 개수에 비례하도록 결정되는 단계]