flowchart TD
    A[기부자로부터 물품기부 요청정보 입력받기] --> B[운영서버로 전송]
    B --> C[낙찰정보 및 낙찰금액과 대응하는 토큰 충전 내역 수신]
    C --> D[후원단체 조회신호와 대응하는 후원단체 색인]
    D --> E[충전된 토큰 중 입력받은 개수와 대응하는 토큰 차감]
    E --> F[차감된 토큰을 색인한 후원단체와 매칭]
    F --> G[후원자/후원단체 단말기로 기부하는 토큰기부정보 전송]
    G --> H[기부완료정보 수신]
    A1[기부자 본인인증] --> A2[운영서버로부터 토큰 지갑주소 부여받기]
    A2 --> A3[핀 번호 인증을 통해 운영서버와 접속]
    A3 --> A4[금융기관과 접속하여 카드정보 또는 계좌정보 등록]
    B1[물품기부 요청정보 업로드] --> B2[물품이 낙찰된 경우 토큰 지갑주소 및 핀 번호와 대응하는 충전된 토큰 충전내역 수신]
    B2 --> B3[토큰 지갑주소와 연동된 충전된 토큰 차감]
    B3 --> B4[차감된 토큰을 후원단체와 매칭된 후원자/후원단체 단말기로 기부]
    B4 --> B5[기부완료정보 수신]
    C1[후원단체 조회신호 전송] --> C2[후원단체 리스트 색인]
    C2 --> C3[선택신호와 대응하는 후원단체 상세정보 출력]