flowchart TD
    A[제1 시계열 데이터를 훈련된 인코더와 디코더로 구성된 순환신경망에 입력] --> B[이상상황 발생 여부 판단]
    B --> C[특이점수에 대한 정상 구간, 주의 구간 및 특이 구간 구분]
    C --> D[특이점수가 정상 구간, 주의 구간 및 특이 구간 중 어느 구간에 포함되는지 판단]
    D --> E[정상 상태, 주의 상태 및 특이 상태로 결정]
    
    A2[제2 시계열 데이터에 레이블 존재 여부 판단] --> A3[레이블이 존재하지 않을 경우 정상 데이터와 특이 데이터 구별]
    A3 --> A4[각 데이터에 대한 특이점수 계산]
    A4 --> A5[정상 데이터와 특이 데이터를 구별]
    
    B2[기 설정된 기준 이상의 특이점수를 갖는 데이터 셋(HD) 구성] --> B3[기 설정된 기준 이상의 특이점수를 갖는 데이터 제거한 데이터 셋(LD)과 손실 함수로 훈련]
    B3 --> B4[N-스코어 계산]
    B4 --> B5[A-스코어 계산]
    B5 --> B6[N-스코어와 A-스코어 비교 및 구분]
    B6 --> B7[정상 데이터와 특이 데이터 구별하는 경계 데이터 탐색]
    B7 --> B8[이상상황 탐지]
    
    C2[제2 시계열 데이터에 레이블 존재할 경우 정상 데이터 및 특이 데이터 분류] --> C3[정상 데이터에 대한 N-스코어 계산]
    C3 --> C4[특이 데이터에 대한 A-스코어 계산]