flowchart TD
    A[공공 데이터 모듈이 공공 데이터를 전달받음] --> B[무의미한 영역 제거 알고리즘 적용]
    B --> C[Cubic(3차원) 보간법 알고리즘 적용]
    C --> D[ToF 센싱 원리 기반 데이터 추출 알고리즘 적용]
    D --> E[ToF 센서 데이터 양식으로 변환된 데이터 생성]
    E --> F[무의미한 영역의 데이터를 0으로 대체하여 Masked Depth Data 생성]
    F --> G[행동과 무관한 영역 제거]
    G --> H[신경망 구조에 입력 가능한 크기로 변환]
    H --> I[3차원 좌표공간 구성]
    I --> J[Distance Array 추출]
    J --> K[행동 인식 방법]
    K --> L[학습 모듈이 변환된 데이터 전달받음]
    L --> M[컨볼루셔널 레이어 필터로 데이터 특징 및 가중치 학습]
    M --> N[행동인식 모듈이 특징 및 가중치를 기반으로 인식]