flowchart TD
    A[복수의 하드디스크들을 포함하는 랙의 최대 활성 디스크 수를 결정하는 단계] --> B[상기 결정된 최대 활성 디스크 수에 기초하여 상기 랙에 포함된 하드디스크들의 스핀업(spin-up)과 스핀다운(spin-down)을 제어하는 단계]
    B --> C[복제본(replica) 개수만큼의 하드디스크들을 포함하는 그룹(group)을 생성하는 단계]
    C --> D[상기 그룹을 구성하는 하드디스크들 각각을 상기 결정된 최대 활성 디스크 수에 기초하여 랙들 각각에 배치하는 단계]
    D --> E[상기 생성된 그룹들 중 제1 그룹의 하드디스크들에 여유 공간이 없는 경우 상기 결정된 최대 활성 디스크 수에 기초하여 상기 제1 그룹의 하드디스크들 중 어느 하나의 하드디스크를 제외한 나머지 하드디스크를 스핀다운(spin-down)시키는 단계]