flowchart TD
    A[사용자에게 특정 행위에 대한 토큰 지급] --> B[토큰을 특정 거래소에서 현금으로 교환할 수 있도록 인터페이스 제공]
    A --> C[토큰을 NFT 아이템과 교환할 수 있도록 스토어 제공]
    A --> D[사용된 토큰 재유통]
    A --> E[토큰 기부 시 다른 토큰으로 환산하여 지급]
    A --> F[토너먼트 참여 이벤트에 대해 상금과 보상 지급]
    F --> G[참가비에 따라 가변적으로 보상 분배]
    A --> H[만보기 기능 활용하여 개인 건강관리 정보 제공]
    H --> I[걸음수에 따라 토큰 자동 적립]
    I --> J[일정 수준 이상 쌓이면 사용자에게 지급]
    A --> K[디지털 치료제 정보를 국가 언어로 번역 제공]
    K --> L[구매 요청 수신 시 검색 기록 이용하여 제 1 검색어 결정]
    L --> M[제 1 검색어의 검색량 확인]
    M --> N[제 2 검색어 추출]
    N --> O[구매로 연결되는 비율 결정]
    O --> P[제 1 검색어에 대한 정보 제공]
    O --> Q[제 2 검색어에 대한 정보 제공]
    O --> R[제 2 검색어를 통한 구매 비율 제공]
    O --> S[의사 단말 목록 제공]
    S --> T[환자 평가 순서로 의사 단말 목록 제공]
    A --> U[전자 계약 제공]
    A --> V[전문가와의 매칭 가이드 제공]
    A --> W[토큰 활용 시스템]