flowchart TD
    A[제어 장치(20)를 통하여, 주변 센서 시뮬레이션을 통해 시뮬레이션된 적어도 하나의 주변 센서(402)의 사용 하에 측정을 실행하기 위한 명령이 센서 테스트 유닛(104)으로 송신되는 단계] --> B[적어도 하나의 시뮬레이션된 주변 센서(402)의 위치를 식별하기 위한 정보가 센서 테스트 유닛(104)을 통해 컴퓨터 장치(102)로 전송되는 단계]
    B --> C[컴퓨터 장치(102)를 통해, 차량 주변부 내의 시뮬레이션된 대상물(404)들에 있는 반사점(410, 412)들의 위치들이 계산되고, 반사점(410, 412)들의 계산된 위치들에 대한 정보가 센서 테스트 유닛(104)으로 전송되는 단계]
    C --> D[센서 테스트 유닛(104)을 통해, 계산된 주변부 데이터가 반사점(410, 412)들의 계산된 위치들에 대한 정보에 기초하여 결정되는 단계]
    D --> E[센서 테스트 유닛(104)을 통해, 반사점(410, 412)들의 얻어진 위치들에 대한 계산된 주변부 데이터가 제어 장치(20)로 전송되는 단계]