flowchart TD
    A[데이터를 입력 받고, 이를 연산 처리한 결과를 출력하기 위한 입출력부] --> B[정점의 특성을 예측하는 방법을 수행하기 위한 프로그램이 저장되는 저장부]
    B --> C[적어도 하나의 프로세서를 포함하며, 상기 프로그램을 실행시킴으로써 상기 입출력부를 통해 수신된 데이터에 포함된 정점의 특성을 예측하는 제어부]
    C --> D[하나의 인코더와 서로 다른 역할을 하는 특성 디코더 및 레이블 디코더를 포함하는 네트워크]
    D --> E[상기 데이터에 포함된 각 정점에 대해 미리 설정된 확률 모델을 사용해 잠재 변수를 생성하는 단계]
    E --> F[상기 인코더를 이용하여 가우시안 마르코프 랜덤 필드(GMRF)를 사용해 상기 데이터에 포함된 각 정점에 대해 잠재 변수를 생성하는 단계]
    F --> G[상기 잠재 변수의 분포가 사전 분포에 가까워지도록 상기 가우시안 마르코프 랜덤 필드(GMRF)를 사용해 상기 잠재 변수의 사전 분포를 모델링하여 상기 잠재 변수가 주어진 그래프 데이터의 구조에 따라 서로 상관 관계를 갖도록 정규화하는 단계]
    G --> H[상기 생성된 잠재 변수를 모델링하는 단계]
    H --> I[특성 디코더 및 레이블 디코더를 이용하여 그래프 구조화된 데이터에 대한 변이 추론을 실행하여 상기 잠재 변수를 모델링함으로써 정점의 특성 벡터 및 레이블을 생성하는 단계]