flowchart TD
    A[사용자 최후 대화 정보 및 사용자 이전 대화 정보 수신] --> B[부적절 텍스트 데이터베이스에서 부적절 여부 정보 및 부적절 텍스트 위치 정보 출력]
    B --> C[부적절 여부 정보가 '분류안됨'인 경우, 사용자 최후 대화 벡터 및 부적절 텍스트 위치 정보를 입력으로 부적절 스코어 출력]
    C --> D[부적절 텍스트를 포함하는 사용자 최후 대화 정보를 입력으로 적절 텍스트 출력]
    D --> E[적절 사용자 최후 대화 정보를 이용하여 인터렉션 생성 모듈의 파라미터 업데이트]
    E --> F[업데이트된 파라미터를 메인 신경망 서버에 업로드]
    F --> G[메인 신경망 서버에서 기학습된 인터렉션 생성 메인 신경망 다운로드]
    G --> H[부적절 스코어 저장 및 통합하여 기준 스코어 이상인 경우 레이블링]
    H --> I[부적절 스코어링 인공신경망 모듈의 학습 세션 수행]
    I --> J[학습 세션 이후의 파라미터를 메인 신경망 서버에 업로드]