flowchart TD
    A[제1 이미지, 제2 이미지 및 템플릿 이미지 획득] --> B[제1 호모그래피를 위한 특징점 검출]
    B --> C[제1 타깃 호모그래피 결정]
    C --> D[제2 호모그래피 결정]
    D --> E[카메라 자세 정보 획득을 위한 상보적 필터링 처리]
    E --> F[제1 회전 및 이동 매트릭스 결정]
    F --> G[제2 회전 및 이동 매트릭스 결정]
    G --> H[상보적 필터링 처리]
    H --> I[제1 필터링 결과 획득]
    I --> J[제2 필터링 결과 획득]
    J --> K[카메라 자세 정보 결정]