flowchart TD
    A[설문에 대한 답변 입력 및 전송] --> B[운동수준 선택]
    B --> C[운동수준별 조건 입력]
    C --> D[조건을 만족하는 트레이너 추천]
    D --> E[비대면 트레이닝 강좌 수강을 위한 통신 구축]
    E --> F[운동결과 기록 및 전송]
    F --> G[트레이너 평가 입력 및 전송]
    G --> H[트레이너 레벨 조정]
    H --> I[운동수준 관련 제품 추천]
    I --> J[과제 수행과정 촬영 및 전송]
    J --> K[과제 수행여부 확인 및 추가 운동 추천]
    
    H --> L[레벨 별 보상 조정]
    L --> M[인증파트너 인증 및 보상 유지]
    L --> N[스타트 파트너보다 높은 수업료 및 낮은 수수료 책정]
    
    B --> O[기초운동인 경우 운동 추천]
    C --> P[운동목적, 운동종류, 신체조건, 나이 입력]
    C --> Q[설문 답변 검색하여 조건 입력]
    
    D --> R[사용자가 선택한 운동에 대한 강좌 제공 트레이너 추천]
    D --> S[입력된 운동기구를 보유한 트레이너 추천]
    
    I --> T[운동결과 측정 IoT 기능이 탑재된 운동기구 추천]
    
    D --> U[AI 분석을 이용한 트레이너 추천]
    D --> V[우선순위에 따라 트레이너 추천]
    
    E --> W[무료 강좌 제공]
    D --> X[찜 기능 선택 시 트레이너 후보 추천]
    D --> Y[찜 기능 미선택 시 추천 제한]
    
    F --> Z[수강중 촬영된 동영상 및 운동결과 저장]