flowchart TD
    A[벼와 기타 작물의 필드 데이터로부터 VV 밴드의 이미지 및 VH 밴드의 이미지와 식생지수 추출] --> B[VV 및 VH 밴드의 이미지를 지형 보정 및 스페클 노이즈 필터링하여 전처리]
    B --> C[VV 밴드의 이미지, VH 밴드의 이미지와 경사방향 자료와 결측지가 없는 식생지수를 페어와이즈한 데이터를 이용해 GAN 모델의 식생지수 예측 학습]
    C --> D[학습된 GAN 모델을 이용하여 식생지수의 결측치가 보완된 이미지 생성]
    D --> E[랜덤 포레스트 모델에서 클라우드 마스킹 및 보정된 이미지를 이용하여 벼 지도 생성]
    E --> F[랜덤 포레스트 모델에서 식생지수가 보완된 이미지를 이용하여 벼 지도 생성]