flowchart TD
    A[복수의 병원체들 각각에 대응되는 복수의 정량 값들을 포함하는 정량 데이터 획득] --> B[건강 데이터 및 질환 데이터를 포함하는 추가 정보 획득]
    B --> C[예측 대상 질환 결정]
    C --> D[정량 데이터 전처리]
    D --> E[전처리된 정량 데이터 및 추가 정보를 인공지능 모델에 입력하여 질환 발생 확률 출력]
    C --> F[미리 정해진 표준 값 이상의 정량 값 식별]
    F --> G[식별된 정량 값에 대응되는 병원체 및 질환 식별]
    G --> C
    C --> H[병원성 미생물의 양 및 질환 유무에 기초한 예측 대상 질환 결정]
    B --> I[펫의 건강 또는 질환에 연관되는 추가 정보 획득]
    I --> E
    C --> J[예측 대상 질환에 대응되는 제1 전처리 알고리즘 선택]
    J --> D
    C --> K[예측 대상 질환에 대응되는 제1 인공지능 모델 선택]
    K --> E
    E --> L[질환 발생 확률을 나타내는 질환 점수 산출]