flowchart TD
    A[제1 비정형 질문을 입력받는 단계] --> B[제1 비정형 질문을 삼중항 손실 기반 또는 BIO 분류 기반의 정제된 질문 생성 모델에 입력하여 제1 정제된 질문을 생성하는 단계]
    B --> C[기계독해 모델에 콘텐츠를 입력하여 콘텐츠를 학습하는 단계]
    C --> D[기계독해 모델에 제1 정제된 질문을 입력하여 콘텐츠 기반의 제1 답변을 도출하는 단계]
    B --> E[제1 비정형 질문을 입력받아 공백, 구두점 및 형태소 단위에 따라 다수의 제1 토큰으로 분할하는 단계]
    E --> F[제1 토큰을 사전 훈련된 임베딩 모델에 입력하여, 제1 임베딩 벡터 집합으로 변환하는 단계]
    F --> G[제1 임베딩 벡터 집합의 각 제1 임베딩 벡터를 다층 퍼셉트론 기반의 제1 BIO 분류기에 입력하여 BIO 클래스별 로짓 값을 산출하는 단계]
    G --> H[BIO 클래스별 로짓 값을 소프트맥스 함수를 통해 BIO 클래스별 확률 분포로 변환하는 단계]
    H --> I[BIO 클래스별 확률 분포 간 내적 연산을 수행하여 제1 유사도를 산출하는 단계]
    I --> J['1 - 제1 유사도'인 경계 토큰의 불확실성을 산출하는 단계]
    J --> K[각 제1 임베딩 벡터마다 산출된 BIO 클래스별 확률 분포 중 최대 확률을 갖는 라벨을 기반으로, 제1 임베딩 벡터를 판정하는 단계]
    K --> L[엔티티 범주로 판정된 제2-1 임베딩 벡터를 동의어 사전과 비교하여 제2 유사도를 산출하는 단계]
    L --> M[제2 유사도가 가장 높은 제2-1 임베딩 벡터를 정규화하여 제3-1 임베딩 벡터로 변환하는 단계]
    M --> N[속성 범주 및 비범주로 판정된 제2-2 임