flowchart TD
    A[복수의 대상 이미지에 대한 인덱스 계열 정보 산출] --> B[비정상 사육 상태 정보 산출]
    A1[대상 이미지를 복수의 격자로 구획] --> A2[가축 격자 밀도 산출]
    A2 --> A3[가축 격자 밀도 배열하여 인덱스 계열 정보 산출]
    B1[정상 사육 상태 기준 인덱스와 유사성 분석] --> B2[비정상 사육 상태 발생 여부 산출]
    
    A --> A1
    B --> B1
    
    A1 --> A2
    A3 --> A
    B1 --> B2