flowchart TD
    A[센서 데이터를 수집하는 단계] --> B[상태 데이터를 도출하는 단계]
    B --> C[상태 벡터를 도출하는 단계]
    C --> D[상태 데이터 및 상태 벡터 비교 단계]
    D --> E[훈련 데이터 업데이트하는 단계]
    E --> F[차수축소모델을 업데이트하는 단계]
    A --> G[차수축소모델을 생성하는 단계]
    G --> H[가상의 부품을 생성하는 단계]
    H --> I[센서 데이터를 도출하는 단계]
    I --> J[상태 데이터를 도출하는 단계]
    J --> K[훈련 데이터를 구성하는 단계]
    K --> L[차수축소모델을 생성하는 단계]
    A --> M[검증모델을 생성하는 단계]
    M --> N[학습 데이터를 마련하는 단계]
    N --> O[검증모델에 입력하는 단계]
    O --> P[상태 벡터를 도출하는 단계]
    P --> Q[손실을 산출하는 단계]
    Q --> R[검증모델의 가중치를 갱신하는 최적화 단계]