flowchart TD
    A[상품을 제조하는 브랜드와 셀러 사이의 매칭 지원] --> B[매칭된 셀러와 브랜드 사이의 계약 지원]
    B --> C[컨택 인터페이스 제공 및 계약 조건 구성]
    C --> D[판매된 상품의 판매 금액 정산 지원]
    D --> E[판매자 계좌와 중개자 계좌 간 자동 이체 설정 요청]
    E --> F[마켓 정보 제공 및 상품 판매 지원]
    F --> G[판매 완료 정보에 따른 나머지 금액 자동 이체]
    G --> H[브랜드 및 셀러에 대한 정산 수행]
    B --> I[계약서 구성 지원]
    I --> J[대화 정보 수집]
    J --> K[대화 정보 분석 및 계약 항목 추출]
    K --> L[계약 조건 구성 및 계약서 구성]
    L --> M[계약서 구성 완료]
    B --> N[계약 구성 인터페이스 제공]
    N --> O[조건 정보 수신]
    O --> P[추천 모델에 입력하여 계약 상대방 추천]
    N --> Q[상품명 입력 메뉴 제공]
    Q --> R[상품 정보 인터페이스 제공]
    N --> S[날짜 지정 캘린더 인터페이스 제공]
    N --> T[수수료 입력 지원]