flowchart TD
    A[회원관리부(10)에서 회원가입 및 관리 수행] --> B[회원정보획득모듈(110)에서 회원 프로필 정보 획득]
    B --> C[회원등급관리모듈(120)에서 회원 종류 구분 및 등급 부여]
    A --> D[매칭관리모듈(210)에서 피보호자 및 보호자와 전문 요양보호사 매칭]
    D --> E[휴먼팩터 관리모듈(220)에서 휴먼팩터 관리]
    D --> F[우선 배정관리모듈(230)에서 우선 배정 관리]
    D --> G[과금 관리모듈(240)에서 과금 예상금액 관리]
    D --> H[매칭 미팅관리모듈(250)에서 미팅 관리]
    D --> I[매칭도 분석 모듈(260)에서 매칭도 분석 및 데이터베이스 전송]
    D --> J[예비 배정 모듈(270)에서 예비 전문 요양보호사 배정]
    D --> K[매칭옥션 관리모듈(280)에서 매칭 정보 전송 및 서비스 매칭 진행]
    A --> L[요양보호서비스부(30)에서 요양보호 서비스 제공]
    L --> M[요양 서비스 신청 모듈(310)에서 서비스 신청]
    L --> N[서비스 제공 확인모듈(320)에서 서비스 제공 여부 확인]
    L --> O[스케줄관리모듈(330)에서 스케줄 관리]
    L --> P[과금관리모듈(340)에서 요금 부과 및 관리]
    L --> Q[상담관리모듈(350)에서 상담 관리]
    A --> R[모니터링부(40)에서 피보호자 및 관리자 모니터링 및 평가]
    A --> S[커뮤니티 관리부(50)에서 커뮤니티 형성]
    S --> T[게시판 활성화 모듈(510)에서 게시글 올리기]
    S --> U[Q&A 관리모듈(520)에서 Q&A 생성 및 관리]
    S --> V[검색관리모듈(530)에서 정보 검색]