flowchart TD
    A[가이드 정보를 학습 데이터 수집 장치에 전송] --> B[이미지들을 학습 데이터 수집 장치로부터 수신]
    B --> C[이미지들로부터 이미지 정보 추출]
    C --> D[추출한 이미지 정보를 가이드 정보와 비교하여 노이즈 이미지 분류]
    D --> E[이미지들을 시간 순으로 나열]
    E --> F[연속된 복수의 이미지를 그룹핑하여 시퀀스 데이터 생성]
    F --> G[시퀀스 데이터 별로 노이즈 이미지 분류]
    G --> H[특정 이미지의 전후 이미지 유사도 비교]
    H --> I[유사도가 사전 설정된 값보다 높고, 특정 이미지와의 유사도가 낮을 경우 방지턱 촬영 이미지 판단]
    D --> J[각 이미지에 포함된 객체 검출]
    J --> K[검출된 객체의 위치 변화 값이 사전 설정된 값보다 높은 이미지를 노이즈 이미지로 분류]
    D --> L[연속된 이미지 사이의 유사도 비교]
    L --> M[유사도가 사전 설정된 값보다 낮은 이미지가 연속적으로 검출된 경우 커브 길에서 촬영된 이미지 판단]
    M --> N[검출된 이미지들을 노이즈 이미지로 분류]