flowchart TD
    A[제1 사이즈를 갖는 얼굴 이미지 획득] --> B[얼굴 이미지를 특징 추출 네트워크로 입력]
    B --> C[특징 추출 네트워크에서 컨볼루션 연산 적용]
    C --> D[특징 맵 생성]
    D --> E[슬라이딩 풀링 연산 적용]
    E --> F[다수의 특징 생성]
    F --> G[다수의 특징을 뉴럴 애그리게이션 네트워크로 입력]
    G --> H[최적 특징 출력]