flowchart TD
    A[실물 센서에서 데이터 수집] --> B[가상센서 모델에 데이터 적용]
    B --> C[디지털 트윈 환경 구성]
    D[엣지 게이트웨이] --> E[실물 센서에서 측정된 데이터 이용하여 가상센서 모델 학습]
    E --> F[가상센서 모델을 엣지 게이트웨이에 배포]
    G[가상센서 프레임워크] --> H[데이터 데이터베이스에 전처리된 데이터 저장]
    H --> I[가상센서 학습모델 모듈로 가상센서 생성]
    I --> J[생성신호 오차 분석 모듈로 데이터 비교 및 오차 보정]
    J --> K[데이터 및 오차 모니터링 시각화 엔진으로 업데이트 필요 판단]
    K --> L[엣지 게이트웨이에 학습을 위한 데이터 수집 요청]