flowchart TD
    A[제1 시간 간격마다 제1 사용자 데이터 및 제1 아이템 데이터 획득] --> B[제1 사용자 데이터에 대한 제1 키워드 및 제1 아이템 데이터에 대한 제2 키워드 획득]
    B --> C[제1 사용자 데이터의 제1 키워드를 DSSM에 입력하여 제1 의미 벡터 생성]
    C --> D[제1 아이템 데이터의 제2 키워드를 DSSM에 입력하여 제2 의미 벡터 생성]
    D --> E[제1 의미 벡터와 제2 의미 벡터 사이의 관련도를 나타내는 제1 벡터 생성]
    E --> F[제1 벡터, 제1 의미 벡터 및 제2 의미 벡터에 대응되는 데이터 저장]
    F --> G[저장된 데이터에 기초하여 제1 인공지능 모델 학습 및 갱신된 가중치 획득]
    G --> H[획득된 가중치를 제2 인공지능 모델에 적용]
    H --> I[제2 인공지능 모델에 기초하여 추천 아이템 또는 추천 사용자 식별 정보 제공]
    I --> J[사용자의 사용자 인터랙션에 기초하여 제1 인공지능 모델의 갱신된 가중치 재갱신]
    I --> K[제2 사용자 데이터 및 제2 아이템 데이터 중 적어도 하나를 실시간으로 획득]
    K --> L[제2 사용자 데이터에 대한 제3 키워드 획득]
    L --> M[제2 사용자 데이터의 제3 키워드를 DSSM에 입력하여 제3 의미 벡터 획득]
    M --> N[제3 의미 벡터를 제2 인공지능 모델에 입력하여 제4 의미 벡터 획득]
    N --> O[제4 의미 벡터에 기초하여 추천 아이템 식별 정보 제공]
    O --> P[입력 인터페이스를 통해 추천 아이템에 연관된 사용자 인터랙션 수신]
    P --> Q[제3 의미 벡터와 제4 의미 벡터 사이의 관련도를 나타내는 제2 벡터 생성]
    K --> R[제2 아이템 데이터에 대한 제4 키워드 획득