flowchart TD
    A[통합 핀테크 단말기가 키관리 서버로부터 수신한 IPEK 및 KSN을 포함하는 인증 IC 정보를 가맹점 인증 IC카드에 등록하는 단계] --> B[통합 핀테크 단말기가 복수의 핀테크 서비스들 중 선택된 하나에 대한 핀테크 요청 정보를 입력받는 단계]
    B --> C[통합 핀테크 단말기가 가맹점 인증 IC카드로부터 IPEK, KSN, 및 가맹점 정보를 수신하는 단계]
    C --> D[통합 핀테크 단말기가 IPEK 및 KSN을 이용하여 OTK를 생성하는 단계]
    D --> E[통합 핀테크 단말기가 OTK를 이용하여 핀테크 요청 정보를 암호화함으로써 암호화 요청 정보를 생성하는 단계]
    E --> F[핀테크 중계 서버가 통합 핀테크 단말기로부터 KSN, 가맹점 정보, 및 암호화 요청 정보를 포함하는 핀테크 서비스 요청을 수신하는 단계]
    F --> G[핀테크 중계 서버가 IPEK와 KSN을 이용하여 OTK를 생성하는 단계]
    G --> H[핀테크 중계 서버가 OTK를 이용하여 암호화 요청 정보를 복호화함으로써 핀테크 요청 정보를 도출하는 단계]
    H --> I[핀테크 중계 서버가 핀테크 요청 정보에 상응하는 핀테크 서비스 서버를 선택하는 단계]
    I --> J[핀테크 중계 서버가 핀테크 서비스 서버에 핀테크 요청 정보를 포함하는 핀테크 서비스 처리 요청을 전송하는 단계]
    J --> K[통합 핀테크 단말기가 가맹점 인증 IC카드로부터 RSA 공개키 및 카드 고유 정보를 수신하는 단계]
    K --> L[통합 핀테크 단말기가 RSA 공개키, 카드 고유 정보, 및 통합 핀테크 단말기의 단말기 고유 정보를 이용하여 키관리 서버와 RSA키 기반의 신뢰성 인증을 수행하는 단계]
    L --> M[통합 핀테크 단말기가 사용