flowchart TD
    A[신체 상에서 복수의 조인트들을 정의] --> B[기준 신체동작 감지]
    B --> C[기준 동작 데이터 생성]
    C --> D[사용자 신체동작 감지]
    D --> E[사용자 동작 데이터 생성]
    E --> F[모션 정규화]
    F --> G[가중치 설정]
    G --> H[유사도 평가 점수 계산]
    H --> I[결과 출력]