flowchart TD
    A[기부자가 특정 매장에 돈을 선지불하여 기부금을 충전] --> B[해당 매장을 방문한 기부대상자에게 충전된 기부금 내에서 특정 매장의 제품 제공]
    B --> C[기부금 충전과 기부금 사용은 매장 또는 주변 상권에 설치된 공용 키오스크를 통해 이루어짐]
    C --> D[키오스크는 협업 중인 매장의 정보 입력 및 노출]
    D --> E[제품 구매 요청과 금액 지불 및 기부금 충전 안내]
    E --> F[키오스크는 포토박스가 일체로 구비되어 기부대상자가 기부금을 이용하는 모습 촬영]
    F --> G[촬영된 사진은 키오스크의 갤러리에 자동 저장]
    G --> H[기부자나 기부대상자가 출력 요청 시 포토박스를 통해 사진 인쇄 제공]
    H --> I[사진은 바코드 또는 QR코드로 이루어져 기부자가 선택한 매장에서 상품 구매 결제코드 제공]
    I --> J[기부자의 이름 또는 상호명과 협업 기관명이 선택적으로 입력되어 기부 영수증이나 기부 인증서로 활용]
    J --> K[키오스크는 메인화면에 기부자 정보 노출하여 지역광고 효과 극대화]
    K --> L[기부자가 불특정 기부대상자 선택 시 후원받은 금액과 상품이 높은 순으로 리스트 노출]
    L --> M[상대적으로 후원이 부족한 기부대상자 선택 유도]