flowchart TD
    A[영상의 복수의 연속된 프레임에서 사람 객체 검출] --> B[동일한 사람 객체 추적]
    B --> C[사람 객체의 행위 순차로 식별]
    C --> D[이상행동 검출]
    D --> E[이상행동 클립 영상 생성]
    E --> F[이상행동에 상응하는 레이블 부여]
    F --> G[이상행동 클립 영상 저장]