flowchart TD
    A[복수의 이미지 센서로부터 복수의 이미지 데이터 수신] --> B[각 이미지 데이터에 대해 사용자 관절 위치 및 자세 추정]
    B --> C[복수의 2차원 포즈 데이터 생성]
    C --> D[2차원 포즈 데이터 결합하여 3차원 포즈 데이터 생성]
    D --> E[3차원 포즈 데이터 트래킹]
    E --> F[트리거 데이터 식별]
    F --> G[트리거와 관련된 상품 식별]
    G --> H[제1 트래킹 데이터 식별]
    H --> I[사용자 후보군 식별]
    I --> J[제1 신뢰도 계산]
    J --> K[트리거와 관련된 사용자 식별]
    K --> L[가상 장바구니 업데이트 서비스 인스트럭션 저장]
    L --> M[데이터 수집 장치 통해 학습]
    M --> N[대상 오브젝트에 대해 복수의 방향으로 영상 촬영]
    N --> O[제1 대상 이미지 데이터 식별]
    O --> P[텍스트와 제1 대상 이미지 데이터 입력]
    P --> Q[제1 중간 이미지 데이터 수신]
    Q --> R[제1 중간 이미지 데이터를 제2 딥러닝 모델에 입력]
    R --> S[제1 세그멘테이션 마스크 셋 수신]
    S --> T[대상 오브젝트만 포함하는 세그멘테이션 마스크 선택]
    T --> U[합성 이미지 생성 인스트럭션 저장]