flowchart TD
    A[터치스크린의 앞면에 부착된 정전식 버튼의 눌림을 검출] --> B[트리거 신호를 햅틱제어모듈에 출력]
    B --> C[트리거 신호가 입력되면 햅틱 데이터에 따라 진동소자 구동]
    C --> D[클릭커소자 구동하여 클릭 사운드 출력]
    A1[정전식 버튼이 부착된 터치스크린의 좌표 또는 좌표 영역을 바탕으로 터치 검출] --> A2[정전식 버튼이 입력된 것으로 판단하여 트리거 신호 출력]
    A1 --> A2
    E[진동소자 및 클릭커소자는 터치스크린의 뒷면에 부착] 
    F[클릭커소자는 릴레이를 포함하고 릴레이의 스위칭 동작에 의해 클릭 사운드 발생] 
    G[햅틱 데이터는 햅틱 강도와 햅틱 주기를 포함] 
    H[햅틱 데이터를 I2C 통신 단자를 통해 햅틱제어모듈에 출력]
    I[내부 변수 초기화 및 통신 단자 초기화]
    J[외부 입력 장치 연결 체크 및 햅틱제어모듈 전원 체크]
    K[전원이 공급된 상태이면 초기화 완료 체크]
    L[초기화가 완료되지 않았을 경우 내부 메모리에 저장된 햅틱 데이터 읽기]
    M[터치 이벤트가 발생하지 않는 경우 업데이트된 햅틱 데이터 수신 체크]
    N[업데이트된 햅틱 데이터 수신 시 내부 메모리에 저장 및 재설정]
    O[터치 이벤트 발생 시 트리거 신호 출력하여 햅틱 기능 온]
    P[진동소자 구동 및 클릭커소자 온 시켜 클릭 사운드 발생]