flowchart TD
    A[자산 거래 요청 정보 수신] --> B[제1 링크 생성]
    B --> C[자산 거래 수락 정보 수신]
    C --> D[자산 거래 체결 확정]
    C --> E[제1 코드 이용하여 접속 요구]
    E --> F[우회적 방식으로 전송]
    E --> G[직접적 방식으로 전송]
    D --> H[조건 변경 또는 거래 취소 가능]
    H --> I[제1 거래자 노드에게 알림 제공]
    H --> J[제1 거래자 노드 승인에 따라 확정]
    H --> K[자산 거래 요청 정보 재전송]