flowchart TD
    A[사용자 관리부: 사용자 정보를 제공받아 관리] --> B[가상지갑 관리부: 사용자 관리코드 및 쓰레기용기코드 저장]
    B --> C[가상코인 데이터베이스에 정보 저장]
    C --> D[코인충전/차감부: 결제정보 제공받아 가상코인 충전]
    D --> E[쓰레기용기코드 리드]
    E --> F[가상코인 차감 및 서비스 제공업체 가상지갑으로 이체]