flowchart TD
    A[학습 데이터 수집] --> B[복수의 엣지 서버 설치]
    B --> C[중앙 서버 설치]
    C --> D[일 조건 데이터를 바탕으로 엣지 서버 선택]
    D --> E[선택된 엣지 서버에 학습 데이터 요청]
    E --> F[선택된 엣지 서버로부터 학습 데이터 수신]
    F --> G[학습 데이터를 바탕으로 맞춤형 콘텐츠 선택]
    G --> H[맞춤형 콘텐츠를 선택된 엣지 서버에 제공]
    I[복수의 엣지 서버에서 환부의 움직임을 포함하는 영상 수집] --> J[공유 모델 학습]
    K[복수의 엣지 서버로부터 분산 학습된 공유 모델 획득] --> L[결과 데이터 획득]
    L --> M[획득된 결과 데이터를 바탕으로 콘텐츠 선택 모델 생성]