flowchart TD
    A[권선 프로세스를 모니터링하는 방법] --> B[상기 권선 프로세스 동안 캡처된 상기 변압기 권선(20)의 적어도 일부를 나타내는 적어도 하나의 이미지(42)를 프로세싱하는 단계]
    B --> C[오브젝트 분류를 수행하는 단계]
    B --> D[상기 오브젝트 분류의 결과와 상기 변압기 권선(20)에 대한 설계 데이터(49) 사이의 불일치를 검출하는 단계]
    D --> E[검출된 상기 불일치에 응답하여 적어도 하나의 액션을 실시하는 단계]
    E --> F[상기 설계 데이터(49)와 조합하여 상기 권선 장치(30)의 병진 포지션 및 회전 포지션 양자 모두에 기초하여 상기 권선 프로세스 동안 상기 적어도 하나의 이미지(42)의 적어도 하나의 이미지 포착 시간을 결정하는 단계]
    E --> G[상기 컴퓨터 비전 시스템(40)에 의해, 인간 기계 인터페이스(HMI)(37)가 상기 검출된 불일치에 의존하는 정보를 출력하게 하는 것]
    E --> H[상기 액션은 상기 권선 장치(30)의 회전 및 병진 변위 중 적어도 하나를 정지시키는 것]
    F --> I[결정된 상기 적어도 하나의 이미지 포착 시간에 기초하여 이미지 포착 디바이스 제어 및 이미지 선택 중 적어도 하나를 수행하는 단계]
    B --> J[상기 오브젝트 분류가 수행될 관심 영역(ROI)(125)을 식별하는 단계]
    J --> K[상기 ROI(125)의 경계들은 상기 변압기 권선(20)의 쉴드들의 에지들(126)을 포함하는 것]
    B --> L[상기 권선 장치(30)의 하나의 또는 수개의 포지션 측정치들을 사용하는 단계]
    L --> M[상기 적어도 하나의 머신 러닝(ML) 모델(100)을 실행하는 단계]
    M --> N[상기 오브젝트 분류가 수행될 관심 영역(ROI)(125) 및