flowchart TD
    A[관리비 정보 수신] --> B[수납 정보 제공]
    A --> C[관리비 고지내역 생성]
    C --> D[고지내역 제공]
    D --> E[결제 요청 수신]
    E --> F[관리비 결제 수행]
    F --> G[수납 정보 생성]
    G --> H[수납 정보 저장]
    H --> I[결제 금액 비교]
    I --> J{부가가치세 포함 여부}
    J -->|예| K[전자세금계산서 발급]
    J -->|아니오| L[프로세스 종료]
    A --> M[인증 정보 저장]
    A --> N[스크래핑 방식으로 결제내역 수신]
    N --> O[고지내역 생성]
    O --> P[사용자 등록정보 저장]
    G --> Q[결제수단 정보 및 결제일정 정보 저장]
    Q --> R[관리비 결제 자동 수행]
    G --> S[소셜 프로필 정보 저장]
    S --> T[알림 정보 전송]
    A --> U[입주자 위치 정보 저장]
    U --> V[광고 정보 제공]
    V --> W[광고료 지급 및 정보 추출]