flowchart TD
    A[복수의 영상별로 점수를 부여하는 단계] --> B[점수를 임계치와 각각 비교한 결과를 기초로 영상 이동]
    B --> C[임계치보다 더 높은 점수의 영상들을 제1DB로, 그 외의 영상들을 제3DB로 이동]
    C --> D[제1DB에 누적된 수가 기설정된 수를 초과한 것을 감지하는 단계]
    D --> E[초과 상태가 감지된 후, 제1영상의 점수가 임계치보다 더 높은 것 감지]
    E --> F[제1DB에 이동된 영상들 중에서 제2영상을 제2DB로 이동시키고, 제1영상을 제1DB로 이동]
    F --> G[복수의 영상이 제1DB 내지 제3DB 중 어느 하나에 이동 완료 시 데이터셋 생성]