flowchart TD
    A[사전학습된 ML 모델 이용] --> B[비정형 텍스트 데이터로부터 공간정보 추출]
    B --> C[KoCharELECTRA 모델 사용]
    C --> D[양방향 문맥 정보 고려]
    D --> E[생성기 및 판별기 포함]
    E --> F[입력된 토큰 리스트 중 일부 마스킹 및 치환]
    E --> G[입력된 토큰 이진 분류로 판별]
    C --> H[입력층 구성]
    H --> I[토큰 임베딩, 마스크 임베딩, 세그먼트 임베딩 구성]
    B --> J[FFNN 및 양방향 LSTM, CRFs 결합]
    J --> K[FFNN으로 음절 벡터 차원 변경]
    K --> L[소프트맥스 레이어를 통한 확률 분포 정규화]
    J --> M[CRFs로 출력 레이블 사이 의존성 고려]
    M --> N[negative log-likelihood 손실 함수 이용]
    M --> O[Viterbi decoding으로 최종 출력 열 선정]