flowchart TD
    A[브라우저 어드레스 바에서 검출된 문자에 대응하는 하나 이상의 문자 수신] --> B[검색 쿼리에 대해 애플리케이션들을 랭킹]
    B --> C[검색 결과인 애플리케이션 중 애플리케이션 선택]
    C --> D[선택된 애플리케이션의 식별을 사용자 장치로 전송]
    D --> E[전송된 식별에 기초하여 웹 문서의 콘텐트 내에 애플리케이션 표시]
    E --> F[표시된 애플리케이션의 사용자 선택에 응답하여 애플리케이션 자동으로 런칭]
    F --> G[애플리케이션에 대한 진보된 엔트리 포인트 설정을 위한 콘텍스트 제공]