flowchart TD
    A[제1 사용자 단말로부터 상품 이미지 정보 수신] --> B[상품 이미지 정보에 대한 이미지 보정 수행]
    B --> C[보정된 상품 이미지 정보 생성 및 저장]
    C --> D[보정된 상품 이미지 정보 광고판 디스플레이에서 출력 제어]
    D --> E[카메라 모듈이 불특정 다수 촬영]
    E --> F[불특정 다수에 대한 제3 객체 추출]
    F --> G[불특정 다수의 움직임 및 시선 식별]
    G --> H[정지한 제1 시간 및 감속되는 제2 시간 산출]
    H --> I[불특정 다수가 광고판 디스플레이를 쳐다보는 제3 시간 산출]
    I --> J[제1 시간이 제1 기준 시간보다 길고, 제2 시간이 제2 기준 시간보다 길고, 제3 시간이 제3 기준 시간보다 긴 경우 보정된 상품 이미지 정보를 소정의 리스트에 포함시키도록 제어]
    J --> K[제1 사용자 단말로부터 제1 카테고리 정보 수신]
    K --> L[제1 카테고리 정보를 기저장된 제2 카테고리 정보에 자동으로 매칭]
    L --> M[제2 사용자 단말로부터 사용자 정보 수신]
    M --> N[선호 가중치에 기반하여 선호 상품 추천 정보 및 상품 추천 푸쉬 생성]
    N --> O[선호 상품 추천 정보 및 상품 추천 푸쉬를 제2 사용자 단말에 전송]
    O --> P[상품에 대한 구매 요청 정보 수신]
    P --> Q[구매 요청 정보 및 제2 카테고리 정보에 기반하여 통관 EDI 폼을 제1 사용자 단말에 전송]
    Q --> R[고객 응답 기능 활성화 및 제공]
    R --> S[고객 문의 기능을 제2 사용자 단말에 제공]
    S --> T[통관 EDI 폼에 포함된 속성들 중 제1 속성에 구매 요청 정보 및 제2 카테고리 정보 자동 매칭]
    T --> U[복수의 속성들 중 제1 속성을 제외한 제2 속성에 대한 입력]