flowchart TD
    A[생두의 재고 관리] --> B[생두의 로스팅 과정 관리]
    B --> C[소분주문정보 수신]
    C --> D[소분포장정보 제공]
    A --> E[원두주문관리서버(100)]
    B --> F[로스팅기계(3)]
    E --> G[생두주문정보 전송]
    E --> H[생두수입관리부(110)]
    E --> I[로스팅관리부(120)]
    E --> J[소분주문관리부(130)]
    E --> K[소분포장부(140)]
    E --> L[원두재고관리부(150)]
    E --> M[원두가격관리부(160)]
    E --> N[발주코드제공부(170)]
    E --> O[고객DB관리부(180)]
    E --> P[구매패턴데이터분석부(190)]
    P --> Q[원두 품종별 그룹화 정보 수집]
    P --> R[판매정보 수집 및 판매순위정보]
    P --> S[원두선호지수 산출]
    P --> T[카페성장지수 산출]