flowchart TD
    A[어드레스 변환 정보 및 연관된 보안 표시자들을 공유 메모리에 저장] --> B[제 1 버스로부터 수신된 각각의 제 1 액세스 요청에 대한 응답]
    B --> C[상기 제 1 요청자 보안 표시자가 비-안전 요청자를 표시하고 상기 제 1 어드레스에 대해 상기 공유 메모리에 저장된 어드레스 변환 정보와 연관된 보안 표시자가 안전 어드레스 범위를 표시하는 것에 대한 응답으로, 상기 제 1 액세스 요청을 거절]
    B --> D[상기 제 1 요청자 보안 표시자가 안전 요청자를 표시하는 것에 대한 응답으로, 상기 어드레스 변환 정보를 사용하여 상기 제 1 액세스 요청을 상기 제 2 버스에 대한 제 2 액세스 요청으로 변환하고 상기 제 2 액세스 요청을 상기 제 2 버스에 통신]
    D --> E[상기 제 2 버스로부터 수신되고 제 3 어드레스를 포함하는 각각의 제 3 액세스 요청에 대한 응답]
    E --> F[상기 공유 메모리에 저장된 어드레스 변환 정보를 이용하여 상기 제 3 액세스 요청을 상기 제 1 버스에 대한 제 4 액세스 요청으로 변환]
    F --> G[상기 제 4 액세스 요청 및 상기 제 4 어드레스에 대한 어드레스 변환 정보와 연관된, 상기 공유 메모리에 저장된 보안 표시자를 상기 제 1 버스에 통신]