flowchart TD
    A[판매자에 대응하는 제1 사용자의 판매 상품에 기초하여 거래 링크를 생성하는 단계] --> B[구매자에 대응하는 제2 사용자로부터 상기 거래 링크에 대한 입력을 수신한 것에 응답하여, 거래 조건을 결정하는 단계]
    B --> C[상기 거래 조건에 기초하여 결제 프로세스를 수행하는 단계]
    C --> D[상기 거래 조건에 기초하여 상기 하나 이상의 거래 매개 자산을 상기 제2 사용자에게 매도함으로써, 상기 제2 사용자의 계좌에 제2 사용자 자산을 예치하는 단계]
    D --> E[상기 제2 사용자 자산을 상기 제1 사용자에게 이체함으로써 상기 제1 사용자의 계좌에 제1 사용자 자산을 예치하는 단계]
    E --> F[상기 제1 사용자 자산을 상기 제1 사용자로부터 매수하는 단계]
    C --> G[상기 금융 거래 권한에 기초하여 상기 결제 프로세스를 수행하는 단계]