flowchart TD
    A[서비스 시나리오 입력 받기] --> B[서비스 시나리오 분석]
    B --> C[사건, 명령, 역할 정보 추출 및 구조화]
    C --> D[그래프 생성]
    D --> E[보일러플레이트 코드 및 배포 리소스 파일 생성]
    E --> F[소프트웨어 애플리케이션 빌드 및 배포]
    
    A1[음성 입력 받기] --> A2[음성 인식 수행]
    A --> A1
    A2 --> B

    B1[문장 집합으로 나타내기] --> B2[문장 분류]
    B3[도식 변환] --> B4[정점 분류]
    B --> B1
    B --> B3

    B5[대규모 언어 모델로 분류] --> B
    B --> B5