flowchart TD
    A[서버] --> B[호스트 기기로부터 라이브 콘텐츠 획득]
    B --> C[구매자 기기에 라이브 콘텐츠 제공]
    C --> D[판매자 정보 및 구매 관련 정보 제공]
    D --> E[구매 의사 밝힌 구매자 확인]
    E --> F[결제용 모바일 페이 코드 연결]
    F --> G[판매 물품 구매 지원]
    A --> H[콘텐츠 관리부]
    H --> I[라이브 콘텐츠 분류]
    H --> J[여행지 분류 및 판매 물품 카테고리 포함]
    A --> K[인터페이스 관리부]
    K --> L[라이브 콘텐츠 재생 레이어와 텍스트 레이어 오버레이]
    A --> M[결제 지원부]
    M --> N[판매자 및 구매자 QR코드 중개]
    N --> O[결제 요청]
    O --> P[구매 결정 요건 판단]
    P --> Q[결제 금액 확인]
    Q --> R[결제 및 구매 결정 취소]
    A --> S[사용자 관리부]
    S --> T[판매자 계정 정보 관리]
    S --> U[구매자 주요 요청 리스트화]
    A --> V[판매 지원 영역 표시]
    V --> W[구매 이벤트 대응]
    A --> X[외부 웹 서비스 이용]
    X --> Y[추가 정보 제공]
    X --> Z[AI 챗봇을 통한 질문 답변]
    A --> AA[QR 연결부]
    AA --> AB[판매자 QR 코드와 구매자 QR 코드 연결]