flowchart TD
    A[이송 챔버] --> B[툴 스테이션]
    A --> C[프로세스 챔버]
    A --> D[이송 챔버 로봇]
    D --> E[하나 이상의 센서들]
    D --> F[엔드 이펙터]
    E --> G[가속도계, 거리 센서, 카메라, 용량성 센서, 반사계, 고온계, 레이저 유도 형광 분광기, 광섬유 프로브, 표면 음향 센서, 와전류 센서, 보어스코프, 포토다이오드 센서, 광전자 증배관, 솔리드 스테이트 검출기, 열전대, 전압 센서, 전류 센서 또는 저항 센서 중 적어도 하나]
    F --> H[하나 이상의 전기 커넥터들]
    E --> I[전자 장치 모듈]
    E --> J[전력 엘리먼트]
    J --> K[파워-업 회로]
    D --> L[데이터 또는 전기 전력 중 적어도 하나를 제공하기 위한 하나 이상의 전기 커넥터들]
    D --> M[데이터 또는 전기 전력 중 적어도 하나를 수신하기 위한 하나 이상의 전기 커넥터들]