flowchart TD
    A[플랫폼 어플리케이션이 설치되는 적어도 하나 이상의 클라이언트] --> B[메타버스-도시를 기반으로 한 이커머스 서비스 제공]
    B --> C[이커머스로 인한 수익 발생 시 거주-수수료 지급]
    C --> D[증권거래소 운영서버 포함]
    D --> E[증권거래 운영방식 결정부 실행]
    E --> F[기 설정된 주기(T) 마다 메타버스/이커머스 관리서버에 접속]
    F --> G[도시DB 수집]
    G --> H[비상장-도시들의 도시DB 추출]
    H --> I[상장여부 판단]
    I --> J[상장대상도시의 토지분할소유권에 대한 IPO 실행]
    J --> K[상장일자 및 계획 수립]
    K --> L[증권거래 서비스 운영 및 관리]