flowchart TD
    A[디스플레이 상에 제1 애플리케이션을 위한 사용자 인터페이스 디스플레이] --> B[결제 어포던스의 선택 검출]
    B --> C[제1 거래 정보를 제2 애플리케이션으로 전달]
    C --> D[디스플레이 상에 제2 애플리케이션을 위한 사용자 인터페이스 디스플레이]
    D --> E[제2 애플리케이션을 위한 사용자 인터페이스 상에 제1 구매 상세사항 어포던스의 선택 수신]
    E --> F[대안적 값들을 선택하기 위한 하나 이상의 어포던스 디스플레이]
    F --> G[대안적 값의 선택 수신]
    G --> H[대안적 값을 제1 구매 상세사항으로 포함하도록 제2 거래 정보 업데이트]