flowchart TD
    A[명령어들을 저장하는 하나 이상의 메모리] --> B[하나 이상의 프로세서]
    B --> C[탄소 저감 이벤트 획득]
    C --> D[탄소 저감량 판별]
    D --> E[탄소 배출권 획득]
    D --> F[제1 탄소량 판별]
    D --> G[제2 탄소량 판별]
    F --> H[탄소 저감량 판별]
    H --> I[이동 기구의 이동 거리 판별]
    H --> J[탄소 배출 계수에 따른 저감량 판별]
    E --> K[증권형 토큰 발행]
    C --> L[주행 목적 판별]
    L --> M[보상 비율에 따른 차등 보상 책정]