flowchart TD
    A[거리 센서의 투광 시스템으로 하여금 객체 상에 광의 3차원 패턴을 투영하게 하는 단계] --> B[거리 센서의 수광 시스템으로 하여금 객체에 투영된 광의 3차원 패턴의 이미지를 획득하게 하는 단계]
    B --> C[상기 수광 시스템으로 하여금 객체의 2차원 이미지를 획득하게 하는 단계]
    C --> D[객체의 2차원 이미지에서 피처 포인트을 검출하는 단계]
    D --> E[상기 피처 포인트에 대한 보간 영역을 식별하는 단계]
    E --> F[상기 보간 영역 내에 있는 복수의 포인트들 중 2개의 포인트들의 3차원 좌표들을 이용하여 보간함으로써 피처 포인트에 대한 3차원 좌표들을 계산하는 단계]