flowchart TD
    A[텍스트-수어 병렬 코퍼스 취득 방법] --> B[전처리 과정]
    B --> C[수어영상 단편화단계]
    C --> D[단편화된 수어영상의 구조화 데이터 생성]
    B --> E[정규화단계]
    E --> F[구간별 구조화 데이터 생성]
    A --> G[분석과정]
    G --> H[ROI 취득단계]
    H --> I[복수의 ROI 취득]
    G --> J[모션데이터 분석단계]
    J --> K[프레임별 요소 데이터 생성 및 저장]
    J --> L[구간별 모션데이터 분석]
    H --> M[신체 부위에 따른 ROI 구분]
    J --> N[핸드 제스쳐 ROI 분석]
    J --> O[상반신 ROI 분석]
    J --> P[머리 ROI 분석]
    N --> Q[수지 및 핸드 요소 데이터 생성]
    O --> R[상반신 요소 데이터 생성]
    P --> S[머리 요소 데이터 생성]
    A --> T[해상도 변환단계]
    T --> U[노이즈 제거단계]
    A --> V[익명화단계]
    A --> W[촬영단계]
    W --> X[저장단계]