flowchart TD
    A[전자지갑 주소 구비] --> B[탑승권 정보 및 수하물 정보 분산 저장]
    B --> C[위탁 수하물의 탑승권 정보 및 실 탑재중량 획득]
    C --> D[승객 수하물 탑재중량 정보 획득]
    D --> E[사용 탑재중량과 실 탑재중량 비교]
    E --> F[신뢰도 판단]
    F --> G[제1보상 할당 및 송금]
    G --> H[미사용 탑재중량 거래 이벤트 발생 시 정보 검색]
    H --> I[판매 승인한 미사용 탑재중량 리스트 표시]
    I --> J[선택된 미사용 탑재중량에 대한 거래 요청 정보 전송]
    J --> K[거래 승인 시 거래체결정보 분산 저장]
    K --> L[제2보상 제공]
    L --> M[미사용 탑재중량 계산 및 보상금액 계산]
    M --> N[미사용 탑재중량 등록량에 따른 제1보상 제공]
    N --> O[거래요청 정보 수신 및 선택]
    O --> P[선택된 거래부로 전송]
    P --> Q[제2보상 현금화 가능한 가상화폐로 제공]