flowchart TD
    A[등록 이미지 제시] --> B[신체 일부 제시 명령]
    B --> C[신체 일부 시계열 후보 이미지 캡쳐링]
    C --> D[후보 이미지 정렬]
    D --> E[후보자 인증]
    E --> F[등록 이미지 캡쳐링]
    F --> G[후보 이미지 시계열 캡쳐링]
    G --> H[후보 이미지 디스플레이]
    H --> I[등록 이미지와 인증 이미지 비교]
    I --> J[정렬 과정] 
    J --> K[정렬 특징 명령]
    K --> L[정렬 기준] 
    L --> M[정렬 특징 그룹] 
    M --> N[미러 인버전 처리]