flowchart TD
    A[악성코드 바이너리 데이터 입력받기] --> B[메타데이터 추출]
    B --> C[메타데이터를 영상 데이터로 변환]
    C --> D[신경망부에서 악성코드 학습]
    C --> E[메타데이터를 그레이스케일 영상 데이터로 변환]
    
    B --> F[메타데이터를 오디오 파일로 변환]
    F --> G[오디오 파일을 스펙트로그램 영상 데이터로 변환]
    
    C --> H[영상 데이터를 미리 정해진 사이즈로 조정]
    
    E --> I[제1 신경망 학습]
    G --> J[제2 신경망 학습]
    
    C --> K[데이터 확장 수행하여 확장 영상 데이터 생성]
    K --> L[주성분분석 적용하여 주성분 피처 추출]
    K --> M[주성분 벡터 산출]
    K --> N[노이즈 지터링을 통해 변형된 관심 영역 생성]
    K --> O[관심 영역을 배경 영상에 융합하여 확장 영상 데이터 생성]
    
    L --> P[악성코드에 대한 학습 수행] 
    
    D --> Q[피처를 t-SNE 알고리즘으로 시각화] 
    
    R[메타데이터 추출부] 
    S[데이터 변환부] 
    T[신경망부] 
    U[제1 영상 생성부] 
    V[오디오 파일 생성부] 
    W[제2 영상 생성부] 
    X[리사이징부]