flowchart TD
    A[하나 이상의 촉각 센서에 기초하여 로봇 디바이스의 자세 식별] --> B[하나 이상의 신경망 사용]
    B --> C[로봇 디바이스가 파지하는 제1 객체의 체적과 동일하거나 작은 제2 객체에 기초]
    C --> D[신경망은 촉각 센서 데이터에 기초하여 훈련]
    D --> E[로봇 디바이스는 복수의 수지부를 갖는 로봇 손]
    E --> F[각 수지부는 촉각 센서 구비]
    F --> G[파지될 객체의 이미지 획득]
    G --> H[획득된 이미지를 사용하여 객체의 6d 자세 추정]
    H --> I[객체의 6d 자세에 기초하여 가상 경계 박스 생성]
    I --> J[가상 경계 박스는 객체의 포인트 클라우드에 기초]
    J --> K[신경망은 인간 손의 이미지에 기초하여 훈련]
    K --> L[신경망은 보상 함수 이용하여 훈련]
    L --> M[보상 함수는 인간 손의 움직임 시연에 기초]
    M --> N[보상 함수는 로봇 디바이스의 능력에 기초]