flowchart TD
    A[사용자 정의 객체 사전을 상기 이미지 캡션 생성 장치의 사용자 정의 객체 사전 데이터베이스에 구축하는 단계] --> B[객체 이미지를 제1 인공신경망에 입력하여 객체 탐지 결과를 출력하는 단계]
    B --> C[상기 사용자 정의 객체 사전을 상기 객체 탐지 결과에 관심 정보로 반영하여 수정된 객체 탐지 결과를 출력하는 단계]
    C --> D[상기 수정된 객체 탐지 결과를 제2 인공신경망에 입력하여 사용자 정의된 이미지 캡션 생성 결과를 출력하는 단계]