flowchart TD
    A[신용 카드와 연관되는 결제 계좌 링크 요청 수신] --> B[검증 필요 여부 결정]
    B -->|검증 필요하지 않음| C[결제 계좌 링크 및 링크 표시 제공]
    B -->|검증 필요함| D[복수의 통신 방법 어포던스 디스플레이]
    D --> E[각 통신 어포던스 활성화 검출]
    E -->|제1 어포던스| F[제1 통신 계정을 통해 검증 통신 요청]
    E -->|제2 어포던스| G[제2 통신 계정을 통해 검증 통신 요청]
    B --> H[각 통신 방법의 대응하는 통신 계정 표시 전송]
    B --> I[검증 통신 수신]
    B --> J[검증 코드 포함 통보 수신]
    J --> K[결제 계좌 링크]
    B --> L[결제 계좌 링크 확인 표시]
    B --> M[검증 코드 요청 사용자 입력 수신]
    M --> N[검증 코드 요청 금융 기관으로 전송]
    N --> O[제2 통보 수신]
    O --> P[검증 코드 포함 제2 통보 수신]