flowchart TD
    A[제N 가상 트레이닝 이미지, 제N 메타 데이터, 제N-K 참조 정보 획득] --> B[제너레이팅 CNN 내의 인코딩 레이어로 컨벌루션 연산 적용]
    B --> C[제N 특징 맵 생성]
    C --> D[디코딩 레이어로 디컨벌루션 연산 적용]
    D --> E[제N 변환 이미지 생성]
    E --> F[디스크리미네이팅 CNN으로 디스크리미네이팅 CNN 연산 적용]
    F --> G[제1 예측 이미지 카테고리 스코어 벡터 생성]
    G --> H[제너레이팅 로스 레이어로 제1 예측 이미지 카테고리 스코어 벡터 및 제1 GT 이미지 카테고리 스코어 벡터 참조하여 제너레이팅 CNN 로스 생성]
    H --> I[백프로퍼게이션 수행하여 제너레이팅 CNN의 파라미터 학습]
    I --> J[디스크리미네이팅 CNN이 제너레이팅 CNN으로부터 출력된 이미지의 카테고리에 대해 틀린 판단을 내릴 확률 증가시키도록 파라미터 학습]