flowchart TD
    A[상품제공서버부(10)에 복수 개의 상품을 등록하고 등록된 상품의 가격을 입력하고, 등록된 상품의 판매수수료를 설정하고 등록된 상품의 샘플 제공 가능여부를 설정하고, 입력되는 메시지를 출력하는 단계(S10)] --> B[위탁판매단말부(20)가 상품제공서버부(10)와 무선 통신으로 연결되며 플랫폼에 접속하여 샘플 제공이 가능한 샘플 요청 신호를 전송하고, 기 설정된 샘플상품의 가격을 결제하는 단계(S20)]
    B --> C[상품제공서버부(10)가 위탁판매단말부(20)에서 요청한 샘플상품에 대응하는 상품의 판매 수량을 산출하고, 산출된 판매 수량과 샘플상품에 해당하는 상품에 설정된 판매수수료를 곱셈 연산하여 판매 보수를 산출하고 판매 보수에 위탁판매단말부(20)에서 결재한 샘플상품의 결제금액을 차감하여 정산 금액을 산출하는 단계(S30)]