flowchart TD
    A[주행 데이터를 이용한 모방 학습에 의해 기초 모델의 학습] --> B[강화 학습 모델을 이용하여 에이전트의 학습 실시]
    B --> C[강화 학습 모델 구성: 액터 네트워크 및 크리틱 네트워크]
    C --> D[액터 네트워크: 제 1 완전 연결층, 제 2 완전 연결층, 제 3 완전 연결층 구성]
    D --> E[크리틱 네트워크: 제 4 완전 연결층 구성]
    E --> F[제 2 완전 연결층 및 제 3 완전 연결층에 드롭 아웃 적용 후 n회 전파]
    F --> G[행동에 대한 보상값 산출: 제 1 통계값 및 제 2 통계값 이용]
    G --> H[제 1 시그모이드 함수값 및 제 2 시그모이드 함수값 산출]
    H --> I[에이전트의 학습 실시: 가중치 고정 상태에서 학습]
    I --> J[에이전트의 학습 실시: 가중치 고정하지 않은 상태에서 학습]