flowchart TD
    A[구매자 단말로부터 의약품 원료 물질에 대한 검색 정보 획득] --> B[구매자 단말에게 의약품 원료 물질에 대한 제품 정보 제공]
    B --> C[구매자 단말로부터 의약품 원료 물질에 대한 주문 정보 획득]
    C --> D[적어도 하나의 공급사 단말에게 의약품 원료 물질에 대한 주문 정보 제공]
    D --> E[적어도 하나의 공급사 단말로부터 견적 정보 획득]
    E --> F[구매자 단말에게 최종 견적 정보 제공]
    F --> G[구매자 단말로부터 구매 요청 정보 획득]
    G --> H[납기 기한 정보에 해당하는 날짜까지 공급 가능량 정보 획득]
    H --> I[최종 견적 정보 생성]
    I --> J[최종 견적 정보를 기반으로 하는 전자결제 링크 포함]
    J --> K[구매자 단말에게 배송추적 정보 제공]
    K --> L[배송원 단말에게 구매자의 주소 제공]
    L --> M[배송원 단말로부터 실시간 위치 정보 획득]
    M --> N[구매자 단말로부터 실시간 재고 정보 획득]
    N --> O[배송원 단말이 구매자의 주소로부터 임계거리 이내로 진입 시 위치 정보 제공]
    O --> P[구체적인 위치 정보에 AR 정보 포함]
    P --> Q[배송원 단말로부터 이미지 정보 획득]
    Q --> R[구매자 단말에게 배송 완료 메시지 전송]