flowchart TD
    A[호스트가 외부 레지스트리로부터 제1 이미지 파일을 획득하는 단계] --> B[호스트가 상기 제1 이미지 파일을 실행함으로써 컨테이너를 생성하는 단계]
    B --> C[호스트가 이미지 파일임을 나타내는 식별자를 포함하는 메타 데이터와 상기 제1 이미지 파일을 상기 스토리지 시스템에 제공하는 단계]
    C --> D[스토리지 시스템이 상기 식별자에 응답하여 상기 제1 이미지 파일을 연속적인 물리 어드레스에 대응하는 저장 영역에 저장하는 단계]
    D --> E[메타 데이터는 상기 제1 이미지 파일의 우선순위를 포함하고]
    E --> F[상기 우선순위가 기설정된 값보다 높은지 여부에 따라 상기 제1 이미지 파일을 상기 저장 영역에서 버퍼 메모리로 로딩하는 단계]
    D --> G[메타 데이터는 상기 이미지 파일에 포함되는 복수의 레이어 이미지들의 우선순위를 포함하고]
    G --> H[상기 복수의 레이어 이미지들 중 기설정된 값보다 높은 우선순위를 갖는 제1 레이어 이미지를 상기 저장 영역에서 버퍼 메모리로 로딩하는 단계]
    H --> I[메타 데이터는 상기 복수의 레이어 이미지들 간의 계층 정보를 포함하고]
    I --> J[호스트가 상기 제1 레이어 이미지에 대한 독출을 상기 스토리지 시스템에 요청하는 단계]
    J --> K[스토리지 시스템이 상기 버퍼 메모리에 로딩된 상기 제1 레이어 이미지를 상기 호스트에 제공하는 단계]