flowchart TD
    A[신호 전송 활동의 패턴들의 복잡성을 판별하는 단계] --> B[입력에 응답하는 다른 신호 전송 활동의 복잡성과 구별 가능한 복잡성을 가진 신호 전송 활동의 타이밍을 판별하는 단계]
    B --> C[구별 가능한 복잡성을 가진 신호 전송 활동의 타이밍에 기반하여 결정 순간을 식별하는 단계]
    A --> D[공동들을 둘러싼 패턴들의 개수를 판별하는 단계]
    B --> E[상기 신호 전송 활동이 상기 순환 인공 신경 네트워크로의 입력에 응답하는가의 여부를 추정하는 단계]
    E --> F[입력 이벤트 이후에 상대적으로 빠르게 신호 전송 활동의 상대적으로 더 복잡한 패턴들이 상기 입력에 응답하지 않는다면 그 입력 이벤트 이후에 상대적으로 빠르게 신호 전송 활동의 상대적으로 더 단순한 패턴들이 상기 입력에 응답한다고 추정]
    E --> G[입력 이벤트 이후에 상대적으로 더 늦게 신호 전송 활동의 상대적으로 더 단순한 패턴들이 상기 입력에 응답하지 않는다면 그 입력 이벤트 이후에 상대적으로 더 늦게 신호 전송 활동의 상대적으로 더 복잡한 패턴들이 상기 입력에 응답한다고 추정]
    B --> H[상기 순환 인공 신경 네트워크 내 순서 정해진 신호 전송 활동을 표시하는 상대적으로 높은 복잡성을 가진 신호 전송 활동의 타이밍을 판별하는 단계]
    A --> I[신호 전송 활동의 소집단 패턴들을 식별하는 단계]
    A --> J[복수의 시간 윈도우들을 한정하는 단계]
    J --> K[상기 복수의 시간 윈도우들 각각에서 신호 전송 활동의 소집단 패턴들을 식별하는 단계]
    K --> L[상기 복수의 시간 윈도우들 중 제1 시간 윈도우 동안에 식별되는 신호 전송 활동의 소집단 패턴들의 구별 가능한 가능성에 기반하여 상기 복수의 시간 윈도우들 중 상기 제1