flowchart TD
    A[명령어를 저장하도록 형상화된 메모리] --> B[메모리와 결합된 하나 이상의 프로세서]
    B --> C[하나 이상의 프로세서는 명령어를 처리하도록 형상화됨]
    C --> D[비접촉식 카드와 연관된 계정 정보를 제3자 지갑에 추가하거나 연결하는 옵션을 제3자 응용프로그램의 GUI 내에 제시]
    D --> E[비접촉식 카드에 대한 계정 정보를 제3자 지갑에 추가하거나 연결하는 옵션의 선택을 제3자 응용프로그램에 의해 감지]
    E --> F[비접촉식 카드를 인증하기 위해 비접촉식 카드로 인증 동작을 수행하도록 제3자 응용프로그램에 의해 결정]
    F --> G[제3자 응용프로그램에 의해, 인증 동작을 수행하도록 제1자 응용프로그램을 유도]
    G --> H[제1자 응용프로그램의 제2 GUI에서 사용자가 기기 위 또는 근처에서 비접촉식 카드를 탭할 수 있는 원터치 인증 옵션을 제시]
    H --> I[비접촉식 카드가 장치의 NFC 범위 내에 들어오면 비접촉식 카드와 근거리 무선 통신(NFC) 교환을 수행]
    I --> J[암호문은 비접촉식 카드를 인증하기 위한 인증 정보를 포함]
    J --> K[비접촉식 카드로부터 NFC 교환의 암호문을 NFC 인터페이스를 통해 제1자 응용프로그램에 의해 수신]
    K --> L[제1자 응용프로그램에 의해 인증 정보를 인증]
    L --> M[인증 정보의 인증에 응답하여, 제3자 응용프로그램에 의해 비접촉식 카드의 계정 정보를 제3자 지갑과 연결하도록 유도]