flowchart TD
    A[도로 상에서 획득된 포인트 클라우드 데이터를 획득하는 동작] --> B[포인트 클라우드 데이터로부터 주행선과 바닥면 데이터를 추출하는 동작]
    B --> C[주행선 상의 각기 제1 간격을 갖는 분할점들을 형성하는 동작]
    C --> D[각 분할점들을 기준으로 좌우 제2 간격의 선들, 이전 분할점을 지나는 선과 이후 분할점들을 지나는 선으로 이루어진 단위 영역들을 서로 중첩되도록 산출하는 동작]
    D --> E[각 단위 영역에 대응하는 바닥면 데이터의 값을 이용하여 인공지능에 기반하여 지정된 객체를 인식하기 위한 인식용 데이터를 생성하는 동작]