flowchart TD
    A[예측 기준 시점 설정] --> B[제1 인공 신경망 학습]
    B --> C[제2 인공 신경망 학습]
    C --> D[학습 결과 업데이트]
    D --> E[제2 인공 신경망을 학습시켜 데이터 예측] 
    B1[상태 추정 네트워크 학습] --> B2[히든 벡터 및 셀 벡터 생성]
    B2 --> C1[상태 전이 네트워크 학습]
    D1[상태 추정 네트워크 학습] --> D2[히든 벡터 및 셀 벡터 업데이트]
    D2 --> C2[상태 전이 네트워크 학습]