flowchart TD
    A[해상풍력터빈 구조물 및 해상풍력터빈 구조물이 설치되는 지반 모델링] --> B[환경하중 정의]
    B --> C[구조해석 수행 및 세굴 취약도 산출]
    C --> D[파괴 기준 정의]
    D --> E[세굴 취약도 평가]
    E --> F[해저면 진폭 계산 및 KC 계산]
    F --> G[세굴 깊이 분포 추정]
    G --> H[세굴 깊이 분포와 세굴 취약도 결합하여 세굴 위험도 평가]