flowchart TD
    A[정사영상수집열서버가 시계열 영상들을 확보하는 단계] --> B[유사도측정서버가 학습모델을 통해 시계열 영상의 유사도를 측정하여 변화여부를 확인하는 단계]
    B --> C[유사도측정서버의 학습모델은 원본이미지와 네거티브이미지를 선정하는 단계]
    C --> D[원본이미지를 토대로 이미지 생성 AI를 통해 유사 이미지를 생성하는 단계]
    D --> E[유사도측정서버는 원본이미지와 네거티브이미지와 유사이미지를 각각 일정하게 벡터화하는 전처리단계]
    E --> F[유사도측정서버는 ResNet50 딥러닝 모델을 통해 특징값을 추출하는 추출단계]
    F --> G[유사도측정서버는 Triplet Loss모델을 통해 클러스터링하는 학습단계]
    A --> H[정사영상수집열서버가 위치 정합된 정사영상들을 확보하는 단계]
    B --> I[유사도측정서버는 시계열 영상의 유사도를 측정하여 변화여부를 확인하는 단계]
    I --> J[각각의 시계열 영상 위에 레이어를 형성한 후 블록화하는 단계]
    J --> K[동일지역의 각 시계열 영상의 블럭 간 유사도를 측정하는 단계]
    K --> L[블럭 단위별로 변화여부 및 그 정도를 확인할 수 있게 표출하는 단계]