flowchart TD
    A[실험 디자인을 구성하는 요소를 벡터화를 통해 수치화하는 전처리부] --> B[수치화된 상기 실험 디자인을 구성하는 요소를 전달 받아 심층 신경망 기반의 생성 모델을 이용하여 실험의 특정 실험 변수들을 인코딩하는 실험 변수 인코딩부]
    B --> C[인코딩된 상기 실험 변수들의 조합을 통해 사용자가 의도한 실험 변수의 조합으로 상기 실험 디자인을 재구성하는 실험 생성 모델부]
    B --> D[가설 시각화 모듈을 통해 인코딩된 실험 변수를 추출]
    D --> E[각 실험 변수 중 중요한 부분을 하이라이트 해주는 히트 맵을 출력]
    C --> F[상기 실험 변수 인코딩부에서 인코딩된 실험 변수를 입력 받아 업샘플링을 통해 실험 디자인을 생성하도록 학습]
    C --> G[가설 임베딩 모듈을 통해 잠재 태스크 벡터에 대한 정보를 찾아 상기 실험 디자인을 구성하는 요소로 반영]