flowchart TD
    A[회원가입된 사용자에게 가상계좌를 렌탈 또는 발급하여 관리하는 가상계좌관리단계] --> B[상기 가상계좌와 연결된 회원카드를 렌탈하여 관리하는 회원카드관리단계]
    B --> C[업체단말로부터 상기 회원카드의 결제정보를 수신하면, 상기 가상계좌의 잔액을 조회하여 상기 결제정보의 금액 이내인 경우 상기 사용자의 기 설정된 사용자단말로 전송하도록 하고, 상기 사용자단말로부터 결제확인정보의 수신 여부에 따라 상기 결제정보의 승인 여부를 결정하는 결제관리단계]
    C --> D[상기 업체단말로부터 상기 결제정보에 대한 결제완료정보를 수신하면 상기 가상계좌로부터 상기 결제정보에 따른 사용금액을 차감하여 상기 업체단말의 계정으로 이체시키도록 하는 이체처리단계]
    D --> E[상기 사용자단말로 기 설정된 시간 주기로 검증정보를 전송하고, 상기 사용자단말로부터 기 설정된 시간 이내에 상기 검증정보에 대한 검증확인정보가 수신되지 않는 경우 상기 가상계좌를 비활성화시키는 검증단계]
    E --> F[상기 사용자단말을 통해 입력된 사진 및 위치정보를 이용하여 상기 사용자의 활동정보를 수집하고, 상기 활동정보에 따라 보상수단을 차등하여 지급하는 보상단계]