flowchart TD
    A[운전자의 최근 주행 경로 분석] --> B[충돌 확률 계산]
    B --> C[학습 장치가 검증용 상황 정보 획득]
    C --> D[상태 네트워크로 상태 특징 맵 생성]
    C --> E[궤적 네트워크로 궤적 특징 맵 생성]
    D --> F[컨캐터네이팅된 특징 맵 획득]
    F --> G[안전성 네트워크로 예측 충돌 확률 산출]
    G --> H[로스 레이어로 로스 생성]
    H --> I[백프로퍼게이션 수행]
    I --> J[네트워크 파라미터 학습]