flowchart TD
    A[구매자로부터 구매하고자 하는 하나 이상의 상품을 입력받는 단계] --> B[상기 입력된 하나 이상의 상품에 대한 결제 프로세스를 수행하는 단계]
    B --> C[상기 결제 프로세스가 완료되는 것에 응답하여 상기 입력된 하나 이상의 상품에 대한 판매를 승인하고, 상기 입력된 하나 이상의 상품의 판매에 관한 판매 데이터를 출력하는 단계]
    A1[상기 하나 이상의 상품을 입력받는 단계] --> A2[상기 구매자의 구매자 단말에 기 설치된 애플리케이션을 실행함에 따라 상기 무인 매장에서 판매하는 복수의 상품에 대한 정보를 포함하는 상품 리스트를 제공]
    A2 --> A3[상기 상품 리스트에 포함된 복수의 상품 중 상기 하나 이상의 상품을 선택받거나, 상기 무인 매장에 비치된 키오스크를 통해 상기 하나 이상의 상품에 인쇄된 바코드를 스캔함으로써, 상기 하나 이상의 상품을 입력받는 단계]
    B1[상기 결제 프로세스를 수행하는 단계] --> B2[상기 애플리케이션에 일회용 보안코드를 전송하는 단계]
    B2 --> B3[상기 키오스크를 통해 상기 일회용 보안코드를 인식하는 단계]
    B3 --> B4[본인 인증을 수행하는 단계]
    B4 --> B5[현금 및 카드 중 적어도 하나를 이용하여 상기 입력된 하나 이상의 상품에 대한 결제를 진행하되, 기 설정된 제1 비율에 따라 결제 금액의 적어도 일부를 제휴 카드사 포인트 또는 제휴 통신사 포인트를 포함하는 제1 포인트로 결제하거나 기 설정된 제2 비율에 따라 상기 결제 금액의 적어도 일부를 상기 무인 매장과 제휴된 복수의 회사 각각으로부터 발급된 회사 복지 포인트를 포함하는 제2 포인트로 결제하는 단계]
    C1[상기 무인 매장에 진열된 복수의 상품 각각의 재고량에 기초하여, 상기 복수의 상품 중 상기 재고량이 기준 값 이하인 적어도