flowchart TD
    A[시각 정보 및 예측된 관심 영역 정보 입력] --> B[제1 인공 신경망 학습]
    B --> C[청각 정보 및 예측된 관심 영역 정보 입력]
    C --> D[제2 인공 신경망 학습]
    D --> E[청각 정보 입력 및 관심 영역 예측]
    E --> F[제3 인공 신경망 학습]
    F --> G[복수 개의 시청각 관심 영역 특징점 생성]
    G --> H[제4 인공 신경망 학습]
    H --> I[각 시각 관심 영역 특징점의 객체 여부 분류]
    I --> J[제5 인공 신경망 학습]
    J --> K[각 청각 관심 영역 특징점의 객체 여부 분류]
    K --> L[제6 인공 신경망 학습]
    L --> M[청각 관심 영역 벡터 출력]
    L --> N[시청각 관심 영역 벡터 출력]
    M --> O[가중치 상호 공유]