flowchart TD
    A[리워드 지급 예정 이벤트 감지] --> B[리워드 디지털 자산 발행 및 제공]
    B --> C[예약 요청 감지]
    C --> D[예약보증금 자동 지급]
    D --> E[예약 요청 예약 확정 처리]
    E --> F[노쇼 여부 판단]
    F --> G[노쇼 처리]
    G --> H[신용등급 발급]
    F --> I[노쇼가 아닐 경우 예약보증금 반환]
    H --> J[신용등급 차등 부여 및 NFT 배지 지급]
    J --> K[고 신용등급 소비자 예약 거래 면제 또는 완화]