flowchart TD
    A[제1 업체 단말로부터 제1 제품에 대한 판매 요청 정보를 수신하는 단계] --> B[상기 판매 요청 정보를 기초로, 상기 제1 제품의 카테고리, 타겟 고객층, 판매 기간 및 판매 예산을 확인하여, 상기 제1 제품의 판매 요구 사항을 분석하는 단계]
    B --> C[SNS 서버로부터 미리 설정된 기간마다 인플루언서 정보를 획득하는 단계]
    C --> D[상기 인플루언서 정보를 기초로, 인플루언서 별로 전문 카테고리 및 영향력 지표를 분석하여, 인플루언서 별로 SNS 활동 현황을 분석하는 단계]
    D --> E[상기 판매 요구 사항의 분석 결과 및 상기 SNS 활동 현황의 분석 결과를 매칭하여, 매칭 결과를 생성하는 단계]
    E --> F[상기 매칭 결과를 인공 신경망에 적용하여, 상기 인공 신경망의 출력을 기초로, 상기 제1 제품의 판매가 가장 적합할 것으로 예상되는 인플루언서를 제1 인플루언서로 선정하는 단계]
    F --> G[상기 제1 제품의 판매에 대한 추천 정보를 제1 인플루언서 단말로 전송하는 단계]
    G --> H[상기 제1 인플루언서 단말로부터 상기 제1 제품에 대한 판매 개시 요청이 수신되면, 상기 제1 인플루언서와 연계하여 상기 제1 제품을 판매하는 판매 페이지인 제1 페이지를 생성하는 단계]
    H --> I[상기 제1 인플루언서에 의해 상기 제1 제품을 소개하는 콘텐츠인 제1 콘텐츠가 제작되어 상기 제1 콘텐츠가 동영상 공유 사이트에 업로드 된 이후, 상기 제1 페이지의 접속을 통해 상기 제1 제품이 판매되면, 상기 제1 페이지를 통해 판매되는 상기 제1 제품의 판매 실적을 상기 제1 인플루언서의 판매 실적으로 산정하는 단계]
    I --> J[상기 제1 인플루언서의 판매 실적을 기반으로, 상기 제1 인플루언서와의 협