flowchart TD
    A[거래 차량 정보, 계약 조건, 보험 및 서비스 조건 포함한 중고차 거래 데이터 수집] --> B[금융사 별 견적 산출]
    B --> C[금융사 선택]
    C --> D[가심사 신청 및 사용자 한도 조회]
    D --> E[본심사 신청 및 확정 견적 조회]
    E --> F[본심사 승인 시 거래 중개]
    F --> G[계약 진행 상태 조회]
    G --> H[계약 완료 시 거래 차량 출고 허가]
    A1[사용자 정보 수집] --> A2[운전면허증 이미지 수신]
    A2 --> A3[사용자 정보 획득]
    A3 --> A4[사용자 소득증빙자료 획득]
    A4 --> A5[사용자 인증 수행]
    A5 --> A6[사용자 신용 정보 획득]
    A6 --> A7[자산 내역 열람 동의 요청]
    A7 --> A8[자산 정보 획득]
    A8 --> A9[소득원 및 정기 소득 여부 식별]
    A9 --> A10[1차 시뮬레이션 수행]
    A10 --> A11[1차 순위 생성]
    A1 --> A12[추가 소득 증빙 자료 열람 동의 요청]
    A12 --> A13[추가 소득 정보 획득]
    A13 --> A14[2차 시뮬레이션 수행]
    A14 --> A15[2차 순위 생성]