flowchart TD
    A[서버와 전자 장치 통신] --> B[캠핑 장소 DB 포함]
    B --> C[캠핑 장소 등록 정보 저장]
    C --> D[캠핑카 소유자의 등록 요청 수신]
    D --> E[캠핑카 등록]
    E --> F[부킹 체결 요청 수신]
    F --> G[부킹 수행]
    G --> H[부킹된 캠핑카 인수 확인]
    H --> I[부킹된 캠핑카 대여 개시]
    I --> J[캠핑카 반납 처리]
    J --> K[캠핑카 이용 상태 변경]
    K --> L[추천 캠핑 장소 선별]
    L --> M[추천 캠핑 장소 목록 형성]
    M --> N[추천 캠핑 장소 목록 전송]
    I --> O[인수 상태 확인 정보 수신]
    O --> P[신분 매칭 확인 정보 수신]
    P --> Q[대여 계약서 양식 전송]
    Q --> R[완성된 대여 계약서 수신]
    R --> S[캠핑카 이용 상태 변경]
    L --> T[주행 편의 등급 산출]
    T --> U[추천 캠핑 장소 목록 생성]
    U --> V[주행 편의 등급 산출 규칙 적용]