flowchart TD
    A[인스트럭션 프로세싱 유닛] --> B[기능 프로세싱 유닛]
    B --> C[제1 기능 프로세싱 모듈]
    B --> D[제2 기능 프로세싱 모듈]
    C --> E[ALU 레지스터 접근]
    D --> F[FPU 스택 접근]
    C --> G[데이터 읽기, 쓰기 및 수정 처리]
    D --> H[데이터 읽기, 쓰기 및 수정 처리]
    A --> I[프로그램 카운터]
    A --> J[인스트럭션 로더]
    A --> K[인스트럭션 큐]
    I --> L[다음 인스트럭션 주소 지정]
    I --> M[프로그램 카운터 값 증가]
    J --> N[인스트럭션 읽기]
    K --> O[인스트럭션 저장 및 접근 지원]
    A --> P[인스트럭션 프로세서]
    P --> Q[인스트럭션 페쳐]
    P --> R[인스트럭션 분해기]
    P --> S[기능 선택기]
    R --> T[오퍼랜드 없는 인스트럭션 처리]
    R --> U[오퍼랜드 있는 인스트럭션 처리]
    B --> V[FPU 스택]
    V --> W[레지스터 스택]
    V --> X[연산전용 레지스터]
    X --> Y[제1 직접 접근 레지스터]
    X --> Z[제2 직접 접근 레지스터]
    X --> AA[결과 저장 레지스터]