flowchart TD
    A[디스플레이를 가지는 전자 디바이스에서 전자 지갑 디스플레이] --> B[인가된 결제 계좌와 연관되는 제2 결제 거래 진행]
    B --> C[제2 거래 정보를 디스플레이]
    C --> D[제2 결제 거래에 관여하는 중개 기관으로부터 제1 추가 정보 수신]
    D --> E[제1 추가 정보를 포함하도록 제2 거래 정보의 디스플레이 업데이트]
    E --> F[제2 추가 정보 수신]
    F --> G[제2 거래 정보의 디스플레이 업데이트]
    A --> H[제1 결제 거래 완료]
    A --> I[물리적 신용 카드 이용하여 제1 결제 거래 완료]
    A --> J[금융 기관으로부터 문자 메시지 수신]
    J --> K[문자 메시지 디스플레이]
    K --> L[문자 메시지 선택 수신]
    L --> M[특정 애플리케이션 디스플레이]
    A --> N[가용 신용 금액 디스플레이]
    A --> O[계좌 상세사항 어포던스 디스플레이]
    O --> P[계좌 상세사항 어포던스 선택 수신]
    P --> Q[거래 상세사항 디스플레이]