flowchart TD
    A[병리 슬라이드 이미지 획득] --> B[면역 세포 및 종양 세포 정보 결정]
    B --> C[면역-종양 세포 상호작용 스코어 산출]
    C --> D[상호작용 스코어를 이용한 반응성 예측]
    
    B --> E[면역 세포 및 종양 세포 위치 결정]
    B --> F[면역 세포 및 종양 세포 조직 정보 결정]
    
    C --> G[면역 세포 및 종양 세포 사이의 거리 산출]
    C --> H[산출된 거리 이용하여 상호작용 스코어 산출]
    
    H --> I[특성에 따른 가중치 결정]
    H --> J[특성 및 거리 이용하여 상호작용 스코어 산출]
    
    D --> K[기계학습 모델에 상호작용 스코어 입력]
    D --> L[반응성 나타내는 값 출력]