flowchart TD
    A[사용자 단말들로부터 특정 크리에이터를 표상하는 굿즈의 추천을 수집하고 추천된 각각의 굿즈에 대한 온라인 팬투표를 수행하는 단계] --> B[상기 온라인 팬투표의 결과를 크리에이터 단말로 제공된 굿즈관리UI에 노출시키는 단계]
    B --> C[상기 크리에이터 단말로부터 출시 굿즈의 입력을 수신하고 상기 출시 굿즈의 제품화를 위한 굿즈제작UI를 상기 크리에이터 단말로 제공하는 단계]
    C --> D[상기 크리에이터 단말의 정산 요청에 응답하여 제품화된 출시 굿즈의 판매에 따른 수익금 중 기 설정된 비율의 금액을 상기 크리에이터 단말로 제공하는 단계]
    A --> E[기 수집된 크리에이터 별 콘텐츠의 종류 및 팔로워의 식별정보를 기 설정된 기계학습 모델에 적용하여 상기 특정 크리에이터의 유사 크리에이터를 적어도 하나 이상 추출하는 단계]
    E --> F[추출된 유사 크리에이터가 출시한 굿즈의 품목을 종합하고 매출액, 판매량, 출시횟수, 리뷰수, 리뷰만족도 및 정산액 중 적어도 하나 이상을 기준으로 각 품목에 대한 우선순위를 파악하는 단계]
    B --> G[상기 크리에이터 단말에 의해 미리 설정된 굿즈에 관한 선호조건 순서에 따라, 상기 기준 별로 파악된 각각의 우선순위에 기초하여 굿즈의 품목을 추천하는 추천 리스트를 생성하고 상기 굿즈관리UI에 표시하는 단계]
    B --> H[상기 크리에이터가 출시한 굿즈 및 상기 크리에이터의 팔로워에 관한 통계 데이터를 기 설정된 양식으로 시각화하여 상기 굿즈관리UI에 표시하는 단계]
    H --> I[상기 통계 데이터는 팔로워의 성별 및 연령 분포, 굿즈의 품목 별 매출액 및 판매량, 굿즈를 구매한 구매자의 성별 및 연령 분