flowchart TD
    A[이미지 수신] --> B[카테고리 세트 결정]
    B --> C[이미지 시그니처 생성]
    C --> D[게시물 세트 식별]
    D --> E[게시물에 등급 할당]
    E --> F[게시물 목록 프리젠테이션]
    F --> G[양태 세트 식별]
    G --> H[신뢰 스코어 생성]
    H --> I[메타데이터 디스크립터 세트 식별]
    I --> J[양태 등급 스코어 생성]
    J --> K[수정된 등급이 매겨진 게시물 목록 생성]
    B --> L[양태 세트 식별]
    L --> M[카테고리 결정]