flowchart TD
    A[학습용 자율 주행 자동차의 학습용 전방 카메라와 후방 카메라에 시퀀스 이미지 획득] --> B[제1_k 트레이닝 이미지와 제2_k 트레이닝 이미지로 구성된 페어 입력]
    B --> C[제k CNN으로 컨캐터네이팅]
    C --> D[컨벌루션 연산 적용하여 학습용 제1 특징 맵 내지 학습용 제n 특징 맵 생성]
    D --> E[학습용 제1 특징 맵 내지 제n 특징 맵을 포워드 RNN에 입력]
    E --> F[제1_k LSTM 모델에서 학습용 제1_k 업데이트 특징 맵 생성]
    F --> G[FC 연산을 적용하여 학습용 제1_1 특징 벡터 내지 제1_n 특징 벡터 생성]
    E --> H[제2_k LSTM 모델에서 학습용 제2_k 업데이트 특징 맵 생성]
    H --> I[FC 연산을 적용하여 학습용 제2_1 특징 벡터 내지 제2_n 특징 벡터 생성]
    G --> J[어텐션 레이어로 입력하여 학습용 자율주행 모드 값 생성]
    I --> J
    J --> K[로스 레이어로 학습용 자율주행 모드 값과 GT 참조하여 로스 산출]
    K --> L[백프로퍼게이션을 통해 로스 최소화]