flowchart TD
    A[정품 정보를 제공하는 상품 공급자 단말] --> B[해외 셀러 단말]
    B --> C[국가 별 마켓 분석 결과 제공]
    C --> D[상품 공급자의 제품 공급 가능 여부 제공]
    D --> E[정품정보를 모델에 학습시켜 가품 탐지 모델 구현]
    E --> F[가품 탐지 모델을 통해 해외 셀러의 가품 제거]
    F --> G[마켓분석정보를 상품 공급자 단말로 제공]
    G --> H[정품의 지식재산권 등록]
    H --> I[해외 셀러 별 판매루트 파악]
    I --> J[판매 루트에 대한 문제점 검출]
    J --> K[검출된 문제점을 해외 셀러에게 제공]
    K --> L[셀러 정보 수집 및 평가]
    L --> M[셀러와 상품 공급자의 매칭 점수 산출]
    M --> N[셀러와 상품 공급자 매칭]
    N --> O[정품 이미지 데이터 분석]
    O --> P[사용자 반응 분석]
    P --> Q[소셜 미디어 데이터 분석]
    Q --> R[가품 판매 플랫폼, 지역 및 사용자 그룹 식별]
    R --> S[디지털 워터마크 삽입]
    S --> T[가격 변동 실시간 분석]
    T --> U[의심 제품 필터링]
    U --> V[지식재산권(IP) 정보 수집]
    V --> W[지식재산권 데이터베이스에 저장]
    W --> X[정품 식별을 위한 시리얼 번호, 모델 번호, QR 코드 연계]
    X --> Y[지식재산권 등록 블록체인 관리]
    Y --> Z[셀러의 주문 이력 데이터 분석]
    Z --> AA[셀러의 물류 경로 및 배송 정보 수집]
    AA --> AB[판매 채널 파악 및 데이터 통합]
    AB --> AC[판매 루트 주요 특성 시각화]
    AC --> AD[가격 모니터링 및 위반 시 알림 전송]