flowchart TD
    A[입력 시퀀스 수신] --> B[입력 시퀀스 프로세싱]
    B --> C[어텐션 블록 입력 생성]
    C --> D[쿼리 입력, 키 입력, 값 입력 수신]
    D --> E[어텐션 계층 입력 수신]
    E --> F[어텐션 메커니즘 적용]
    F --> G[어텐션 계층 출력 생성]
    G --> H[게이팅 신경망 계층 수신]
    H --> I[게이팅 메커니즘 적용]
    I --> J[게이팅된 어텐션 출력 생성]
    J --> K[정규화된 쿼리 입력, 키 입력, 값 입력 생성]
    K --> L[정규화된-게이팅된 어텐션 출력 생성]
    L --> M[템포러리 어텐션 블록 출력 생성]