flowchart TD
    A[제1 결제 관리 서버가 모(母) 카드에 설정된 제1 지급 한도를 제2 지급 한도로 분할하여 가상 카드 발행] --> B[결제 매개 수단의 발행사가 제2 결제 관리 서버를 사용하여 가상 카드 정보 전달받고 결제 매개 정보 생성 후 발행]
    B --> C[사용자에 의해 가맹점 단말기가 결제 요청을 받은 경우, 결제 요청 신호를 제2 결제 관리 서버로 전송]
    C --> D[제2 결제 관리 서버가 결제 요청 신호에 포함된 결제 매개 정보로부터 가상 카드 정보 추출 후 승인 요청 신호를 제1 결제 관리 서버로 전송]