flowchart TD
    A[협력사의 월간 매출액, 월간 판매량, 월간 반품률, 주간 매출액, 주간 판매량 및 주간 반품률에 따라 협력사의 등급을 계산하는 단계] --> B[계산된 협력사의 등급에 따라 빠른 정산 가능 금액을 계산하는 단계]
    B --> C[협력사의 빠른 정산 신청 금액과 계산된 빠른 정산 가능 금액을 비교하여 협력사의 빠른 정산 신청을 결정하는 단계]
    C --> D[협력사의 등급을 판단하는 단계]
    D --> E[협력사의 월간 매출액, 월간 판매량, 월간 반품률, 주간 매출액, 주간 판매량 및 주간 반품률 각각이 복수의 등급들 중 어디에 속하는지 판단하는 단계]
    E --> F[판단된 등급들에 따라 부여된 점수들을 합산하는 단계]
    F --> G[합산된 점수에 따라 협력사의 등급을 판단하는 단계]
    B --> H[판단된 협력사의 등급에 대응하여 제1비율과 전주 주문 건 정산 가능 금액을 곱하여 빠른 정산 가능 금액을 예비적으로 계산하는 단계]
    H --> I[판매사의 현재 잔고, 전주 결제금액, 및 예상 지출에 따라 전주 대비 이번주 예상 잔고 비율을 계산하는 단계]
    I --> J[복수의 등급에 따라 나뉜 테이블에서 전주 대비 이번주 예상 잔고 비율과 대응하는 제2비율을 찾는 단계]
    J --> K[전주 주문 건 정산 가능 금액과 제2비율을 곱한 금액을 빠른 정산 가능 추가 금액으로 결정하는 단계]
    K --> L[예비적으로 계산한 빠른 정산 가능 금액에 빠른 정산 가능 추가 금액을 더하여 빠른 정산 가능 금액을 최종적으로 결정하는 단계]