flowchart TD
    A[구인 정보 등록] --> B[구직 정보 등록]
    B --> C[회원 관리 기능 수행]
    C --> D[인력 발주 내용 입력]
    D --> E[인력 관리 업체 추천]
    E --> F[인재 리스트 생성]
    F --> G[구직자 정보 등록]
    G --> H[구인 단말 및 구직 단말 통신]
    H --> I[구인 및 구직 기능 수행]
    I --> J[면접 후보자 선정]
    J --> K[최종 합격자 선정]
    K --> L[합격자 정보 표시]