flowchart TD
    A[학생 단말] --> B[시설 단말]
    B --> C[배달자 단말]
    C --> D[플랫폼 제공 서버]
    D --> E[예약 기능 제공]
    D --> F[학식 상호 배달 기능 제공]
    D --> G[마일리지 적립 기능 제공]
    D --> H[학생 식당 구독 서비스 제공]
    D --> I[커뮤니티 기능 제공]
    D --> J[실시간 인기 식당 및 인기 메뉴 기능 제공]
    D --> K[그린 캠퍼스 기능 제공]
    D --> L[예상 배달 시간 계산]
    L --> M[배달자 정보 및 신뢰도 산출]
    M --> N[배달자 정보 업데이트]
    L --> O[재료 부족 메뉴 처리]
    O --> P[대체 메뉴 안내]