flowchart TD
    A[어플리케이션 프로그램에 의해 백그라운드 상태 또는 포어그라운드 상태에 따라 권한 저장] --> B[권한을 정상 권한 및 위험 권한으로 분류]
    B --> C[접근 요청 수신]
    C --> D[포어그라운드 상태에서 제1 동작 수행]
    D --> E[제1 동작 수행 중 백그라운드 상태로 전환]
    E --> F[권한의 획득 요청 확인]
    F --> G[위험 권한으로 분류 및 사용 제한]
    F --> H[위험 권한으로 분류 및 접근 허용]