flowchart TD
    A[입력 이미지 획득] --> B[기준 이미지 검색]
    B --> C[기준 영역 식별]
    C --> D[유사성 맵 획득]
    D --> E[기준 부분 후보 선택]
    E --> F[최상의 매칭 기준 부분 선택]
    F --> G[차이 맵 발생]
    G --> H[복수의 차이 맵 획득]
    H --> I[복합 차이 맵 결합]
    A --> J[슬라이딩 윈도우 사용]
    A --> K[세그먼트화]
    A --> L[오경보 차이 발생]
    L --> M[이미징 조건 차이]
    B --> N[인스턴스 디스크립터 사용]