flowchart TD
    A[AR 시스템의 외향 카메라를 사용하여 환경의 이미지 획득] --> B[사람, 제1 문서, 제2 문서 검출]
    B --> C[제1 문서의 제1 부분 분석하여 제1 개인 정보 추출]
    C --> D[제2 문서의 제2 부분 분석하여 제2 개인 정보 추출]
    D --> E[사람의 제3 부분 분석하여 제3 개인 정보 추출]
    E --> F[제1 개인 정보, 제2 개인 정보, 제3 개인 정보 매치에 기초하여 링키지 결정]