flowchart TD
    A[공공 데이터 수집] --> B[시계열 데이터 생성]
    B --> C[학습용 이미지 데이터셋 변환]
    C --> D[CNN 모델에서 학습]
    D --> E[미세먼지 발생 여부 판단]
    E --> F[미세먼지 발생 등급 추론]
    F --> G[RNN 모델로 등급 보정]
    G --> H[미세먼지 농도 예측]
    H --> I[예측된 미세먼지 농도 수치적 표시]
    I --> J[가중치 적용하여 표준편차 유지]