flowchart TD
    A[자연 언어 형식의 질의 입력을 수신하는 단계] --> B[상기 질의 입력에 관련된 이미지 입력을 수신하는 단계]
    B --> C[상기 질의 입력 및 상기 이미지 입력을 멀티모드 질의 응답(mQA) 모델에 입력하여 순차적으로 생성되는 다중 문자를 포함하는 응답을 생성하는 단계]
    C --> D[제1 문자 임베딩층 및 제1 장단기 메모리(LSTM) 층을 포함하는 제1 LSTM 부재를 이용하여 질의 입력의 어의적 의미를 추출하는 단계]
    D --> E[심층 나선형 신경망(CNN) 부재를 이용하여 상기 질의 입력에 관련된 이미지 입력의 표현을 생성하는 단계]
    E --> F[제2 문자 임베딩층 및 제2 LSTM 층을 포함하는 제2 LSTM 부재를 이용하여 상기 응답 중의 현재 문자의 표현을 추출하는 단계]
    F --> G[상기 어의적 의미, 상기 이미지 입력의 표현 및 상기 응답 중의 현재 문자의 표현을 융합하여 상기 응답 중의 다음 문자를 예측하는 단계]