flowchart TD
    A[거래 요청 수신] --> B[식별 데이터 수신]
    B --> C[사용자 고유 식별 여부 판단]
    C --> D[동일성 정보 제공 여부 판단]
    D --> E[추가 사용자 식별자 요청 반복]
    E --> F[구매 릴리스 파라미터 설정]
    F --> G[거래 인가]
    G --> H[지불 요청 전 거래 인가 추가]
    H --> I[사용자 데이터 제시]
    I --> J[소셜 미디어 서비스로부터 사용자 식별 정보 획득]
    J --> K[지불 방법 선택 전 거래 인가]
    K --> L[사용자 지불 정보 수신 전 거래 인가]
    L --> M[사용자 지불 정보 수신 전 거래 완료]