flowchart TD
    A[3D 스캔을 하여 타겟 손가락의 손가락 3D 데이터 DataFinger를 획득] --> B[손가락 3D 데이터를 3D 포인트 클라우드 데이터로 전환하여 손가락 포인트 클라우드 CloudFinger를 획득]
    B --> C[손가락 포인트 클라우드 CloudFinger를 분할하여 손톱 곡면 포인트 클라우드 CloudNail-s를 획득]
    C --> D[손톱 곡면 포인트 클라우드 CloudNail-s의 표면적을 평탄화하여 손톱 평면 포인트 클라우드 CloudNail-p를 획득]
    D --> E[손톱 평면 포인트 클라우드 CloudNail-p의 윤곽 포인트 클라우드 CloudContour의 형상에 기반하여 그리기를 진행하여 손톱의 손톱 형태를 획득]