flowchart TD
    A[사용자의 안면 이미지 업로드] --> B[성형전 이미지와 매핑된 후기 데이터 출력]
    C[성형전 이미지, 성형후 이미지, 부위 데이터, 후기 데이터, 의료기관 데이터 수집] --> D[빅데이터 구축]
    D --> E[부위 데이터, 후기 데이터, 의료기관 데이터 성형후 이미지에 매핑하여 저장]
    F[안면 이미지를 인공지능 알고리즘에 질의] --> G[유사도를 초과하는 성형전 이미지 추출]
    G --> H[추출된 성형전 이미지와 매핑된 후기 데이터를 사용자 단말로 전송]
    I[성형부위 선택 시 부위 데이터와 일치하는 후기 데이터 추출] --> J[사용자 단말로 제공]
    K[인공지능 알고리즘 모델링 시 얼굴 특징점 기반 학습 및 검증] --> L[유사도를 초과하는 성형전 이미지 선택]
    M[성형후 이미지 선택 후 의료기관 질의] --> N[의료기관 데이터 전송]
    O[유사도를 초과하여 성형전 이미지 분할 및 부위 데이터 라벨링] --> P[부분 이미지와 후기 데이터 전송]
    Q[의료진 성명 선택 시 의료기관 홈페이지 엑세스 및 검색] --> R[의직 안내]
    S[후기 데이터 언어 번역] --> T[사용자가 설정한 언어로 제공]
    U[의료기관 데이터 선택 시 후기 데이터 분류 및 요약 제공] --> V[문서요약 알고리즘으로 요약]