flowchart TD
    A[판매자 단말에서 차량 정비소의 위치 및 영업시간 등록] --> B[판매자 단말에서 차량부품 판매 데이터 업로드]
    C[구매자 단말에서 차량부품 검색] --> D[검색결과 내 차량부품 선택 및 구매]
    E[구매자 단말에서 결제 이벤트 전송] --> F[판매자 단말에서 운송장 등록]
    G[판매자 단말에서 배송 트래킹 결과 공유] --> H[구매자 단말에서 수취확인]
    I[판매자 단말로 대금 정산] --> J[판매자 단말에서 차량부품 모델명 입력]
    K[모델명으로 거래가격 평균가 제시] --> L[판매자 단말에서 재고 데이터 업로드]
    M[재고소진 이벤트 출력] --> N[재고 데이터 업로드]
    O[구매자 단말에서 안전거래 요청] --> P[차량부품 작동여부 확인]
    Q[진동, 전류 및 속도 분석] --> R[상태 진단 및 고장발생 시기 예측]
    S[구매자 단말에 제공]
    T[모델명에 따른 차량부품 상태 분석 및 가격 제공]
    U[판매자 단말에서 차량부품 사진 및 바코드 입력]
    V[웹크롤러로 차량부품 사양 수집]
    W[수집된 사양 및 사진 매핑하여 업로드]
    X[모든 재고 판매 시 자동 검색 및 업로드]
    Y[위치 기반 검색 시 차량 정비소 위치 및 가격 표시]
    Z[카테고리 선택하여 차량부품 검색]