flowchart TD
    A[검출 단계] --> B[터치 종류 판별 단계]
    B --> C[행동 제어 단계]
    B --> D[압력 터치 판별]
    D --> E[행동 제어 단계 - 압력 터치]
    E --> F[소정 위치 확인]
    F --> G[행동 수행]
    B --> H[단순 터치 판별]
    H --> I[행동 제어 단계 - 단순 터치]
    I --> J[제1 행동 수행]
    I --> K[제2 행동 수행]
    B --> L[약한 압력 터치 판별]
    L --> M[행동 제어 단계 - 약한 압력 터치]
    M --> N[제2 행동 수행]
    L --> O[강한 압력 터치 판별]
    O --> P[행동 제어 단계 - 강한 압력 터치]
    P --> Q[제3 행동 수행]
    A --> R[터치 시간 검출]
    R --> S[행동 제어 단계 - 기준시간범위 확인]
    S --> T[행동 수행]
    S --> U[다른 행동 수행]