flowchart TD
    A[하드웨어 회로의 메모리의 제1 부분으로부터 입력 텐서 전송] --> B[행렬 곱셈 회로에서 텐서 생성]
    A --> C[하드웨어 회로의 메모리의 제2 부분으로부터 커널 전송]
    B --> D[입력 텐서와 커널의 콘볼루션 수행하여 제1 텐서 생성]
    D --> E[제1 텐서와 제1 마스킹 텐서의 엘리먼트-별 곱셈 수행하여 제2 텐서 생성]
    E --> F[제2 텐서와 제2 마스킹 텐서의 엘리먼트-별 곱셈 수행하여 출력 텐서 생성]