flowchart TD
    A[사용자의 소셜 미디어 게시물 수집] --> B[LSTM, 셀프 어텐션, BiTCN이 결합된 앙상블 모델을 통해 자살 표현 식별]
    B --> C[위험군으로 분류 또는 관리자 모니터링 대상 선정]
    C --> D[실시간 데이터를 기초로 자살 관련 위험도 평가]
    B --> E[자살 징후 내용과 자살과 관련 없는 내용 분리]
    B --> F[LSTM 레이어를 포함하는 앙상블 모델]
    F --> G[드롭아웃 레이어에서 처리된 벡터 표현 수신]
    F --> H[BiTCN 레이어가 문장 내 단어의 순방향 및 역방향 시퀀스 처리]
    F --> I[셀프-어텐션 레이어 배치]
    G --> J[드롭아웃 레이어 배치]
    A --> K[자연어 툴킷을 통한 토큰화된 데이터로 학습된 앙상블 모델]
    A --> L[비지도 학습 기반의 GloVe 모델을 이용한 단어 임베딩]