flowchart TD
    A[영상으로부터 제1 프레임 및 제2 프레임을 포함하는 복수의 프레임을 추출하는 단계] --> B[상기 제1 프레임이 포르노 영상에 등장하는 신체 부위에 대응하는 제1 객체 및 제2 객체를 포함하는 복수의 객체 중 적어도 일부의 객체를 포함하는지 여부를 판정하는 단계]
    B --> C[상기 제1 프레임이 상기 적어도 일부의 객체를 포함하는 것으로 판정된 경우, 상기 제1 프레임에 포함된 전체 객체의 수, 상기 제1 객체의 수, 상기 제2 객체의 수 및 객체 종류 수를 산출하는 단계]
    C --> D[상기 제2 프레임이 포르노 영상에 등장하는 신체 부위에 대응하는 제1 객체 및 제2 객체를 포함하는 복수의 객체 중 적어도 일부의 객체를 포함하는지 여부를 판정하는 단계]
    D --> E[상기 제2 프레임이 상기 적어도 일부의 객체를 포함하는 것으로 판정된 경우, 상기 제2 프레임에 포함된 전체 객체의 수, 상기 제1 객체의 수, 상기 제2 객체의 수 및 객체 종류 수를 산출하는 단계]
    E --> F[상기 제1 프레임에 포함된 전체 객체의 수, 상기 제1 객체의 수, 상기 제2 객체의 수 및 객체 종류 수 및 상기 제2 프레임에 포함된 전체 객체의 수, 상기 제1 객체의 수, 상기 제2 객체의 수 및 객체 종류 수를 기초로 상기 영상을 포르노 영상 또는 일반 영상으로 분류하는 단계]
    F --> G[상기 영상을 포르노 영상 또는 일반 영상으로 분류하는 단계는, 상기 제1 프레임에서 상기 제1 객체 및 상기 제2 객체의 동시 탐지 여부 및 상기 제2 프레임에서 상기 제1 객체 및 상기 제2 객체의 동시 탐지 여부를 추가로 이용하여 상기 영상을 분류하는 단계]