flowchart TD
    A[서버는, 촬영부로부터 촬영된 이미지들을 획득하는 단계] --> B[서버는, 상기 촬영부로부터 획득한 상기 이미지들로부터 검지영역을 추출하여 상기 검지영역에서 차량을 검지하는 단계]
    B --> C[서버는, 차량이 검지되면 상기 이미지로부터 인식영역을 추출하고 상기 인식영역에서 차량번호판과 차량을 인식하는 단계]
    C --> D[인식영역 추출단계]
    C --> E[번호판 인식단계]
    C --> F[번호인식단계]
    C --> G[차량인식단계]