flowchart TD
    A[설정 데이터 획득] --> B[특징 정보 및 청진 위치 정보 획득]
    B --> C[결합 정보 생성]
    C --> D[AI 모델에 결합 정보 입력]
    D --> E[질병 정보 확인]
    B --> F[청진 위치 정보 임베딩]
    C --> G[특징 정보 및 청진 위치 정보 연결]
    F --> H[청진 가능 위치 성분 설정]
    H --> I[제1 값 및 제2 값 설정]
    J[생체 데이터 획득] --> K[생체 정보 획득]
    C --> L[생체 정보 결합]
    M[생체 데이터 범주 성분 설정] --> N[제1 값 및 제2 값 설정]
    O[특징 정보 및 청진 위치 정보 맵 형태] --> P[채널로서 청진 위치 정보 추가]
    Q[청진 가능 위치 맵 성분 설정] --> R[제1 값 및 제2 값 설정]
    S[생체 정보 맵 형태] --> T[채널로서 생체 정보 추가]