flowchart TD
    A[독성 가스 분산 데이터 변환] --> B[변환 모듈]
    B --> C[시뮬레이션 데이터 추출]
    C --> D[2D 데이터 추출]
    D --> E[2D 데이터 압축]
    E --> F[오토인코더 포함]
    F --> G[특징 감지 및 추출]
    G --> H[생성 모듈]
    H --> I[변환된 데이터 매핑]
    I --> J[예측 모델 생성]
    J --> K[인공 신경망 기반 반복 학습]
    K --> L[변분 추론 이용]
    L --> M[손실 함수 비교 평가]
    M --> N[완전 연결된 레이어 포함]
    N --> O[데이터 분포 정규화]