flowchart TD
    A[선박의 특징 정보 입력] --> B[선박 등록 여부 분류를 위한 드론의 선박 분류 모델 학습]
    B --> C[관제 서버로부터 모니터링 지시 신호 수신]
    C --> D[촬영 시작점으로 이동]
    D --> E[촬영 구역에서 선박 촬영 영상 및 3차원 선박 영상 수집]
    E --> F[선박 촬영 영상 및 3차원 선박 영상 전처리하여 선박 이미지 생성]
    F --> G[선박 이미지를 선박 분류 모델로 입력하여 등록 여부 분류]
    G --> H[미등록 선박 정보 관제 서버로 전송]
    H --> I[미등록 선박 등록 여부 재 확인]