flowchart TD
    A[리필스테이션에 설치되는 리필제공모듈] --> B[처리부 설치]
    B --> C[중앙서버 통신]
    C --> D[환경공단서버 통신]
    D --> E[제1데이터베이스 포함]
    E --> F[입력부 포함]
    F --> G[제2데이터베이스 포함]
    G --> H[제품구매정보 입력]
    H --> I[제품결제요청 송신]
    I --> J[제품결제 수행]
    J --> K[판매정보 갱신]
    K --> L[제품구매정보 송신]
    L --> M[인센티브발급부 포함]
    M --> N[인센티브정보 저장]
    N --> O[판매정보 송신]
    O --> P[발급인센티브정보 송신]
    P --> Q[인센티브정보 갱신]
    Q --> R[탄소배출권관리부 포함]
    R --> S[탄소배출권정보 저장]
    S --> T[탄소배출절감량정보 산출]
    T --> U[탄소배출권정보 갱신]
    U --> V[탄소배출권발급요청 송신]
    V --> W[탄소배출권 전송]
    W --> X[리필스테이션 충진 제어]