flowchart TD
    A[증명서 이미지에서 제1정보 영역의 영역 위치를 획득] --> B[주소 정보 영역의 하단 가장자리 확정]
    B --> C[주소 정보 영역의 상단 가장자리 확정]
    C --> D[주소 정보 영역의 왼쪽 가장자리 확정]
    D --> E[주소 정보 영역의 오른쪽 가장자리 확정]
    E --> F[주소 정보 영역을 트리밍]
    F --> G[제2정보 영역에 대하여 영역 분할 수행] 
    G --> H[적어도 하나의 문자 영역을 획득]