flowchart TD
    A[사용자 단말에서 관리 서버에 접속하여 코인을 포인트로 교환하는 단계] --> B[사용자 단말에서 쇼핑몰 서버에 접속하여 물품을 구매하는 단계]
    B --> C[쇼핑몰 서버에서 결제 수단을 식별하여, 결제가 카드 결제인 경우에만 물품 판매 금액에 따라 적립 포인트를 생성]
    C --> D[관리 서버에서 교환된 포인트에 의한 결제인 경우에는 적립 포인트를 생성하지 않음]
    D --> E[생성된 적립 포인트를 퍼블릭 블록체인을 사용하여 구매자 및 추천인에게 연속적이고 다단식으로 누적되도록 분배하는 단계]