flowchart TD
    A[비디오 영상을 입력받는 단계] --> B[관절의 좌표 및 위치 정보 생성하는 단계]
    B --> C[차분 정보 생성하는 단계]
    C --> D[입력벡터 생성하는 단계]
    D --> E[행동 인식하는 단계]
    
    B --> F[사람 객체를 골격화하여 골격화 객체 도출하는 단계]
    F --> G[골격화 객체로부터 위치 정보 생성하는 단계]
    
    C --> H[단기 차분 정보 추출하는 단계]
    C --> I[장기 차분 정보 추출하는 단계]
    
    D --> J[위치정보벡터 생성하는 단계]
    D --> K[단기차분정보벡터 생성하는 단계]
    D --> L[장기차분정보벡터 생성하는 단계]