flowchart TD
    A[농장 관리자 단말로부터 분양 대상 농장 정보 획득] --> B[수분양자 단말로부터 청약 정보 획득]
    B --> C[농장 관리자 단말과 수분양자 단말에 분양 결과 제공]
    C --> D[수분양자 단말에 수익 분배 방법 제공]
    D --> E[제1 방법 선택 정보 획득]
    E --> F[최소 보장 시세 및 판매 시세 정보 획득]
    F --> G{판매 시세 > 최소 보장 시세?}
    G -->|예| H[수익 분배 방법을 제1 방법으로 결정]
    G -->|아니오| I[수익 분배 방법을 제2 방법으로 결정]
    I --> J[제2 방법 선택 정보 획득]
    J --> K[제공 가능한 수량 정보 및 스케쥴 정보 제공]
    K --> L[스케쥴 선택 정보 및 배송지 정보 획득]
    H --> M[제3 방법 선택 정보 획득]
    M --> N[상품 정보 및 판매 링크 정보 제공]
    N --> O[판매 링크를 통한 상품의 주문 정보 획득]
    O --> P[상품의 판매 실적 식별]