flowchart TD
    A[RGB 카메라가 RGB 영상을 획득하는 단계] --> B[라이다 카메라가 라이다 정보를 획득하는 단계]
    B --> C[그룹 행동 인식 처리부가 RGB 영상 및 라이다 정보를 활용하여 다중 모달리티 사회 그룹 활동을 인식하여 출력하는 단계]
    C --> D[RGB 영상의 사람들의 특징 지도 중에서 중요한 부분을 부각하여 제1 개인 특징 벡터 행렬을 생성하는 단계]
    D --> E[라이다 정보의 사람들의 특징 지도 중에서 중요한 부분을 부각하여 제2 개인 특징 벡터 행렬을 생성하는 단계]
    E --> F[제1 개인 특징 벡터 행렬과 제2 개인 특징 벡터 행렬을 융합한 융합 개인 특징 벡터 행렬을 생성하는 단계]
    F --> G[융합 개인 특징 벡터 간의 코사인 유사성 값, GIoU 값 및 3차원 경계 상자의 중앙 점 간 거리 값을 바탕으로 두 사람이 같은 사회 그룹에 속할 확률을 예측하는 단계]