flowchart TD
    A[데이터를 획득하는 단계] --> B[제1 인코더부를 통해 손실 압축된 제1 데이터를 생성하는 단계]
    B --> C[기 학습된 확률 분포 예측 신경망을 이용하여 잔차 데이터의 확률 분포에 대한 복수의 파라미터를 예측하는 단계]
    C --> D[제2 인코더부를 통해 잔차 데이터가 무손실 압축된 제2 데이터를 생성하는 단계]