flowchart TD
    A[데이터 베이스에 반려동물 별 안면 데이터, 비문 데이터, 음성 데이터, 모션 데이터 저장] 
    A --> B[반려 동물의 안면 탐색 및 안면 이미지 캡쳐]
    B --> C[특징점 추출 및 안면 식별 데이터 생성]
    C --> D[안면 판단 정보 생성]
    B --> E[관심영역 추출 및 비문 식별 데이터 생성]
    E --> F[비문 판단 정보 생성]
    D --> G[안면 판단 정보, 비문 판단 정보 입력 및 개체 식별 정보 생성]
    G --> H[8개의 특징점 추출 및 정규화 수행]
    H --> I[가중치 적용하여 품종 및 성별 식별]
    I --> J[식별된 품종 및 성별 정보 및 관심 영역 이미지 데이터 입력]
    J --> K[안면 식별 데이터 생성 및 정확도 상승]
    K --> L[가중치 산출 및 갱신]
    L --> M[최적의 가중치 지수 산출 및 갱신]