flowchart TD
    A[로우(Raw) 데이터 수집] --> B[데이터 전처리]
    B --> C[전처리 데이터 전송]
    C --> D[이상 데이터 식별 및 분석]
    D --> E[예지 및 보전 대상 결정]
    E --> F[상태 모니터링 및 디스플레이]
    F --> G[머신 러닝 알고리즘 생성]
    G --> H[예지보전 알고리즘 업데이트]
    H --> I[선박 서버로 배포 또는 원격 업데이트]
    D --> J[이상 데이터 판단]
    J --> K[SR-CNN 기반 이상검출]
    J --> L[최소-최대 검출 알고리즘]
    G --> M[데이터 세트 준비]
    M --> N[기계학습 트레이닝]
    N --> O[성능 평가]
    O --> P[최적 후보 학습 모델 채택]
    P --> Q[하이퍼파라미터 조정]