flowchart TD
    A[대상체의 생체 신호를 획득하는 단계] --> B[상기 획득된 생체 신호를 제1 신경망 모델에 입력하여, 제1 결과 값을 획득하는 단계]
    B --> C[상기 획득된 생체 신호를 제2 신경망 모델에 입력하여, 제2 결과 값을 획득하는 단계]
    C --> D[상기 획득된 제1 결과 값에 대응하는 가중치를 상기 제2 결과 값에 적용하여, 조정된 제2 결과 값을 획득하는 단계]
    D --> E[상기 조정된 제2 결과 값에 기초하여 상기 대상체의 건강 상태를 예측하는 단계]