flowchart TD
    A[복합 센서로부터 수집한 복수 유형의 센싱값으로 제1 GCN 그래프 분석] --> B[제1 추정 상황 출력]
    A --> C[복수 유형의 센싱값을 정상 및 비정상으로 나타낸 제2 GCN 그래프 분석]
    C --> D[제2 추정 상황 출력]
    B --> E[제1 추정 상황 및 제2 추정 상황 분석]
    E --> F[제3 추정 상황 출력]
    B --> G[제1 LSTM으로 제1 추정 상황 시계열적 분석]
    D --> H[제2 LSTM으로 제2 추정 상황 시계열적 분석]