flowchart TD
    A[하나 이상의 컴퓨터 서브 시스템] --> B[하나 이상의 컴포넌트]
    B --> C[신경망에 입력된 표본에 대한 훈련 세트 내의 입력 이미지의 반전 피처 결정]
    C --> D[반전 피처로부터 입력 이미지를 재구성하여 출력 이미지 세트 생성]
    D --> E[입력 이미지와 출력 이미지 간의 차이 결정]
    E --> F[차이에 기초하여 신경망의 파라미터 변경]
    F --> G[훈련된 신경망이 런타임 이미지에 대한 반전 피처 결정]