flowchart TD
    A[플랫폼 서버에서 판매자와 소비자 간의 거래 상황을 경영정보관리시스템으로 관리하는 단계] --> B[소비자의 구매 확정 시 거래 사실 및 거래 품목을 특정하는 단계]
    B --> C[특정된 품목에 대한 SCM 코드를 생성하여 소비자에게 제공하는 단계]
    C --> D[소비자가 SCM 코드를 이용하여 생성한 리뷰 NFT와 제3 소비자의 경로를 생성하는 단계]
    D --> E[판매자와 소비자 간 거래가 플랫폼 서버를 직접 경유하지 않고 제휴 플랫폼을 통해 이루어진 경우, 제휴 플랫폼으로 고객의 주문 결제 정보를 요청하고 수신하는 단계]
    
    E --> F[외부 플랫폼에 고객의 주문 결제 정보를 요청하여 수신하는 단계]
    F --> G[수신한 주문 결제 정보를 바탕으로 판매자와 소비자 간의 거래를 확인하는 단계]
    
    E --> H[소비자의 영수증 정보를 플랫폼 서버에서 수집하는 단계]
    H --> I[수집한 영수증 정보를 바탕으로 판매자에게 판매 정보를 요청하는 단계]
    I --> J[수신한 판매 정보를 바탕으로 거래 상황을 관리하는 단계]
    
    D --> K[제3 소비자와 판매자 간의 거래를 리뷰 NFT의 블록체인 노드에서 수행하는 단계]
    K --> L[리뷰 NFT의 블록체인 노드에서 스마트 컨트랙트에 의해 거래를 검증하는 단계]
    
    D --> M[생성된 리뷰 NFT에 대응되는 거래가 취소되는 경우 생성된 경로를 차단하는 단계]