flowchart TD
    A[대상 식품 성분 점수 산출] --> B[성분 점수 산출 단계]
    B --> C[상기 성분 점수 산출]
    C --> D[상기 질병별 효능 점수 산출]
    D --> E[상기 성분 점수는 상대적인 순위 점수 포함]
    E --> F[상기 성분 정보는 함량 및 함량 순위 포함]
    F --> G[상기 성분 점수 산출 단계]
    G --> H[상기 성분들 각각에 대해 순위 점수 산출]
    H --> I[상기 질병 가중치 설정]
    I --> J[상기 근거 요소 포함]
    J --> K[상기 질병 가중치 설정]
    K --> L[제1가중치 및 제2가중치 기반 설정]
    L --> M[상기 성분 점수는 권장 점수 포함]
    M --> N[상기 권장 점수 산출]
    N --> O[상기 효능 점수 산출 단계]
    O --> P[제1 효능 점수 산출]
    O --> Q[제2 효능 점수 산출]
    P --> R[최종 효능 점수 산출]