flowchart TD
    A[설계] --> B[강재적치]
    B --> C[강재절단(S/C:Steel Cutting)]
    C --> D[조립(Steel Construction and Section Assembly)]
    D --> E[선행의장(Pre-Outfitting)]
    E --> F[도장(Painting)]
    F --> G[블록건조(block building)]
    G --> H[용골거치(K/L:Keel Laying)]
    H --> I[탑재(Erection)]
    I --> J[진수(L/C:LaunChing)]
    J --> K[안벽작업(Quay Outfitting)]
    K --> L[선박인도(D/L:Delivery)]