flowchart TD
    A[모바일 지역 상품권 권한 부여] --> B[신용카드 결제 사용 인가]
    B --> C[결제사용 수수료 적립 파악]
    C --> D[지방세 거둬들이기]
    D --> E[결제사용 수수료 대납]
    E --> F[발행 수수료 납부]
    F --> G[상품 구매 및 용역 서비스 수혜]
    G --> H[신용카드 결제]
    H --> I[잔여금 실시간 공지]
    I --> J[지방세 납부]
    J --> K[발행 수수료 관리 감독]
    K --> L[포인트 점수 적립]
    L --> M[기부 포인트 전환]
    M --> N[기부 포인트 축적]
    N --> O[복지 포인트 전환]
    O --> P[복지수혜 대상자 통신 단말기 전달]
    P --> Q[모바일 페이 결제]