flowchart TD
    A[결제 단말로서 사용되는 디바이스에 설치하기 위한 보안 요소] --> B[디바이스는 POS 애플리케이션을 실행]
    B --> C[POS 애플리케이션은 결제 제어 애플리케이션을 포함]
    C --> D[결제 제어 애플리케이션은 보안 요소를 제어하기 위한 제어 명령을 포함]
    D --> E[디바이스는 프로세서, 인터페이스 및 통신 인터페이스를 포함]
    E --> F[보안 요소는 비일시적 컴퓨터 판독가능 저장 매체로부터 액세스되는 명령을 포함]
    F --> G[보안 요소는 EMV 거래 모듈로서 데이터 처리]
    G --> H[EMV 거래 모듈은 보안 금융 거래를 행하기 위한 요청을 수신]
    H --> I[결제 장치로부터 금융 계좌에 관한 데이터 획득]
    I --> J[PPSE 요청을 전송]
    J --> K[결제 장치로부터 응답 수신]
    K --> L[결제 애플리케이션 선택]
    L --> M[서버와의 통신 채널을 확립하기 위한 요청 전송]
    M --> N[보안 통신 채널을 확립]
    N --> O[승인 요청을 서버에 전송]
    O --> P[승인 요청에 대한 응답 수신]
    P --> Q[보안 통신 채널을 폐쇄]
    Q --> R[승인 요청에 대한 응답을 처리하여 거래 상태 생성]