flowchart TD
    A[사용자 기기로부터 개인 정보, 광고 영역 정보 및 광고 이용 정보를 포함하는 광고 판매 정보를 수신하는 단계] --> B[광고 판매 정보를 저장하는 단계]
    B --> C[광고주 서비스 서버로부터 광고 구매 요청을 수신하는 단계]
    C --> D[수신된 광고 구매 요청에 따라 사용자 기기에 보상을 포함하는 광고 구매 확인 정보를 전송하는 단계]
    A --> E[사용자 기기에 표시된 광고 영역 선택 화면들을 통해 선택된 광고 영역을 수신하는 단계]
    C --> F[광고주 서비스 서버로부터 광고 영역을 구매하기 위한 광고 구매 요청을 수신하는 단계]