flowchart TD
    A[사전 학습된 제 1 모델을 사용하여 특징 벡터 생성] --> B[사전 학습된 제 2 모델을 사용하여 중요도 추정]
    B --> C[중요도를 기초로 모델 입력 영상 선별]
    C --> D[사전 학습된 제 3 모델을 사용하여 뇌 실질 영역 추출]
    D --> E[제 1 모델을 사용하여 특징 벡터 생성]
    E --> F[제 1 신경망으로부터 특징 추출]
    F --> G[제 2 신경망으로 뇌 질환 예측값 출력]
    B --> H[트리 기반의 부스팅 알고리즘을 이용한 중요도 추정]
    C --> I[중요도와 임계값 비교 후 모델 입력 영상 선정]
    I --> J[3차원 의료 영상 내에서 기준 번호 정보 획득]
    C --> K[선별된 모델 입력 영상을 질환 진단 모델의 학습 데이터로 사용]
    L[사전 학습된 세그먼테이션 모델을 사용하여 뇌 영역 구획]
    L --> M[구획된 뇌 영역에 대한 정보를 기초로 모델 입력 영상 선정]
    M --> N[기준 영역이 중앙 측두엽을 포함]
    N --> O[구획된 뇌 영역이 해마, 편도체, 내후각피질, 해마곁피질 및 뇌실 중 적어도 하나 포함]