flowchart TD
    A[하나 이상의 테이블 엔트리들에 액세스] --> B[액세스 플래그에 따라 액세스]
    B --> C[하드웨어를 통해 원자 업데이트 수행]
    C --> D[액세스 플래그 내의 액세스 비트 수정]
    D --> E[안전 및 비-안전 테이블 엔트리들 나타내기]
    E --> F[하나 이상의 메모리 동작들에 기초하여 메모리 어드레스 수정]
    F --> G[메모리 어드레스 설정 및 클리어]
    G --> H[더티 비트 수정]
    H --> I[액세스 플래그 및 더티 비트 업데이트]