flowchart TD
    A[상품 또는 서비스 등록] --> B[매장 데이터 업로드]
    B --> C[가맹점으로 등록]
    C --> D[현위치 또는 입력된 위치 기반 가맹점 검색]
    D --> E[가맹점 지도에 오버레이 출력]
    E --> F[가맹점 단말로부터 상품 또는 서비스 매핑 저장]
    F --> G[현위치 또는 입력된 위치 전송]
    G --> H[상품 또는 서비스 제공하는 가맹점 단말 추출]
    H --> I[추출된 가맹점 지도에 오버레이 출력]
    I --> J[길찾기, 경로안내 및 택시호출 서비스 제공]
    I --> K[취미정보 입력 또는 추출]
    K --> L[사용자 간 매칭 수행]
    I --> M[테마별 추천 서비스 제공]
    M --> N[상품 또는 서비스 추천]
    I --> O[아이템 중개 서비스 제공]
    I --> P[예약 이벤트 출력]
    P --> Q[예약 이벤트 전송]
    Q --> R[이용요금 선결제]