flowchart TD
    A[복수의 시스템 규칙, 시스템 상태, 복수의 템플릿에 기초하여 시스템 자동 관리] --> B[컨트롤러에 대한 연결을 위한 리소스]
    B --> C[제1 서비스 및 제2 서비스 포함]
    C --> D[제1 서비스는 제2 서비스에 대한 종속성 서비스 포함]
    C --> E[제2 서비스는 제1 서비스에 대한 종속 서비스 포함]
    B --> F[API 포함]
    F --> G[복수의 템플릿은 제2 서비스 설정에 필요한 종속성 리스트 포함]
    G --> H[상기 제2 서비스에 대한 상기 제1 서비스의 상호운용성 관리]
    H --> I[제2 서비스 구성]
    I --> J[제2 서비스에 대한 템플릿으로부터 종속성 리스트에 기초하여 관리]