flowchart TD
    A[제1 복합수지의 제조 레시피 및 물성 데이터 수집] --> B1[결측치 제거]
    B1 --> B2_1[동일한 제조 레시피끼리 카테고리화]
    B2_1 --> B2_2[훈련, 검정, 테스트 데이터셋으로 전처리]
    B2_2 --> C[머신러닝 모델 학습]
    C --> D[예측성능 검증 및 지능화 모델 획득]
    D --> E[제2 복합수지의 물성 예측]