flowchart TD
    A[입력 데이터 및 상기 입력 데이터에 대응하는 정답 데이터 획득] --> B[인공신경망 모듈을 사용하여 출력 데이터 획득]
    B --> C[손실 계산]
    C --> D[인공신경망 모듈 학습]
    D --> E[차량 이미지에 대한 연속되는 복수의 프레임 각각에 대해 수치 값 산출]
    E --> F[수치 값이 기 설정된 임계값 이상인 프레임에 대해 제1 가중치 적용]
    E --> G[수치 값이 기 설정된 임계값 미만인 프레임에 대해 제2 가중치 적용]
    F --> H[제1 가중치가 적용된 프레임 및 제2 가중치가 적용된 프레임에 기초하여 출력 데이터 획득]
    G --> H
    H --> I[정답 데이터 및 출력 데이터 비교하여 손실 계산]