flowchart TD
    A[제1공간을 포함하는 제1하우징] --> B[제1하우징에 대하여 슬라이딩 가능하게 결합되고, 제2공간을 포함하는 제2하우징]
    B --> C[제1하우징과 연결되고, 인입 상태에서, 적어도 부분적으로 제2공간으로 수용되는 밴딩 가능 지지 부재]
    C --> D[인출 상태에서, 제1하우징의 일부와 적어도 부분적으로 동일한 평면을 형성하는 밴딩 가능 지지 부재]
    D --> E[상기 인입 상태 및 인출 상태에서, 외부로부터 보여지는 제1영역 및 제2영역을 포함하는 플렉서블 디스플레이]
    E --> F[밴딩 가능 지지 부재의 배면을 가압하는 서포트 어셈블리]
    F --> G[가압 부재 및 적어도 하나의 지지 구조를 포함하는 전자 장치]