flowchart TD
    A[조리 및 취식 공간 대여 플랫폼 이용] --> B[조리 또는 취식을 위한 공간 예약]
    B --> C[대여코드 발급]
    C --> D[대여코드 유효성 확인]
    D --> E[주방기자재 및 식재료 정보 표시]
    E --> F[사용량에 따른 비용처리 요청]
    F --> G[키오스크 비용처리 내역 분석]
    G --> H[조리영상 정보 SNS에 LIVE 채널 생성]
    H --> I[실시간 조횟수 모니터링]
    I --> J[식자재 재고량 및 유통기한 관리]
    J --> K[소비패턴 분석 및 발주주문 요청]
    K --> L[후기 및 만족도 평점 기록]
    L --> M[현금성 리워드 지급]
    M --> N[조리공간 광고 정보 제공]
    N --> O[검색 키워드로 광고 정보 추출]