flowchart TD
    A[소상공인 운영 점포에 대한 잠재고객의 소비자 단말기로부터 센서를 구비한 폐디바이스의 기부의사정보를 마켓플레이스 플랫폼으로 전송하는 단계] --> B[설문조사를 수행하여 클라이언트 단말기로부터 마켓플레이스 플랫폼으로 클라이언트의 요구사항과 필요사항을 포함하는 니즈정보를 확보하는 단계]
    B --> C[상기 마켓플레이스 플랫폼에서 상기 니즈정보를 분석하여 니즈를 해결하기 위한 AI모델의 기획 및 설계를 수행하여 AI모델 제공자 단말기로 상기 니즈정보 및 기획설계정보를 전송하는 단계]
    C --> D[상기 AI모델 제공자 단말기가 상기 기획설계정보를 기반으로 학습데이터셋을 구축하여, 정형화와 텍스트 식별과 이미지 인식과 영상 인식과 객체 탐지와 예측과 유지보수와 추천을 수행하는 AI모델을 생성하여서, 상기 마켓플레이스 플랫폼으로 전송하는 단계]
    D --> E[상기 마켓플레이스 플랫폼에서 미리설정된 테스트기준에 따라 상기 AI모델을 평가하고 검증하는 단계]
    E --> F[AI모델 구독계약정보에 따라, 소상공인 단말기와 연동하며, AI모델을 구동하는 엣지 분석모듈과 센서로부터 감지되는 계측값을 관리하는 엣지 IoT모듈을 포함하여 AI모델의 엣지 컴퓨팅을 수행하는 플랫폼 OS가 재구축된 상기 폐디바이스를 해당 점포의 엣지 디바이스로 제공하는 단계]
    F --> G[상기 마켓플레이스 플랫폼으로부터 상기 테스트 기준을 통과한 상기 AI모델을 다운로드받아 상기 엣지 디바이스에서 실행하는 단계]
    G --> H[상기 엣지 디바이스에서 실행된 상기 AI모델의 예측결과 데이터를 상기 마켓플레이스 플랫폼으로 전송하는 단계]
    H --> I[상기 마켓플레이스 플랫폼이