flowchart TD
    A[제1 코덱스부] --> B[딜러부]
    A --> C[제2 코덱스부]
    B --> D[딜러 계정 생성 유닛]
    B --> E[보증 바우처 발행 유닛]
    B --> F[원본 자산 전달 유닛]
    B --> G[대체 자산 전달 유닛]
    B --> H[딜러 계정 삭제 유닛]
    C --> I[제1 코덱스 계정 생성 유닛]
    C --> J[제1 코덱스 계정 승인 유닛]
    C --> K[예치금 수신 유닛]
    C --> L[바우처 생성 유닛]
    C --> M[제1 자산 전달 유닛]