flowchart TD
    A[건물주 등록] --> B[관리 서비스 등록]
    B --> C[공동구매 진행]
    C --> D[서비스 요청 전송]
    D --> E[관리 서비스 실행 요청]
    E --> F[관리 서비스 추천]
    F --> G[비서 서비스 요청]
    G --> H[라이프스타일 정보 제공]
    H --> I[커뮤니티 서비스 제공]
    C --> J[정보 제공]
    J --> K[선택 입력]
    K --> L[선택 수 카운트]
    L --> M[할인 금액 산정]
    M --> N[결제 프로세스 제공]