flowchart TD
    A[판매자에 의하여 판매된 아이템에 대한 정산 요청을 판매자 단말로부터 수신] --> B[정산 요청에 대한 승인 여부 확인]
    B -->|승인되는 경우| C[정산 작업 정보 생성]
    C --> D[금융서비스 서버로 정산 작업 정보 전송]
    B -->|승인되지 않는 경우| E[종료]
    B --> F[정산 요청에 기반하여 문제가 발생할 수 있는지 여부 판단]
    C --> G[정산 요청에 대응하는 정산 작업 수행 시각 결정]
    C --> H[결정한 시각을 포함하여 정산 작업 정보 생성]
    A --> I[정산 요청은 판매자의 아이템 판매 대금 정보, 사용자 정보 및 계좌 정보 포함]
    C --> J[정산 작업 정보는 금액 정보 및 계좌 정보 포함]
    A --> K[정산 요청 및 정산 작업 정보는 식별 정보 포함]
    B --> L[정산 요청에 포함된 정보 일부를 회계 관련 정보를 처리하는 노드로 전송]
    L --> M[노드로부터 정산 요청에 대한 승인 여부 수신]
    C --> N[정산 작업 정보에 기초하여 정산 작업 수행]
    N --> O[정산용 계좌로부터 판매자가 설정한 계좌로 금액 이체 시도]
    P[정산용 계좌의 잔액 확인] --> Q[잔액이 미리 설정된 금액보다 작은 경우]
    Q --> R[잔액이 커지도록 자금 입금 요청]
    P --> S[잔액이 미리 설정된 금액보다 작은 경우 계좌 목록에서 제외]
    T[결정된 시각에 수행될 정산 작업 개수가 기준 초과 시 빠른 승인 요청] --> U[회계 관련 정보를 처리하는 서버]