flowchart TD
    A[전압프로파일 생성] --> B[열화상태 예측]
    A --> C[프로파일예측모델]
    B --> D[상태예측모델]
    C --> E[전압파형 입력]
    C --> F[전체 전압파형 예측]
    D --> G[배터리 충전용량 예측]
    E --> H[도메인 전이 네트워크]
    F --> I[생성적대립신경망(GAN)]
    I --> J[예측 전압프로파일 출력]
    I --> K[구분자]
    K --> L[모조데이터 구분]
    G --> M[지도학습 방법]