flowchart TD
    A[포터블 통신 디바이스의 현재 지오로케이션 수신] --> B[동적 임시 인증서 발행]
    B --> C[동적 임시 인증서 송신]
    C --> D[거래 인가 위험 스코어화]
    D --> E[검증 매핑 게이트웨이 접속]
    E --> F[위험 스코어 결정]
    F --> G[최종 사용자 인증]
    G --> H[사용자 데이터베이스와 연관]
    H --> I[패스코드 확인]
    I --> J[고유 디지털 서명 확인]
    J --> K[고객 아이덴티티 확인]