flowchart TD
    A[사용자 위치 기반의 실시간 여행정보 제공시스템] --> B[사용자단말로부터 실시간 전송받는 위치정보 수신]
    B --> C[여행객 여부 판단]
    C -->|여행객인 경우| D[관심대상 관광지 선택]
    D --> E[관심대상 관광지에 따라 시설리스트 탐색]
    E --> F[시설정보 제공]
    F --> G[후기 정보 및 불량상품 AR 이미지 피드백 수집]
    G --> H[손상 객체 분류 및 알고리즘 생성]
    H --> I[구매상품 AR 이미지로부터 상품객체 추출]
    I --> J[불량확률 도출]
    J -->|불량확률이 기설정된 수치 미만| K[정상 판단 정보 전송]
    C --> L[시설관리자들과 할인 계약된 시설 선택]
    L --> M[시설이미지 관련 SNS 게시글 캡쳐 요청]
    M --> N[응답받은 SNS 게시글 캡쳐 중계]
    N --> O[시설할인권 전송받아 중계]
    L --> P[광고주들과 리워드 보상 계약된 광고상품 관련 특정 문구 질의 요청]
    A --> Q[관광지정보 제공부]
    Q --> R[관광지리스트 실내 및 실외 관광지 분류]
    R --> S[기상 환경 변화 및 유행질병 관련 필터링]
    S --> T[추천 실외 관광지 방문일정 스케쥴링]
    S --> U[최저비용 추천 실내 관광지 방문일정 스케쥴링]
    F --> V[시설추천부]
    V --> W[시설촬영 이미지와 시설정보 식별]
    W --> X[시설 상세 정보 및 후기 정보 푸쉬 알림 제공]
    Q --> Y[키워드 검색 정보 자동 번역 제공]