flowchart TD
    A[여행 체험 플랫폼 서비스 제공 시스템] --> B[사용자 정보 저장부]
    B --> C[제 1 사용자 단말로부터 여행지의 영상을 수신]
    C --> D[여행 당시 이용한 항공권 정보에 기반하여 여행 날짜, 여행 기간, 항공기 비용 산출]
    D --> E[사용자의 카드 사용 내역에 기반하여 숙박 비용 및 쇼핑 비용 산출]
    E --> F[사용자 입력에 기반하여 여행 인원 수, 여행지에 대한 평가 점수 및 후기 수신]
    F --> G[인공지능 학습 모델로 전송]
    B --> H[제 2 사용자 단말로부터 여행 기간, 여행 장소, 여행 목적, 예산, 여행 인원 정보 수신]
    H --> I[인공지능 학습 모델로 전송]
    A --> J[제어부]
    J --> K[인공지능 학습 모델을 이용하여 정보 저장]
    K --> L[여행 장소에 기반하여 1차적으로 여행지 영상 정보 선별]
    L --> M[여행 날짜, 여행 기간, 여행 인원 수에 기반하여 2차적으로 여행지 영상 정보 선별]
    M --> N[예산 정보 및 항공기 비용, 숙박 비용, 쇼핑 비용에 기반하여 3차적으로 여행지 영상 정보 선별]
    N --> O[선별된 여행지 영상과 평가 점수 및 후기 출력]
    O --> P[항공편, 숙박 시설, 쇼핑 할인 정보 및 예약 가능한 관광 상품 정보 수신]
    P --> Q[인공지능 학습 모델로부터 출력된 정보 추가 표시]
    A --> R[상품 정보 제공부]
    R --> S[인공지능 학습 모델로부터 출력된 정보 제 2 사용자 단말로 전송]
    S --> T[선별된 여행지에 대한 정보 제 2 사용자 단말에게 전송]
    T --> U[제 2 사용자가 광고 클릭 여부 및 체류 시간, 구매 여부에 따라 광고 노출 결정]
    U --> V[광고의 유효 노출 여부, 노출 횟수 및 구매 예상 금액에 기반하여 광고비 책정]
    V --> W[제 1 사용자에게 리워드 제공]