flowchart TD
    A[이벤트의 기본 정보 획득] --> B[이벤트의 계획 정보 생성]
    B --> C[계획 정보 제공]
    B --> D[예산 정보 생성]
    D --> E[유사 이벤트 결정]
    E --> F[성과도 산출]
    F --> G[참고 이벤트 선정]
    G --> H[사은품 확인]
    H --> I[사은품 콘텐츠 비율 확인]
    I --> J[후기 콘텐츠 개수 산출]
    J --> K[참고 이벤트 유용도 산출]
    K --> L[참고 이벤트 효율도 결정]
    L --> M[사은품 비율 산출]
    M --> N[사은품에 할당될 예산 결정]
    
    B --> O[참고 이벤트 방문자 위치 정보 추출]
    O --> P[체류 장소 확인]
    P --> Q[방문 순서 확인]
    Q --> R[장소 지수 산출]
    R --> S[인테리어 이미지 수집]
    R --> T[구조 이미지 수집]
    S --> U[이벤트 계획 이미지 출력]
    U --> V[동선 출력]
    V --> W[이벤트 계획 이미지 수정]