flowchart TD
    A[이동식 저장매체가 단말기의 드라이브에 접속] --> B[저장경로 설정단계]
    B --> C[저장파일 실행단계]
    C --> D[격리공간 관리단계]
    A --> E[이동식 저장매체 접속단계]
    D --> F[격리공간의 저장 데이터 삭제]
    C --> G[제1단계: 저장파일 및 변경데이터 암호화]
    G --> H[제2단계: 저장파일 및 변경데이터 복호화]
    E --> I[격리공간 생성]