flowchart TD
    A[상점 단말기 설치] --> B[소비자 단말기 설치]
    B --> C[전통시장 장보기 관련 앱 배포]
    C --> D[상점 영업 정보 실시간 업데이트]
    D --> E[상품 거래 모듈 작동]
    E --> F[안내정보 제공 모듈 작동]
    F --> G[3D 정보 제공 모듈 작동]
    G --> H[라이브커머스 서비스 제공]
    H --> I[상품 거래 발생]
    I --> J[상품 집하 및 분류]
    J --> K[보관함 전자키 정보 전송]
    K --> L[보관함 도어락 개방]
    L --> M[상품 보관]
    M --> N[3D 모델링 모듈 구축]
    N --> O[가상현실 쇼핑몰 접속]
    O --> P[주문 및 배송 요청]
    P --> Q[재고 소진 시 추천 정보 전송]
    Q --> R[스마트카트에 의한 상품 집하]
    R --> S[카메라로 실시간 영상 전송]
    S --> T[QR코드 식별을 통한 정보 제공]