flowchart TD
    S100[이형제 분사량 측정기술 개발단계] --> S110[영상데이터 획득단계]
    S100 --> S120[분사량측정 인공지능모델 구현단계]
    S120 --> S121[분사원점 인공지능모델 구현단계]
    S121 --> S122[분사형상데이터 획득단계]
    S122 --> S123[선형회귀 인공지능모델 구현단계]
    S200[이형제 도포품질 평가기술 개발단계] --> S210[이미지데이터 획득단계]
    S200 --> S220[도포품질평가 인공지능모델 구현단계]
    S220 --> S211[증강처리모듈 구현단계]
    S220 --> S222[판별인공지능모델 구현단계]