flowchart TD
    A[학습자의 제1 단말과 교사의 제2 단말을 원격 연결] --> B[비대면 환경에서 멀티모달 학습 데이터 수집 및 분석]
    B --> C[제1 이벤트 정보 실시간 검출]
    C --> D[제1,2 단말 및 웹, 외부 서버와 네트워크 구축]
    D --> E[제2 이벤트 정보 획득]
    E --> F[제1,2 이벤트 정보 데이터 매칭]
    F --> G[임의의 멀티모달 분석정보 생성]
    G --> H[미리 설정된 알림신호 출력]
    H --> I[알림부에 시각적으로 디스플레이]
    I --> J[제어부가 2개의 학습분석 표준모델 기반으로 데이터 수집]
    J --> K[IMS Caliper Analytics 표준 적용]
    J --> L[xAPI 표준 적용]
    K --> M[데이터 생성부가 이벤트 정보 데이터화]
    M --> N[데이터 베이스부에 기록 및 관리]
    N --> O[변화값 비교 분석 및 멀티모달 분석정보 생성]
    O --> P[알림신호 출력부가 알림신호 출력]
    C --> Q[이미지 센서로 학습자 촬영]
    Q --> R[안면, 안구, 동공, 눈꺼풀 이미지 검출]
    C --> S[음성센서로 학습자 음성 감지]
    S --> T[억양, 발음, 목소리 높낮이 및 크기 검출]
    T --> U[음향출력부가 미리 설정된 음향 출력]
    E --> V[콘텐츠별 소비량, 학습시간, 문항별 풀이시간, 정오답 여부 검출]
    G --> W[학습자의 이해(성취)수준, 취약점, 학습성향, 콘텐츠별 선호도 분석]