flowchart TD
    A[농업법인 또는 농업 생산물에 대한 수익 창출 계약과 연관된 대체 불가능 토큰의 발행 요청 수신] --> B[블록체인망 상에서 발행 계약 코드 실행]
    B --> C[복수 개의 대체 불가능 토큰 발행 지원]
    C --> D[대체 불가능 토큰 발행 요청 정보 수신]
    D --> E[배당 요청 수신]
    E --> F[블록체인망 상에서 분배 계약 코드 실행]
    F --> G[각 투자자 단말에 대한 배당 실행 지원]
    G --> H[청산 요청 수신]
    H --> I[블록체인망 상에서 청산 계약 코드 실행]
    I --> J[청산 실행 지원]
    J --> K[농장 매출 및 재무정보 제공]
    K --> L[농장 가상화 및 가상의 지도 표시]
    L --> M[농장 영상 및 이미지 제공]
    M --> N[NFT 거래소 인터페이스 제공]
    N --> O[아바타 생성]
    O --> P[게임 퀘스트 제공]
    P --> Q[아바타가 게임 퀘스트 완료 시 리워드 제공]