flowchart TD
    A[메타버스 공간 형성] --> B[가상 전자명함 형성]
    B --> C[가상 전자명함 공유]
    C --> D[가상 전자명함 판매 분위기 형성]
    D --> E[가상 전자명함 구매 및 결제 수행]
    E --> F[가상 전자명함 판매존망 형성]
    F --> G[비즈니스 플랫폼 형성]
    G --> H[스마트 결제 제어]
    H --> I[NFT 거래 제어]
    I --> J[포인트 형성 제어]
    J --> K[가상 전자명함 제작]
    K --> L[암호화]
    L --> M[AR 전자명함 변환]
    M --> N[메타데이터 변환]