flowchart TD
    A[상점 단말기 설치] --> B[상품관리 수행]
    B --> C[주문관리 수행]
    C --> D[판매관리 수행]
    D --> E[배송관리 수행]
    E --> F[고객관리 수행]
    F --> G[영업관리 수행]
    G --> H[매출관리 수행]
    H --> I[재고관리 수행]
    I --> J[오프라인 매출정보 생성]
    J --> K[소비자 단말기 설치]
    K --> L[상품검색 수행]
    L --> M[주문 수행]
    M --> N[배송요청 수행]
    N --> O[재고식별 수행]
    O --> P[반품요청 수행]
    P --> Q[상품판매방송 제공]
    Q --> R[제1온라인 매출정보 생성]
    R --> S[오픈마켓 서비스 제공]
    S --> T[제2온라인 매출정보 생성]
    T --> U[온오프라인 매출정보 저장]
    U --> V[상점영업정보 실시간 업데이트]
    V --> W[판매 예측 수행]
    W --> X[상점정보 저장]
    X --> Y[상품 거래 수행]
    Y --> Z[안내정보 제공]
    Z --> AA[3D 정보 제공]
    AA --> AB[제1지능형 카메라 설치]
    AB --> AC[유동량 추출]
    AC --> AD[상관관계 통계분석]
    AD --> AE[소비자 방문 예측]
    AE --> AF[상품거래내역 통합 관리]
    AF --> AG[이벤트 개최]
    AG --> AH[보관함에 상품 보관]
    AH --> AI[전자키정보 전송]
    AI --> AJ[보관함 도어락 개방]
    AJ --> AK[증강현실 기반 전통시장 모델 구축]
    AK --> AL[상점영업정보 디스플레이 제공]