flowchart TD
    A[생성 요청을 서버로 전송하는 제안자 단말] --> B[프로젝트와 관련된 카테고리 정보, 대상지 정보, 및 참여자 정보를 기반으로 응답자 선택]
    B --> C[선택된 응답자의 응답자 단말로 프로젝트 생성 알림]
    C --> D[참여 요청을 서버로 전송하는 응답자 단말]
    D --> E[생성된 프로젝트와 응답자를 매칭]
    E --> F[일치 정도가 기준치 이상인 경우 프로젝트 추천]
    F --> G[기준치 이상의 검색 내역 생성 시 기간별 관심 카테고리 지정]
    G --> H[대상지의 면적 및 위치를 바탕으로 프로젝트 규모에 따른 등급 지정]
    H --> I[응답자의 자본 규모에 따른 등급 설정]
    I --> J[기간별 관심 카테고리에 대응하며 동일한 등급의 프로젝트 추천]
    J --> K[응답자가 기 생성된 프로젝트 선택 시 참여 요청]
    K --> L[프로젝트의 제안자와 응답자 간의 전자 계약 수행]
    L --> M[수수료 결제 및 계약 과정 진행]