flowchart TD
    A[업체정보 등록] --> B[고객정보 수집]
    B --> C[업체 선정 및 추천 업체 정보 생성]
    C --> D[지식재산 아이템 등록]
    D --> E[가격 산출]
    E --> F[지식재산 아이템 추천]
    F --> G[정보 수집 모듈]
    G --> H[우선순위 생성 모듈]
    H --> I[가격 산출 모듈]
    I --> J[신뢰도 산출 모듈]
    J --> K[업체평가 모듈]
    K --> L[리워드 산출 모듈]
    L --> M[업체 선정]
    M --> N[업체 평가 및 리워드 제공]