flowchart TD
    A[하나 이상의 컨텐츠를 미리 지정된 크기로 표시하는 단계] --> B[상기 터치 입력에 따라 상기 컨텐츠를 이동시키고 상기 컨텐츠의 크기를 확대하여 상기 터치스크린을 통해 표시하는 단계]
    B --> C[상기 터치 입력 중 드래그(drag) 입력에 따른 경로선이 교차되는 경우, 상기 경로선 중 단일폐곡선에 의해 형성된 도형에 따른 크기 및 위치에 상응하도록 상기 컨텐츠를 표시하는 단계]