flowchart TD
    A[하나 이상의 신경망을 사용하여 객체 검출 신경망을 훈련시키는 단계] --> B[전경 외관 손실 및 배경 외관 손실을 사용하여 훈련]
    B --> C[이미지에 부가할 객체의 위치를 특정하는 입력에 의해 제어]
    B --> D[객체의 표현을 생성하는 제1 네트워크 포함]
    B --> E[배경 이미지를 생성하는 제2 네트워크 포함]
    D --> F[배경 이미지 및 객체의 표현을 결합]
    B --> G[2차원 이미지들을 사용하여 훈련]
    B --> H[손실을 사용하여 훈련]
    H --> I[출력은 객체 검출 신경망에 의해 검출된 객체의 제1 위치]
    H --> J[입력은 이미지에서 객체를 생성할 위치를 식별]
    B --> K[생성된 이미지에 배치될 객체의 포즈 제공]