flowchart TD
    A[결제 서비스 운영사의 전자지갑 계정으로의 가상자산 이체를 통한 결제 서비스 제공] --> B[정보 데이터베이스에서 전자지갑 계정 정보 확인]
    B --> C[회원 데이터베이스에서 회원 식별 정보 확인]
    C --> D[제1 회원의 결제용 바코드 발급 요청 수신]
    D --> E[제1 결제용 바코드 생성 및 전송]
    E --> F[포스 단말기로부터 상품 가격 정보 수신]
    F --> G[결제 이벤트 발생]
    G --> H[전자지갑 계정 정보 확인]
    H --> I[거래소 서버에 접속]
    I --> J[가상자산 이체 명령 전송]
    J --> K[거래소 서버로부터 이체 완료 응답 수신]
    K --> L[결제 완료 메시지 포스 단말기로 전송]
    L --> M[사용자 인증 이벤트 발생]
    M --> N[회원 식별 정보 데이터 분할]
    N --> O[일회용 비밀번호 생성]