flowchart TD
    A[클라이언트 접속] --> B[온/오프라인 가맹점 서버와 연결]
    B --> C[이커머스-맵 저장]
    C --> D[가맹점 인터페이스 생성]
    D --> E[온/오프라인 가맹점 주소 설정]
    E --> F[가맹점 아이콘 매칭 및 배치]
    F --> G[회원 가입 요청 수신]
    G --> H[회원 가입부에 의해 회원 등록]
    H --> I[전시-룸 할당]
    I --> J[전시-룸 인터페이스 생성]
    J --> K[전시-룸 아이콘 매칭 및 배치]
    K --> L[서비스-상품 구매 시 거주-수수료 지급]
    L --> M[가맹점 등록 요청 수신]
    M --> N[가맹점 등록부에 등록]
    N --> O[제품 등록 요청 수신]
    O --> P[제품 등록/갱신부에 의해 서비스-상품 정보 갱신]
    P --> Q[가맹점 인터페이스 갱신]
    Q --> R[이커머스-맵 생성 및 갱신]
    R --> S[이커머스-맵 제공]
    S --> T[아이콘 클릭 시 인터페이스 제공]
    T --> U[서비스-상품 분양 요청 수신]
    U --> V[전시-룸 인터페이스 갱신]