# Generated by Django 5.0.6 on 2026-06-08 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_groups_alter_user_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('inventor', '발명가'), ('attorney', '변리사')], default='inventor', max_length=20, verbose_name='가입 유형'),
        ),
    ]
