%% 1020167020762 - 타겟 인디케이터 위치 결정 흐름도
%% 생성일: 2026-05-11

flowchart TD
    100["머리 장착형 컴퓨팅 디바이스"]
    200["시선 추적 시스템"]
    300["머리 추적 시스템"]
    400["위치결정 모듈"]
    100 -->| "연결" | 200
    100 -->| "연결" | 300
    200 -->| "데이터 사용" | 400
    300 -->| "데이터 사용" | 400