%% 1020220113636 - 1차 추론 결과 예시
%% 생성일: 2026-05-11

flowchart TD
    100["카메라"]
    200["학습 서버"]
    300["저장 서버"]
    400["영상 수신 및 프레임 단위로 분할"]
    500["1차 학습 수행"]
    600["제1 추론 단계에서 객체 탐지 및 라벨링"]
    700["가중치 부여 및 2차 학습 수행"]
    800["최종 객체 탐지"]

    100 -->| "영상 수신" | 200
    200 -->| "모델 저장" | 300
    200 --> 400
    400 --> 500
    500 --> 600
    600 --> 700
    700 --> 800