%% 1020220072515 - 딥러닝 모델 학습 및 진단 과정
%% 생성일: 2026-05-11

flowchart TD
    100["프로세서"]
    200["OCT 이미지"]
    300["제1 데이터셋"]
    400["제2 데이터셋"]
    500["딥러닝 모델"]
    
    200 -->| "처리" | 100
    300 -->| "학습에 사용" | 100
    400 -->| "라벨링에 사용" | 100
    300 -->| "학습" | 500
    400 -->| "진단" | 500