%% 1020210057704 - 시스템 구성도
%% 생성일: 2026-05-11

classDiagram
    class 프로세서및메모리회로PMC {
        +String 이미지처리
        +segment화()
    }
    class 제1확률맵 {
        +String 픽셀확률
    }
    class 제1라벨맵 {
        +String 세그먼트정보
    }
    class 제2확률맵 {
        +String 모의실험확률
    }
    class 제2라벨맵 {
        +String 최종라벨정보
    }
    프로세서및메모리회로PMC --> 제1확률맵 : "생성됨"
    프로세서및메모리회로PMC --> 제1라벨맵 : "생성됨"
    제1라벨맵 --> 제2확률맵 : "기반하여 생성됨"
    제1확률맵 --> 제2라벨맵 : "기반하여 생성됨"
    제2확률맵 --> 제2라벨맵 : "기반하여 생성됨"