%% 1020210057704 - 반도체 시편 이미지 세그먼트화 과정
%% 생성일: 2026-05-11

flowchart TD
    100["프로세서 및 메모리 회로(PMC)"]
    200["제1 확률 맵"]
    300["제1 라벨 맵"]
    400["제2 확률 맵"]
    500["제2 라벨 맵"]
    
    100 -->|"생성됨"| 200
    100 -->|"생성됨"| 300
    300 -->|"기반하여 생성됨"| 400
    200 -->|"기반하여 생성됨"| 500
    400 -->|"기반하여 생성됨"| 500