%% 1020230008511 - 농장 분양 및 수익 분배 방법 흐름도
%% 생성일: 2026-05-11

flowchart TD
    100["서버"]
    200["농장 관리자 단말"]
    300["수분양자 단말"]
    400["산출물"]
    500["판매 링크"]
    
    200 -->| "정보 제공" | 100
    300 -->| "청약 정보 제공" | 100
    100 -->| "분양 결과 제공" | 300
    100 -->| "수익 분배 방법 제공" | 300
    300 -->| "수익 분배 방법 선택" | 100
    100 -->| "판매 시세 정보 획득 및 비교" | 300
    100 -->| "수익 분배 방법 결정" | 300
    100 -->| "상품 정보 및 판매 링크 제공" | 500
    300 -->| "주문 정보 획득 및 판매 실적 식별" | 400