%% 1020230059615 - 리필스테이션 운영 흐름도
%% 생성일: 2026-05-11

flowchart TD
    500["사용자단말"]
    100["리필스테이션"]
    200["중앙서버"]
    300["환경공단서버"]
    400["제1데이터베이스"]
    
    500 -->|"제품 구매 정보 입력"| 200
    200 -->|"제품 결제 요청 송신"| 400
    200 -->|"결제 수행 및 판매정보 갱신"| 400
    200 -->|"제품 충진 요청 송신"| 100
    200 -->|"인센티브 정보 관리"| 300