%% 1020230059615 - 시스템 구성도
%% 생성일: 2026-05-11

classDiagram
    class 리필스테이션 {
        +String 제품정보
        +제어()
    }
    class 중앙서버 {
        +String 결제정보
        +데이터 저장()
        +통신()
    }
    class 환경공단서버 {
        +String 인센티브정보
        +데이터 송신()
    }
    class 제1데이터베이스 {
        +String 판매정보
        +String 사용자정보
    }
    class 사용자단말 {
        +String 구매정보
        +정보 송신()
    }
    사용자단말 --> 중앙서버 : "정보 송신"
    중앙서버 --> 리필스테이션 : "제어"
    중앙서버 --> 환경공단서버 : "통신"
    환경공단서버 <-- 중앙서버 : "데이터 송신"
    중앙서버 <-- 제1데이터베이스 : "데이터 저장"