%% 1020177008531 - 스마트 센서 구성도
%% 생성일: 2026-05-11

classDiagram
    class 센서어레이 {
        +String 센서데이터
    }
    class 전용컴퓨터시각연산하드웨어 {
        +computeCVFeatures()
    }
    class 제1프로세싱유닛 {
        +processSignal()
        +generateEvent()
    }
    class 제2프로세싱유닛 {
        +receiveEvent()
    }
    센서어레이 --> 전용컴퓨터시각연산하드웨어 : "데이터 수신"
    전용컴퓨터시각연산하드웨어 --> 제1프로세싱유닛 : "신호 프로세싱"
    제1프로세싱유닛 --> 제2프로세싱유닛 : "이벤트 생성"
    제2프로세싱유닛 <-- 제1프로세싱유닛 : "이벤트 수신"