%% 1020217010501 - 저전력 상태 진입 프로세스
%% 생성일: 2026-05-11

flowchart TD
    100["앰비언트 컴퓨팅 디바이스"]
    200["메모리 제어기"]
    300["캐시"]
    400["저전력 상태 진입"]
    100 -->|"데이터 요청을 처리"| 200
    200 -->|"데이터 요청을 캐시"| 300
    300 -->|"프리페치 프로세스를 수행하여 캐시를 채운다."| 400
    400 -->|"프리페치된 명령과 데이터를 사용하여 입력을 처리한다."| 100