%% 1020200126707 - 피해 감지 방법 흐름도
%% 생성일: 2026-05-11

flowchart TD
    100["샘플 데이터 셋"]
    200["서브세트"]
    300["이상 객체 데이터 세트"]
    400["피해 감지 모델"]
    100 -->|"포함됨"| 200
    200 -->|"학습"| 400
    400 -->|"추정"| 300