%% 1020087021561 - 인스트럭션 세트 처리 흐름
%% 생성일: 2026-05-11

flowchart TD
    100["병렬 프로세서"]
    200["마스터 프로세서"]
    300["컴퓨터 메모리"]
    400["로컬 캐시"]
    500["특정 레지스터"]
    
    200 -->|"관리"| 100
    300 <-->|"액세스"| 100
    400 -->|"할당"| 100
    500 -->|"사용"| 100
    
    100 -->|"로컬 캐시 할당"| 400
    100 -->|"스레드 할당"| 200
    100 -->|"스레드 프로세싱"| 500
    100 -->|"결과 프로세싱"| 300
    100 -->|"스레드 탈-할당"| 200