%% 1020087021561 - 주소 지정 방식
%% 생성일: 2026-05-11

flowchart TD
    100["병렬 프로세서"]
    200["마스터 프로세서"]
    300["컴퓨터 메모리"]
    400["로컬 캐시"]
    500["특정 레지스터"]
    
    200 -->|"관리"| 100
    300 <--|"액세스"| 100
    400 -->|"할당"| 100
    500 -->|"사용"| 100