%% 1020200168183 - 의료 영상 기반 질환 예측 방법 흐름도
%% 생성일: 2026-05-11

flowchart TD
    100["프로세서"]
    200["메모리"]
    300["네트워크부"]
    400["제 1 모델"]
    500["제 2 모델"]
    600["세그먼테이션 모델"]
    
    300 -->|"의료 영상 수신"| 100
    100 <--|"저장된 코드 실행"| 200
    100 -->|"특징 벡터 생성"| 400
    400 -->|"중요도 추정"| 500
    500 -->|"모델 입력 영상 선별"| 600
    600 -->|"학습 데이터로 사용"| 100